SELECT * FROM PREVIO_TOFILESTRING OPER
WHERE OPER.ID_INDIVIDUO LIKE '1455148800000.531'
ORDER BY OPER.FECHA_SEMANA ASC;

SELECT * FROM PREVIO_TOFILESTRING OPER
--WHERE OPER.PIPS_SEMANA>0 AND OPER.PIPS_MES>0 AND OPER.PIPS_ANYO>0 AND OPER.PIPS_TOTALES>8000
ORDER BY PTFS.FECHA_SEMANA DESC
;

SELECT * FROM PREVIO_TOFILESTRING PTFS
--WHERE OPER.PIPS_SEMANA>0 AND OPER.PIPS_MES>0 AND OPER.PIPS_ANYO>0 AND OPER.PIPS_TOTALES>8000
ORDER BY PTFS.FECHA_SEMANA DESC, PTFS.R2_CONSOL DESC, PTFS.PENDIENTE_CONSOL DESC
;

SELECT PTFS.FECHA_SEMANA, ROUND(MAX(PTFS.R2_SEMANA),5) R2_SEMANA, ROUND(MAX(PTFS.R2_MES),5) R2_MES,
  ROUND(MAX(PTFS.R2_ANYO),5) R2_ANYO, ROUND(MAX(PTFS.R2_CONSOL),5) R2_CONSOL,
  ROUND(MAX(PTFS.PENDIENTE_SEMANA),5) PENDIENTE_SEMANA, ROUND(MAX(PTFS.PENDIENTE_MES),5) PENDIENTE_MES,
  ROUND(MAX(PTFS.PENDIENTE_ANYO),5) PENDIENTE_ANYO, ROUND(MAX(PTFS.PENDIENTE_CONSOL),5) PENDIENTE_CONSOL
FROM PREVIO_TOFILESTRING PTFS
  INNER JOIN PROCESO P ON PTFS.ID_INDIVIDUO=P.ID_INDIVIDUO AND P.FECHA_PROCESO>TRUNC(SYSDATE)
WHERE PTFS.R2_CONSOL IS NOT NULL
GROUP BY PTFS.FECHA_SEMANA
--ORDER BY PTFS.FECHA_SEMANA DESC
ORDER BY MAX(PTFS.R2_CONSOL) DESC, MAX(PTFS.PENDIENTE_CONSOL) DESC
;

SELECT PTFS.* FROM PREVIO_TOFILESTRING PTFS
  INNER JOIN PROCESO P ON PTFS.ID_INDIVIDUO=P.ID_INDIVIDUO --AND P.FECHA_PROCESO>TRUNC(SYSDATE)
WHERE --PTFS.PIPS_SEMANA>0 AND PTFS.PIPS_MES>0 AND PTFS.PIPS_ANYO>0 AND PTFS.PIPS_TOTALES>0 AND
----AND PTFS.FECHA_SEMANA>=TO_DATE('2014/01/01 00:00', 'YYYY/MM/DD HH24:MI') 
--AND PTFS.R2_CONSOL>0.5 AND PTFS.R2_ANYO>0.2 AND 
PTFS.R2_MES>0.2 AND
--AND PTFS.R2_SEMANA>0.2
--AND 
PTFS.R_COUNT_CONSOL>10 AND PTFS.R_COUNT_ANYO>10 
AND PTFS.PENDIENTE_CONSOL>5 AND PTFS.PENDIENTE_ANYO>10 
AND PTFS.PENDIENTE_MES>20 AND NVL(PTFS.PENDIENTE_SEMANA,0)>0
--AND PTFS.ID_INDIVIDUO='1463541693654.3821'
ORDER BY PTFS.FECHA_SEMANA ASC, PTFS.R2_CONSOL DESC;

SELECT PTFS.* FROM PREVIO_TOFILESTRING PTFS
  INNER JOIN PROCESO P ON PTFS.ID_INDIVIDUO=P.ID_INDIVIDUO
WHERE PTFS.R_COUNT_CONSOL>10 AND PTFS.PENDIENTE_CONSOL>0
--PTFS.PENDIENTE_SEMANA>0 AND 
AND PTFS.PENDIENTE_ANYO>PTFS.PENDIENTE_CONSOL 
AND PTFS.PENDIENTE_MES>PTFS.PENDIENTE_ANYO
--AND PTFS.PENDIENTE_CONSOL>0
AND PTFS.R2_CONSOL>0.6 --AND PTFS.R2_ANYO>0.5 AND PTFS.R2_MES>0.5
AND PTFS.FECHA_SEMANA<SYSDATE-1
ORDER BY PTFS.FECHA_SEMANA DESC, PTFS.R2_CONSOL DESC;

SELECT TO_CHAR(OPER.FECHA_SEMANA, 'YYYYMM') FE, 
  ROUND(AVG(OPER.PIPS_SEMANA)) PIPSS, ROUND(AVG(OPER.PIPS_MES)) PIPSM, 
  ROUND(AVG(OPER.PIPS_ANYO)) PIPSA, ROUND(AVG(OPER.PIPS_TOTALES)) PIPST 
FROM PREVIO_TOFILESTRING OPER
GROUP BY TO_CHAR(OPER.FECHA_SEMANA, 'YYYYMM')
ORDER BY TO_CHAR(OPER.FECHA_SEMANA, 'YYYYMM') DESC
;

SELECT OPER.FECHA_SEMANA-TO_DATE('20160901','YYYYMMDD') DIFF, OPER.* FROM OPERACION_X_SEMANA OPER
WHERE OPER.ID_INDIVIDUO LIKE '1455148800000.531'
ORDER BY OPER.FECHA_SEMANA ASC;

SELECT * FROM OPERACION_X_SEMANA OPER 
WHERE 
OPER.ID_INDIVIDUO LIKE '1455148800000.531'
--AND FECHA_SEMANA>=TO_DATE('20120101', 'YYYYMMDD')
ORDER BY FECHA_SEMANA ASC
;

SELECT * FROM OPERACIONES_ACUM_SEMANA_MES OPER
WHERE OPER.ID_INDIVIDUO='1455148800000.531'
--AND FECHA_SEMANA>=TO_DATE('20160713', 'YYYYMMDD')
ORDER BY FECHA_SEMANA ASC
;

SELECT * FROM OPERACIONES_ACUM_SEMANA_ANYO OPER
WHERE OPER.ID_INDIVIDUO='1455148800000.531'
--AND FECHA_SEMANA>=TO_DATE('20150913', 'YYYYMMDD')
ORDER BY FECHA_SEMANA ASC
;

SELECT OPER.*
FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
WHERE OPER.ID_INDIVIDUO='1455148800000.531'
--AND FECHA_SEMANA>=TO_DATE('20160713', 'YYYYMMDD')
ORDER BY FECHA_SEMANA ASC
;

SELECT * FROM TMP_TOFILESTRING2 
ORDER BY VIGENCIA1 DESC, CRITERIO_ORDER1 DESC;

SELECT OPER.FECHA_SEMANA, OPER.ID_INDIVIDUO FROM
  OPERACIONES_ACUM_SEMANA_CONSOL OPER
  INNER JOIN 
  (SELECT FECHA_SEMANA, MAX(PIPS) PIPS FROM OPERACIONES_ACUM_SEMANA_CONSOL
  WHERE FECHA_SEMANA>=TO_DATE('20140101', 'YYYYMMDD')
  GROUP BY FECHA_SEMANA
--ORDER BY FECHA_SEMANA ASC
  ) TMP ON OPER.FECHA_SEMANA=TMP.FECHA_SEMANA AND OPER.PIPS=TMP.PIPS
;

SELECT 'SEMANA', count(*), MAX(FECHA_SEMANA), AVG(PIPS) FROM OPERACION_X_SEMANA SEM
--WHERE SEM.PIPS>0
;
UNION ALL
SELECT 'MES', COUNT(*), MAX(FECHA_SEMANA), AVG(PIPS) FROM OPERACIONES_ACUM_SEMANA_MES OPER
--WHERE OPER.PIPS>-1000
;
UNION ALL
SELECT 'ANYO', COUNT(*), MAX(FECHA_SEMANA), AVG(PIPS) FROM OPERACIONES_ACUM_SEMANA_ANYO OPER
--WHERE OPER.PIPS>-2000
;
SELECT 'CONSOL', COUNT(*), MAX(FECHA_SEMANA), AVG(PIPS) FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
--WHERE OPER.PIPS>-3000
;

SELECT * FROM OPERACION_X_SEMANA OPER
ORDER BY FECHA_SEMANA DESC
;
SELECT * FROM OPERACIONES_ACUM_SEMANA_MES OPER
ORDER BY FECHA_SEMANA DESC
;
SELECT * FROM OPERACIONES_ACUM_SEMANA_ANYO OPER
ORDER BY FECHA_SEMANA DESC
;
SELECT * FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
ORDER BY PIPS DESC
;
SELECT * FROM PREVIO_TOFILESTRING TFS 
ORDER BY TFS.FECHA_SEMANA DESC;

SELECT * FROM SEMANAS ORDER BY FECHA_SEMANA ASC;

SELECT * FROM OPERACION_X_SEMANA OPER
WHERE --OPER.ID_INDIVIDUO IN ('1453687605734.178', '1453044410021.4') AND 
OPER.FECHA_SEMANA<=TO_DATE('20160401', 'YYYYMMDD')
AND OPER.PIPS>0
AND OPER.TIPO_OPERACION='SELL'
ORDER BY OPER.FECHA_SEMANA DESC
--ORDER BY OPER.PIPS DESC
;

SELECT * FROM OPERACIONES_ACUM_SEMANA_MES OPER
WHERE --OPER.ID_INDIVIDUO='1460948821579.426' AND 
OPER.FECHA_SEMANA>=TO_DATE('20160321', 'YYYYMMDD')
AND OPER.PIPS>0
ORDER BY OPER.FECHA_SEMANA ASC
;

SELECT * FROM OPERACIONES_ACUM_SEMANA_ANYO OPER
WHERE --OPER.ID_INDIVIDUO='1460948821579.426' AND 
OPER.FECHA_SEMANA>=TO_DATE('20160321', 'YYYYMMDD')
AND OPER.PIPS>0
ORDER BY OPER.FECHA_SEMANA ASC
;

SELECT * FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
WHERE --OPER.ID_INDIVIDUO='1460948821579.426' AND 
OPER.FECHA_SEMANA>=TO_DATE('20160321', 'YYYYMMDD')
AND OPER.PIPS>0
ORDER BY OPER.FECHA_SEMANA ASC
;

