ALTER TABLE OPERACION_X_SEMANA 
ADD (R_COUNT NUMBER );
ALTER TABLE OPERACION_X_SEMANA 
ADD (R2 NUMBER );
ALTER TABLE OPERACION_X_SEMANA 
ADD (PENDIENTE NUMBER );
ALTER TABLE OPERACION_X_SEMANA 
ADD (INTERCEPCION NUMBER );

ALTER TABLE OPERACIONES_ACUM_SEMANA_MES
ADD (R_COUNT NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_MES
ADD (R2 NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_MES
ADD (PENDIENTE NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_MES
ADD (INTERCEPCION NUMBER );

ALTER TABLE OPERACIONES_ACUM_SEMANA_ANYO
ADD (R_COUNT NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_ANYO
ADD (R2 NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_ANYO
ADD (PENDIENTE NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_ANYO
ADD (INTERCEPCION NUMBER );

ALTER TABLE OPERACIONES_ACUM_SEMANA_CONSOL
ADD (R_COUNT NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_CONSOL
ADD (R2 NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_CONSOL
ADD (PENDIENTE NUMBER );
ALTER TABLE OPERACIONES_ACUM_SEMANA_CONSOL
ADD (INTERCEPCION NUMBER );

ALTER TABLE PREVIO_TOFILESTRING
ADD (R_COUNT_SEMANA NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (R2_SEMANA NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (PENDIENTE_SEMANA NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (INTERCEPCION_SEMANA NUMBER );

ALTER TABLE PREVIO_TOFILESTRING
ADD (R_COUNT_MES NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (R2_MES NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (PENDIENTE_MES NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (INTERCEPCION_MES NUMBER );

ALTER TABLE PREVIO_TOFILESTRING
ADD (R_COUNT_ANYO NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (R2_ANYO NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (PENDIENTE_ANYO NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (INTERCEPCION_ANYO NUMBER );

ALTER TABLE PREVIO_TOFILESTRING
ADD (R_COUNT_CONSOL NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (R2_CONSOL NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (PENDIENTE_CONSOL NUMBER );
ALTER TABLE PREVIO_TOFILESTRING
ADD (INTERCEPCION_CONSOL NUMBER );
