CREATE TABLE DATO_ADICIONAL_TPO 
(
  FECHA_BASE DATE NOT NULL 
, R2_PROMEDIO NUMBER(10,5) NOT NULL 
, PENDIENTE_PROMEDIO NUMBER(10,5) NOT NULL 
, PROBABILIDAD_PROMEDIO NUMBER(10,5) NOT NULL 
, FECHA DATE NOT NULL default sysdate
, NUMERO_TENDENCIAS NUMBER(10,5)
, CANTIDAD_TOTAL_TENDENCIAS NUMBER(10,5)
, NUM_PENDIENTES_POSITIVAS NUMBER(10)
, NUM_PENDIENTES_NEGATIVAS NUMBER(10)
, DIFF_PRECIO_EXTREMO_SUPERIOR NUMBER(10,5)
, DIFF_PRECIO_EXTREMO_INFERIOR NUMBER(10,5)

, CONSTRAINT DATO_ADICIONAL_TPO_PK PRIMARY KEY 
  (
		FECHA_BASE 
  )
  ENABLE 
);