--ALTER TABLE FOREX.OPERACION MOVE TABLESPACE USERS2;
--ALTER INDEX FOREX.OPERACION_PK REBUILD TABLESPACE USERS2;
ALTER INDEX FOREX.OPERACION_INDIV_FECHA_IDX REBUILD TABLESPACE USERS2;
ALTER INDEX FOREX.OPER_FECHA_IDX REBUILD TABLESPACE USERS2;
ALTER INDEX FOREX.OPER_IDINDIV_FECIERRE_IDX REBUILD TABLESPACE USERS2;
ALTER INDEX FOREX.OPER_IDX1 REBUILD TABLESPACE USERS2;