DECLARE
	V_T1 VARCHAR2(1000);
	PARAM_DATE DATE;
	CURSOR C1 (V_DATE DATE) IS
			WITH TIEMPO_TENDENCIA AS (
				SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
					(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
					0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
					V_DATE FECHA,
					'xBUY_SELL_20170125' TIPO_TENDENCIA1, 'BUY_SELL_20170131-3' TIPO_TENDENCIA2, 'xBUY_SELL_20170131-2' TIPO_TENDENCIA3 
					FROM DUAL),
				TENDENCIA_6H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
							ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
							ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
							WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
							AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
							AND TEN.FECHA_BASE<=TT.FECHA
							AND TEN.FECHA_TENDENCIA>TT.FECHA
							AND TEN.FECHA_TENDENCIA<=TT.FECHA+6/24
						GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
				TENDENCIA_12H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
							ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
							ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
							WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
							AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
							AND TEN.FECHA_BASE<=TT.FECHA
							AND TEN.FECHA_TENDENCIA>TT.FECHA
							AND TEN.FECHA_TENDENCIA<=TT.FECHA+6/24
						GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
				TENDENCIA_1D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
							ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
							ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
							WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
							AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
							AND TEN.FECHA_BASE<=TT.FECHA
							AND TEN.FECHA_TENDENCIA>TT.FECHA
							AND TEN.FECHA_TENDENCIA<=TT.FECHA+6/24
						GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
				TENDENCIA_2D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
							ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
							ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
							WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
							AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
							AND TEN.FECHA_BASE<=TT.FECHA
							AND TEN.FECHA_TENDENCIA>TT.FECHA
							AND TEN.FECHA_TENDENCIA<=TT.FECHA+6/24
						GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
				TENDENCIA_5D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
							ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
							ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
							WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
							AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
							--AND TEN.FECHA_BASE<TEN.FECHA_TENDENCIA-1/24
							AND TEN.FECHA_BASE<=TT.FECHA
							AND TEN.FECHA_TENDENCIA>TT.FECHA
							AND TEN.FECHA_TENDENCIA<=TT.FECHA+6/24
						GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
			SELECT 'FECHA_TENDENCIA='||(TEN5D.FECHA_TENDENCIA)||',PRECIO_CALCULADO='
					||ROUND((MULTIPLE_NVL(TEN6H.PRECIO_CALCULADO,TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO)*TT.PORC6H
						+MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,NULL)*TT.PORC12H
						+MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,NULL,NULL)*TT.PORC1D
						+MULTIPLE_NVL(TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,NULL,NULL)*TT.PORC2D
						+TEN5D.PRECIO_CALCULADO*TT.PORC5D),5) VAL_TENDENCIA
			FROM TIEMPO_TENDENCIA TT, TENDENCIA_5D TEN5D
				LEFT JOIN TENDENCIA_6H TEN6H ON TEN5D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
				LEFT JOIN TENDENCIA_12H TEN12H ON TEN5D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
				LEFT JOIN TENDENCIA_1D TEN1D ON TEN5D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
				LEFT JOIN TENDENCIA_2D TEN2D ON TEN5D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
			ORDER BY TO_DATE(TEN5D.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
			;
BEGIN
	--DBMS_OUTPUT.PUT_LINE('CONSULTANDO...');
	PARAM_DATE:=TO_DATE('2017/01/25 23:47','YYYY/MM/DD HH24:MI');
	FOR i IN 1.. 50 LOOP
			--DBMS_OUTPUT.PUT_LINE(PARAM_DATE);
			FOR V_T1 IN C1(PARAM_DATE) LOOP				
				DBMS_OUTPUT.PUT_LINE(V_T1.VAL_TENDENCIA);
			END LOOP;	
			PARAM_DATE:=PARAM_DATE+7/24;
	END LOOP;
END;
/