SELECT COUNT(*) FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE CANTIDAD<2 AND CANTIDAD_PARALELAS<2;

DECLARE 
  REG_EOP ESTRATEGIA_OPERACION_PERIODO%ROWTYPE;
CURSOR C_EOP IS
  SELECT EOP.ID FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE CANTIDAD<2 AND CANTIDAD_PARALELAS<2;
BEGIN
  FOR REG_EOP IN C_EOP LOOP
		DELETE FROM OPERACION_ESTRATEGIA_PERIODO OEP WHERE OEP.ESTRATEGIA_PERIODO=REG_EOP.ID;
		DELETE FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE EOP.ID=REG_EOP.ID;
		COMMIT;  
  END LOOP;
  
  EXCEPTION
    WHEN OTHERS THEN 
      ROLLBACK;
END;

