SELECT SYSDATE FROM DUAL;
/
DECLARE
  REG_OPER OPERACION%ROWTYPE;
CURSOR C_OPER IS
  SELECT OPER2.ID_INDIVIDUO, OPER2.FECHA_APERTURA FROM OPERACION OPER1 
			INNER JOIN OPERACION OPER2
				ON OPER1.ID_INDIVIDUO=OPER2.ID_INDIVIDUO
				AND OPER2.FECHA_APERTURA>OPER1.FECHA_APERTURA AND OPER2.FECHA_APERTURA<=OPER1.FECHA_CIERRE
			INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER1.ID_INDIVIDUO AND (P.FECHA_PROCESO)>=TRUNC(SYSDATE)
			WHERE ROWNUM<10;
BEGIN
  FOR i IN 1..10 LOOP
		FOR REG_OPER IN C_OPER LOOP
			DELETE FROM OPERACION WHERE ID_INDIVIDUO=REG_OPER.ID_INDIVIDUO AND FECHA_APERTURA=REG_OPER.FECHA_APERTURA;
			COMMIT;
		END LOOP;
  END LOOP;
END;	
/
SELECT SYSDATE FROM DUAL;
/
SELECT OPER2.ID_INDIVIDUO, OPER2.FECHA_APERTURA FROM OPERACION OPER1 
			INNER JOIN OPERACION OPER2
				ON OPER1.ID_INDIVIDUO=OPER2.ID_INDIVIDUO
				AND OPER2.FECHA_APERTURA>OPER1.FECHA_APERTURA AND OPER2.FECHA_APERTURA<=OPER1.FECHA_CIERRE
			INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER1.ID_INDIVIDUO AND (P.FECHA_PROCESO)>=TRUNC(SYSDATE)
			WHERE ROWNUM<10;
/
SELECT SYSDATE FROM DUAL;
/
