SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI') FROM DUAL;
/
DECLARE 
--  REG_EOP ESTRATEGIA_OPERACION_PERIODO%ROWTYPE;
--CURSOR C_EOP IS
--  SELECT EOP.ID FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE PIPS_TOTALES<0 AND PIPS_TOTALES_PARALELAS<0 AND ROWNUM<10000;
BEGIN
  --FOR REG_EOP IN C_EOP LOOP
	FOR i IN 1..1000 LOOP
		--DELETE FROM OPERACION_ESTRATEGIA_PERIODO OEP WHERE OEP.ESTRATEGIA_PERIODO=REG_EOP.ID;
		DELETE FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE PIPS_TOTALES<0 AND PIPS_TOTALES_PARALELAS<0 AND ROWNUM<=100;
		COMMIT;  
  END LOOP;
  
  EXCEPTION
    WHEN OTHERS THEN 
      ROLLBACK;
END;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI') FROM DUAL;
/