DECLARE
--REG_INDIVIDUO VARCHAR2(100);
--CURSOR C_INDIVIDUO IS SELECT DISTINCT SEM.ID_INDIVIDUO FROM OPERACION_X_SEMANA SEM
--  WHERE NOT EXISTS (SELECT 1 FROM OPERACIONES_ACUM_SEMANA_CONSOL OPC WHERE OPC.ID_INDIVIDUO=SEM.ID_INDIVIDUO);
BEGIN

  FOR i IN 1..1 LOOP
    INSERT INTO OPERACIONES_ACUM_SEMANA_CONSOL (ID_INDIVIDUO, SEMANA, FECHA_SEMANA, PIPS, CANTIDAD, FECHA_HISTORICO)
      SELECT TMP.ID_INDIVIDUO, SEMANAS.SEMANA, SEMANAS.FECHA_SEMANA, SUM(TMP.PIPS) PIPS, SUM(TMP.CANTIDAD) CANTIDAD,
      MAX(P.FECHA_HISTORICO) FECHA_HISTORICO
      FROM OPERACION_X_SEMANA TMP
        INNER JOIN PROCESO P ON P.ID_INDIVIDUO=TMP.ID_INDIVIDUO  
        INNER JOIN (SELECT DISTINCT SEM.FECHA_SEMANA, SEMANA FROM OPERACION_X_SEMANA SEM) SEMANAS
        ON TMP.FECHA_SEMANA<SEMANAS.FECHA_SEMANA
      WHERE --TMP.ID_INDIVIDUO='1453664590875.284' AND
      --NOT EXISTS (SELECT 1 FROM OPERACIONES_ACUM_SEMANA_CONSOL OPC WHERE OPC.ID_INDIVIDUO=TMP.ID_INDIVIDUO)
      TMP.ID_INDIVIDUO IN (SELECT ID_INDIVIDUO FROM (
           SELECT DISTINCT SEM.ID_INDIVIDUO FROM OPERACION_X_SEMANA SEM
            WHERE NOT EXISTS (SELECT 1 FROM OPERACIONES_ACUM_SEMANA_CONSOL OPC WHERE OPC.ID_INDIVIDUO=SEM.ID_INDIVIDUO)
            ) WHERE ROWNUM<100)
      AND SEMANAS.FECHA_SEMANA>=TO_DATE('20110101','YYYYMMDD')
      --AND TMP.ID_INDIVIDUO=REG_INDIVIDUO.ID_INDIVIDUO
      GROUP BY TMP.ID_INDIVIDUO, SEMANAS.SEMANA, SEMANAS.FECHA_SEMANA;
      COMMIT;
    END LOOP;
END;