DECLARE 
  REG_INDIVIDUO PROCESO%ROWTYPE;
CURSOR C_II IS
  SELECT OPER.ID_INDIVIDUO, MAX(OPER.FECHA_CIERRE) FECHA_HISTORICO FROM OPERACION OPER
		INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
			AND (OPER.FECHA_APERTURA>P.FECHA_HISTORICO OR OPER.FECHA_CIERRE>P.FECHA_HISTORICO)
			--AND P.ID_INDIVIDUO='1477365411387.12590'
		GROUP BY OPER.ID_INDIVIDUO;  
BEGIN
  FOR REG_INDIVIDUO IN C_II LOOP
		UPDATE PROCESO P SET FECHA_PROCESO=SYSDATE, FECHA_HISTORICO=REG_INDIVIDUO.FECHA_HISTORICO
		WHERE P.ID_INDIVIDUO=REG_INDIVIDUO.ID_INDIVIDUO;
		COMMIT;  
  END LOOP;
  
  EXCEPTION
    WHEN OTHERS THEN 
      ROLLBACK;
END;

