DROP TABLE OLD_OPER_ACUM_MES_ANYO;
DROP TABLE OLD_OPER_ACUM_MES_CONSOL;
DROP TABLE OPERACION_X_ANYO;
DROP TABLE OPERACION_X_MES;
DROP TABLE PIPS_MENSUALES_INDIVIDUO;
DROP TABLE TEMP_INDIVIDUO;
DROP TABLE TEMP_OPERACIONES_NEGATIVAS;
DROP TABLE TEMP_OPERACIONES_POSITIVAS;
DROP TABLE TEMP_ROWID_ANYO;
DROP TABLE TEMP_ROWID_CONSOL;
DROP TABLE TEMP_ROWID_MES;

TRUNCATE TABLE TENDENCIA_PROCESADA;
TRUNCATE TABLE TENDENCIA;
TRUNCATE TABLE TENDENCIA_PROCESADA;