DECLARE 
  P_FECHA DATE;
  P_COUNT INTEGER;
  REG_ESTRATEGIA ESTRATEGIA_OPERACION_PERIODO%ROWTYPE;
CURSOR C_ESTRATEGIAS(F IN DATE) IS
  SELECT EOP.ID FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE EOP.FECHA_FINAL>F;
  
BEGIN
  P_FECHA:=TO_DATE('2016/09/11 00:00', 'YYYY/MM/DD HH24:MI');
  P_COUNT := 0;

/*DELETE FROM DATOHISTORICO DH WHERE DH.FECHA>P_FECHA;
COMMIT;

DELETE FROM OPERACION OPER WHERE FECHA_APERTURA>P_FECHA;

UPDATE OPERACION OPER SET FECHA_CIERRE=NULL 
  WHERE FECHA_APERTURA<=P_FECHA AND FECHA_CIERRE>P_FECHA;
COMMIT;

DELETE FROM OPERACION_X_SEMANA WHERE ID_INDIVIDUO IN 
  (SELECT P.ID_INDIVIDUO FROM PROCESO P WHERE P.FECHA_HISTORICO>P_FECHA);
DELETE FROM OPERACIONES_ACUM_SEMANA_MES WHERE ID_INDIVIDUO IN 
  (SELECT P.ID_INDIVIDUO FROM PROCESO P WHERE P.FECHA_HISTORICO>P_FECHA);
DELETE FROM OPERACIONES_ACUM_SEMANA_ANYO WHERE ID_INDIVIDUO IN 
  (SELECT P.ID_INDIVIDUO FROM PROCESO P WHERE P.FECHA_HISTORICO>P_FECHA);
DELETE FROM OPERACIONES_ACUM_SEMANA_CONSOL WHERE ID_INDIVIDUO IN 
  (SELECT P.ID_INDIVIDUO FROM PROCESO P WHERE P.FECHA_HISTORICO>P_FECHA);
DELETE FROM PREVIO_TOFILESTRING WHERE ID_INDIVIDUO IN 
  (SELECT P.ID_INDIVIDUO FROM PROCESO P WHERE P.FECHA_HISTORICO>P_FECHA);
COMMIT;

UPDATE PROCESO P SET P.FECHA_HISTORICO=P_FECHA, FECHA_PROCESO=SYSDATE WHERE P.FECHA_HISTORICO>P_FECHA;
COMMIT;
*/
FOR REG_ESTRATEGIA IN C_ESTRATEGIAS(P_FECHA) LOOP
	DELETE FROM OPERACION_ESTRATEGIA_PERIODO OP 
	  WHERE OP.ESTRATEGIA_PERIODO=REG_ESTRATEGIA.ID;
  
	DELETE FROM ESTRATEGIA_OPERACION_PERIODO EOP 
	WHERE EOP.ID=REG_ESTRATEGIA.ID;

  P_COUNT := P_COUNT+1;
  IF (P_COUNT >= 100) THEN
    COMMIT;
    P_COUNT := 0;
  END IF;

END LOOP;

COMMIT;

END;