DECLARE

REG_INDIVIDUO INDIVIDUO%ROWTYPE;
REG_INDIVIDUO_REPETIDO INDIVIDUOS_REPETIDOS%ROWTYPE;

CURSOR C_REPETIDOS IS 
SELECT DISTINCT REP.ID_INDIVIDUO1, REP.ID_INDIVIDUO2 FROM INDIVIDUOS_REPETIDOS_OPER REP
  INNER JOIN INDICADOR_INDIVIDUO_TENDENCIAS IIT1 ON IIT1.ID_INDIVIDUO=REP.ID_INDIVIDUO1
  INNER JOIN INDICADOR_INDIVIDUO_TENDENCIAS IIT2 ON IIT2.ID_INDIVIDUO=REP.ID_INDIVIDUO2;

BEGIN

  FOR REG_INDIVIDUO_REPETIDO IN C_REPETIDOS LOOP
    --DBMS_OUTPUT.PUT_LINE('REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2='||REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2);
  	DELETE FROM TENDENCIA WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    DELETE FROM PROCESO WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    DELETE FROM OPERACION WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;

    DELETE FROM INDICADOR_INDIVIDUO WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    DELETE FROM INDICADOR_INDIVIDUO_TENDENCIAS WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    DELETE FROM INDIVIDUO WHERE ID=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    COMMIT;
  END LOOP;

END;
/