DECLARE

REG_INDIVIDUO INDIVIDUO%ROWTYPE;
REG_INDIVIDUO_REPETIDO INDIVIDUOS_REPETIDOS%ROWTYPE;
CURSOR C_INDIVIDUOS IS 
  SELECT IND.* FROM INDIVIDUO IND 
--  WHERE IND.ID IN (SELECT OPERB.ID_INDIVIDUO FROM OPERACION_BASE OPERB)
  ORDER BY ID DESC;

CURSOR C_REPETIDOS (ID_INDIVIDUO_BASE IN VARCHAR2) IS 
  SELECT * FROM INDIVIDUOS_REPETIDOS
  WHERE ID_INDIVIDUO1=ID_INDIVIDUO_BASE;
BEGIN

FOR REG_INDIVIDUO IN C_INDIVIDUOS LOOP
  --DBMS_OUTPUT.PUT_LINE('REG_INDIVIDUO.ID='||REG_INDIVIDUO.ID);
  FOR REG_INDIVIDUO_REPETIDO IN C_REPETIDOS(REG_INDIVIDUO.ID) LOOP
    --DBMS_OUTPUT.PUT_LINE('REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2='||REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2);
    DELETE FROM PROCESO WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    DELETE FROM OPERACION WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    DELETE FROM OPERACION_BASE WHERE ID_INDIVIDUO=REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2;
    SMART_DELETE(REG_INDIVIDUO_REPETIDO.ID_INDIVIDUO2, 'DUPLICADO', REG_INDIVIDUO.ID);
  END LOOP;
  COMMIT;  
END LOOP;

END;
/