DECLARE

REG_INDIVIDUO INDIVIDUO%ROWTYPE;
CURSOR C_INDIVIDUOS IS 
SELECT IND.* FROM PROCESO P 
  INNER JOIN INDIVIDUO IND ON IND.ID=P.ID_INDIVIDUO
  INNER JOIN 
      (SELECT OP.ID_INDIVIDUO, count(*), ROUND(AVG(PIPS)) PIPS, 
      ROUND(AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60), 2) DUR FROM OPERACION OP
      GROUP BY OP.ID_INDIVIDUO
      HAVING AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60)<5) OPER
    ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
WHERE P.FECHA_HISTORICO>TO_DATE('20120101', 'YYYYMMDD');

BEGIN

FOR REG_INDIVIDUO IN C_INDIVIDUOS LOOP
  DELETE FROM TENDENCIA WHERE ID_INDIVIDUO=REG_INDIVIDUO.ID;
  DELETE FROM PROCESO WHERE ID_INDIVIDUO=REG_INDIVIDUO.ID;
  DELETE FROM OPERACION WHERE ID_INDIVIDUO=REG_INDIVIDUO.ID;
  SMART_DELETE(REG_INDIVIDUO.ID, 'MAL_PIP', NULL);
END LOOP;

END;
/

SELECT COUNT(*) FROM PROCESO P 
  INNER JOIN INDIVIDUO IND ON IND.ID=P.ID_INDIVIDUO
  INNER JOIN 
      (SELECT OP.ID_INDIVIDUO, count(*), ROUND(AVG(PIPS)) PIPS, 
      ROUND(AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60), 2) DUR FROM OPERACION OP
      GROUP BY OP.ID_INDIVIDUO
      HAVING AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60)<5) OPER
    ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
WHERE P.FECHA_HISTORICO>TO_DATE('20120101', 'YYYYMMDD');

