CREATE OR REPLACE
  FUNCTION CALCULAR_CLOSE_PRICE_TP(
      FECHA_CURRENT IN DATE )
    RETURN NUMBER
  AS
    CLOSE_PRICE NUMBER;
    FECHA_PREV  DATE;
    REG_DH FOREX.DATOHISTORICO%ROWTYPE;
    CURSOR C_DATOHISTORICO(FECHA_PROCESO IN DATE)
    IS
      SELECT * FROM DATOHISTORICO WHERE FECHA=FECHA_PROCESO;-- AND PAR=PAR_PROCESO;
  BEGIN
    SELECT MIN(FECHA)
    INTO FECHA_PREV
    FROM DATOHISTORICO
    WHERE FECHA > FECHA_CURRENT;-- AND PAR=PAR_PROCESO;
    OPEN C_DATOHISTORICO(FECHA_PREV);
    FETCH C_DATOHISTORICO INTO REG_DH;
    CLOSE_PRICE := REG_DH.LOW;
    CLOSE C_DATOHISTORICO;
    RETURN CLOSE_PRICE;
  END CALCULAR_CLOSE_PRICE_TP;