
WITH TIEMPO_TENDENCIA AS (
	SELECT (120) T2H, (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*3/24)*24*60 T3D, (24*5/24)*24*60 T5D, (24*10/24)*24*60 T10D,
		--0.2 R2_MINIMO, 0.0001 PENDIENTE_MINIMA,
		0.8 R2_MINIMO, 0.002 PENDIENTE_MINIMA, 15 MINPIPS,
		--0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.2 PORC2D, 0.2 PORC5D, 0.3 PORC10D,
		0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.15 PORC2D, 0.15 PORC3D, 0.2 PORC5D, 0.2 PORC10D,
		7 CANTIDAD_TENDENCIAS,
		(24*5/24)*24*60  TIEMPO_PROYECCION, (24*5/24)*24*60 TIEMPO_REGRESION, (24*2/24)*24*60 TIEMPO_MAX_MIN,
		--V_DATE FECHA_PROCESO,
		TO_DATE('2017.02.09 03:59', 'YYYY/MM/DD HH24:MI') FECHA_PROCESO,
		'BUY_SELL_20170204-2' TIPO_TENDENCIA1, NULL TIPO_TENDENCIA2, NULL TIPO_TENDENCIA3 FROM DUAL),
TENDENCIA_6H AS (SELECT '6H' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_12H AS (SELECT '12H' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_1D AS (SELECT '1D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_2D AS (SELECT '2D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_3D AS (SELECT '3D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T3D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_5D AS (SELECT '5D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_10D AS (SELECT '10D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
		ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
		COUNT(*) CANTIDAD,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T10D
		AND TEN.FECHA_BASE<=TT.FECHA_PROCESO AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
		
	GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
PONDERADO AS (SELECT 'TOTAL' PERIODO, TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA,
		(ROUND((NVL(TEN6H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)))*TT.PORC6H
		+NVL(TEN12H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO))*TT.PORC12H
		+MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC1D
		+MULTIPLE_NVL(TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC2D
		+MULTIPLE_NVL(TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC3D
		+NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC5D
		+TEN10D.PRECIO_CALCULADO*TT.PORC10D),5)) PRECIO_CALCULADO,
		TEN10D.CANTIDAD CANTIDAD, TEN10D.MINFETENDENCIA, TEN10D.MAXFETENDENCIA
FROM TIEMPO_TENDENCIA TT, TENDENCIA_10D TEN10D
	LEFT JOIN TENDENCIA_6H TEN6H ON TEN10D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_12H TEN12H ON TEN10D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_1D TEN1D ON TEN10D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_2D TEN2D ON TEN10D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_3D TEN3D ON TEN10D.FECHA_TENDENCIA=TEN3D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_5D TEN5D ON TEN10D.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA)
--SELECT * FROM PONDERADO ORDER BY FECHA_TENDENCIA ASC
SELECT * FROM TENDENCIA_1D ORDER BY FECHA_TENDENCIA ASC
;