
SELECT INDE.ID_INDIVIDUO, 
  --MIN(PTFS.PIPS_SEMANA),
	--ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES))/4),
  INDE.FECHA_SEMANA, INDE.FECHA_SEMANA+7
  --,MAX(EOP.FECHA), MAX(EOP.FECHA_FINAL) 
FROM INDIVIDUO_X_ESTRATEGIA INDE
	--INNER JOIN PREVIO_TOFILESTRING PTFS ON PTFS.ROWID=INDE.PTFS_ROWID
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO EOP ON
		--EOP.ID=INDE.ESTRATEGIA_PERIODO
		EOP.ROWID=INDE.EOP_ROWID
  WHERE 
	(EOP.PIPS_TOTALES>1000
	  AND EOP.PIPS_TOTALES_PARALELAS>1000
	 )
  GROUP BY INDE.ID_INDIVIDUO, INDE.FECHA_SEMANA;


SELECT INDE.ID_INDIVIDUO, 
  --MIN(PTFS.PIPS_SEMANA),
	--ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES))/4),
  INDE.FECHA_SEMANA, INDE.FECHA_SEMANA+7
  --MAX(EOP.FECHA), MAX(EOP.FECHA_FINAL) 
FROM INDIVIDUO_X_ESTRATEGIA INDE
	--INNER JOIN PREVIO_TOFILESTRING PTFS ON PTFS.ROWID=INDE.PTFS_ROWID
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO EOP ON EOP.ROWID=INDE.EOP_ROWID
  WHERE 
	((EOP.TIPO_OPERACION='BUY' AND EOP.PIPS_TOTALES>1000 
	  AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
	  AND EOP.PIPS_TOTALES_PARALELAS>3000
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>1000 AND EOP.PIPS_AGRUPADO_HORAS>1000 AND EOP.PIPS_AGRUPADO_DIAS>1000)
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)<10	  
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)>1
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND EOP.CANTIDAD/((EOP.FECHA_FINAL-EOP.FECHA_INICIAL)/30)>1
	  AND (EOP.PIPS_TOTALES/EOP.CANTIDAD)>200
	  --AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200
	 ) OR
	(EOP.TIPO_OPERACION='SELL' AND EOP.PIPS_TOTALES>1000
	  AND EOP.PIPS_TOTALES_PARALELAS>1000
	 ) OR
	(EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200	
	 )
	)
  GROUP BY INDE.ID_INDIVIDUO, INDE.FECHA_SEMANA;

--drop INDEX INDE_IDX2;

CREATE INDEX "FOREX"."INDE_IDX2" ON "FOREX"."INDIVIDUO_X_ESTRATEGIA" (ID_INDIVIDUO DESC, ESTRATEGIA_PERIODO DESC, FECHA_SEMANA DESC, 
	(FECHA_SEMANA+7) DESC, EOP_ROWID DESC, PTFS_ROWID DESC ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" ;