SELECT 'EOP' NOMBRE, COUNT(*), SYSDATE FROM ESTRATEGIA_OPERACION_PERIODO
UNION ALL
SELECT 'EOP_NEG' NOMBRE, COUNT(*), SYSDATE FROM ESTRATEGIA_OPERACION_PERIODO EOP 
WHERE PIPS_TOTALES<0 AND PIPS_TOTALES_PARALELAS<0
--UNION ALL SELECT 'OEP' NOMBRE, COUNT(*) FROM OPERACION_ESTRATEGIA_PERIODO
;

--DELETE FROM ESTRATEGIA_OPERACION_PERIODO EOP WHERE PIPS_TOTALES<0 AND PIPS_TOTALES_PARALELAS<0 AND ROWNUM<100;

