SET ECHO ON;
SET feedback ON;
SPOOL ON;

SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_EOP...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_EOP"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARALELAS_EOP...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARALELAS_EOP"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PTFS...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PTFS"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR_SELL...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARA_OPERAR_SELL"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR_BUY...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARA_OPERAR_BUY"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR_BOTH...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARA_OPERAR_BOTH"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'TRUNCATING TMP_TOFILESTRING2...' FROM DUAL;
/
TRUNCATE TABLE TMP_TOFILESTRING2;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'INSERTING INTO TMP_TOFILESTRING2...' FROM DUAL;
/
INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2, FECHA_ORDER1, FECHA_ORDER2)
SELECT FILT.ID_INDIVIDUO,
			MIN(CRITERIO_ORDER1),
			MIN(CRITERIO_ORDER2),
			VIGENCIA1, VIGENCIA1+7,
			MIN(FECHA_ORDER1), MIN(FECHA_ORDER2)
	FROM (SELECT FILTERED.ID_INDIVIDUO,
				NVL(MIN(FILTERED.PIPS_TOTALES),0) CRITERIO_ORDER1,
				NVL(MIN(FILTERED.PIPS_TOTALES),0) CRITERIO_ORDER2,
				--ROUND((NVL(MIN(FILTERED.PIPS_MES),0)+NVL(MIN(FILTERED.PIPS_ANYO),0)+MIN(PIPS_TOTALES))/3) CRITERIO_ORDER2,
				--ROUND((NVL(MIN(FILTERED.PIPS_ANYO),0)+NVL(MIN(FILTERED.PIPS_MES),0)+NVL(MIN(FILTERED.PIPS_ANYO),0))/3) CRITERIO_ORDER2,
				FILTERED.FECHA_SEMANA VIGENCIA1,
				MAX(FILTERED.FECHA) FECHA_ORDER1, MAX(FILTERED.FECHA_FINAL) FECHA_ORDER2
			FROM FILTERED_PARA_OPERAR_SELL FILTERED
			WHERE FILTERED.CANTIDAD/((FILTERED.FECHA_FINAL-FILTERED.FECHA_INICIAL)/30)<10 AND
			(FILTERED.PIPS_AGRUPADO_MINUTOS>1000 AND FILTERED.PIPS_AGRUPADO_HORAS>1000 AND FILTERED.PIPS_AGRUPADO_DIAS>1000)
			AND (FILTERED.CANTIDAD_PARALELAS/FILTERED.CANTIDAD)<10	  
			AND (FILTERED.CANTIDAD_PARALELAS/FILTERED.CANTIDAD)>1
			AND FILTERED.CANTIDAD/((FILTERED.FECHA_FINAL-FILTERED.FECHA_INICIAL)/30)>1
			AND (FILTERED.PIPS_TOTALES/FILTERED.CANTIDAD)>200
		GROUP BY FILTERED.ID_INDIVIDUO, FILTERED.FECHA_SEMANA
		UNION ALL
		SELECT FILTERED.ID_INDIVIDUO,
				NVL(MIN(FILTERED.PIPS_MES),0) CRITERIO_ORDER1,
				NVL(MIN(FILTERED.PIPS_SEMANA),0) CRITERIO_ORDER2,
				--ROUND((NVL(MIN(FILTERED.PIPS_MES),0)+NVL(MIN(FILTERED.PIPS_ANYO),0)+MIN(PIPS_TOTALES))/3) CRITERIO_ORDER2,
				--ROUND((NVL(MIN(FILTERED.PIPS_ANYO),0)+NVL(MIN(FILTERED.PIPS_MES),0)+NVL(MIN(FILTERED.PIPS_ANYO),0))/3) CRITERIO_ORDER2,
				FILTERED.FECHA_SEMANA VIGENCIA1,
				MAX(FILTERED.FECHA) FECHA_ORDER1, MAX(FILTERED.FECHA_FINAL) FECHA_ORDER2
			FROM FILTERED_PARA_OPERAR_BUY FILTERED
			WHERE FILTERED.CANTIDAD/((FILTERED.FECHA_FINAL-FILTERED.FECHA_INICIAL)/30)<10
		GROUP BY FILTERED.ID_INDIVIDUO, FILTERED.FECHA_SEMANA
		UNION ALL
				SELECT FILTERED.ID_INDIVIDUO,
				NVL(MIN(FILTERED.PIPS_TOTALES),0) CRITERIO_ORDER1,
				NVL(MIN(FILTERED.PIPS_TOTALES),0) CRITERIO_ORDER2,
				--ROUND((NVL(MIN(FILTERED.PIPS_MES),0)+NVL(MIN(FILTERED.PIPS_ANYO),0)+MIN(PIPS_TOTALES))/3) CRITERIO_ORDER2,
				--ROUND((NVL(MIN(FILTERED.PIPS_ANYO),0)+NVL(MIN(FILTERED.PIPS_MES),0)+NVL(MIN(FILTERED.PIPS_ANYO),0))/3) CRITERIO_ORDER2,
				FILTERED.FECHA_SEMANA VIGENCIA1,
				MAX(FILTERED.FECHA) FECHA_ORDER1, MAX(FILTERED.FECHA_FINAL) FECHA_ORDER2
			FROM FILTERED_PARA_OPERAR_BOTH FILTERED
			WHERE FILTERED.CANTIDAD/((FILTERED.FECHA_FINAL-FILTERED.FECHA_INICIAL)/30)<10
		GROUP BY FILTERED.ID_INDIVIDUO, FILTERED.FECHA_SEMANA
	) FILT
GROUP BY FILT.ID_INDIVIDUO, FILT.VIGENCIA1;
commit;
/
@"d:\ricardorq85\JavaProjects\Git\genetic-forex\ForexGenetic\sql\ToFileStringFromTEMP_TOFILESTRING.sql";
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR...' FROM DUAL;
/
