WITH
	PARAMETROS AS (
		SELECT TO_DATE('2015/12/31 09:39', 'YYYY/MM/DD HH24:MI') FE1, 
			TO_DATE('2016/12/31 09:39', 'YYYY/MM/DD HH24:MI') FE2 FROM DUAL
	),
	DIAS AS (
		SELECT TRUNC(DH.FECHA) FECHA
		FROM PARAMETROS P, DATOHISTORICO DH
		WHERE DH.FECHA BETWEEN P.FE1 AND P.FE2
		GROUP BY TRUNC(DH.FECHA) 
	),
	COUNT_DIAS AS (
		SELECT D.FECHA, COUNT(TEN.FECHA_BASE) CANTIDAD
		FROM DIAS D LEFT JOIN TENDENCIA TEN ON D.FECHA=TRUNC(TEN.FECHA_BASE)
		GROUP BY D.FECHA
		ORDER BY CANTIDAD aSC, D.FECHA deSC
	)
	SELECT * FROM COUNT_DIAS
;
