CREATE MATERIALIZED VIEW TENDENCIA_ULTIMOMES 
NOCACHE 
USING INDEX 
REFRESH ON DEMAND 
FORCE 
WITH ROWID 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS 
SELECT *    
FROM TENDENCIA WHERE FECHA_BASE>SYSDATE-40;

CREATE INDEX TENDENCIA_ULTIMOMES_INDEX1 ON TENDENCIA_ULTIMOMES (FECHA_BASE);

  CREATE INDEX "FOREX"."FETENDENCIAUm_IDX" ON "FOREX"."TENDENCIA_ULTIMOMES" ("FECHA_TENDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 551550976 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "FOREX"."TENDENCIAUM_IDX1" ON "FOREX"."TENDENCIA_ULTIMOMES" ("FECHA_BASE" DESC, "FECHA_TENDENCIA", TRUNC("FECHA_TENDENCIA",'fmhh24'), "FOREX"."WEEK_MINUTES"("FECHA_TENDENCIA","FECHA_BASE") DESC, "TIPO_TENDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" ;

  CREATE INDEX "FOREX"."TENDENCIAUM_IDX2" ON "FOREX"."TENDENCIA_ULTIMOMES" ("ID_INDIVIDUO", "FECHA_BASE", "FECHA_TENDENCIA", "FECHA_APERTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1702887424 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "FOREX"."TENDENCIAUM_IDX5" ON "FOREX"."TENDENCIA_ULTIMOMES" ("ID_INDIVIDUO", "FECHA_BASE", "FECHA_APERTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1426063360 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
