-- USER SQL
CREATE USER FOREX IDENTIFIED BY forex	
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO FOREX;
GRANT CREATE TABLE TO FOREX ;
GRANT CREATE ANY INDEX TO FOREX ;
GRANT SELECT ANY TABLE TO FOREX ;
GRANT DROP ANY TYPE TO FOREX ;
GRANT CREATE ANY VIEW TO FOREX ;
GRANT CREATE ANY TRIGGER TO FOREX ;
GRANT DROP ANY SEQUENCE TO FOREX ;
GRANT DROP ANY TABLE TO FOREX ;
GRANT EXECUTE ANY PROCEDURE TO FOREX ;
GRANT DROP ANY VIEW TO FOREX ;
GRANT ALTER ANY TRIGGER TO FOREX ;
GRANT CREATE SYNONYM TO FOREX ;
GRANT ALTER ANY TABLE TO FOREX ;
GRANT CREATE VIEW TO FOREX ;
GRANT DROP ANY INDEX TO FOREX ;
GRANT CREATE ANY TABLE TO FOREX ;
GRANT CREATE SESSION TO FOREX ;
GRANT CREATE MATERIALIZED VIEW TO FOREX ;

GRANT UNLIMITED TABLESPACE TO FOREX;
GRANT CREATE PROCEDURE TO FOREX;
GRANT IMP_FULL_DATABASE TO FOREX;