CREATE TABLE INDIVIDUO (
  ID VARCHAR2(50 CHAR) NOT NULL,
  PARENT_ID_1 VARCHAR2(50 CHAR),
  PARENT_ID_2 VARCHAR2(50 CHAR),
  TAKE_PROFIT NUMBER(5),
  STOP_LOSS NUMBER(5), LOTE NUMBER(5,2), INITIAL_BALANCE NUMBER(5), CREATION_DATE DATE
);

alter table "FOREX"."INDIVIDUO" add constraint INDIVIDUO_PK primary key("ID") ;


  CREATE TABLE "FOREX"."INDICADOR_INDIVIDUO"
   (	"ID_INDICADOR" VARCHAR2(50 BYTE),
	"ID_INDIVIDUO" VARCHAR2(50 BYTE),
	"INTERVALO_INFERIOR" NUMBER(10,5),
	"INTERVALO_SUPERIOR" NUMBER(10,5),
	"TIPO" VARCHAR2(10 BYTE),
	 CONSTRAINT "INDICADOR_INDIVIDUO_PK" PRIMARY KEY ("ID_INDICADOR", "ID_INDIVIDUO", "TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "INDICADOR_INDIVIDUO_FK1" FOREIGN KEY ("ID_INDICADOR")
	  REFERENCES "FOREX"."INDIVIDUO" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "FOREX"."INDIVIDUO_BORRADO"
   (	"ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"PARENT_ID_1" VARCHAR2(50 CHAR),
	"PARENT_ID_2" VARCHAR2(50 CHAR),
	"TAKE_PROFIT" NUMBER(5,0),
	"STOP_LOSS" NUMBER(5,0),
	"LOTE" NUMBER(5,2),
	"INITIAL_BALANCE" NUMBER(5,0),
	"CREATION_DATE" DATE,
	 CONSTRAINT "INDIVIDUO_BORRADO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "FOREX"."INDICADOR_INDIVIDUO_BORRADO"
   (	"ID_INDICADOR" VARCHAR2(50 BYTE),
	"ID_INDIVIDUO" VARCHAR2(50 BYTE),
	"INTERVALO_INFERIOR" NUMBER(10,5),
	"INTERVALO_SUPERIOR" NUMBER(10,5),
	"TIPO" VARCHAR2(10 BYTE),
	 CONSTRAINT "INDICADOR_INDIVIDUO_BORRADO_PK" PRIMARY KEY ("ID_INDICADOR", "ID_INDIVIDUO", "TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


ALTER TABLE INDICADOR_INDIVIDUO
DROP CONSTRAINT INDICADOR_INDIVIDUO_FK1;

ALTER TABLE INDICADOR_INDIVIDUO
ADD CONSTRAINT INDICADOR_INDIVIDUO_FK1 FOREIGN KEY
(
  ID_INDIVIDUO
)
REFERENCES INDIVIDUO
(
  ID
)
ENABLE;

ALTER TABLE INDICADOR_INDIVIDUO_BORRADO
ADD CONSTRAINT INDIC_INDIV_BORR_FK1 FOREIGN KEY
(
  ID_INDIVIDUO
)
REFERENCES INDIVIDUO_BORRADO
(
  ID
)
ENABLE;


CREATE INDEX INDIC_INDIV_IDX2 ON INDICADOR_INDIVIDUO (ID_INDIVIDUO);
CREATE INDEX INDIC_INDIV_BORR_IDX2 ON INDICADOR_INDIVIDUO_BORRADO (ID_INDIVIDUO);

CREATE INDEX INDIC_INDIV_IDX3 ON INDICADOR_INDIVIDUO (INTERVALO_INFERIOR, INTERVALO_SUPERIOR);
CREATE INDEX INDIC_INDIV_BORR_IDX3 ON INDICADOR_INDIVIDUO_BORRADO (INTERVALO_INFERIOR, INTERVALO_SUPERIOR);

DROP INDEX INDIC_INDIV_IDX2;

CREATE INDEX INDIC_INDIV_IDX2 ON INDICADOR_INDIVIDUO (ID_INDIVIDUO ASC, ID_INDICADOR)
LOGGING
TABLESPACE "USERS"
PCTFREE 10
INITRANS 2
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);

DROP INDEX INDIC_INDIV_BORR_IDX2;

CREATE INDEX INDIC_INDIV_BORR_IDX2 ON INDICADOR_INDIVIDUO_BORRADO (ID_INDIVIDUO ASC, ID_INDICADOR)
LOGGING
TABLESPACE "USERS"
PCTFREE 10
INITRANS 2
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
);
