
  CREATE TABLE "FOREX"."TMP_TOFILESTRING" 
   (	"ID_INDIVIDUO" VARCHAR2(50 BYTE), 
	"CRITERIO_ORDER1" NUMBER, 
	"CRITERIO_ORDER2" NUMBER, 
	"VIGENCIA1" DATE, 
	"VIGENCIA2" DATE, 
	 CONSTRAINT "TMP_TOFILESTRING_PK" PRIMARY KEY ("ID_INDIVIDUO", "VIGENCIA1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "FOREX"."INDEX3" ON "FOREX"."TMP_TOFILESTRING" ("ID_INDIVIDUO" DESC, "CRITERIO_ORDER1" DESC, "CRITERIO_ORDER2" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
