CREATE TABLE OPERACION
(ID_INDIVIDUO VARCHAR2(50), TAKE_PROFIT NUMBER(5), STOP_LOSS NUMBER(10,3),
FECHA_APERTURA DATE, FECHA_CIERRE DATE, SPREAD NUMBER(3), OPEN_PRICE NUMBER(10,5), PIPS NUMBER(5));

ALTER TABLE "FOREX"."OPERACION" ADD CONSTRAINT OPERACION_PK PRIMARY KEY("ID_INDIVIDUO","FECHA_APERTURA") ;
ALTER TABLE OPERACION ADD (LOTE NUMBER(5, 2) );