CREATE OR REPLACE VIEW INTERVALO_INDICADOR_PROCESADOS AS
  SELECT ID_INDICADOR, TIPO,
    ROUND(MIN(II.INTERVALO_SUPERIOR-II.INTERVALO_INFERIOR),5) DIFFMIN,
    ROUND(MAX(II.INTERVALO_SUPERIOR-II.INTERVALO_INFERIOR),5) DIFFMAX
    FROM INDICADOR_INDIVIDUO II 
      INNER JOIN PROCESO P ON P.ID_INDIVIDUO=II.ID_INDIVIDUO AND P.FECHA_HISTORICO>TO_DATE('20160101','YYYYMMDD')
    WHERE II.TIPO='OPEN'
  GROUP BY ID_INDICADOR, TIPO
  ORDER BY ID_INDICADOR ASC, TIPO DESC
;

CREATE OR REPLACE VIEW INTERVALO_INDICADOR_SIN_OPER AS
SELECT ID_INDICADOR, TIPO,
  ROUND(MIN(II.INTERVALO_SUPERIOR-II.INTERVALO_INFERIOR),5) DIFFMIN,
  ROUND(MAX(II.INTERVALO_SUPERIOR-II.INTERVALO_INFERIOR),5) DIFFMAX
  FROM INDICADOR_INDIVIDUO_BORRADO II 
    INNER JOIN INDIVIDUO_BORRADO IND ON IND.ID=II.ID_INDIVIDUO AND IND.TIPO_BORRADO='SIN_OPERACIONES'
  WHERE II.TIPO='OPEN'
GROUP BY ID_INDICADOR, TIPO
ORDER BY ID_INDICADOR ASC, TIPO DESC
;