--DROP TABLE OPERACION_CONSOLIDADAS;
--DROP TABLE OPERACION_X_ANYO;
--DROP TABLE OPERACION_X_MES;
--DROP TABLE OPERACION_X_SEMANA;

/*CREATE TABLE OPERACION_CONSOLIDADAS AS
  SELECT OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, MAX(P.FECHA_HISTORICO) FECHA_HISTORICO, SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD
  FROM OPERACION OPER
    INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO
    INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
  WHERE OPER.FECHA_CIERRE IS NOT NULL
  GROUP BY OPER.ID_INDIVIDUO, IND.TIPO_OPERACION;
  
CREATE TABLE OPERACION_X_ANYO AS
  SELECT OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, MAX(P.FECHA_HISTORICO) FECHA_HISTORICO, TO_CHAR(FECHA_APERTURA, 'YYYY') ANYO, SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD
  FROM OPERACION OPER  
    INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO
    INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
  WHERE OPER.FECHA_CIERRE IS NOT NULL
  GROUP BY OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, TO_CHAR(OPER.FECHA_APERTURA, 'YYYY');

CREATE TABLE OPERACION_X_MES AS
  SELECT OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, MAX(P.FECHA_HISTORICO) FECHA_HISTORICO, 
  TO_CHAR(FECHA_APERTURA, 'YYYYMM') MES, SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD
  FROM OPERACION OPER
    INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO
    INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
  WHERE OPER.FECHA_CIERRE IS NOT NULL
  GROUP BY OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, TO_CHAR(OPER.FECHA_APERTURA, 'YYYYMM');  
*/

CREATE TABLE OPERACION_X_SEMANA AS
  SELECT OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, MAX(P.FECHA_HISTORICO) FECHA_HISTORICO, 
  TO_CHAR(FECHA_APERTURA, 'YYYYWW') SEMANA, SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD, TRUNC(MIN(FECHA_APERTURA),'WW') FECHA_SEMANA
  FROM OPERACION OPER
    INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO
    INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
  WHERE OPER.FECHA_CIERRE IS NOT NULL
  GROUP BY OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, TO_CHAR(OPER.FECHA_APERTURA, 'YYYYWW');
  
--alter table OPERACION_CONSOLIDADAS add constraint OPERACION_CONSOLIDADAS primary key(ID_INDIVIDUO);
--alter table OPERACION_X_ANYO add constraint OPERACION_X_ANYO_PK primary key(ID_INDIVIDUO, ANYO);
--alter table OPERACION_X_MES add constraint OPERACION_X_MES_PK primary key(ID_INDIVIDUO, MES);
alter table OPERACION_X_SEMANA add constraint OPERACION_X_SEMANA_PK primary key(ID_INDIVIDUO, FECHA_SEMANA);


CREATE TABLE SEMANAS AS
SELECT DISTINCT SEM.FECHA_SEMANA, SEMANA FROM OPERACION_X_SEMANA SEM;

ALTER TABLE "FOREX"."SEMANAS" ADD CONSTRAINT "SEMANAS_PK" PRIMARY KEY ("FECHA_SEMANA");
