DROP MATERIALIZED VIEW PDI_MVIEW;
DROP MATERIALIZED VIEW PSI_MVIEW;
DROP MATERIALIZED VIEW PMI_MVIEW;

CREATE MATERIALIZED VIEW PDI_MVIEW
  AS SELECT PD1.ID_INDIVIDUO ID_INDIVIDUO, PD1.DIA DIA1, PD1.MIN_FECHA MIN_FECHA1, PD1.NUM_OPERACIONES NUM_OPERACIONES1, PD1.PIPS PIPS1,
    --PD2.DIA DIA2, PD2.MIN_FECHA MIN2ECHA2, PD2.NUM_OPERACIONES NUM_OPERACIONES2, PD2.PIPS PIPS2,
    --PD3.DIA DIA_F, PD3.MIN_FECHA MIN_FECHA_F, PD3.NUM_OPERACIONES NUM_OPERACIONES_F, PD3.PIPS PIPS_F
      PD2.DIA DIA_F, PD2.MIN_FECHA MIN_FECHA_F, PD2.NUM_OPERACIONES NUM_OPERACIONES_F, PD2.PIPS PIPS_F
    FROM MV_PIPS_DIARIOS_INDIVIDUO PD1
  INNER JOIN MV_PIPS_DIARIOS_INDIVIDUO PD2 ON PD1.ID_INDIVIDUO=PD2.ID_INDIVIDUO
      AND TRUNC(PD2.MIN_FECHA)-TRUNC(PD1.MIN_FECHA)=1 AND PD2.MIN_FECHA>PD1.MIN_FECHA
  --INNER JOIN MV_PIPS_DIARIOS_INDIVIDUO PD3 ON PD1.ID_INDIVIDUO=PD3.ID_INDIVIDUO
    --  AND TRUNC(PD3.MIN_FECHA)-TRUNC(PD2.MIN_FECHA)=1 AND PD3.MIN_FECHA>PD2.MIN_FECHA      
WHERE PD1.DIA LIKE '2012____'
  --AND PD1.ID_INDIVIDUO='1334463374425.3347'
  AND PD1.PIPS>0
  AND PD2.PIPS>0
  --AND PD3.PIPS>0  
;

CREATE MATERIALIZED VIEW PSI_MVIEW AS
SELECT PS1.ID_INDIVIDUO ID_INDIVIDUO, PS1.SEMANA SEMANA1, PS1.MIN_FECHA MIN_FECHA1, PS1.NUM_OPERACIONES NUM_OPERACIONES1, PS1.PIPS PIPS1,
    --PS2.SEMANA SEMANA2, PS2.MIN_FECHA MIN_FECHA2, PS2.NUM_OPERACIONES NUM_OPERACIONES2, PS2.PIPS PIPS2,
    PS2.SEMANA SEMANA_F, PS2.MIN_FECHA MIN_FECHA_F, PS2.NUM_OPERACIONES NUM_OPERACIONES_F, PS2.PIPS PIPS_F
    --PS3.SEMANA SEMANA_F, PS3.MIN_FECHA MIN_FECHA_F, PS3.NUM_OPERACIONES NUM_OPERACIONES_F, PS3.PIPS PIPS_F
  FROM MV_PIPS_SEMANALES_INDIVIDUO PS1
  INNER JOIN MV_PIPS_SEMANALES_INDIVIDUO PS2 ON PS1.ID_INDIVIDUO=PS2.ID_INDIVIDUO
      AND PS2.MIN_FECHA-8<PS1.MIN_FECHA AND PS2.MIN_FECHA>PS1.MIN_FECHA
  INNER JOIN MV_PIPS_SEMANALES_INDIVIDUO PS3 ON PS1.ID_INDIVIDUO=PS3.ID_INDIVIDUO
      AND PS3.MIN_FECHA-8<PS2.MIN_FECHA AND PS3.MIN_FECHA>PS2.MIN_FECHA
WHERE PS1.SEMANA LIKE '2012___'  
  AND PS1.PIPS>0
  AND PS2.PIPS>0
  --AND PS3.PIPS>0
;

CREATE MATERIALIZED VIEW PMI_MVIEW AS
SELECT PM1.ID_INDIVIDUO ID_INDIVIDUO, PM1.MES MES_F, PM1.MIN_FECHA MIN_FECHA_F, 
  PM1.NUM_OPERACIONES NUM_OPERACIONES_F, PM1.PIPS PIPS_F
  FROM MV_PIPS_MENSUALES_INDIVIDUO PM1
WHERE PM1.MES LIKE '2012__'
  AND PM1.PIPS>0
;
