CREATE TABLE PARAMETRO 
(
  NOMBRE VARCHAR2(50 CHAR) NOT NULL 
, VALOR VARCHAR2(100 CHAR) 
, FECHA DATE DEFAULT SYSDATE 
, CONSTRAINT PARAMETRO_PK PRIMARY KEY 
  (
    NOMBRE 
  )
  ENABLE 
);

CREATE INDEX PARAMETRO_INDEX1 ON PARAMETRO (VALOR);