DROP TABLE TOFILESTRING_2D2S1M_2012;

CREATE TABLE TOFILESTRING_2D2S1M_2012 AS
SELECT PS1.ID_INDIVIDUO, TRUNC(MIN(PD1.MIN_FECHA_F)+1) VIGENCIA1, TRUNC(MIN(PD1.MIN_FECHA_F)+1)+1 VIGENCIA2, 
  AVG(PD1.PIPS_F+PS1.PIPS_F) PIPS_PROM
    FROM PDI_MVIEW_2012 PD1 INNER JOIN PSI_MVIEW_2012 PS1 
        ON PS1.ID_INDIVIDUO = PD1.ID_INDIVIDUO AND TO_CHAR(PS1.MIN_FECHA_F, 'WW')=TO_CHAR(PD1.MIN_FECHA1, 'WW')-1
      --INNER JOIN PMI_MVIEW_2012 PM1  ON PM1.ID_INDIVIDUO = PD1.ID_INDIVIDUO 
        --AND TO_CHAR(PM1.MIN_FECHA_F, 'MM')=TO_CHAR(PS1.MIN_FECHA1, 'MM')-1
        --AND TO_CHAR(PM1.MIN_FECHA_F, 'MM')=TO_CHAR(PS1.MIN_FECHA_F, 'MM')-1
      WHERE /*(SELECT SUM(OPER2.PIPS)
            FROM OPERACION OPER2 WHERE OPER2.ID_INDIVIDUO = PD1.ID_INDIVIDUO 
              AND OPER2.FECHA_APERTURA>=TO_DATE(TO_CHAR(ADD_MONTHS(PM1.MIN_FECHA_F,1), 'YYYYMM')||'01', 'YYYYMMDD')
              AND OPER2.FECHA_CIERRE<=PD1.MIN_FECHA_F
              GROUP BY OPER2.ID_INDIVIDUO)>0 
      AND*/ PS1.ID_INDIVIDUO NOT IN (
        SELECT OPER3.ID_INDIVIDUO FROM OPERACION OPER3 WHERE OPER3.ID_INDIVIDUO = PD1.ID_INDIVIDUO
          AND OPER3.FECHA_APERTURA<TRUNC(PD1.MIN_FECHA_F)+1
          AND (OPER3.FECHA_CIERRE IS NULL OR OPER3.FECHA_CIERRE>TRUNC(PD1.MIN_FECHA_F)+1)
        )
    AND EXISTS (
      SELECT COUNT(*) FROM PMI_MVIEW_2012 PM2 
      WHERE PM2.ID_INDIVIDUO=PD1.ID_INDIVIDUO AND TO_CHAR(PM2.MIN_FECHA_F, 'MM')<TO_CHAR(PS1.MIN_FECHA_F, 'MM')
      )
GROUP BY PS1.ID_INDIVIDUO, PD1.MIN_FECHA_F
;

SELECT COUNT(*) FROM TOFILESTRING_2D2S1M_2012;