--DROP MATERIALIZED VIEW INDIVIDUO_X_ESTRATEGIA;

CREATE MATERIALIZED VIEW INDIVIDUO_X_ESTRATEGIA2
NOCACHE 
USING INDEX 
REFRESH ON COMMIT 
FAST 
WITH PRIMARY KEY 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS
SELECT PTFS.ID_INDIVIDUO ID_INDIVIDUO, EOP.ID ESTRATEGIA_PERIODO, PTFS.FECHA_SEMANA	FECHA_SEMANA, PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID
  FROM PREVIO_TOFILESTRING PTFS, ESTRATEGIA_OPERACION_PERIODO EOP
		WHERE (( NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND NVL(PTFS.PIPS_MES,0)>EOP.FILTRO_PIPS_X_MES 
			AND NVL(PTFS.PIPS_ANYO,0)>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND NVL(PTFS.R2_MES,0)>EOP.FILTRO_R2_MES 
			AND NVL(PTFS.R2_ANYO,0)>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND NVL(PTFS.PENDIENTE_MES,0)>EOP.FILTRO_PENDIENTE_MES 
			AND NVL(PTFS.PENDIENTE_ANYO,0)>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7))
		AND PTFS.FECHA_SEMANA>TO_DATE('20141231','YYYYMMDD');

--CREATE INDEX INDIVIDUO_X_ESTRATEGIA_INDEX1 ON INDIVIDUO_X_ESTRATEGIA (ID_INDIVIDUO, ESTRATEGIA_PERIODO, FECHA_SEMANA);
--CREATE INDEX INDE_ROWIDEOP_IDX ON INDIVIDUO_X_ESTRATEGIA (EOP_ROWID);
