
  CREATE TABLE "FOREX"."DATOHISTORICO" 
   (	"PAR" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"MINUTOS" NUMBER(2,0) NOT NULL ENABLE, 
	"PAR_COMPARE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"OPEN" NUMBER(10,5), 
	"LOW" NUMBER(10,5), 
	"HIGH" NUMBER(10,5), 
	"CLOSE" NUMBER(10,5), 
	"VOLUME" NUMBER(10,5), 
	"SPREAD" NUMBER(5,0), 
	"AVERAGE" NUMBER(10,5), 
	"MACD_VALUE" NUMBER(10,5), 
	"MACD_SIGNAL" NUMBER(10,5),
	"COMPARE_VALUE" NUMBER(10,5), 
	"AVERAGE_COMPARE" NUMBER(10,5), 
	"SAR" NUMBER(10,5), 
	"ADX_VALUE" NUMBER(10,5), 
	"ADX_PLUS" NUMBER(10,5), 
	"ADX_MINUS" NUMBER(10,5), 
	"RSI" NUMBER(10,5), 
	"BOLLINGER_UPPER" NUMBER(10,5), 
	"BOLLINGER_LOWER" NUMBER(10,5), 
	"MOMENTUM" NUMBER(10,5), 
	"ICHIMOKUTENKANSEN" NUMBER(10,5), 
	"ICHIMOKUKIJUNSEN" NUMBER(10,5), 
	"ICHIMOKUSENKOUSPANA" NUMBER(10,5), 
	"ICHIMOKUSENKOUSPANB" NUMBER(10,5), 
	"ICHIMOKUCHINKOUSPAN" NUMBER(10,5), 
	 CONSTRAINT "DATOHISTORICO_PK" PRIMARY KEY ("PAR", "MINUTOS", "FECHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX DATOSHISTORICO_IDX1 ON DATOHISTORICO (FECHA);