CREATE TABLE ESTRATEGIA_OPERACION_PERIODO 
(
  PIPS_TOTALES NUMBER(10) NOT NULL 
, CANTIDAD NUMBER(10) NOT NULL 
, FILTRO_PIPS_X_MES NUMBER(10) NOT NULL 
, FILTRO_PIPS_X_ANYO NUMBER(10) NOT NULL 
, FILTRO_PIPS_TOTALES NUMBER(10) NOT NULL 
, FIRST_ORDER VARCHAR2(100) NOT NULL 
, SECOND_ORDER VARCHAR2(100) 
, CONSTRAINT ESTRATEGIA_OPERACION_PERIO_PK PRIMARY KEY 
  (
    FILTRO_PIPS_X_MES 
  , FILTRO_PIPS_X_ANYO 
  , FILTRO_PIPS_TOTALES 
  , FIRST_ORDER 
  )
  ENABLE 
);
