SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'CREATING FILTERED_PARA_OPERAR...' FROM DUAL;
/
DROP MATERIALIZED VIEW FILTERED_PARA_OPERAR_SELL ;
/
CREATE MATERIALIZED VIEW FILTERED_PARA_OPERAR_SELL
NOCACHE 
USING INDEX 
REFRESH ON DEMAND 
FORCE 
WITH PRIMARY KEY 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS
SELECT PTFS.ID_INDIVIDUO ID_INDIVIDUO, PTFS.FECHA_SEMANA FECHA_SEMANA,
	PTFS.PIPS_SEMANA, PTFS.PIPS_MES, PTFS.PIPS_ANYO, PTFS.PIPS_TOTALES, 
	EOP.FECHA, EOP.FECHA_INICIAL, EOP.FECHA_FINAL,
	PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID
  FROM PREVIO_TOFILESTRING PTFS, ESTRATEGIA_OPERACION_PERIODO EOP
		WHERE ( --PTFS.PIPS_SEMANA IS NOT NULL AND PTFS.PIPS_SEMANA>0 AND
			 NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>EOP.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND PTFS.R2_MES>EOP.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>EOP.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7)   
	AND ((EOP.TIPO_OPERACION='SELL' AND EOP.PIPS_TOTALES>1000
		AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
		AND EOP.PIPS_TOTALES_PARALELAS>3000
	 ) OR
	(EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200	
	 )
	)
	AND EOP.TIPO_OPERACION='SELL'
	AND PTFS.FECHA_SEMANA>TO_DATE('20131231','YYYYMMDD')	
	;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'CREATED FILTERED_PARA_OPERAR...' FROM DUAL;
/
DROP MATERIALIZED VIEW FILTERED_PARA_OPERAR_BUY ;
/
CREATE MATERIALIZED VIEW FILTERED_PARA_OPERAR_BUY
NOCACHE 
USING INDEX 
REFRESH ON DEMAND 
FORCE 
WITH PRIMARY KEY 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS
SELECT PTFS.ID_INDIVIDUO ID_INDIVIDUO, PTFS.FECHA_SEMANA FECHA_SEMANA,
	PTFS.PIPS_SEMANA, PTFS.PIPS_MES, PTFS.PIPS_ANYO, PTFS.PIPS_TOTALES, 
	EOP.FECHA, EOP.FECHA_INICIAL, EOP.FECHA_FINAL,
	PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID
  FROM PREVIO_TOFILESTRING PTFS, ESTRATEGIA_OPERACION_PERIODO EOP
		WHERE ( --PTFS.PIPS_SEMANA IS NOT NULL AND PTFS.PIPS_SEMANA>0 AND
			 NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>EOP.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND PTFS.R2_MES>EOP.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>EOP.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7)   
	AND ((EOP.TIPO_OPERACION='BUY' AND EOP.PIPS_TOTALES>1000 
	  AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
	  AND EOP.PIPS_TOTALES_PARALELAS>3000
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>1000 AND EOP.PIPS_AGRUPADO_HORAS>1000 AND EOP.PIPS_AGRUPADO_DIAS>1000)
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)<10	  
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)>1
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND EOP.CANTIDAD/((EOP.FECHA_FINAL-EOP.FECHA_INICIAL)/30)>1
	  AND (EOP.PIPS_TOTALES/EOP.CANTIDAD)>200
	  --AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200
	 ) OR
	(EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200	
	 )
	)
	AND EOP.TIPO_OPERACION='BUY'
	AND PTFS.FECHA_SEMANA>TO_DATE('20131231','YYYYMMDD')	
	;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'CREATED FILTERED_PARA_OPERAR...' FROM DUAL;
/
