-- USER SQL
CREATE USER INTEGRATE IDENTIFIED BY integrate
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO INTEGRATE;
GRANT CREATE TABLE TO INTEGRATE ;
GRANT CREATE ANY INDEX TO INTEGRATE ;
GRANT SELECT ANY TABLE TO INTEGRATE ;
GRANT DROP ANY TYPE TO INTEGRATE ;
GRANT CREATE ANY VIEW TO INTEGRATE ;
GRANT CREATE ANY TRIGGER TO INTEGRATE ;
GRANT DROP ANY SEQUENCE TO INTEGRATE ;
GRANT DROP ANY TABLE TO INTEGRATE ;
GRANT EXECUTE ANY PROCEDURE TO INTEGRATE ;
GRANT DROP ANY VIEW TO INTEGRATE ;
GRANT ALTER ANY TRIGGER TO INTEGRATE ;
GRANT CREATE SYNONYM TO INTEGRATE ;
GRANT ALTER ANY TABLE TO INTEGRATE ;
GRANT CREATE VIEW TO INTEGRATE ;
GRANT DROP ANY INDEX TO INTEGRATE ;
GRANT CREATE ANY TABLE TO INTEGRATE ;
GRANT CREATE SESSION TO INTEGRATE ;
GRANT CREATE MATERIALIZED VIEW TO INTEGRATE ;

GRANT UNLIMITED TABLESPACE TO INTEGRATE;
GRANT CREATE PROCEDURE TO INTEGRATE;
GRANT IMP_FULL_DATABASE TO INTEGRATE;