CREATE TABLE OPERACION_BASE
(ID_INDIVIDUO VARCHAR2(50), 
FECHA_APERTURA DATE, 
FECHA_CIERRE DATE);

alter table "FOREX"."OPERACION_BASE" add constraint OPERACION_BASE_PK primary key("ID_INDIVIDUO","FECHA_APERTURA") 

