	CREATE TABLE TENDENCIA_ULTIMOSDATOS AS SELECT * FROM TENDENCIA WHERE FECHA_BASE>SYSDATE-30;

  CREATE INDEX TENDENCIA_ULTM_INDEX1 ON TENDENCIA_ULTIMOSDATOS (FECHA_BASE);

  CREATE INDEX "FOREX"."FETENDENCIAULTM_IDX" ON "FOREX"."TENDENCIA_ULTIMOSDATOS" ("FECHA_TENDENCIA");

  CREATE INDEX "FOREX"."TENDENCIAULTM_IDX1" ON "FOREX"."TENDENCIA_ULTIMOSDATOS" ("FECHA_BASE" DESC, "FECHA_TENDENCIA", TRUNC("FECHA_TENDENCIA",'fmhh24'), "FOREX"."WEEK_MINUTES"("FECHA_TENDENCIA","FECHA_BASE") DESC, "TIPO_TENDENCIA");

  CREATE INDEX "FOREX"."TENDENCIAULTM_IDX2" ON "FOREX"."TENDENCIA_ULTIMOSDATOS" ("ID_INDIVIDUO", "FECHA_BASE", "FECHA_TENDENCIA", "FECHA_APERTURA");

  CREATE INDEX "FOREX"."TENDENCIAULTM_IDX5" ON "FOREX"."TENDENCIA_ULTIMOSDATOS" ("ID_INDIVIDUO", "FECHA_BASE", "FECHA_APERTURA");

