DELETE FROM OPERACIONES_ACUM_SEMANA_CONSOL OPX
WHERE OPX.ID_INDIVIDUO NOT IN (SELECT ID FROM INDIVIDUO);

DELETE FROM OPERACIONES_ACUM_SEMANA_ANYO OPX
WHERE OPX.ID_INDIVIDUO NOT IN (SELECT ID FROM INDIVIDUO);

DELETE FROM OPERACIONES_ACUM_SEMANA_MES OPX
WHERE OPX.ID_INDIVIDUO NOT IN (SELECT ID FROM INDIVIDUO);

DELETE FROM OPERACION_X_SEMANA OPX
WHERE OPX.ID_INDIVIDUO NOT IN (SELECT ID FROM INDIVIDUO);

DELETE FROM TENDENCIA WHERE ID_INDIVIDUO IN ( --''
 SELECT IND.ID FROM INDIVIDUO IND 
 --WHERE ID LIKE '1452%'
 --WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
 WHERE IND.TIPO_INDIVIDUO IS NULL
)
;

DELETE FROM PROCESO WHERE ID_INDIVIDUO IN ( --'1338654577824.4270'
  SELECT IND.ID FROM INDIVIDUO IND 
  --WHERE ID LIKE '1453593600000.11'
  --WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
  WHERE IND.TIPO_INDIVIDUO IS NULL
)
;

DELETE FROM OPERACION WHERE ID_INDIVIDUO IN ( --'1338654577824.4270'
  SELECT IND.ID FROM INDIVIDUO IND 
  --WHERE ID LIKE '1453593600000.11'
  --WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
  WHERE IND.TIPO_INDIVIDUO IS NULL
)
;

DELETE FROM INDICADOR_INDIVIDUO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND 
  --WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
  WHERE IND.TIPO_INDIVIDUO IS NULL
)
;

DELETE FROM INDICADOR_INDIVIDUO_TENDENCIAS WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND 
  --WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
  WHERE IND.TIPO_INDIVIDUO IS NULL
)
;

DELETE FROM OPERACION_ESTRATEGIA_PERIODO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND 
  --WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
  WHERE IND.TIPO_INDIVIDUO IS NULL
)
;

DELETE FROM INDIVIDUO IND 
--WHERE ID LIKE '1452%'
--WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
WHERE IND.TIPO_INDIVIDUO IS NULL
;

--COMMIT;

SELECT IND.ID FROM INDIVIDUO IND 
--WHERE CREATION_DATE>TO_DATE('2016/02/27 00:00', 'YYYY/MM/DD HH24:MI')
WHERE IND.TIPO_INDIVIDUO IS NULL
;


