SELECT COUNT(PIPS) FROM OPERACIONES_ACUM_SEMANA_CONSOL WHERE PIPS<-3000;
SELECT COUNT(PIPS) FROM OPERACIONES_ACUM_SEMANA_ANYO WHERE PIPS<-2000;
SELECT COUNT(PIPS) FROM OPERACIONES_ACUM_SEMANA_MES WHERE PIPS<-1000;

DECLARE

BEGIN
  FOR i IN 1..100 LOOP
    DELETE FROM OPERACIONES_ACUM_SEMANA_CONSOL WHERE PIPS<-3000 AND ROWNUM<25000;
    COMMIT;
    DELETE FROM OPERACIONES_ACUM_SEMANA_ANYO WHERE PIPS<-2000 AND ROWNUM<23000;
    COMMIT;
    DELETE FROM OPERACIONES_ACUM_SEMANA_MES WHERE PIPS<-1000 AND ROWNUM<13000;
    COMMIT;
  END LOOP;
END;

