DELETE FROM FOREX.PROCESO
WHERE ID_INDIVIDUO IN (
  SELECT DISTINCT ID_INDIVIDUO FROM OPERACION WHERE TAKE_PROFIT=0
);
 
DELETE FROM FOREX.OPERACION
WHERE ID_INDIVIDUO IN (
  SELECT DISTINCT ID_INDIVIDUO FROM OPERACION WHERE TAKE_PROFIT=0
);

COMMIT;