DELETE FROM FOREX.TENDENCIA
WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND WHERE IND.TAKE_PROFIT<50 OR IND.STOP_LOSS<50
);

DELETE FROM FOREX.PROCESO
WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND WHERE IND.TAKE_PROFIT<50 OR IND.STOP_LOSS<50
);
 
DELETE FROM FOREX.OPERACION
WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND WHERE IND.TAKE_PROFIT<50 OR IND.STOP_LOSS<50
);

DELETE FROM INDICADOR_INDIVIDUO
WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM INDIVIDUO IND WHERE IND.TAKE_PROFIT<50 OR IND.STOP_LOSS<50
);

DELETE FROM INDIVIDUO IND WHERE IND.TAKE_PROFIT<50 OR IND.STOP_LOSS<50;

COMMIT;
