--SELECT COUNT(*) 
DELETE
FROM OPERACION_ESTRATEGIA_PERIODO OP
WHERE OP.ESTRATEGIA_PERIODO IN (
  SELECT EST.ID FROM ESTRATEGIA_OPERACION_PERIODO EST WHERE EST.PIPS_TOTALES < -40000
  )
;

COMMIT;


SELECT COUNT(EST.ID)
--EST.PIPS_TOTALES, EST.PIPS_TOTALES_PARALELAS, EST.* 
FROM ESTRATEGIA_OPERACION_PERIODO EST 
  INNER JOIN OPERACION_ESTRATEGIA_PERIODO OP ON OP.ESTRATEGIA_PERIODO=EST.ID
WHERE EST.PIPS_TOTALES < -40000
ORDER BY EST.PIPS_TOTALES ASC;
