--UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=1
--WHERE ACTIVA=0 AND FECHA_BASE>TO_DATE('2017/01/01 00:00', 'YYYY/MM/DD HH24:MI')
--AND EXISTS (	SELECT TOP2.FECHA_BASE FROM TENDENCIA_PARA_OPERAR TOP2
--WHERE TOP2.FECHA_BASE=TOP.FECHA_BASE AND TOP2.PERIODO='EXTREMO'
--	AND TOP2.TIPO_OPERACION=TOP.TIPO_OPERACION);

--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=0 WHERE PERIODO='EXTREMO_SINFILTRAR' AND ACTIVA=1;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=0
--WHERE ACTIVA=1 AND FECHA_BASE>TO_DATE('2017/01/01 00:00', 'YYYY/MM/DD HH24:MI')
--AND NOT EXISTS (	SELECT TOP2.FECHA_BASE FROM TENDENCIA_PARA_OPERAR TOP2
--WHERE TOP2.FECHA_BASE=TOP.FECHA_BASE AND TOP2.PERIODO='EXTREMO'
--	AND TOP2.TIPO_OPERACION=TOP.TIPO_OPERACION);
	
--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=1;

UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=0 
WHERE TOP.TIPO_OPERACION='SELL' AND ACTIVA=1
AND EXISTS (SELECT TOP.FECHA_BASE FROM DATO_ADICIONAL_TPO ADDTOP
	WHERE ADDTOP.FECHA_BASE=TOP.FECHA_BASE AND ADDTOP.PENDIENTE_PROMEDIO>0)
;

UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=0 
	WHERE TOP.TIPO_OPERACION='BUY' AND ACTIVA=1
AND EXISTS (	SELECT TOP.FECHA_BASE FROM DATO_ADICIONAL_TPO ADDTOP
WHERE ADDTOP.FECHA_BASE=TOP.FECHA_BASE AND ADDTOP.PENDIENTE_PROMEDIO<0)
;	

COMMIT;
exit;



--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=0 WHERE PERIODO='EXTREMO' AND ACTIVA=1;

--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=0;
--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=1 WHERE PERIODO='EXTREMO' AND ACTIVA=0;

--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=1 WHERE ACTIVA IS NULL;
--UPDATE TENDENCIA_PARA_OPERAR SET ACTIVA=0 WHERE PERIODO='EXTREMO_SINFILTRAR' AND ACTIVA=1;

--UPDATE TENDENCIA_PARA_OPERAR SET LOTE=0.01;
--UPDATE TENDENCIA_PARA_OPERAR SET LOTE_CALCULADO=LOTE;


--UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=1
--WHERE ACTIVA=0
--AND EXISTS (SELECT TOP.FECHA_BASE FROM DATO_ADICIONAL_TPO ADDTOP
--	WHERE ADDTOP.FECHA_BASE=TOP.FECHA_BASE AND 
--	(DIFF_PRECIO_EXTREMO_SUPERIOR<1 OR DIFF_PRECIO_EXTREMO_INFERIOR<1))
--;
--
--UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=0
--WHERE ACTIVA=1 AND TOP.TIPO_OPERACION='BUY'
--AND EXISTS (SELECT TOP.FECHA_BASE FROM DATO_ADICIONAL_TPO ADDTOP
--	WHERE ADDTOP.FECHA_BASE=TOP.FECHA_BASE
--	AND DIFF_PRECIO_EXTREMO_SUPERIOR<DIFF_PRECIO_EXTREMO_INFERIOR)	
--;
--UPDATE TENDENCIA_PARA_OPERAR TOP SET ACTIVA=0
--WHERE ACTIVA=1 AND TOP.TIPO_OPERACION='SELL'
--AND EXISTS (SELECT TOP.FECHA_BASE FROM DATO_ADICIONAL_TPO ADDTOP
--	WHERE ADDTOP.FECHA_BASE=TOP.FECHA_BASE
--	AND DIFF_PRECIO_EXTREMO_INFERIOR<DIFF_PRECIO_EXTREMO_SUPERIOR)	
--;

--DELETE 
--SELECT COUNT(*)
--FROM TENDENCIA_PARA_OPERAR TOP 
--WHERE NOT EXISTS (SELECT TEN.FECHA_BASE FROM TENDENCIA TEN WHERE TOP.FECHA_BASE=TEN.FECHA_BASE)
--AND TOP.FECHA_BASE>TO_DATE('2017/04/24 12:13', 'YYYY/MM/DD HH24:MI')
--;

/*
SELECT * FROM TENDENCIA_PARA_OPERAR TOP
WHERE FECHA_BASE>TO_DATE('2017/01/01 00:00', 'YYYY/MM/DD HH24:MI')
AND NOT EXISTS (	SELECT TOP2.FECHA_BASE FROM TENDENCIA_PARA_OPERAR TOP2
WHERE TOP2.FECHA_BASE=TOP.FECHA_BASE AND TOP2.PERIODO='EXTREMO'
	AND TOP2.TIPO_OPERACION=TOP.TIPO_OPERACION
)
AND R2<=0.1 AND PERIODO NOT LIKE 'EXTREMO%'
ORDER BY FECHA_BASE ASC
;
*/