SELECT OPER.ID_INDIVIDUO, MAX(OPER.CANTIDAD) CANTIDAD, COUNT(*) C, MIN(OPER.PIPS),
ROUND(STDDEV(OPER.PIPS),2) --OVER (ORDER BY OPER.ID_INDIVIDUO) "STDDEV"
FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
--WHERE 
--OPER.ID_INDIVIDUO='1463541693654.6069'
--AND OPER.FECHA_SEMANA<TO_DATE('20160101','YYYYMMDD')
GROUP BY OPER.ID_INDIVIDUO
HAVING STDDEV(OPER.PIPS)>0 AND MAX(OPER.CANTIDAD)>10 AND COUNT(*)>10 AND MIN(OPER.PIPS)>0
ORDER BY STDDEV(OPER.PIPS) DESC
;

SELECT OPER.ID_INDIVIDUO, ROUND(STDDEV(OPER.PIPS),2) --OVER (ORDER BY OPER.ID_INDIVIDUO) "STDDEV"
FROM OPERACION OPER
WHERE OPER.ID_INDIVIDUO='1463541693654.6069'
GROUP BY OPER.ID_INDIVIDUO;

SELECT OPER.ID_INDIVIDUO, MIN(OPER.FECHA_SEMANA) MIN_FECHA, MAX(OPER.FECHA_SEMANA) MAX_FECHA, MAX(OPER.PIPS) PIPS,
ROUND(REGR_SLOPE(TO_NUMBER(TO_CHAR(OPER.FECHA_SEMANA, 'YYYYMMDDHH24MI')), OPER.PIPS),2) SLOPE, 
ROUND(REGR_R2(TO_NUMBER(TO_CHAR(OPER.FECHA_SEMANA, 'YYYYMMDDHH24MI')), OPER.PIPS),2) R2 
FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
--WHERE 
--OPER.ID_INDIVIDUO='1463541693654.6069'
--AND OPER.FECHA_SEMANA<TO_DATE('20160101','YYYYMMDD')
GROUP BY OPER.ID_INDIVIDUO
HAVING --STDDEV(OPER.PIPS)>0 AND 
MAX(OPER.CANTIDAD)>10 AND COUNT(*)>10 AND MIN(OPER.PIPS)>0
ORDER BY REGR_R2(OPER.PIPS, TO_NUMBER(TO_CHAR(OPER.FECHA_SEMANA, 'YYYYMMDDHH24MI'))) DESC
;
