
  CREATE OR REPLACE FORCE VIEW "FOREX"."DETALLE_ESTADISTICAS" ("ID_INDIVIDUO", "CANTIDAD_POSITIVOS", "CANTIDAD_NEGATIVOS", "CANTIDAD_TOTAL", "PIPS_POSITIVOS", "PIPS_NEGATIVOS", "PIPS_TOTALES", "PIPS_MINIMOS_POS", "PIPS_MINIMOS_NEG", "PIPS_MINIMOS", "PIPS_RETROCESO_MINIMO_POS", "PIPS_RETROCESO_MINIMO_NEG", "PIPS_RETROCESO_MINIMO_TOTAL", "PIPS_MAXIMOS_POS", "PIPS_MAXIMOS_NEG", "PIPS_MAXIMOS", "PIPS_RETROCESO_MAXIMO_POS", "PIPS_RETROCESO_MAXIMO_NEG", "PIPS_RETROCESO_MAXIMO_TOTAL", "AVG_PIPS_POS", "AVG_PIPS_NEG", "AVG_PIPS", "PIPS_RETROCESO_PROMEDIO_POS", "PIPS_RETROCESO_PROMEDIO_NEG", "PIPS_RETROCESO_PROMEDIO_TOTAL", "PIPS_MODA_POS", "PIPS_MODA_NEG", "PIPS_MODA", "PIPS_RETROCESO_MODA_POS", "PIPS_RETROCESO_MODA_NEG", "PIPS_RETROCESO_MODA_TOTAL", "DUR_MIN_POS", "DUR_MIN_NEG", "DUR_MIN", "DUR_MAX_POS", "DUR_MAX_NEG", "DUR_MAX", "DUR_PROM_POS", "DUR_PROM_NEG", "DUR_PROM", "DUR_MODA_POS", "DUR_MODA_NEG", "DUR_MODA", "DUR_DESV_POS", "DUR_DESV_NEG", "DUR_DESV") AS 
  SELECT IND.ID ID_INDIVIDUO, 
  NVL(SUM(POSITIVOS.CANTIDAD),0) CANTIDAD_POSITIVOS, NVL(SUM(NEGATIVOS.CANTIDAD),0) CANTIDAD_NEGATIVOS, NVL(SUM(OPER.CANTIDAD),0) CANTIDAD_TOTAL,
  NVL(SUM(POSITIVOS.PIPS),0) PIPS_POSITIVOS, NVL(SUM(NEGATIVOS.PIPS),0) PIPS_NEGATIVOS, NVL(SUM(POSITIVOS.PIPS),0)+NVL(SUM(NEGATIVOS.PIPS),0) PIPS_TOTALES,
  NVL(MIN(POSITIVOS.PIPS_MINIMOS),0) PIPS_MINIMOS_POS, NVL(MIN(NEGATIVOS.PIPS_MINIMOS),0) PIPS_MINIMOS_NEG, NVL(MIN(OPER.PIPS_MINIMOS),0) PIPS_MINIMOS,
    NVL(MIN(POSITIVOS.PIPS_RETROCESO_MINIMO),0) PIPS_RETROCESO_MINIMO_POS,NVL(MIN(NEGATIVOS.PIPS_RETROCESO_MINIMO),0) PIPS_RETROCESO_MINIMO_NEG, NVL(MIN(OPER.PIPS_RETROCESO_MINIMO),0) PIPS_RETROCESO_MINIMO_TOTAL,
  NVL(MAX(POSITIVOS.PIPS_MAXIMOS),0) PIPS_MAXIMOS_POS, NVL(MAX(NEGATIVOS.PIPS_MAXIMOS),0) PIPS_MAXIMOS_NEG, NVL(MAX(OPER.PIPS_MAXIMOS),0) PIPS_MAXIMOS,
    NVL(MIN(POSITIVOS.PIPS_RETROCESO_MAXIMO),0) PIPS_RETROCESO_MAXIMO_POS,NVL(MIN(NEGATIVOS.PIPS_RETROCESO_MAXIMO),0) PIPS_RETROCESO_MAXIMO_NEG, NVL(MIN(OPER.PIPS_RETROCESO_MAXIMO),0) PIPS_RETROCESO_MAXIMO_TOTAL,
  ROUND(NVL(AVG(POSITIVOS.PIPS_PROMEDIO),0),5) AVG_PIPS_POS, ROUND(NVL(AVG(NEGATIVOS.PIPS_PROMEDIO),0),0) AVG_PIPS_NEG, ROUND(NVL(AVG(OPER.PIPS_PROMEDIO),0),0) AVG_PIPS,
    ROUND(NVL(MIN(POSITIVOS.PIPS_RETROCESO_PROMEDIO),0),5) PIPS_RETROCESO_PROMEDIO_POS,ROUND(NVL(MIN(NEGATIVOS.PIPS_RETROCESO_PROMEDIO),0),5) PIPS_RETROCESO_PROMEDIO_NEG, ROUND(NVL(MIN(OPER.PIPS_RETROCESO_PROMEDIO),0),5) PIPS_RETROCESO_PROMEDIO_TOTAL,
  NVL(SUM(POSITIVOS.PIPS_MODA),0) PIPS_MODA_POS, NVL(SUM(NEGATIVOS.PIPS_MODA),0) PIPS_MODA_NEG, NVL(SUM(OPER.PIPS_MODA),0) PIPS_MODA,
    NVL(MIN(POSITIVOS.PIPS_RETROCESO_MODA),0) PIPS_RETROCESO_MODA_POS,NVL(MIN(NEGATIVOS.PIPS_RETROCESO_MODA),0) PIPS_RETROCESO_MODA_NEG, NVL(MIN(OPER.PIPS_RETROCESO_MODA),0) PIPS_RETROCESO_MODA_TOTAL,
  ROUND(NVL(SUM(POSITIVOS.DUR_MINIMA),0),5) DUR_MIN_POS, ROUND(NVL(SUM(NEGATIVOS.DUR_MINIMA),0),5) DUR_MIN_NEG, ROUND(NVL(SUM(OPER.DUR_MINIMA),0),5) DUR_MIN, 
  ROUND(NVL(SUM(POSITIVOS.DUR_MAXIMA),0),5) DUR_MAX_POS, ROUND(NVL(SUM(NEGATIVOS.DUR_MAXIMA),0),5) DUR_MAX_NEG, ROUND(NVL(SUM(OPER.DUR_MAXIMA),0),5) DUR_MAX,
  ROUND(NVL(SUM(POSITIVOS.DUR_PROMEDIO),0),5) DUR_PROM_POS, ROUND(NVL(SUM(NEGATIVOS.DUR_PROMEDIO),0),5) DUR_PROM_NEG, ROUND(NVL(SUM(OPER.DUR_PROMEDIO),0),5) DUR_PROM,
  ROUND(NVL(SUM(POSITIVOS.DUR_MODA),0),5) DUR_MODA_POS, ROUND(NVL(SUM(NEGATIVOS.DUR_MODA),0),5) DUR_MODA_NEG, ROUND(NVL(SUM(OPER.DUR_MODA),0),5) DUR_MODA, 
  ROUND(NVL(SUM(POSITIVOS.DUR_DESV),0),5) DUR_DESV_POS, ROUND(NVL(SUM(NEGATIVOS.DUR_DESV),0),5) DUR_DESV_NEG, ROUND(NVL(SUM(OPER.DUR_DESV),0),5) DUR_DESV
FROM INDIVIDUO IND
  INNER JOIN (SELECT OPER.ID_INDIVIDUO, MIN(OPER.PIPS) PIPS_MINIMOS, MAX(OPER.PIPS) PIPS_MAXIMOS, AVG(OPER.PIPS) PIPS_PROMEDIO, STATS_MODE(PIPS) PIPS_MODA,
    MIN(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MINIMA, MAX(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MAXIMA,
    AVG(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_PROMEDIO, STATS_MODE(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MODA,
    STDDEV(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_DESV,
    MIN(OPER.MAX_PIPS_RETROCESO) PIPS_RETROCESO_MINIMO, MAX(OPER.MAX_PIPS_RETROCESO) PIPS_RETROCESO_MAXIMO, AVG(OPER.MAX_PIPS_RETROCESO) PIPS_RETROCESO_PROMEDIO, STATS_MODE(OPER.MAX_PIPS_RETROCESO) PIPS_RETROCESO_MODA,    
    COUNT(*) CANTIDAD
    FROM OPERACION OPER, PARAMETROS_ESTADISTICAS PARAM
		WHERE OPER.FECHA_CIERRE IS NOT NULL AND OPER.FECHA_CIERRE < PARAM.PARAM_FECHA
    AND (WEEK_MINUTES(OPER.FECHA_CIERRE,OPER.FECHA_APERTURA))>=NVL(PARAM.PARAM_DURACION,0)
    AND (PARAM.PARAM_RETROCESO IS NULL OR
      (OPER.PIPS<0 AND PARAM.PARAM_RETROCESO/1>0 
      AND OPER.MAX_PIPS_RETROCESO>=NVL(PARAM.PARAM_RETROCESO,0)) 
      OR (OPER.PIPS>0 AND PARAM.PARAM_RETROCESO/-1>0 
      AND OPER.MAX_PIPS_RETROCESO<=NVL(PARAM.PARAM_RETROCESO,0))
      OR ((OPER.PIPS<0 AND PARAM.PARAM_RETROCESO/1<0 
      AND OPER.PIPS<=NVL(PARAM.PARAM_RETROCESO,0)))
      OR ((OPER.PIPS>0 AND PARAM.PARAM_RETROCESO/-1<0 
      AND OPER.PIPS>=NVL(PARAM.PARAM_RETROCESO,0))))
	GROUP BY OPER.ID_INDIVIDUO) OPER ON OPER.ID_INDIVIDUO=IND.ID
  LEFT JOIN (SELECT P.ID_INDIVIDUO, SUM(P.PIPS) PIPS, MIN(P.PIPS) PIPS_MINIMOS, MAX(P.PIPS) PIPS_MAXIMOS, AVG(P.PIPS) PIPS_PROMEDIO, STATS_MODE(P.PIPS) PIPS_MODA,
    MIN(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MINIMA, MAX(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MAXIMA,
    AVG(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_PROMEDIO, STATS_MODE(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MODA,
    STDDEV(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_DESV,
    MIN(MAX_PIPS_RETROCESO) PIPS_RETROCESO_MINIMO, MAX(MAX_PIPS_RETROCESO) PIPS_RETROCESO_MAXIMO, AVG(MAX_PIPS_RETROCESO) PIPS_RETROCESO_PROMEDIO, STATS_MODE(MAX_PIPS_RETROCESO) PIPS_RETROCESO_MODA,    
    COUNT(*) CANTIDAD
    FROM OPERACION P, PARAMETROS_ESTADISTICAS PARAM 
    WHERE P.PIPS>0 
    AND P.FECHA_CIERRE IS NOT NULL AND P.FECHA_CIERRE < PARAM.PARAM_FECHA    
    AND (WEEK_MINUTES(P.FECHA_CIERRE,P.FECHA_APERTURA))>=NVL(PARAM.PARAM_DURACION,0)
    AND ((PARAM.PARAM_RETROCESO IS NULL)
     OR (PARAM.PARAM_RETROCESO>0
      AND (P.PIPS>=PARAM.PARAM_RETROCESO))
     OR (PARAM.PARAM_RETROCESO<0
      AND P.MAX_PIPS_RETROCESO<=NVL(PARAM.PARAM_RETROCESO,0)))
	GROUP BY P.ID_INDIVIDUO) POSITIVOS ON POSITIVOS.ID_INDIVIDUO=IND.ID
  LEFT JOIN (SELECT N.ID_INDIVIDUO, SUM(N.PIPS) PIPS, MIN(N.PIPS) PIPS_MINIMOS, MAX(N.PIPS) PIPS_MAXIMOS, AVG(N.PIPS) PIPS_PROMEDIO, STATS_MODE(N.PIPS) PIPS_MODA,
    MIN(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MINIMA, MAX(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MAXIMA,
    AVG(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_PROMEDIO, STATS_MODE(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_MODA,
    STDDEV(WEEK_MINUTES(FECHA_CIERRE,FECHA_APERTURA)) DUR_DESV,
    MIN(MAX_PIPS_RETROCESO) PIPS_RETROCESO_MINIMO, MAX(MAX_PIPS_RETROCESO) PIPS_RETROCESO_MAXIMO, AVG(MAX_PIPS_RETROCESO) PIPS_RETROCESO_PROMEDIO, STATS_MODE(MAX_PIPS_RETROCESO) PIPS_RETROCESO_MODA,    
    COUNT(*) CANTIDAD
    FROM OPERACION N, PARAMETROS_ESTADISTICAS PARAM
		WHERE N.PIPS<=0 
    AND N.FECHA_CIERRE IS NOT NULL AND N.FECHA_CIERRE < PARAM.PARAM_FECHA
    AND (WEEK_MINUTES(N.FECHA_CIERRE,N.FECHA_APERTURA))>=NVL(PARAM.PARAM_DURACION,0)
    AND ((PARAM.PARAM_RETROCESO IS NULL)
      OR (PARAM.PARAM_RETROCESO<0
        AND(N.PIPS<=PARAM.PARAM_RETROCESO))
     OR (PARAM.PARAM_RETROCESO>0
      AND (N.MAX_PIPS_RETROCESO>=NVL(PARAM.PARAM_RETROCESO,0))))		
  GROUP BY N.ID_INDIVIDUO) NEGATIVOS ON NEGATIVOS.ID_INDIVIDUO=IND.ID
GROUP BY IND.ID;
