--TO_CHAR(TEN.FECHA_BASE,'YYYYMM'), 
WITH DIAS_MES AS
		(SELECT TRUNC(TEN.FECHA_BASE,'DD') DIA FROM TENDENCIA TEN
		WHERE TO_CHAR(TEN.FECHA_BASE, 'YYYY')='2016'
		GROUP BY TRUNC(TEN.FECHA_BASE,'DD') ),
	MESES AS (
	SELECT TRUNC(DIA,'MM') MES, COUNT(*) FROM DIAS_MES
	GROUP BY TRUNC(DIA,'MM'))

--SELECT * FROM DIAS_MES ORDER BY DIA ASC
SELECT * FROM MESES 
ORDER BY MES ASC
;

SELECT TRUNC(SYSDATE, 'MM') FROM DUAL;