DROP TABLE INDIVIDUOS_ESTRATEGIA;
DROP TABLE ESTRATEGIAS;
DROP TABLE INDICADOR_INDIVIDUO_TENDENCIAS;

DROP TABLE OLD_OPER_ACUM_MES_ANYO;
DROP TABLE OLD_OPER_ACUM_MES_CONSOL;
DROP TABLE TEMP_INDIVIDUO;
DROP TABLE TEMP_ROWID_ANYO;
DROP TABLE TEMP_ROWID_CONSOL;
DROP TABLE TEMP_ROWID_MES;

DROP TABLE TENDENCIA;
DROP TABLE TENDENCIA_PROCESADA;
DROP TABLE TENDENCIA_QUERY;

