DROP TABLE PIPS_MENSUALES_INDIVIDUO;
DROP TABLE OPERACIONES_ACUM_SEMANA_CONSOL;
DROP TABLE OPERACIONES_ACUM_SEMANA_ANYO;
DROP TABLE OPERACIONES_ACUM_SEMANA_MES;
DROP TABLE OPERACION_X_ANYO;
DROP TABLE OPERACION_X_MES;
DROP TABLE OPERACION_X_SEMANA;
DROP TABLE OPERACION_CONSOLIDADAS;