SELECT OPER.*
FROM OPERACION_CONSOLIDADAS OPER
WHERE EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE OPER.ID_INDIVIDUO=II.ID_INDIVIDUO AND II.INTERVALO_INFERIOR IS NOT NULL)
--AND OPER.ID_INDIVIDUO='1394841600000.96'
ORDER BY OPER.PIPS DESC;

SELECT OPER.*
FROM OPERACION_X_ANYO OPER
WHERE EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE OPER.ID_INDIVIDUO=II.ID_INDIVIDUO AND II.INTERVALO_INFERIOR IS NOT NULL)
--AND OPER.ID_INDIVIDUO='1331220412316.224'
AND OPER.ANYO='2014'
ORDER BY OPER.PIPS DESC;

SELECT OPER.*
FROM OPERACION_X_MES OPER
WHERE EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE OPER.ID_INDIVIDUO=II.ID_INDIVIDUO AND II.INTERVALO_INFERIOR IS NOT NULL)
--AND OPER.ID_INDIVIDUO='1454112000000.32'
AND OPER.MES='201409'
--AND OPER.PIPS>0
ORDER BY OPER.PIPS DESC;

SELECT OPER_MES.ID_INDIVIDUO, MESES.MES, MAX(OPER_MES.FECHA_HISTORICO) FECHA_HISTORICO, 
  SUM(OPER_MES.PIPS) PIPS_MES, SUM(OPER_ANYO.PIPS) PIPS_ANYO, SUM(OPER.PIPS) PIPS_TOTALES, 
  SUM(OPER_MES.CANTIDAD) CANTIDAD_MES, SUM(OPER_ANYO.CANTIDAD) CANTIDAD_ANYO, SUM(OPER.CANTIDAD) CANTIDAD_TOTAL
  --OPER_MES.ID_INDIVIDUO, OPER_MES.MES
FROM OPERACION_X_MES OPER_MES
  INNER JOIN (SELECT DISTINCT MESES.MES FROM OPERACION_X_MES MESES) MESES
    ON TO_DATE(OPER_MES.MES,'YYYYMM')=ADD_MONTHS(TO_DATE(MESES.MES,'YYYYMM'),-1) 
  INNER JOIN OPERACIONES_ACUM_MES_ANYO OPER_ANYO 
    ON OPER_ANYO.ID_INDIVIDUO=OPER_MES.ID_INDIVIDUO     
      AND TO_DATE(OPER_MES.MES,'YYYYMM')=ADD_MONTHS(TO_DATE(OPER_ANYO.MES,'YYYYMM'),-1) AND OPER_ANYO.PIPS>=1000
  INNER JOIN OPERACIONES_ACUM_MES_CONSOL OPER
    ON OPER_MES.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
    AND TO_DATE(OPER_MES.MES,'YYYYMM')=ADD_MONTHS(TO_DATE(OPER.MES,'YYYYMM'),-1) AND OPER.PIPS>1500
WHERE EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE OPER_MES.ID_INDIVIDUO=II.ID_INDIVIDUO AND II.INTERVALO_INFERIOR IS NOT NULL)
AND OPER_MES.PIPS>=1000 AND OPER_MES.CANTIDAD>1
--AND OPER_MES.TIPO_OPERACION='BUY'
--AND OPER_MES.ID_INDIVIDUO ='1453664590875.284'
GROUP BY OPER_MES.ID_INDIVIDUO, MESES.MES
ORDER BY MESES.MES ASC
;

SELECT TO_DATE('201409','YYYYMM'), ADD_MONTHS(TO_DATE('201409','YYYYMM'),-12) FROM DUAL;

SELECT ID_INDIVIDUO, TIPO, COUNT(*), SUM(PIPS)
 FROM FOREX.OPERACION OPER
--WHERE ID_INDIVIDUO LIKE '1456618363402.%'
--AND FECHA_CIERRE IS NOT NULL
--AND TO_CHAR(FECHA_CIERRE, 'YYYY')='2014'
GROUP BY ID_INDIVIDUO, TIPO
ORDER BY SUM(PIPS) DESC
;


SELECT OPER.*
FROM OPERACION_X_ANYO OPER
--WHERE --(
--ID_INDIVIDUO LIKE '1453780593359.%'
--ID_INDIVIDUO LIKE '1453911939750.%'
--ID_INDIVIDUO LIKE '1454112000000.%'
--ID_INDIVIDUO LIKE '1454196071797.%'
--ID_INDIVIDUO LIKE '1454630400000.%'
--ID_INDIVIDUO LIKE '1454724967301.%'
--)
--TO_CHAR(FECHA_CIERRE, 'YYYY')<'2012'
--AND EXISTS (SELECT 1 FROM OPERACION OP WHERE OP.ID_INDIVIDUO=OPER.ID_INDIVIDUO AND TO_CHAR(OP.FECHA_CIERRE, 'YYYY')='2015')
ORDER BY OPER.PIPS DESC
;

SELECT AVG_PIPS_POS, AVG_PIPS_NEG, DUR_PROM_POS, DUR_PROM_NEG, DEST.*
FROM DETALLE_ESTADISTICAS DEST
WHERE ID_INDIVIDUO IN (
'1453128626781.100'
);
UNION ALL;

SELECT AVG_PIPS_POS, AVG_PIPS_NEG, ROUND(AVG_PIPS_NEG/AVG_PIPS_POS, 2) PORC_PIPS,
  ROUND(DEST.CANTIDAD_POSITIVOS/DEST.CANTIDAD_NEGATIVOS,2) PORC_CANT,
  DEST.PIPS_TOTALES,
  DEST.*
FROM DETALLE_ESTADISTICAS_OLD DEST
WHERE DEST.AVG_PIPS_POS > 0 AND DEST.CANTIDAD_NEGATIVOS > 0 AND
ORDER BY DEST.PIPS_TOTALES ASC
;

