SELECT PTFS.ID_INDIVIDUO, 
	ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES)+MAX(PERI.PIPS_TOTALES_PARALELAS))/5), 
	MAX(PERI.PIPS_TOTALES_PARALELAS),
  PTFS.FECHA_SEMANA, PTFS.FECHA_SEMANA+14, MAX(PERI.FECHA), MAX(PERI.FECHA_FINAL)
  FROM PREVIO_TOFILESTRING PTFS
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO PERI
		ON ( NVL(PTFS.PIPS_SEMANA,0)>PERI.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>PERI.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>PERI.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>PERI.FILTRO_PIPS_TOTALES)
			AND (PTFS.R2_SEMANA>PERI.FILTRO_R2_SEMANA AND PTFS.R2_MES>PERI.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>PERI.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>PERI.FILTRO_R2_TOTALES)
			AND (PTFS.PENDIENTE_SEMANA>PERI.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>PERI.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>PERI.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>PERI.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=PERI.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN PERI.FECHA_FINAL AND ADD_MONTHS(PERI.FECHA_FINAL,1)
	INNER JOIN (SELECT ESTRATEGIA_PERIODO, MAX(FECHA_CIERRE) FECHA_FINAL FROM OPERACION_ESTRATEGIA_PERIODO GROUP BY ESTRATEGIA_PERIODO
    ) OP ON OP.ESTRATEGIA_PERIODO=PERI.ID AND PTFS.FECHA_SEMANA BETWEEN OP.FECHA_FINAL AND ADD_MONTHS(OP.FECHA_FINAL,1)
  WHERE 
	(PERI.PIPS_TOTALES>1000 
	  --AND PERI.ID BETWEEN 1627690 AND 11627690 
	  AND PERI.ID>=174481
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10	  
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  )	  
	  AND PERI.FECHA_FINAL>TO_DATE('20131231','YYYYMMDD')
  GROUP BY PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA;