SELECT PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA, EOP.ID, PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID, EOP.*
  FROM FILTERED_PTFS PTFS, FILTERED_EOP EOP
	--PREVIO_TOFILESTRING PTFS, ESTRATEGIA_OPERACION_PERIODO EOP
		WHERE  --PTFS.PIPS_SEMANA IS NOT NULL AND PTFS.PIPS_SEMANA>0 AND
			 NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND NVL(PTFS.PIPS_MES,0)>EOP.FILTRO_PIPS_X_MES 
			AND NVL(PTFS.PIPS_ANYO,0)>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES
			AND NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA 
			AND NVL(PTFS.R2_MES,0)>EOP.FILTRO_R2_MES 
			AND NVL(PTFS.R2_ANYO,0)>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES
			AND NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA 
			AND NVL(PTFS.PENDIENTE_MES,0)>EOP.FILTRO_PENDIENTE_MES 
			AND NVL(PTFS.PENDIENTE_ANYO,0)>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES
			 AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7)
	--AND EOP.TIPO_OPERACION='SELL'
	AND PTFS.FECHA_SEMANA>=TO_DATE('20161017','YYYYMMDD')
--	AND EOP.ID=1178206 --1169749
	AND PTFS.ID_INDIVIDUO='1454889600000.878'
	;

SELECT * FROM FILTERED_PARA_OPERAR FILTERED
WHERE FILTERED.ID_INDIVIDUO='1477365411387.4766';

SELECT FILTERED.ID_INDIVIDUO, 
		NVL(MIN(FILTERED.PIPS_SEMANA),0),
		NVL(ROUND((MIN(FILTERED.PIPS_SEMANA)+MIN(FILTERED.PIPS_MES)+MIN(FILTERED.PIPS_ANYO)+MIN(FILTERED.PIPS_TOTALES))/4),0),
		FILTERED.FECHA_SEMANA, FILTERED.FECHA_SEMANA+7, 
		MAX(FILTERED.FECHA), MAX(FILTERED.FECHA_FINAL)
  --FROM FILTERED_PARA_OPERAR_SELL FILTERED
  FROM FILTERED_PARA_OPERAR FILTERED
	WHERE FILTERED.ID_INDIVIDUO='1477365411387.16335'	
GROUP BY FILTERED.ID_INDIVIDUO, FILTERED.FECHA_SEMANA;
	
 SELECT PTFS.ID_INDIVIDUO, 
  MIN(PTFS.PIPS_SEMANA),
	ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES))/4),
	--MAX(PERI.PIPS_TOTALES_PARALELAS),
  PTFS.FECHA_SEMANA, PTFS.FECHA_SEMANA+7, 
  --PTFS.FECHA_SEMANA, MAX(PERI.FECHA_FINAL)+7,
  MAX(PERI.FECHA), MAX(PERI.FECHA_FINAL)
  --TRUNC(PERI.FECHA_FINAL)+1, TRUNC(PERI.FECHA_FINAL)+8, MAX(PERI.FECHA), MAX(PERI.MAX_FECHA_CIERRE)
  FROM PREVIO_TOFILESTRING PTFS
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO PERI
		ON ( --PTFS.PIPS_SEMANA IS NOT NULL AND PTFS.PIPS_SEMANA>0 AND
			 NVL(PTFS.PIPS_SEMANA,0)>PERI.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>PERI.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>PERI.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>PERI.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>PERI.FILTRO_R2_SEMANA AND PTFS.R2_MES>PERI.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>PERI.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>PERI.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>PERI.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>PERI.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>PERI.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>PERI.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=PERI.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN PERI.FECHA_FINAL AND (PERI.FECHA_FINAL+7) --ADD_MONTHS(PERI.FECHA_FINAL,1)
			AND PTFS.FECHA_SEMANA BETWEEN PERI.MAX_FECHA_CIERRE AND (PERI.MAX_FECHA_CIERRE+7) --ADD_MONTHS(PERI.MAX_FECHA_CIERRE,1)
  WHERE 
	(/*(PERI.TIPO_OPERACION='BUY' AND PERI.PIPS_TOTALES>1000 
	  AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10	  
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  --AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	 ) OR*/
	(PERI.TIPO_OPERACION='SELL' AND PERI.PIPS_TOTALES>0  
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	 ) /*OR
	(PERI.PIPS_TOTALES<=1000
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>0 AND PERI.PIPS_AGRUPADO_HORAS>0 AND PERI.PIPS_AGRUPADO_DIAS>0)
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200	
	 )*/
	)
	  AND PTFS.FECHA_SEMANA>TO_DATE('20131231','YYYYMMDD')
  GROUP BY PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA;

SELECT TO_CHAR(PERI.FECHA_FINAL,'YYYYMM') FE, COUNT(*), SUM(PIPS_TOTALES), ROUND(AVG(FECHA_FINAL-FECHA_INICIAL)/30,2) PROMES
FROM ESTRATEGIA_OPERACION_PERIODO PERI
WHERE 
	(/*(PERI.TIPO_OPERACION='BUY' AND PERI.PIPS_TOTALES>1000 
	  AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10	  
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  --AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	 ) OR*/
	(PERI.TIPO_OPERACION='SELL' AND PERI.PIPS_TOTALES>0  
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	 ) /*OR
	(PERI.PIPS_TOTALES<=1000
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>0 AND PERI.PIPS_AGRUPADO_HORAS>0 AND PERI.PIPS_AGRUPADO_DIAS>0)
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200	
	 )*/
	)
AND PERI.FECHA_FINAL>=TO_DATE('20131231','YYYYMMDD')
AND PERI.FECHA>TRUNC(SYSDATE)
GROUP BY TO_CHAR(PERI.FECHA_FINAL,'YYYYMM')
ORDER BY TO_CHAR(PERI.FECHA_FINAL,'YYYYMM') DESC
;

SELECT ROUND(PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30),2) PROCANT, 
  ROUND((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30,2) MESES, PERI.*
FROM ESTRATEGIA_OPERACION_PERIODO PERI
WHERE 
	((PERI.TIPO_OPERACION='BUY' AND PERI.PIPS_TOTALES>1000 
	  AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10	  
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  --AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	 ) OR
	(PERI.TIPO_OPERACION='SELL' AND PERI.PIPS_TOTALES>0  
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	 ) OR
	(PERI.PIPS_TOTALES<=1000
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>0 AND PERI.PIPS_AGRUPADO_HORAS>0 AND PERI.PIPS_AGRUPADO_DIAS>0)
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200	
	 )
	)  
AND PERI.FECHA_FINAL>=TO_DATE('20161030','YYYYMMDD')
ORDER BY PERI.FECHA_FINAL DESC, PERI.ID DESC
;

SELECT ROUND(((PTFS.PIPS_SEMANA)+(PTFS.PIPS_MES)+(PTFS.PIPS_ANYO)+(PTFS.PIPS_TOTALES)+(PERI.PIPS_TOTALES_PARALELAS))/5) ORDER1,
  PERI.ID, PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA, ROUND((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30) DIFF, PERI.*
	--,ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES))/4) PROM, 
	--MIN(PTFS.PIPS_TOTALES) ORDER2,
  --PTFS.FECHA_SEMANA, PTFS.FECHA_SEMANA+7
  FROM PREVIO_TOFILESTRING PTFS
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO PERI
		ON ( NVL(PTFS.PIPS_SEMANA,0)>PERI.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>PERI.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>PERI.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>PERI.FILTRO_PIPS_TOTALES)
			--AND (NVL(PTFS.R2_SEMANA,0)>PERI.FILTRO_R2_SEMANA AND PTFS.R2_MES>PERI.FILTRO_R2_MES 
			--AND PTFS.R2_ANYO>PERI.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>PERI.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>PERI.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>PERI.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>PERI.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>PERI.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=PERI.TIPO_OPERACION
			--AND PTFS.FECHA_SEMANA BETWEEN PERI.FECHA_FINAL AND (PERI.FECHA_FINAL+7) --ADD_MONTHS(PERI.FECHA_FINAL,1)
			--AND PTFS.FECHA_SEMANA BETWEEN PERI.MAX_FECHA_CIERRE AND (PERI.MAX_FECHA_CIERRE+7) --ADD_MONTHS(PERI.MAX_FECHA_CIERRE,1)
  WHERE 
	((PERI.TIPO_OPERACION='BUY' AND PERI.PIPS_TOTALES>1000 
	  AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10	  
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  --AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	 ) OR
	(PERI.TIPO_OPERACION='SELL' --AND PERI.PIPS_TOTALES>0  
	  --AND PERI.PIPS_TOTALES_PARALELAS>0
	 ) OR
	(PERI.PIPS_TOTALES<=1000
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>0 AND PERI.PIPS_AGRUPADO_HORAS>0 AND PERI.PIPS_AGRUPADO_DIAS>0)
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200	
	 )
	)
	  AND PTFS.FECHA_SEMANA>TO_DATE('20131011','YYYYMMDD')
    AND PTFS.ID_INDIVIDUO='1477365411387.16129'
    --AND PERI.ID=902455
    --AND ROWNUM<10
  --GROUP BY PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA, PERI.ID
  ORDER BY PTFS.FECHA_SEMANA DESC, PERI.MAX_FECHA_CIERRE DESC,
    ROUND(((PTFS.PIPS_SEMANA)+(PTFS.PIPS_MES)+(PTFS.PIPS_ANYO)+(PTFS.PIPS_TOTALES)+(PERI.PIPS_TOTALES_PARALELAS))/5) DESC,
    PERI.ID DESC;
    
SELECT MIN(FILTRO_R2_SEMANA) MIN_R2_SEM, MAX(FILTRO_R2_SEMANA) MAX_R2_SEM,
  MIN(FILTRO_R2_MES) MIN_R2_MES, MAX(FILTRO_R2_MES) MAX_R2_MES,
  MIN(FILTRO_R2_ANYO) MIN_R2_ANYO, MAX(FILTRO_R2_ANYO) MAX_R2_ANYO,
  MIN(FILTRO_R2_TOTALES) MIN_R2_TOTALES, MAX(FILTRO_R2_TOTALES) MAX_R2_TOTALES,
  MIN(FILTRO_PENDIENTE_SEMANA) MIN_PENDIENTE_SEM, MAX(FILTRO_PENDIENTE_SEMANA) MAX_PENDIENTE_SEM,
  MIN(FILTRO_PENDIENTE_MES) MIN_PENDIENTE_MES, MAX(FILTRO_PENDIENTE_MES) MAX_PENDIENTE_MES,
  MIN(FILTRO_PENDIENTE_ANYO) MIN_PENDIENTE_ANYO, MAX(FILTRO_PENDIENTE_ANYO) MAX_PENDIENTE_ANYO,
  MIN(FILTRO_PENDIENTE_TOTALES) MIN_PENDIENTE_TOTALES, MAX(FILTRO_PENDIENTE_TOTALES) MAX_PENDIENTE_TOTALES,
  MIN(FILTRO_PIPS_X_SEMANA) MIN_SEM, MAX(FILTRO_PIPS_X_SEMANA) MAX_SEM,
  MIN(FILTRO_PIPS_X_MES) MIN_MES, MAX(FILTRO_PIPS_X_MES) MAX_MES,
  MIN(FILTRO_PIPS_X_ANYO) MIN_ANYO, MAX(FILTRO_PIPS_X_ANYO) MAX_ANYO,
  MIN(FILTRO_PIPS_TOTALES) MINTOT, MAX(FILTRO_PIPS_TOTALES) MAXTOT,
  ROUND(AVG(FECHA_FINAL-FECHA_INICIAL)/30) MESES
FROM ESTRATEGIA_OPERACION_PERIODO EOP
WHERE PIPS_TOTALES>0 AND EOP.FECHA_FINAL>=TO_DATE('20131001','YYYYMMDD')
;
SELECT 
DISTINCT 
				 FILTRO_PIPS_X_SEMANA R_SEMANA, FILTRO_PIPS_X_MES R_MES, 
				 FILTRO_PIPS_X_ANYO R_ANYO, FILTRO_PIPS_TOTALES R_TOTALES,
				 FILTRO_R2_SEMANA R2_SEMANA, FILTRO_R2_MES R2_MES, 
				 FILTRO_R2_ANYO R2_ANYO, FILTRO_R2_TOTALES R2_TOTALES, 
				 FILTRO_PENDIENTE_SEMANA PENDIENTE_SEMANA, FILTRO_PENDIENTE_MES PENDIENTE_MES,
				 FILTRO_PENDIENTE_ANYO PENDIENTE_ANYO, FILTRO_PENDIENTE_TOTALES PENDIENTE_TOTALES
--				 ,EOP.*
				 FROM ESTRATEGIA_OPERACION_PERIODO EOP
				 WHERE EOP.PIPS_TOTALES>0 AND  EOP.PIPS_TOTALES_PARALELAS>0 
				 AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
				 AND CANTIDAD>1 AND CANTIDAD_INDIVIDUOS>1
				 AND TIPO_OPERACION='SELL'
				 --AND ROWNUM<100
				 ;
				 
--SELECT COUNT(*) FROM (
SELECT MAX(EOP.PIPS_TOTALES), MAX(EOP.PIPS_TOTALES_PARALELAS),
  FLOOR(FILTRO_PIPS_X_SEMANA/ 100)*100 R_SEMANA, FLOOR(FILTRO_PIPS_X_MES/ 100)*100 R_MES, FLOOR(
  FILTRO_PIPS_X_ANYO        / 100)*100 R_ANYO  , FLOOR(FILTRO_PIPS_TOTALES/ 100)*100 R_TOTALES,
  ROUND(FILTRO_R2_SEMANA,2) R2_SEMANA          , ROUND(FILTRO_R2_MES,2) R2_MES, ROUND(
  FILTRO_R2_ANYO,2) R2_ANYO                    , ROUND(FILTRO_R2_TOTALES,2) R2_TOTALES, ROUND(
  FILTRO_PENDIENTE_SEMANA,2) PENDIENTE_SEMANA  , ROUND(FILTRO_PENDIENTE_MES,2) PENDIENTE_MES,
  ROUND(FILTRO_PENDIENTE_ANYO,2) PENDIENTE_ANYO, ROUND(FILTRO_PENDIENTE_TOTALES,2)
  PENDIENTE_TOTALES
FROM
  ESTRATEGIA_OPERACION_PERIODO EOP
--WHERE EOP.TIPO_OPERACION='SELL'
GROUP BY
  FLOOR(FILTRO_PIPS_X_SEMANA/ 100), FLOOR(FILTRO_PIPS_X_MES/ 100), FLOOR(FILTRO_PIPS_X_ANYO/ 100),
  FLOOR(FILTRO_PIPS_TOTALES / 100), ROUND(FILTRO_R2_SEMANA,2), ROUND(FILTRO_R2_MES,2), ROUND(
  FILTRO_R2_ANYO,2)               , ROUND(FILTRO_R2_TOTALES,2), ROUND(FILTRO_PENDIENTE_SEMANA,2),
  ROUND(FILTRO_PENDIENTE_MES,2)   , ROUND(FILTRO_PENDIENTE_ANYO,2), ROUND(FILTRO_PENDIENTE_TOTALES
  ,2)
HAVING
  MAX(EOP.PIPS_TOTALES)>0 AND
  MAX(EOP.PIPS_TOTALES_PARALELAS)>0
ORDER BY MAX(EOP.PIPS_TOTALES_PARALELAS) DESC, MAX(EOP.PIPS_TOTALES) DESC,
  ROUND(FLOOR(AVG(EOP.PIPS_TOTALES)/1000))*1000 DESC, ROUND(FLOOR(AVG(EOP.PIPS_TOTALES_PARALELAS)/
  1000))                           *1000 DESC       , ROUND(FLOOR(AVG(EOP.PIPS_AGRUPADO_DIAS)/100)
  )                                *100 DESC        , ROUND(FLOOR(AVG(EOP.PIPS_AGRUPADO_HORAS)/100
  ))                               *100 DESC        , ROUND(FLOOR(AVG(EOP.PIPS_AGRUPADO_MINUTOS)/
  100))                            *100 DESC 
  --)
  ;
  
SELECT PTFS.ID_INDIVIDUO, MAX(PERI.ID),
	ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES)+MAX(PERI.PIPS_TOTALES_PARALELAS))/5) PROM, 
	MAX(PERI.PIPS_TOTALES_PARALELAS) MAXPTP,
  PTFS.FECHA_SEMANA, PTFS.FECHA_SEMANA+7, MAX(PERI.FECHA) MAXFE, MAX(PERI.MAX_FECHA_CIERRE) MAXFECIERRE
  --TRUNC(PERI.FECHA_FINAL)+1, TRUNC(PERI.FECHA_FINAL)+8, MAX(PERI.FECHA), MAX(PERI.MAX_FECHA_CIERRE)
  FROM PREVIO_TOFILESTRING PTFS
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO PERI
		ON ( NVL(PTFS.PIPS_SEMANA,0)>PERI.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>PERI.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>PERI.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>PERI.FILTRO_PIPS_TOTALES)
			AND (PTFS.R2_SEMANA>PERI.FILTRO_R2_SEMANA AND PTFS.R2_MES>PERI.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>PERI.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>PERI.FILTRO_R2_TOTALES)
			AND (PTFS.PENDIENTE_SEMANA>PERI.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>PERI.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>PERI.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>PERI.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=PERI.TIPO_OPERACION
			--AND PTFS.FECHA_SEMANA BETWEEN PERI.FECHA_FINAL AND (PERI.FECHA_FINAL+14) --ADD_MONTHS(PERI.FECHA_FINAL,1)
			--AND PTFS.FECHA_SEMANA BETWEEN PERI.MAX_FECHA_CIERRE AND (PERI.MAX_FECHA_CIERRE+14) --ADD_MONTHS(PERI.MAX_FECHA_CIERRE,1)
  WHERE 
	(PERI.PIPS_TOTALES>1000 
	  --AND PERI.ID BETWEEN 1627690 AND 11627690 
	  --AND PERI.ID>=278221 --174486 --1047445 --278221
	  AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10	  
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  --AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  --AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	  )
	  AND PERI.FECHA_FINAL>TO_DATE('20131231','YYYYMMDD')
    AND PTFS.FECHA_SEMANA>TO_DATE('20161101','YYYYMMDD')
  GROUP BY PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA
  ORDER BY PTFS.FECHA_SEMANA DESC
  ;
  
  SELECT EOP1.*, EOP2.*
FROM ESTRATEGIA_OPERACION_PERIODO EOP1
INNER JOIN ESTRATEGIA_OPERACION_PERIODO EOP2
  ON EOP1.ID<>EOP2.ID AND EOP1.FILTRO_PIPS_X_SEMANA=EOP2.FILTRO_PIPS_X_SEMANA AND EOP1.FILTRO_PIPS_X_MES=EOP2.FILTRO_PIPS_X_MES
			AND EOP1.FILTRO_PIPS_X_ANYO=EOP2.FILTRO_PIPS_X_ANYO AND EOP1.FILTRO_PIPS_TOTALES=EOP2.FILTRO_PIPS_TOTALES
      AND EOP1.FILTRO_R2_SEMANA=EOP2.FILTRO_R2_SEMANA AND EOP1.FILTRO_R2_MES=EOP2.FILTRO_R2_MES
			AND EOP1.FILTRO_R2_ANYO=EOP2.FILTRO_R2_ANYO AND EOP1.FILTRO_PIPS_TOTALES=EOP2.FILTRO_PIPS_TOTALES
      AND EOP1.FILTRO_PENDIENTE_SEMANA=EOP2.FILTRO_PENDIENTE_SEMANA AND EOP1.FILTRO_PENDIENTE_MES=EOP2.FILTRO_PENDIENTE_MES
			AND EOP1.FILTRO_PENDIENTE_ANYO=EOP2.FILTRO_PENDIENTE_ANYO AND EOP1.FILTRO_PIPS_TOTALES=EOP2.FILTRO_PIPS_TOTALES
      AND (EOP1.FECHA_INICIAL<>EOP2.FECHA_INICIAL OR EOP1.FECHA_FINAL<>EOP2.FECHA_FINAL)
WHERE (EOP1.PIPS_TOTALES>EOP2.PIPS_TOTALES AND EOP1.PIPS_TOTALES_PARALELAS>EOP2.PIPS_TOTALES_PARALELAS)
AND EOP1.CANTIDAD>0 AND EOP2.CANTIDAD>0
ORDER BY EOP1.ID DESC
      ;
