SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'Altering PREVIO_TOFILESTRING ...' FROM DUAL;
/
DROP INDEX PTFS_IDX1;
CREATE INDEX PTFS_IDX1 ON PREVIO_TOFILESTRING (ID_INDIVIDUO ASC, FECHA_SEMANA ASC, TIPO_OPERACION ASC, 
	NVL(PIPS_SEMANA, 0) ASC, PIPS_MES ASC, PIPS_ANYO ASC, PIPS_TOTALES ASC,
	NVL(R2_SEMANA, 0) ASC, R2_MES ASC, R2_ANYO ASC, R2_CONSOL ASC,
	NVL(PENDIENTE_SEMANA, 0) ASC, PENDIENTE_MES ASC, PENDIENTE_ANYO ASC, PENDIENTE_CONSOL ASC) 
LOGGING 
TABLESPACE TS_FOREX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'Altering ESTRATEGIA_OPERACION_PERIODO ...' FROM DUAL;
/

ALTER TABLE ESTRATEGIA_OPERACION_PERIODO ADD (EOP_VERSION VARCHAR2(10 CHAR) );

CREATE INDEX EOP_VERSION_IDX ON ESTRATEGIA_OPERACION_PERIODO (EOP_VERSION ASC);
ALTER TABLE ESTRATEGIA_OPERACION_PERIODO 
DROP CONSTRAINT ESTRATEGIA_OPERACION_PERIO_PK;

ALTER TABLE ESTRATEGIA_OPERACION_PERIODO  
MODIFY (MAX_FECHA_CIERRE NOT NULL);

ALTER TABLE ESTRATEGIA_OPERACION_PERIODO
ADD CONSTRAINT ESTRATEGIA_OPERACION_PERIO_PK PRIMARY KEY 
(
  FILTRO_PIPS_X_SEMANA 
, FILTRO_PIPS_X_MES 
, FILTRO_PIPS_X_ANYO 
, FILTRO_PIPS_TOTALES 
, FIRST_ORDER 
, FECHA_INICIAL 
, FECHA_FINAL 
, TIPO_OPERACION 
, FILTRO_PENDIENTE_SEMANA 
, FILTRO_PENDIENTE_MES 
, FILTRO_PENDIENTE_ANYO 
, FILTRO_PENDIENTE_TOTALES 
, FILTRO_R2_SEMANA 
, FILTRO_R2_MES 
, FILTRO_R2_ANYO 
, FILTRO_R2_TOTALES 
, MAX_FECHA_CIERRE 
)
ENABLE;

UPDATE ESTRATEGIA_OPERACION_PERIODO SET EOP_VERSION = '2016' WHERE EOP_VERSION IS NULL AND ROWNUM<10000;
COMMIT;
/

SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'Creating VIEW LOGS...' FROM DUAL;
/
CREATE MATERIALIZED VIEW LOG ON ESTRATEGIA_OPERACION_PERIODO 
WITH ROWID 
INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON PREVIO_TOFILESTRING 
WITH ROWID 
INCLUDING NEW VALUES;

--DROP MATERIALIZED VIEW FILTERED_PARA_OPERAR ;
--/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'CREATING FILTERED_PARA_OPERAR_SELL...' FROM DUAL;
/
CREATE MATERIALIZED VIEW FILTERED_PARA_OPERAR_SELL
NOCACHE 
USING INDEX 
REFRESH ON DEMAND 
FORCE 
WITH PRIMARY KEY 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS
SELECT PTFS.ID_INDIVIDUO,PTFS.FECHA_SEMANA,PTFS.PIPS_SEMANA,PTFS.PIPS_MES,PTFS.PIPS_ANYO,PTFS.PIPS_TOTALES,PTFS.TIPO_OPERACION,PTFS.FECHA_HISTORICO,PTFS.R_COUNT_SEMANA,PTFS.R2_SEMANA,PTFS.PENDIENTE_SEMANA,PTFS.INTERCEPCION_SEMANA,PTFS.R_COUNT_MES,PTFS.R2_MES,PTFS.PENDIENTE_MES,PTFS.INTERCEPCION_MES,PTFS.R_COUNT_ANYO,PTFS.R2_ANYO,PTFS.PENDIENTE_ANYO,PTFS.INTERCEPCION_ANYO,PTFS.R_COUNT_CONSOL,PTFS.R2_CONSOL,PTFS.PENDIENTE_CONSOL,PTFS.INTERCEPCION_CONSOL,
	EOP.CANTIDAD,EOP.FILTRO_PIPS_X_MES,EOP.FILTRO_PIPS_X_ANYO,EOP.FILTRO_PIPS_TOTALES,EOP.FIRST_ORDER,EOP.SECOND_ORDER,EOP.FECHA,EOP.PIPS_TOTALES EOP_PIPS_TOTALES,EOP.FECHA_INICIAL,EOP.FECHA_FINAL,EOP.ID,EOP.CANTIDAD_PARALELAS,EOP.PIPS_TOTALES_PARALELAS,EOP.PIPS_AGRUPADO_MINUTOS,EOP.PIPS_AGRUPADO_HORAS,EOP.PIPS_AGRUPADO_DIAS,EOP.FILTRO_PIPS_X_SEMANA,EOP.FILTRO_PENDIENTE_SEMANA,EOP.FILTRO_PENDIENTE_MES,EOP.FILTRO_PENDIENTE_ANYO,EOP.FILTRO_PENDIENTE_TOTALES,EOP.FILTRO_R2_SEMANA,EOP.FILTRO_R2_MES,EOP.FILTRO_R2_ANYO,EOP.FILTRO_R2_TOTALES,EOP.CANTIDAD_INDIVIDUOS,EOP.MAX_FECHA_CIERRE,EOP.EOP_VERSION,
	PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID
  FROM PREVIO_TOFILESTRING PTFS, ESTRATEGIA_OPERACION_PERIODO EOP
		WHERE ( --PTFS.PIPS_SEMANA IS NOT NULL AND PTFS.PIPS_SEMANA>0 AND
			 NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>EOP.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND PTFS.R2_MES>EOP.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>EOP.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7)   
	AND ((EOP.TIPO_OPERACION='SELL' AND EOP.PIPS_TOTALES>0
		AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
		AND EOP.PIPS_TOTALES_PARALELAS>0
	 ) OR
	(EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200	
	 )
	)
	AND EOP.TIPO_OPERACION='SELL'
	AND PTFS.FECHA_SEMANA>TO_DATE('20141231','YYYYMMDD')	
	;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'CREATED FILTERED_PARA_OPERAR_BUY...' FROM DUAL;
/
CREATE MATERIALIZED VIEW FILTERED_PARA_OPERAR_BUY
NOCACHE 
USING INDEX 
REFRESH ON DEMAND 
FORCE 
WITH PRIMARY KEY 
USING DEFAULT ROLLBACK SEGMENT 
DISABLE QUERY REWRITE AS
SELECT PTFS.ID_INDIVIDUO,PTFS.FECHA_SEMANA,PTFS.PIPS_SEMANA,PTFS.PIPS_MES,PTFS.PIPS_ANYO,PTFS.PIPS_TOTALES,PTFS.TIPO_OPERACION,PTFS.FECHA_HISTORICO,PTFS.R_COUNT_SEMANA,PTFS.R2_SEMANA,PTFS.PENDIENTE_SEMANA,PTFS.INTERCEPCION_SEMANA,PTFS.R_COUNT_MES,PTFS.R2_MES,PTFS.PENDIENTE_MES,PTFS.INTERCEPCION_MES,PTFS.R_COUNT_ANYO,PTFS.R2_ANYO,PTFS.PENDIENTE_ANYO,PTFS.INTERCEPCION_ANYO,PTFS.R_COUNT_CONSOL,PTFS.R2_CONSOL,PTFS.PENDIENTE_CONSOL,PTFS.INTERCEPCION_CONSOL,
	EOP.CANTIDAD,EOP.FILTRO_PIPS_X_MES,EOP.FILTRO_PIPS_X_ANYO,EOP.FILTRO_PIPS_TOTALES,EOP.FIRST_ORDER,EOP.SECOND_ORDER,EOP.FECHA,EOP.PIPS_TOTALES EOP_PIPS_TOTALES,EOP.FECHA_INICIAL,EOP.FECHA_FINAL,EOP.ID,EOP.CANTIDAD_PARALELAS,EOP.PIPS_TOTALES_PARALELAS,EOP.PIPS_AGRUPADO_MINUTOS,EOP.PIPS_AGRUPADO_HORAS,EOP.PIPS_AGRUPADO_DIAS,EOP.FILTRO_PIPS_X_SEMANA,EOP.FILTRO_PENDIENTE_SEMANA,EOP.FILTRO_PENDIENTE_MES,EOP.FILTRO_PENDIENTE_ANYO,EOP.FILTRO_PENDIENTE_TOTALES,EOP.FILTRO_R2_SEMANA,EOP.FILTRO_R2_MES,EOP.FILTRO_R2_ANYO,EOP.FILTRO_R2_TOTALES,EOP.CANTIDAD_INDIVIDUOS,EOP.MAX_FECHA_CIERRE,EOP.EOP_VERSION,
	PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID
  FROM PREVIO_TOFILESTRING PTFS, ESTRATEGIA_OPERACION_PERIODO EOP
		WHERE ( --PTFS.PIPS_SEMANA IS NOT NULL AND PTFS.PIPS_SEMANA>0 AND
			 NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND PTFS.PIPS_MES>EOP.FILTRO_PIPS_X_MES 
			AND PTFS.PIPS_ANYO>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND PTFS.R2_MES>EOP.FILTRO_R2_MES 
			AND PTFS.R2_ANYO>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND PTFS.PENDIENTE_MES>EOP.FILTRO_PENDIENTE_MES 
			AND PTFS.PENDIENTE_ANYO>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7)   
	AND ((EOP.TIPO_OPERACION='BUY' AND EOP.PIPS_TOTALES>1000 
	  AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
	  AND EOP.PIPS_TOTALES_PARALELAS>3000
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>1000 AND EOP.PIPS_AGRUPADO_HORAS>1000 AND EOP.PIPS_AGRUPADO_DIAS>1000)
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)<10	  
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)>1
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND EOP.CANTIDAD/((EOP.FECHA_FINAL-EOP.FECHA_INICIAL)/30)>1
	  AND (EOP.PIPS_TOTALES/EOP.CANTIDAD)>200
	  --AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200
	 ) OR
	(EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200	
	 )
	)
	AND EOP.TIPO_OPERACION='BUY'
	AND PTFS.FECHA_SEMANA>TO_DATE('20141231','YYYYMMDD')	
	;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'CREATED FILTERED_PARA_OPERAR...' FROM DUAL;
/
