SET echo OFF;
SET feedback off;
SET term off;
SET pagesize 0;
SET linesize 5000;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias6HMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*0.25/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
	FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;
SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias12HMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*0.5/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;
SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias1DMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*1/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;
SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias2DMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*2/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO		
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		--AND WEEK_MINUTES(TT.FECHA, TEN.FECHA_BASE)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;
SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias3DMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*3/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;
SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias5DMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*5/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;

SPOOL c:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\Common\Files\estrategias\Tendencias10DMOD.csv;
WITH TIEMPO_TENDENCIA AS (SELECT (24*10/24)*24*60 TIEMPO, TO_DATE('2017.03.13 18:22','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='
		--'FECHA_TENDENCIA='||TO_CHAR(GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120), 'YYYY.MM.DD HH24:MI')||',PRECIO_CALCULADO='
		||ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND (TT.FECHA-TEN.FECHA_BASE)<1
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA, 'HH24')
	GROUP BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120)
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24')
	ORDER BY 
		--GROUP_BY_MINUTES(TEN.FECHA_TENDENCIA, 120) ASC
		TO_CHAR(TEN.FECHA_TENDENCIA-(TIEMPO/60/24), 'YYYY.MM.DD HH24') ASC
;
SPOOL OFF;
