ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
/
DECLARE
	V_T1 VARCHAR2(1000);
	PARAM_DATE DATE;
	MAX_DATE DATE;
	CURSOR C1 (V_DATE DATE) IS
WITH TIEMPO_TENDENCIA AS (
	SELECT (120) T2H, (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*3/24)*24*60 T3D, (24*5/24)*24*60 T5D, (24*10/24)*24*60 T10D,
		--0.2 R2_MINIMO, 0.0001 PENDIENTE_MINIMA,
		0.5 R2_MINIMO, 0.005 PENDIENTE_MINIMA, 15 MINPIPS,
		--0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.2 PORC2D, 0.2 PORC5D, 0.3 PORC10D,
		--0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.15 PORC2D, 0.15 PORC3D, 0.2 PORC5D, 0.2 PORC10D,
		0.05 PORC6H, 0.05 PORC12H, 0.1 PORC1D, 0.2 PORC2D, 0.2 PORC3D, 0.2 PORC5D, 0.2 PORC10D,
		7 CANTIDAD_TENDENCIAS,
		(24*1/24)*24*60  TIEMPO_PROYECCION, (24*5/24)*24*60 TIEMPO_REGRESION, (24*2/24)*24*60 TIEMPO_MAX_MIN,
		V_DATE FECHA_PROCESO,
		--TO_DATE('2017.01.19 08:19', 'YYYY/MM/DD HH24:MI') FECHA_PROCESO,
		'BUY_SELL_20170204-2' TIPO_TENDENCIA1 FROM DUAL),
TENDENCIA_6H AS (SELECT '6H' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_12H AS (SELECT '12H' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_1D AS (SELECT '1D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_2D AS (SELECT '2D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_3D AS (SELECT '3D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T3D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_5D AS (SELECT '5D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
			AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
			AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
			AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
TENDENCIA_10D AS (SELECT '10D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
		ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
		COUNT(*) CANTIDAD,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T10D
		AND TEN.FECHA_BASE<=TT.FECHA_PROCESO
		AND TEN.FECHA_TENDENCIA>TT.FECHA_PROCESO
		AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
		--AND TRUNC(TEN.FECHA_TENDENCIA, 'HH24')>TRUNC(TT.FECHA_PROCESO, 'HH24')
	GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
PONDERADO AS (SELECT 'TOTAL' PERIODO, TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA,
		(ROUND((NVL(TEN6H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)))*TT.PORC6H
		+NVL(TEN12H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO))*TT.PORC12H
		+MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC1D
		+MULTIPLE_NVL(TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC2D
		+MULTIPLE_NVL(TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC3D
		+NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC5D
		+TEN10D.PRECIO_CALCULADO*TT.PORC10D),5)) PRECIO_CALCULADO,
		TEN10D.CANTIDAD CANTIDAD, TEN10D.MINFETENDENCIA, TEN10D.MAXFETENDENCIA
FROM TIEMPO_TENDENCIA TT, TENDENCIA_10D TEN10D
	LEFT JOIN TENDENCIA_6H TEN6H ON TEN10D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_12H TEN12H ON TEN10D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_1D TEN1D ON TEN10D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_2D TEN2D ON TEN10D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_3D TEN3D ON TEN10D.FECHA_TENDENCIA=TEN3D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_5D TEN5D ON TEN10D.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA),
REGRESION_6H AS (SELECT '6H' PERIODO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) PENDIENTE,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA_6H TEN
		--WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.T6H
		--ORDER BY TEN.FECHA_TENDENCIA ASC
		),
REGRESION_12H AS (SELECT '12H' PERIODO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) PENDIENTE,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA_12H TEN
		--WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.T12H
		--ORDER BY TEN.FECHA_TENDENCIA ASC
		),	
REGRESION_1D AS (SELECT '1D' PERIODO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) PENDIENTE,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA_1D TEN
		--WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.T1D
		--ORDER BY TEN.FECHA_TENDENCIA ASC
		),	
REGRESION_2D AS (SELECT '2D' PERIODO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) PENDIENTE,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA_2D TEN
		--WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.T2D
		--ORDER BY TEN.FECHA_TENDENCIA ASC
		),
REGRESION_3D AS (SELECT '3D' PERIODO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) PENDIENTE,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
		FROM TIEMPO_TENDENCIA TT, TENDENCIA_3D TEN
		--WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.T3D
		--ORDER BY TEN.FECHA_TENDENCIA ASC
		),
REGRESION_5D AS (SELECT '5D' PERIODO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) R2,
	ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-TT.FECHA_PROCESO),5) PENDIENTE,
	MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
	FROM TIEMPO_TENDENCIA TT, TENDENCIA_5D TEN
	--WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.T5D
	--ORDER BY TEN.FECHA_TENDENCIA ASC
	),
REGRESIONES AS (
	SELECT REGS.PERIODO, REGS.R2, REGS.PENDIENTE, REGS.MINFETENDENCIA, REGS.MAXFETENDENCIA FROM (
		SELECT REG.* FROM TIEMPO_TENDENCIA TT, REGRESION_6H REG, REGRESION_5D REG_5D WHERE (REG.PENDIENTE*REG_5D.PENDIENTE)>0 AND REG.R2>TT.R2_MINIMO AND ABS(REG.PENDIENTE)>TT.PENDIENTE_MINIMA
		UNION ALL SELECT REG.* FROM TIEMPO_TENDENCIA TT, REGRESION_12H REG, REGRESION_5D REG_5D WHERE (REG.PENDIENTE*REG_5D.PENDIENTE)>0 AND REG.R2>TT.R2_MINIMO AND ABS(REG.PENDIENTE)>TT.PENDIENTE_MINIMA
		UNION ALL SELECT REG.* FROM TIEMPO_TENDENCIA TT, REGRESION_1D REG, REGRESION_5D REG_5D WHERE (REG.PENDIENTE*REG_5D.PENDIENTE)>0 AND REG.R2>TT.R2_MINIMO AND ABS(REG.PENDIENTE)>TT.PENDIENTE_MINIMA
		UNION ALL SELECT REG.* FROM TIEMPO_TENDENCIA TT, REGRESION_2D REG, REGRESION_5D REG_5D WHERE (REG.PENDIENTE*REG_5D.PENDIENTE)>0 AND REG.R2>TT.R2_MINIMO AND ABS(REG.PENDIENTE)>TT.PENDIENTE_MINIMA
		UNION ALL SELECT REG.* FROM TIEMPO_TENDENCIA TT, REGRESION_3D REG, REGRESION_5D REG_5D WHERE (REG.PENDIENTE*REG_5D.PENDIENTE)>0 AND REG.R2>TT.R2_MINIMO AND ABS(REG.PENDIENTE)>TT.PENDIENTE_MINIMA
		UNION ALL SELECT REG.* FROM TIEMPO_TENDENCIA TT, REGRESION_5D REG WHERE REG.R2>TT.R2_MINIMO AND ABS(REG.PENDIENTE)>TT.PENDIENTE_MINIMA
		) REGS
),
CANTIDAD_REG_IGUAL_PEND AS (
	SELECT COUNT(*) CANTIDAD FROM REGRESIONES
),
MEJOR_REGRESION AS (
	SELECT * FROM (
		SELECT REG.R2, REG.PENDIENTE, REG.MINFETENDENCIA, REG.MAXFETENDENCIA, ROW_NUMBER() OVER (ORDER BY PENDIENTE DESC) RN
		FROM REGRESIONES REG, CANTIDAD_REG_IGUAL_PEND CANTIDAD_REG, TIEMPO_TENDENCIA TT WHERE CANTIDAD_REG.CANTIDAD=TT.CANTIDAD_TENDENCIAS-1
	) WHERE RN=1
),
UNION_TENDENCIAS AS (
	SELECT * FROM TENDENCIA_6H TEN
			UNION ALL SELECT * FROM TENDENCIA_12H TEN
			UNION ALL SELECT * FROM TENDENCIA_1D TEN
			UNION ALL SELECT * FROM TENDENCIA_2D TEN
			UNION ALL SELECT * FROM TENDENCIA_5D TEN
			UNION ALL SELECT * FROM TENDENCIA_10D TEN
			UNION ALL SELECT * FROM PONDERADO TEN
),
TENDENCIAS_X_REGRESION AS (
	SELECT DISTINCT TEN.PERIODO PERIODO_TENDENCIA, TEN.FECHA_TENDENCIA FECHA_TENDENCIA, 
		PRECIO_CALCULADO, TEN.CANTIDAD, TEN.MINFETENDENCIA MINFETENDENCIA, TEN.MAXFETENDENCIA MAXFETENDENCIA,
		REG.PERIODO PERIODO_REGRESION, REG.R2, REG.PENDIENTE, 
		REG.MINFETENDENCIA MINFEREGRESION, REG.MAXFETENDENCIA MAXFEREGRESION
		FROM UNION_TENDENCIAS TEN, REGRESIONES REG
	WHERE TEN.FECHA_TENDENCIA BETWEEN REG.MINFETENDENCIA AND REG.MAXFETENDENCIA
),
MAX_MIN_X_REGRESION AS (
	SELECT REG.MINFETENDENCIA, REG.MAXFETENDENCIA, MIN(POND.PRECIO_CALCULADO) MINPRECIO, MAX(POND.PRECIO_CALCULADO) MAXPRECIO
	FROM REGRESIONES REG, PONDERADO POND
	WHERE POND.FECHA_TENDENCIA BETWEEN REG.MINFETENDENCIA AND REG.MAXFETENDENCIA
	GROUP BY REG.MINFETENDENCIA, REG.MAXFETENDENCIA
),
OPERAR_BUY AS (
	SELECT TEN.PERIODO_TENDENCIA, TEN.FECHA_TENDENCIA FECHA_TENDENCIA, TEN.PRECIO_CALCULADO, 
		MAXMIN.MAXPRECIO TAKE_PROFIT,
		LEAST(MAXMIN.MINPRECIO,TEN.PRECIO_CALCULADO-70/10000) STOP_LOSS,
		'BUY' TIPO_OPERACION, TEN.R2, TEN.PENDIENTE
	FROM MAX_MIN_X_REGRESION MAXMIN, TIEMPO_TENDENCIA TT, TENDENCIAS_X_REGRESION TEN, PONDERADO POND
	WHERE MAXMIN.MINFETENDENCIA=TEN.MINFEREGRESION AND MAXMIN.MAXFETENDENCIA=TEN.MAXFEREGRESION
	AND POND.FECHA_TENDENCIA=TEN.FECHA_TENDENCIA AND TEN.PRECIO_CALCULADO<=POND.PRECIO_CALCULADO
	AND TEN.PENDIENTE>0
	AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.TIEMPO_PROYECCION
),
OPERAR_SELL AS (
	SELECT TEN.PERIODO_TENDENCIA, TEN.FECHA_TENDENCIA FECHA_TENDENCIA, TEN.PRECIO_CALCULADO, 
		MAXMIN.MINPRECIO TAKE_PROFIT,
		GREATEST(MAXMIN.MAXPRECIO,TEN.PRECIO_CALCULADO+70/10000) STOP_LOSS,
		'SELL' TIPO_OPERACION, TEN.R2, TEN.PENDIENTE
	FROM MAX_MIN_X_REGRESION MAXMIN, TIEMPO_TENDENCIA TT, TENDENCIAS_X_REGRESION TEN, PONDERADO POND
	WHERE MAXMIN.MINFETENDENCIA=TEN.MINFEREGRESION AND MAXMIN.MAXFETENDENCIA=TEN.MAXFEREGRESION
	AND POND.FECHA_TENDENCIA=TEN.FECHA_TENDENCIA AND TEN.PRECIO_CALCULADO>=POND.PRECIO_CALCULADO
	AND TEN.PENDIENTE<0
	AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TT.FECHA_PROCESO)<TT.TIEMPO_PROYECCION
),
OPERAR AS (SELECT OP.*, 0.1 LOTE FROM (
		SELECT MIN(OPE.PERIODO_TENDENCIA) PERIODO, OPE.FECHA_TENDENCIA, OPE.PRECIO_CALCULADO,
			OPE.TAKE_PROFIT, MIN(OPE.STOP_LOSS) STOP_LOSS, OPE.TIPO_OPERACION, MAX(OPE.R2) R2, MAX(OPE.PENDIENTE) PENDIENTE
		FROM OPERAR_BUY OPE WHERE OPE.TAKE_PROFIT>OPE.PRECIO_CALCULADO
			GROUP BY OPE.FECHA_TENDENCIA, OPE.TIPO_OPERACION, OPE.PRECIO_CALCULADO, OPE.TAKE_PROFIT
		UNION ALL 
		SELECT MIN(OPE.PERIODO_TENDENCIA) PERIODO, OPE.FECHA_TENDENCIA, OPE.PRECIO_CALCULADO,
			OPE.TAKE_PROFIT, MAX(OPE.STOP_LOSS) STOP_LOSS, OPE.TIPO_OPERACION, MAX(OPE.R2) R2, MAX(OPE.PENDIENTE) PENDIENTE
		FROM OPERAR_SELL OPE WHERE OPE.TAKE_PROFIT<OPE.PRECIO_CALCULADO 
		GROUP BY OPE.FECHA_TENDENCIA, OPE.TIPO_OPERACION, OPE.PRECIO_CALCULADO, OPE.TAKE_PROFIT
	) OP, TIEMPO_TENDENCIA TT
	WHERE ABS(OP.PRECIO_CALCULADO-OP.TAKE_PROFIT)*10000>TT.MINPIPS
	AND ABS(OP.PRECIO_CALCULADO-OP.STOP_LOSS)*10000>TT.MINPIPS
), VALORES_TENDENCIA AS (
SELECT 'NAME='||OPERAR.PERIODO
		||',TIPO_OPERACION='||OPERAR.TIPO_OPERACION
		||',LOTE='||OPERAR.LOTE
		||',FECHA_TENDENCIA='||(TO_CHAR(OPERAR.FECHA_TENDENCIA, 'YYYY.MM.DD HH24:MI'))||',PRECIO_CALCULADO='
		||(OPERAR.PRECIO_CALCULADO)||',TAKE_PROFIT='||OPERAR.TAKE_PROFIT||',STOP_LOSS='||OPERAR.STOP_LOSS
			||',VIGENCIALOWER='||(TO_CHAR(GREATEST(TT.FECHA_PROCESO,OPERAR.FECHA_TENDENCIA), 'YYYY.MM.DD HH24:MI'))||',VIGENCIAHIGHER='||(TO_CHAR(OPERAR.FECHA_TENDENCIA+(2/24+1/60/24), 'YYYY.MM.DD HH24:MI'))
			||',FECHA_BASE='||(TO_CHAR(TT.FECHA_PROCESO, 'YYYY.MM.DD HH24:MI'))
			||',R2='||OPERAR.R2||',PENDIENTE='||OPERAR.PENDIENTE
			||',WEEK_MINUTES='||WEEK_MINUTES(OPERAR.FECHA_TENDENCIA,TT.FECHA_PROCESO)
		VAL_TENDENCIA
FROM TIEMPO_TENDENCIA TT, OPERAR OPERAR
ORDER BY OPERAR.FECHA_TENDENCIA ASC)
SELECT * FROM VALORES_TENDENCIA
;

BEGIN
	--DBMS_OUTPUT.PUT_LINE('CONSULTANDO...');
	PARAM_DATE:=TO_DATE('2017/01/19 00:00','YYYY/MM/DD HH24:MI');
	--PARAM_DATE:=TO_DATE('2017/02/10 01:13','YYYY/MM/DD HH24:MI');
	
	MAX_DATE:=TO_DATE('2017/02/10 23:58','YYYY/MM/DD HH24:MI');
	--MAX_DATE:=TO_DATE('2017.02.02 12:43','YYYY/MM/DD HH24:MI');
	WHILE ((PARAM_DATE <= MAX_DATE) AND (PARAM_DATE IS NOT NULL)) LOOP
			SELECT MIN(T.FECHA_BASE) INTO PARAM_DATE FROM
			(SELECT TEN.FECHA_BASE, COUNT(*) FROM TENDENCIA TEN WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170204-2')
				AND TEN.FECHA_BASE>PARAM_DATE+3/24
				GROUP BY TEN.FECHA_BASE
				HAVING COUNT(*)>100) T
			;
			FOR V_T1 IN C1((PARAM_DATE)) LOOP
				DBMS_OUTPUT.PUT_LINE(V_T1.VAL_TENDENCIA);
			END LOOP;
			DBMS_OUTPUT.PUT_LINE('PARAM_DATE 2: '||PARAM_DATE);
			--SELECT MIN(TEN.FECHA_BASE) INTO PARAM_DATE
			--FROM TENDENCIA TEN WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170204-2')
			--AND TEN.FECHA_BASE>PARAM_DATE;
	END LOOP;
END;
/
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
/

