TRUNCATE TABLE TMP_TOFILESTRING2;

INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2)
  SELECT OPER_SEMANA.ID_INDIVIDUO, SUM(OPER.PIPS), SUM(OPER.PIPS),
  SEMANAS.FECHA_SEMANA, SEMANAS.FECHA_SEMANA+7
  FROM OPERACION_X_SEMANA OPER_SEMANA
        INNER JOIN SEMANAS ON OPER_SEMANA.FECHA_SEMANA=(SEMANAS.FECHA_SEMANA-7) 
    INNER JOIN OPERACIONES_ACUM_SEMANA_MES OPER_MES
      ON OPER_MES.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO     
        AND OPER_MES.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
    INNER JOIN OPERACIONES_ACUM_SEMANA_ANYO OPER_ANYO 
      ON OPER_ANYO.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO     
        AND OPER_ANYO.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
    INNER JOIN OPERACIONES_ACUM_SEMANA_CONSOL OPER
      ON OPER_SEMANA.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
      AND OPER.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
  WHERE 
  ( ( OPER_SEMANA.PIPS>500 AND OPER_MES.PIPS>3800 AND OPER_ANYO.PIPS>4000 AND OPER.PIPS>1500)
 OR ( OPER_SEMANA.PIPS>500 AND OPER_MES.PIPS>3800 AND OPER_ANYO.PIPS>4000 AND OPER.PIPS>-1500)
 OR ( OPER_SEMANA.PIPS>-1000 AND OPER_MES.PIPS>3800 AND OPER_ANYO.PIPS>1600 AND OPER.PIPS>1500)
 OR ( OPER_SEMANA.PIPS>500 AND OPER_MES.PIPS>3800 AND OPER_ANYO.PIPS>4000 AND OPER.PIPS>-3000)
 OR ( OPER_SEMANA.PIPS>500 AND OPER_MES.PIPS>3800 AND OPER_ANYO.PIPS>4000 AND OPER.PIPS>0)
  )
 AND SEMANAS.FECHA_SEMANA > TO_DATE('20111231','YYYYMMDD')
  --AND OPER_SEMANA.ID_INDIVIDUO ='1453664590875.284'
  GROUP BY OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA;
commit;

@"d:\ricardorq85\Informacion\FOREX\DATABASE\ToFileStringFromTEMP_TOFILESTRING.sql";