ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
/
DECLARE
	V_T1 VARCHAR2(1000);
	PARAM_DATE DATE;
	MAX_DATE DATE;
	CURSOR C1 (V_DATE DATE) IS
		WITH TIEMPO_TENDENCIA AS (
			SELECT (120) T2H, (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
				(24*2/24)*24*60 T2D, (24*3/24)*24*60 T3D, (24*5/24)*24*60 T5D, (24*10/24)*24*60 T10D,
				--0.2 R2_MINIMO, 0.0001 PENDIENTE_MINIMA,
				0.001 R2_MINIMO, 0.00005 PENDIENTE_MINIMA,
				--0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.2 PORC2D, 0.2 PORC5D, 0.3 PORC10D,
				0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.15 PORC2D, 0.15 PORC3D, 0.2 PORC5D, 0.2 PORC10D,
				(24*1/24)*24*60 TIEMPO_PROYECCION, (24*5/24)*24*60 TIEMPO_REGRESION, (24*2/24)*24*60 TIEMPO_MAX_MIN,
							V_DATE FECHA,
							--TO_DATE('2017.02.07 06:00', 'YYYY/MM/DD HH24:MI') FECHA,
							'BUY_SELL_20170204-2' TIPO_TENDENCIA1, NULL TIPO_TENDENCIA2, NULL TIPO_TENDENCIA3 
							FROM DUAL),
						TENDENCIA_6H AS (SELECT '6H' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									COUNT(*) CANTIDAD,
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H									
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_12H AS (SELECT '12H' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									COUNT(*) CANTIDAD, 
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_1D AS (SELECT '1D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									COUNT(*) CANTIDAD, 
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D									
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_2D AS (SELECT '2D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									COUNT(*) CANTIDAD, 
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D									
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_3D AS (SELECT '3D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									COUNT(*) CANTIDAD, 
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T3D									
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_5D AS (SELECT '5D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									COUNT(*) CANTIDAD, 
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D									
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
				TENDENCIA_10D AS (SELECT '10D' PERIODO, TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
						ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
						COUNT(*) CANTIDAD,
						MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
						WHERE TEN.TIPO_TENDENCIA=TIPO_TENDENCIA1
						AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T10D						
						AND TEN.FECHA_BASE<=TT.FECHA
						AND TEN.FECHA_TENDENCIA>TT.FECHA
						AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
					GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
					PONDERADO AS (SELECT 'TOTAL' PERIODO, TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA,
								(ROUND((NVL(TEN6H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)))*TT.PORC6H
								+NVL(TEN12H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO))*TT.PORC12H
								+MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC1D
								+MULTIPLE_NVL(TEN2D.PRECIO_CALCULADO,TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC2D
								+MULTIPLE_NVL(TEN3D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC3D
								+NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC5D
								+TEN10D.PRECIO_CALCULADO*TT.PORC10D),5)) PRECIO_CALCULADO,
								TEN10D.CANTIDAD CANTIDAD, TEN10D.MINFETENDENCIA, TEN10D.MAXFETENDENCIA
						FROM TIEMPO_TENDENCIA TT, TENDENCIA_10D TEN10D
							LEFT JOIN TENDENCIA_6H TEN6H ON TEN10D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_12H TEN12H ON TEN10D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_1D TEN1D ON TEN10D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_2D TEN2D ON TEN10D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_3D TEN3D ON TEN10D.FECHA_TENDENCIA=TEN3D.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_5D TEN5D ON TEN10D.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA),
					REGRESION AS (SELECT ROUND(REGR_R2(POND.PRECIO_CALCULADO, POND.FECHA_TENDENCIA-TT.FECHA),5) R2,
							ROUND(REGR_SLOPE(POND.PRECIO_CALCULADO, POND.FECHA_TENDENCIA-TT.FECHA),5) PENDIENTE,
							MIN(POND.FECHA_TENDENCIA) MINFETENDENCIA, MAX(POND.FECHA_TENDENCIA) MAXFETENDENCIA
							FROM TIEMPO_TENDENCIA TT, PONDERADO POND
							WHERE WEEK_MINUTES(POND.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO_REGRESION
							--ORDER BY POND.FECHA_TENDENCIA ASC
							),							
					MAX_MIN_TENDENCIA AS (
						SELECT MAX(PERIODO) PERIODO, MAX(MAXPRECIO) MAXPRECIO, MIN(MINPRECIO) MINPRECIO, 
						MAX(MAXFETENDENCIA) MAXFETENDENCIA, MIN(MINFETENDENCIA) MINFETENDENCIA
						FROM (
							SELECT MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA, MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.PERIODO) PERIODO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO, MIN(TEN.PRECIO_CALCULADO) MINPRECIO FROM TENDENCIA_6H TEN
							UNION ALL SELECT MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA, MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.PERIODO) PERIODO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO, MIN(TEN.PRECIO_CALCULADO) MINPRECIO FROM TENDENCIA_12H TEN
							UNION ALL SELECT MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA, MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.PERIODO) PERIODO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO, MIN(TEN.PRECIO_CALCULADO) MINPRECIO FROM TENDENCIA_1D TEN
							UNION ALL SELECT MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA, MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.PERIODO) PERIODO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO, MIN(TEN.PRECIO_CALCULADO) MINPRECIO FROM TENDENCIA_2D TEN
							UNION ALL SELECT MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA, MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.PERIODO) PERIODO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO, MIN(TEN.PRECIO_CALCULADO) MINPRECIO FROM TENDENCIA_5D TEN
							UNION ALL SELECT MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA, MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.PERIODO) PERIODO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO, MIN(TEN.PRECIO_CALCULADO) MINPRECIO FROM TENDENCIA_10D TEN
							)
					),
					OPERAR_BUY AS (
						SELECT MAXMIN.PERIODO, TT.FECHA FECHA_TENDENCIA,
							MAXMIN.MINFETENDENCIA, MAXMIN.MAXFETENDENCIA, 
							MAXMIN.MINPRECIO PRECIO_CALCULADO,
							MAXMIN.MAXPRECIO+30/10000 TAKE_PROFIT, MAXMIN.MINPRECIO-70/10000 STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, 
							MAX_MIN_TENDENCIA MAXMIN, REGRESION REG
						WHERE REG.PENDIENTE>0
						--WHERE TODO: VALIDAR CUAL FECHA ES PRIMERO, LA MINIMA O LA MAXIMA.
					),
					OPERAR_SELL AS (
						SELECT MAXMIN.PERIODO, TT.FECHA FECHA_TENDENCIA,
							MAXMIN.MINFETENDENCIA, MAXMIN.MAXFETENDENCIA, 
							MAXMIN.MAXPRECIO PRECIO_CALCULADO,
							MAXMIN.MINPRECIO-30/10000 TAKE_PROFIT, MAXMIN.MAXPRECIO+70/10000 STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, 
							MAX_MIN_TENDENCIA MAXMIN, REGRESION REG
						--WHERE TODO: VALIDAR CUAL FECHA ES PRIMERO, LA MINIMA O LA MAXIMA.
						WHERE REG.PENDIENTE<0
					),
					OPERAR AS (SELECT OP.*, 0.1 LOTE FROM (
							SELECT MIN(OPE.PERIODO) PERIODO, OPE.FECHA_TENDENCIA, OPE.PRECIO_CALCULADO,
								OPE.TAKE_PROFIT, MIN(OPE.STOP_LOSS) STOP_LOSS, OPE.TIPO_OPERACION,
								MAX(OPE.MAXFETENDENCIA) MAXFETENDENCIA, MIN(OPE.MINFETENDENCIA) MINFETENDENCIA
							FROM OPERAR_BUY OPE WHERE OPE.TAKE_PROFIT>OPE.PRECIO_CALCULADO
								GROUP BY OPE.FECHA_TENDENCIA, OPE.TIPO_OPERACION, OPE.PRECIO_CALCULADO, OPE.TAKE_PROFIT
							UNION ALL 
							SELECT MIN(OPE.PERIODO) PERIODO, OPE.FECHA_TENDENCIA, OPE.PRECIO_CALCULADO,
								OPE.TAKE_PROFIT, MAX(OPE.STOP_LOSS) STOP_LOSS, OPE.TIPO_OPERACION,
								MAX(OPE.MAXFETENDENCIA) MAXFETENDENCIA, MIN(OPE.MINFETENDENCIA) MINFETENDENCIA
							FROM OPERAR_SELL OPE WHERE OPE.TAKE_PROFIT<OPE.PRECIO_CALCULADO 
							GROUP BY OPE.FECHA_TENDENCIA, OPE.TIPO_OPERACION, OPE.PRECIO_CALCULADO, OPE.TAKE_PROFIT
						) OP
						WHERE ABS(OP.PRECIO_CALCULADO-OP.TAKE_PROFIT)*10000>20
						AND ABS(OP.PRECIO_CALCULADO-OP.STOP_LOSS)*10000>20						
					), VALORES_TENDENCIA AS (
					SELECT 'NAME='||OPERAR.PERIODO
							||',TIPO_OPERACION='||OPERAR.TIPO_OPERACION
							||',LOTE='||OPERAR.LOTE
							||',FECHA_TENDENCIA='||(TO_CHAR(TT.FECHA, 'YYYY.MM.DD HH24:MI'))||',PRECIO_CALCULADO='
							||(OPERAR.PRECIO_CALCULADO)||',TAKE_PROFIT='||OPERAR.TAKE_PROFIT||',STOP_LOSS='||OPERAR.STOP_LOSS							
								||',VIGENCIALOWER='||(TO_CHAR(OPERAR.MINFETENDENCIA, 'YYYY.MM.DD HH24:MI'))||',VIGENCIAHIGHER='||(TO_CHAR(OPERAR.MAXFETENDENCIA, 'YYYY.MM.DD HH24:MI'))
								||',FECHA_BASE='||(TO_CHAR(TT.FECHA, 'YYYY.MM.DD HH24:MI'))
								||',WEEK_MINUTES='||WEEK_MINUTES(OPERAR.FECHA_TENDENCIA,TT.FECHA)
							VAL_TENDENCIA
					FROM TIEMPO_TENDENCIA TT, OPERAR OPERAR
					ORDER BY OPERAR.FECHA_TENDENCIA ASC)
SELECT * FROM VALORES_TENDENCIA
--SELECT * FROM OPERAR
--SELECT * FROM OPERAR_BUY
--SELECT * FROM OPERAR_SELL
;
BEGIN
	--DBMS_OUTPUT.PUT_LINE('CONSULTANDO...');
	--PARAM_DATE:=TO_DATE('2017/01/06 00:00','YYYY/MM/DD HH24:MI');
	PARAM_DATE:=TO_DATE('2017.01.01 00:00','YYYY/MM/DD HH24:MI');
	
	MAX_DATE:=TO_DATE('2017.02.10 23:58','YYYY/MM/DD HH24:MI');
	--MAX_DATE:=TO_DATE('2017/01/26 04:19','YYYY/MM/DD HH24:MI');
	WHILE ((PARAM_DATE <= MAX_DATE) AND (PARAM_DATE IS NOT NULL)) LOOP
			SELECT MIN(T.FECHA_BASE) INTO PARAM_DATE FROM
			(SELECT TEN.FECHA_BASE, COUNT(*) FROM TENDENCIA TEN WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170204-2')
				AND TEN.FECHA_BASE>PARAM_DATE+3/24
				GROUP BY TEN.FECHA_BASE
				HAVING COUNT(*)>100) T
			;
			FOR V_T1 IN C1((PARAM_DATE)) LOOP
				DBMS_OUTPUT.PUT_LINE(V_T1.VAL_TENDENCIA);
			END LOOP;
			DBMS_OUTPUT.PUT_LINE('PARAM_DATE 2: '||PARAM_DATE);
			--SELECT MIN(TEN.FECHA_BASE) INTO PARAM_DATE
			--FROM TENDENCIA TEN WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170204-2')
			--AND TEN.FECHA_BASE>PARAM_DATE;
	END LOOP;
END;
/
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
/