ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
/
DECLARE
	V_T1 VARCHAR2(1000);
	PARAM_DATE DATE;
	MAX_DATE DATE;
	CURSOR C1 (V_DATE DATE) IS
		WITH TIEMPO_TENDENCIA AS (
			SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
				(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, (24*10/24)*24*60 T10D,
				0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.2 PORC2D, 0.2 PORC5D, 0.3 PORC10D, 
				5/24 HORASPROYECCION, (24*5/24)*24*60 TIEMPO_REGRESION, (24*2/24)*24*60 TIEMPO_MAX_MIN, -- TODO: MAX MIN PARA TAKE_PROFIT Y STOP_LOSS
							V_DATE FECHA, 
							0.1 R2_MINIMO,
							'BUY_SELL_20170204-2' TIPO_TENDENCIA1, NULL TIPO_TENDENCIA2, NULL TIPO_TENDENCIA3 
							FROM DUAL),
						TENDENCIA_6H AS (SELECT TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND TEN.FECHA_TENDENCIA<=TT.FECHA+HORASPROYECCION
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_12H AS (SELECT 	TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND TEN.FECHA_TENDENCIA<=TT.FECHA+HORASPROYECCION
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_1D AS (SELECT TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND TEN.FECHA_TENDENCIA<=TT.FECHA+HORASPROYECCION
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_2D AS (SELECT 	TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
									AND TEN.FECHA_TENDENCIA<=TT.FECHA+HORASPROYECCION
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
						TENDENCIA_5D AS (SELECT 	TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
									ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
									ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD, 
									MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
								FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
									WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
									AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
									AND TEN.FECHA_BASE<=TT.FECHA
									AND TEN.FECHA_TENDENCIA>TT.FECHA
								GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
				TENDENCIA_10D AS (SELECT 	TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
						ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
						ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD,
						MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
						WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
						AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T10D
						AND TEN.FECHA_BASE<=TT.FECHA
						AND TEN.FECHA_TENDENCIA>TT.FECHA
					GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24')),
					PONDERADO AS (SELECT TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA,
								(ROUND((NVL(TEN6H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO))*TT.PORC6H
								+MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC12H
								+MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO,NULL)*TT.PORC1D
								+MULTIPLE_NVL(TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO,NULL)*TT.PORC2D
								+NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC5D
								+TEN10D.PRECIO_CALCULADO*TT.PORC10D),5)) PRECIO_CALCULADO,
								TEN10D.CANTIDAD CANTIDAD, TEN10D.MINFETENDENCIA, TEN10D.MAXFETENDENCIA
						FROM TIEMPO_TENDENCIA TT, TENDENCIA_10D TEN10D
							LEFT JOIN TENDENCIA_6H TEN6H ON TEN10D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_12H TEN12H ON TEN10D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_1D TEN1D ON TEN10D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_2D TEN2D ON TEN10D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
							LEFT JOIN TENDENCIA_5D TEN5D ON TEN10D.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA),					
					MAX_MIN_OPERAR AS (SELECT MAX(POND.PRECIO_CALCULADO) MAXIMO, MIN(POND.PRECIO_CALCULADO) MINIMO								
							FROM TIEMPO_TENDENCIA TT, PONDERADO POND 
							WHERE WEEK_MINUTES(POND.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO_MAX_MIN),
					REGRESION AS (SELECT ROUND(REGR_R2(POND.PRECIO_CALCULADO, POND.FECHA_TENDENCIA-TT.FECHA),5) R2_POND,
							ROUND(REGR_SLOPE(POND.PRECIO_CALCULADO, POND.FECHA_TENDENCIA-TT.FECHA),5) PENDIENTE_POND
							FROM TIEMPO_TENDENCIA TT, PONDERADO POND
							WHERE WEEK_MINUTES(POND.FECHA_TENDENCIA,TT.FECHA)<TT.TIEMPO_REGRESION
							ORDER BY POND.FECHA_TENDENCIA ASC
							),
					OPERAR_BUY_6H AS (
						SELECT '6H' PERIODO, TEN6H.FECHA_TENDENCIA FECHA_TENDENCIA, TEN6H.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TEN6H.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_6H TEN6H							
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_SELL_6H AS (
						SELECT '6H' PERIODO, TEN6H.FECHA_TENDENCIA FECHA_TENDENCIA, TEN6H.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TEN6H.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_6H TEN6H
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_BUY_12H AS (
						SELECT '12H' PERIODO, TEN12H.FECHA_TENDENCIA FECHA_TENDENCIA, TEN12H.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TEN12H.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_12H TEN12H
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_SELL_12H AS (
						SELECT '12H' PERIODO, TEN12H.FECHA_TENDENCIA FECHA_TENDENCIA, TEN12H.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TEN12H.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_12H TEN12H
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_BUY_1D AS (
						SELECT '1D' PERIODO, TEN1D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN1D.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TEN1D.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_1D TEN1D
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_SELL_1D AS (
						SELECT '1D' PERIODO, TEN1D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN1D.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TEN1D.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_1D TEN1D
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_BUY_2D AS (
						SELECT '2D' PERIODO, TEN2D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN2D.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TEN2D.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_2D TEN2D
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_SELL_2D AS (
						SELECT '2D' PERIODO, TEN2D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN2D.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TEN2D.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_2D TEN2D
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_BUY_5D AS (
						SELECT '5D' PERIODO, TEN5D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN5D.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TEN5D.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_5D TEN5D
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_SELL_5D AS (
						SELECT '5D' PERIODO, TEN5D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN5D.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TEN5D.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_5D TEN5D
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_BUY_10D AS (
						SELECT '10D' PERIODO, TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN10D.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TEN10D.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_10D TEN10D
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_SELL_10D AS (
						SELECT '10D' PERIODO, TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA, TEN10D.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TEN10D.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, TENDENCIA_10D TEN10D
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR_BUY_TOTAL AS (
						SELECT 'TOTAL' PERIODO, TENTOTAL.FECHA_TENDENCIA FECHA_TENDENCIA, TENTOTAL.PRECIO_CALCULADO, 
							MM.MAXIMO TAKE_PROFIT, LEAST(MM.MINIMO, TENTOTAL.PRECIO_CALCULADO-70/10000) STOP_LOSS,
							'BUY' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, PONDERADO TENTOTAL
						WHERE REG.PENDIENTE_POND>0 AND REG.R2_POND>TT.R2_MINIMO						
					),
					OPERAR_SELL_TOTAL AS (
						SELECT 'TOTAL' PERIODO, TENTOTAL.FECHA_TENDENCIA FECHA_TENDENCIA, TENTOTAL.PRECIO_CALCULADO, 
							MM.MINIMO TAKE_PROFIT, GREATEST(MM.MAXIMO, TENTOTAL.PRECIO_CALCULADO+70/10000) STOP_LOSS,
							'SELL' TIPO_OPERACION
						FROM TIEMPO_TENDENCIA TT, REGRESION REG, MAX_MIN_OPERAR MM, PONDERADO TENTOTAL
						WHERE REG.PENDIENTE_POND<0 AND REG.R2_POND>TT.R2_MINIMO
					),
					OPERAR AS (SELECT * FROM (
						SELECT * FROM OPERAR_BUY_6H UNION ALL SELECT * FROM OPERAR_SELL_6H
						UNION ALL SELECT * FROM OPERAR_BUY_12H UNION ALL SELECT * FROM OPERAR_SELL_12H
						UNION ALL SELECT * FROM OPERAR_BUY_1D UNION ALL SELECT * FROM OPERAR_SELL_1D
						UNION ALL SELECT * FROM OPERAR_BUY_2D UNION ALL SELECT * FROM OPERAR_SELL_2D
						UNION ALL SELECT * FROM OPERAR_BUY_5D UNION ALL SELECT * FROM OPERAR_SELL_5D
						UNION ALL SELECT * FROM OPERAR_BUY_10D UNION ALL SELECT * FROM OPERAR_SELL_10D
						UNION ALL SELECT * FROM OPERAR_BUY_TOTAL UNION ALL SELECT * FROM OPERAR_SELL_TOTAL) OP
						WHERE ABS(OP.PRECIO_CALCULADO-OP.TAKE_PROFIT)*10000>20
					)
				SELECT 'NAME='||OPERAR.PERIODO||',FECHA_TENDENCIA='||(TO_CHAR(OPERAR.FECHA_TENDENCIA, 'YYYY.MM.DD HH24:MI'))||',PRECIO_CALCULADO='
							||(OPERAR.PRECIO_CALCULADO)||',TAKE_PROFIT='||OPERAR.TAKE_PROFIT||',STOP_LOSS='||OPERAR.STOP_LOSS
							||',TIPO_OPERACION='||OPERAR.TIPO_OPERACION
								||',VIGENCIALOWER='||(TO_CHAR(OPERAR.FECHA_TENDENCIA, 'YYYY.MM.DD HH24:MI'))||',VIGENCIAHIGHER='||(TO_DATE(OPERAR.FECHA_TENDENCIA, 'YYYY.MM.DD HH24:MI')+2/24)
								||',FECHA_BASE='||(TO_CHAR(TT.FECHA, 'YYYY.MM.DD HH24:MI'))
								||',R2='||REG.R2_POND||',PENDIENTE='||REG.PENDIENTE_POND
							VAL_TENDENCIA
					FROM TIEMPO_TENDENCIA TT, REGRESION REG, OPERAR OPERAR
					ORDER BY OPERAR.FECHA_TENDENCIA ASC
					;
BEGIN
	--DBMS_OUTPUT.PUT_LINE('CONSULTANDO...');
	PARAM_DATE:=TO_DATE('2017/01/30 00:02','YYYY/MM/DD HH24:MI');
	--PARAM_DATE:=TO_DATE('2017/02/07 02:57','YYYY/MM/DD HH24:MI');
	MAX_DATE:=TO_DATE('2017/02/08 05:43','YYYY/MM/DD HH24:MI');
	--FOR i IN 1.. 9 LOOP
	WHILE ((PARAM_DATE <= MAX_DATE) AND (PARAM_DATE IS NOT NULL)) LOOP
			--DBMS_OUTPUT.PUT_LINE(PARAM_DATE);
			/*IF (TO_CHAR(PARAM_DATE, 'DY', 'nls_date_language=AMERICAN') IN ('SAT')) THEN			
				PARAM_DATE:=TRUNC(PARAM_DATE)+2+(1/24);
			ELSIF (TO_CHAR(PARAM_DATE, 'DY', 'nls_date_language=AMERICAN') IN ('SUN')) THEN
				PARAM_DATE:=TRUNC(PARAM_DATE)+1+(1/24);
			END IF;*/
			FOR V_T1 IN C1((PARAM_DATE)) LOOP
				DBMS_OUTPUT.PUT_LINE(V_T1.VAL_TENDENCIA);
			END LOOP;
			--PARAM_DATE:=PARAM_DATE+(2/24);
			SELECT MIN(TEN.FECHA_BASE) INTO PARAM_DATE
			FROM TENDENCIA TEN WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170204-2')
			AND TEN.FECHA_BASE>PARAM_DATE+3/24;
	END LOOP;
END;
/
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
/