-- TENDENCIAS DE OPERACIONES DE INDIVIDUOS
-- PERIODOS DE OPERACION SIMILAR DE INDIVIDUOS

SELECT --sum(oper1.pips)
  oper1.open_price, OPER1.id_individuo, oper1.take_profit, oper1.stop_loss, oper1.fecha_apertura, oper1.fecha_cierre,
  oper1.pips,
  OPER2.id_individuo, OPER2.take_profit, OPER2.stop_loss, OPER2.fecha_apertura, oper1.fecha_cierre,
  OPER2.pips
FROM OPERACION OPER1
  INNER JOIN OPERACION OPER2
    ON OPER1.ID_INDIVIDUO=OPER2.ID_INDIVIDUO
WHERE OPER2.FECHA_APERTURA<=TO_DATE('2014/10/02 05:14', 'YYYY/MM/DD HH24:MI')
  --AND OPER2.FECHA_CIERRE>TO_DATE('2014/10/02 05:14', 'YYYY/MM/DD HH24:MI')
  AND 
  oper2.open_price=1.10734
  and oper1.open_price=oper2.open_price
  and OPER1.FECHA_APERTURA<OPER2.FECHA_APERTURA

ORDER BY oper1.id_individuo, OPER1.FECHA_APERTURA ASC
;
 
SELECT OPER1.*, OPER2.* 
 FROM FOREX.OPERACION OPER1
  INNER JOIN OPERACION OPER2 ON OPER1.ID_INDIVIDUO = OPER2.ID_INDIVIDUO AND OPER1.PIPS = OPER2.PIPS 
    --AND TO_CHAR(OPER1.FECHA_APERTURA, 'YYYY') < TO_CHAR(OPER2.FECHA_APERTURA, 'YYYY')
    AND OPER1.FECHA_APERTURA < OPER2.FECHA_APERTURA
    AND OPER1.OPEN_PRICE = OPER2.OPEN_PRICE

WHERE OPER1.ID_INDIVIDUO IN (
'1340921104809.42257'
)
--AND OPER1.PIPS<0
--AND TO_CHAR(OPER1.FECHA_APERTURA, 'YYYY')>'2008'
--AND STOP_LOSS>=TAKE_PROFIT*2
ORDER BY --ID_INDIVIDUO DESC, 
  OPER2.FECHA_APERTURA asc
  --OPER.PIPS ASC
;

SELECT * FROM OPERACION OPER
WHERE OPER.FECHA_APERTURA < TO_DATE('2009/02/11 03:08', 'YYYY/MM/DD HH24:MI')
AND OPER.FECHA_CIERRE > TO_DATE('2009/02/11 03:08', 'YYYY/MM/DD HH24:MI')
AND OPER.ID_INDIVIDUO IN (
  SELECT DISTINCT OP.ID_INDIVIDUO FROM OPERACION OP
    WHERE OP.OPEN_PRICE = 1.24364
)
;

SELECT * FROM OPERACION OPER
WHERE OPER.OPEN_PRICE = 1.10734
ORDER BY OPER.FECHA_APERTURA DESC
;
