SET ORACLE_SID='FOREX'
CD /D D:\app\USER\product\11.2.0\eurjpy_home\BIN
IMP FOREX/forex@FOREX FILE=d:\ricardorq85\Informacion\FOREX\DATABASE\DMP\EXPDAT_TEMP_OPERACIONES.DMP tables=(TEMP_OPERACIONES_POSITIVAS, TEMP_OPERACIONES_NEGATIVAS) full=n rows=y
PAUSE