SELECT * FROM INDIVIDUO_BORRADO IB 
ORDER BY FECHA_BORRADO DESC;
SELECT * FROM INDIVIDUO_BORRADO IB
WHERE IB.ID='1459391969000.108';

SELECT * FROM INDICADOR_INDIVIDUO_BORRADO 
WHERE ID_INDIVIDUO='1476485020741.8';

SELECT COUNT(*) FROM INDIVIDUO_BORRADO IB;

SELECT TRUNC(FECHA_BORRADO), COUNT(*) FROM INDIVIDUO_BORRADO IB GROUP BY TRUNC(FECHA_BORRADO) ORDER BY TRUNC(FECHA_BORRADO) DESC;

SELECT TIPO_BORRADO, COUNT(*) FROM INDIVIDUO_BORRADO IB GROUP BY TIPO_BORRADO;

SELECT COUNT(*) FROM PROCESO P 
  INNER JOIN INDIVIDUO IND ON IND.ID=P.ID_INDIVIDUO
  INNER JOIN 
      (SELECT OP.ID_INDIVIDUO, count(*), ROUND(AVG(PIPS)) PIPS, 
      ROUND(AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60), 2) DUR FROM OPERACION OP
      GROUP BY OP.ID_INDIVIDUO
      HAVING AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60)<5) OPER
    ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
WHERE P.FECHA_HISTORICO>TO_DATE('20120101', 'YYYYMMDD');
