SELECT COUNT(*), 'PROCESADOS' FROM PROCESO_REPETIDOS WHERE TIPO_PROCESO='DUPLICADO_OPERACIONES'
UNION
SELECT COUNT(*), 'BORRADOS' FROM FOREX.INDIVIDUO_BORRADO WHERE TIPO_BORRADO='DUPLICADO_OPERACIONES'
;

SELECT * FROM FOREX.PROCESO_REPETIDOS WHERE TIPO_PROCESO='DUPLICADO_OPERACIONES' ORDER BY FECHA_PROCESO DESC;
SELECT * FROM FOREX.INDIVIDUO_BORRADO WHERE TIPO_BORRADO='DUPLICADO_OPERACIONES' ORDER BY FECHA_BORRADO DESC;


SELECT * FROM (SELECT IND.ID ID_INDIVIDUO FROM INDIVIDUO IND 
  WHERE IND.ID NOT IN (SELECT PR.ID_INDIVIDUO_PADRE FROM PROCESO_REPETIDOS PR)  
  ORDER BY IND.ID DESC) WHERE ROWNUM < 1000;
  
 SELECT ID_INDIVIDUO2 FROM INDIVIDUOS_REPETIDOS
  WHERE ID_INDIVIDUO1='1343961291508.414';  
  
SELECT COUNT(*) FROM PROCESO_REPETIDOS;
SELECT count(*) FROM PROCESO_REPETIDOS WHERE TIPO_PROCESO='DUPLICADO_OPERACIONES';
SELECT * FROM PROCESO_REPETIDOS ORDER BY FECHA_PROCESO DESC;
SELECT * FROM FOREX.INDIVIDUO_BORRADO ORDER BY FECHA_BORRADO DESC
--WHERE TIPO_BORRADO='DUPLICADO'
;

SELECT COUNT(*) FROM FOREX.INDIVIDUO_BORRADO;-- WHERE TIPO_BORRADO='DUPLICADO';
SELECT * FROM FOREX.INDIVIDUO_BORRADO WHERE TIPO_BORRADO='DUPLICADO_APERTURA';

SELECT ID_INDIVIDUO_BASE, COUNT(*) FROM FOREX.INDIVIDUO_BORRADO 
WHERE CAUSA_BORRADO='DUPLICADO' GROUP BY ID_INDIVIDUO_BASE ORDER BY COUNT(*) DESC;

SELECT * FROM INDIVIDUOS_REPETIDOS
WHERE ID_INDIVIDUO1='1341766313059.988';

  SELECT IND.* FROM INDIVIDUO IND 
  WHERE IND.ID IN (SELECT OPERB.ID_INDIVIDUO FROM OPERACION_BASE OPERB)
  AND IND.ID = '1341766313059.988'
  ORDER BY ID DESC;

