SELECT IB.FECHA_BORRADO, IB.* FROM INDIVIDUO_BORRADO IB 
ORDER BY IB.FECHA_BORRADO DESC;

SELECT * FROM INDIVIDUO_BORRADO IB
WHERE IB.TIPO_BORRADO='CANTIDAD_LIMITE';

--1482172714513.1008	1482172714513.810	1477883335391.1259
SELECT * FROM INDIVIDUO_BORRADO IB
WHERE IB.ID='1453687605734.271';

SELECT * FROM INDICADOR_INDIVIDUO_BORRADO 
WHERE ID_INDIVIDUO='1477365411387.7579'
AND TIPO='OPEN'
;

SELECT TIPO_BORRADO, COUNT(*) FROM INDIVIDUO_BORRADO IB
--WHERE PARENT_ID_2 IS NOT NULL
GROUP BY TIPO_BORRADO 
ORDER BY COUNT(*) DESC;

SELECT * FROM INDIVIDUO_INDICADORES_BORRADOS 
WHERE ID='1477365411387.7579'
;

SELECT * FROM (
SELECT II.* FROM FOREX.INDICADOR_INDIVIDUO_BORRADO II
WHERE II.ID_INDIVIDUO LIKE '1453687605734.271'
UNION ALL 
SELECT II.* FROM FOREX.INDICADOR_INDIVIDUO II
WHERE II.ID_INDIVIDUO IN ('1453687605734.636')
)
ORDER BY TIPO DESC, ID_INDICADOR, ID_INDIVIDUO
;

SELECT COUNT(*) FROM INDIVIDUO_BORRADO IB;

SELECT COUNT(*) FROM INDIVIDUO_INDICADORES_BORRADOS;

SELECT ID_INDIVIDUO2 ID_INDIVIDUO, ID_INDIVIDUO1 ID_INDIVIDUO_PADRE FROM INDIVIDUOS_REPETIDOS_BORRADOS --WHERE ROWNUM < 300
;

SELECT NVL2(PARENT_ID_1, 'CON PADRE 1', 'NULL'), NVL2(PARENT_ID_2, 'CON PADRE 2', 'NULL'), COUNT(*) 
FROM INDIVIDUO_BORRADO IB 
GROUP BY NVL2(PARENT_ID_1, 'CON PADRE 1', 'NULL'), NVL2(PARENT_ID_2, 'CON PADRE 2', 'NULL');

SELECT TIPO_BORRADO, TRUNC(CREATION_DATE), COUNT(*) FROM INDIVIDUO_BORRADO IB
GROUP BY TIPO_BORRADO, TRUNC(CREATION_DATE)
ORDER BY TRUNC(CREATION_DATE) DESC, TIPO_BORRADO ASC;

SELECT TRUNC(FECHA_BORRADO), COUNT(*) FROM INDIVIDUO_BORRADO IB GROUP BY TRUNC(FECHA_BORRADO) ORDER BY TRUNC(FECHA_BORRADO) DESC;

SELECT TIPO_BORRADO, COUNT(*) FROM INDIVIDUO_BORRADO IB GROUP BY TIPO_BORRADO;

SELECT COUNT(*) FROM PROCESO P 
  INNER JOIN INDIVIDUO IND ON IND.ID=P.ID_INDIVIDUO
  INNER JOIN 
      (SELECT OP.ID_INDIVIDUO, count(*), ROUND(AVG(PIPS)) PIPS, 
      ROUND(AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60), 2) DUR FROM OPERACION OP
      GROUP BY OP.ID_INDIVIDUO
      HAVING AVG((OP.FECHA_CIERRE-OP.FECHA_APERTURA)*24*60)<5) OPER
    ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
WHERE P.FECHA_HISTORICO>TO_DATE('20120101', 'YYYYMMDD');

SELECT * FROM INDIVIDUOS_REPETIDOS;