CREATE OR REPLACE VIEW INDICADORES_COLUMNAS AS 
	SELECT IND.*,    II_MA.INTERVALO_INFERIOR INFERIOR_MA, II_MA.INTERVALO_SUPERIOR SUPERIOR_MA,   
	II_MACD.INTERVALO_INFERIOR INFERIOR_MACD, II_MACD.INTERVALO_SUPERIOR SUPERIOR_MACD,   
	II_COMPARE.INTERVALO_INFERIOR INFERIOR_COMPARE, II_COMPARE.INTERVALO_SUPERIOR SUPERIOR_COMPARE,   
	II_ADX.INTERVALO_INFERIOR INFERIOR_ADX, II_ADX.INTERVALO_SUPERIOR SUPERIOR_ADX,   
	II_BOLLINGER.INTERVALO_INFERIOR INFERIOR_BOLLINGER, II_BOLLINGER.INTERVALO_SUPERIOR SUPERIOR_BOLLINGER,   
	II_ICHISIGNAL.INTERVALO_INFERIOR INFERIOR_ICHISIGNAL, II_ICHISIGNAL.INTERVALO_SUPERIOR SUPERIOR_ICHISIGNAL,   
	II_ICHITREND.INTERVALO_INFERIOR INFERIOR_ICHITREND, II_ICHITREND.INTERVALO_SUPERIOR SUPERIOR_ICHITREND,   
	II_MOMENTUM.INTERVALO_INFERIOR INFERIOR_MOMENTUM, II_MOMENTUM.INTERVALO_SUPERIOR SUPERIOR_MOMENTUM,   
	II_RSI.INTERVALO_INFERIOR INFERIOR_RSI, II_RSI.INTERVALO_SUPERIOR SUPERIOR_RSI,   
	II_SAR.INTERVALO_INFERIOR INFERIOR_SAR, II_SAR.INTERVALO_SUPERIOR SUPERIOR_SAR,
	II_MA1200.INTERVALO_INFERIOR INFERIOR_MA1200, II_MA1200.INTERVALO_SUPERIOR SUPERIOR_MA1200
FROM INDIVIDUO IND   
	INNER JOIN INDICADOR_INDIVIDUO II_MA ON IND.ID=II_MA.ID_INDIVIDUO AND II_MA.ID_INDICADOR='MA' AND II_MA.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_MACD ON IND.ID=II_MACD.ID_INDIVIDUO AND II_MACD.ID_INDICADOR='MACD' AND II_MACD.TIPO='OPEN'
	INNER JOIN INDICADOR_INDIVIDUO II_COMPARE ON IND.ID=II_COMPARE.ID_INDIVIDUO AND II_COMPARE.ID_INDICADOR='COMPARE_MA' AND II_COMPARE.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_ADX ON IND.ID=II_ADX.ID_INDIVIDUO AND II_ADX.ID_INDICADOR='ADX' AND II_ADX.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_BOLLINGER ON IND.ID=II_BOLLINGER.ID_INDIVIDUO AND II_BOLLINGER.ID_INDICADOR='BOLLINGER' AND II_BOLLINGER.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_ICHISIGNAL ON IND.ID=II_ICHISIGNAL.ID_INDIVIDUO AND II_ICHISIGNAL.ID_INDICADOR='ICHIMOKU_SIGNAL' AND II_ICHISIGNAL.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_ICHITREND ON IND.ID=II_ICHITREND.ID_INDIVIDUO AND II_ICHITREND.ID_INDICADOR='ICHIMOKU_TREND' AND II_ICHITREND.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_MOMENTUM ON IND.ID=II_MOMENTUM.ID_INDIVIDUO AND II_MOMENTUM.ID_INDICADOR='MOMENTUM' AND II_MOMENTUM.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_RSI ON IND.ID=II_RSI.ID_INDIVIDUO AND II_RSI.ID_INDICADOR='RSI' AND II_RSI.TIPO='OPEN'   
	INNER JOIN INDICADOR_INDIVIDUO II_SAR ON IND.ID=II_SAR.ID_INDIVIDUO AND II_SAR.ID_INDICADOR='SAR' AND II_SAR.TIPO='OPEN' 
	INNER JOIN INDICADOR_INDIVIDUO II_MA1200 ON IND.ID=II_MA1200.ID_INDIVIDUO AND II_MA1200.ID_INDICADOR='MA1200' AND II_MA1200.TIPO='OPEN'   
WHERE IND.ID = '1453593600000.11';