
SELECT *
FROM INDICADOR_INDIVIDUO_TENDENCIAS
WHERE TIPO='OPEN'
AND ID_INDIVIDUO IN ('1327818809271.13')
ORDER BY ID_INDICADOR, ID_INDIVIDUO DESC ;

--Cambiar query de consulta de individuos para el archivo de propiedades para traerlos ordenados por diferentes criterios, ej. PIPS X OPERACION
--SELECT * FROM (
SELECT IND.PARENT_ID_1, IND.PARENT_ID_2, OP.* FROM 
  INDIVIDUO IND INNER JOIN (
  SELECT OPER.ID_INDIVIDUO, COUNT(*),  MIN(OPER.FECHA_APERTURA) MINFECHA,  MAX(OPER.FECHA_CIERRE) MAXFECHA,
    SUM (OPER.PIPS) PIPS,  ROUND((SUM (OPER.PIPS))/(MAX(OPER.FECHA_CIERRE)-MIN(OPER.FECHA_APERTURA)),5) PIPS_DIA,
    ROUND((SUM (OPER.PIPS))/COUNT(*)) PIPS_OPER,  ROUND(AVG(OPER.STOP_LOSS)) AVG_SL
  FROM OPERACION OPER
  WHERE EXISTS
    (SELECT 1  FROM INDICADOR_INDIVIDUO_TENDENCIAS IIT
    WHERE OPER.ID_INDIVIDUO=IIT.ID_INDIVIDUO
    )
    AND ID_INDIVIDUO LIKE '1426268002764.%'
    --AND ID_INDIVIDUO IN ('1422746069706.38', '1426010455198.1')
  GROUP BY OPER.ID_INDIVIDUO) OP
  ON IND.ID=OP.ID_INDIVIDUO
ORDER BY OP.PIPS DESC 
--ORDER BY OP.PIPS_OPER DESC
;

SELECT ROUND(AVG(INTERVALO_INFERIOR)) PROM, 
  MIN(INTERVALO_INFERIOR) MINIMO, MAX(INTERVALO_INFERIOR) MAXIMO, STATS_MODE(INTERVALO_INFERIOR) MODA
FROM INDICADOR_INDIVIDUO_TENDENCIAS
WHERE TIPO='OPEN'
AND ID_INDICADOR='MIN_CANTIDAD_INDIVIDUOS';

SELECT *
FROM INDICADOR_INDIVIDUO_TENDENCIAS
WHERE TIPO='OPEN'
AND ID_INDICADOR='MIN_CANTIDAD_INDIVIDUOS';


SELECT * FROM (
  SELECT OPER.ID_INDIVIDUO, SUM (PIPS) PIPS,
  COUNT(*),  MIN(OPER.FECHA_APERTURA) MINFECHA,  MAX(OPER.FECHA_CIERRE) MAXFECHA,
    ROUND((SUM (OPER.PIPS))/(MAX(OPER.FECHA_CIERRE)-MIN(OPER.FECHA_APERTURA)),5) PIPS_DIA,
    ROUND((SUM (OPER.PIPS))/COUNT(*)) PIPS_OPER,  ROUND(AVG(OPER.STOP_LOSS)) AVG_SL
  FROM OPERACION OPER
  WHERE EXISTS
    (SELECT 1  FROM INDICADOR_INDIVIDUO_TENDENCIAS IIT
    WHERE OPER.ID_INDIVIDUO=IIT.ID_INDIVIDUO
    )
  GROUP BY OPER.ID_INDIVIDUO
  ORDER BY SUM(OPER.PIPS) DESC)
--WHERE ROWNUM<10
;


--CREATE TABLE INDICADOR_INDIVIDUO_TENDENCIAS AS SELECT * FROM INDICADOR_INDIVIDUO WHERE ROWNUM<2;
--TRUNCATE TABLE INDICADOR_INDIVIDUO_TENDENCIAS;
