SELECT * FROM INDIVIDUO ORDER BY ID DESC;
SELECT COUNT(*) FROM INDIVIDUO;
SELECT COUNT(*) FROM INDICADOR_INDIVIDUO;
SELECT COUNT(*) FROM INDIVIDUO_BORRADO;

SELECT * FROM FOREX.INDIVIDUO WHERE ID IN ('20130320213641.1');


SELECT II.*
FROM FOREX.INDICADOR_INDIVIDUO II
WHERE II.ID_INDIVIDUO IN (
'1341461435364.12659',
'1341461435364.13578',
'1341461435364.10685',
'1341461435364.14343',
'1341461435364.14457',
'1341461435364.12567',
'1341461435364.11697',
'1341461435364.12572'
)
ORDER BY TIPO DESC, ID_INDICADOR, INTERVALO_INFERIOR, INTERVALO_SUPERIOR
;


SELECT *  FROM FOREX.INDIVIDUO_BORRADO 
WHERE ID='1338955830567.5740'
;


SELECT COUNT(*) FROM FOREX.INDIVIDUO_BORRADO WHERE CAUSA_BORRADO='DUPLICADO_APERTURA';
SELECT * FROM FOREX.INDIVIDUO_BORRADO WHERE TIPO_BORRADO='ANTIGUO';

SELECT II.*--, II.INTERVALO_INFERIOR*100, II.INTERVALO_SUPERIOR*100 
FROM FOREX.INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO IN ('1342007251051.69929')
--AND TIPO='OPEN'
ORDER BY II.TIPO DESC, ID_INDICADOR ASC;

SELECT * FROM (
SELECT II.*--, II.INTERVALO_INFERIOR*100, II.INTERVALO_SUPERIOR*100 
FROM FOREX.INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO IN ('1342007251051.69929')
--AND TIPO='OPEN'
UNION
SELECT II.*--, II.INTERVALO_INFERIOR*100, II.INTERVALO_SUPERIOR*100 
FROM INDICADOR_INDIVIDUO_BORRADO II WHERE II.ID_INDIVIDUO IN ('1342007251051.68839')
--AND TIPO='OPEN'
) ORDER BY TIPO DESC, ID_INDICADOR ASC;
;

SELECT COUNT(*) FROM INDIVIDUO_BORRADO;
SELECT * FROM INDIVIDUO_BORRADO ORDER BY ID DESC;
SELECT * FROM INDICADOR_INDIVIDUO_BORRADO;

SELECT * FROM FOREX.INDIVIDUO WHERE CREATION_DATE IS NOT NULL ORDER BY ID DESC;

SELECT * FROM FOREX.INDICADOR;

SELECT * FROM FOREX.INDICADOR WHERE ID='ICHIMOKU_SIGNAL' AND TIPO='CLOSE';

SELECT * FROM FOREX.INDICADOR_INDIVIDUO
ORDER BY ID_INDIVIDUO,TIPO ASC;

SELECT * FROM FOREX.INDICADOR_INDIVIDUO
WHERE ID_INDICADOR='ICHIMOKU_SIGNAL' AND TIPO='CLOSE' AND ID_INDIVIDUO='1327755218940.22316'
;

SELECT COUNT(*) FROM INDICADOR_INDIVIDUO;

SELECT IND2.ID ID_INDIVIDUO, IND2.PARENT_ID_1, IND2.PARENT_ID_2, IND2.TAKE_PROFIT, IND2.STOP_LOSS, 
                 IND2.LOTE, IND2.INITIAL_BALANCE, IND2.CREATION_DATE, IND_MAXIMOS.FECHA_HISTORICO,
                 IND3.ID_INDICADOR, IND3.INTERVALO_INFERIOR, IND3.INTERVALO_SUPERIOR, IND3.TIPO,
                 OPER.FECHA_APERTURA, OPER.SPREAD, OPER.OPEN_PRICE
                  FROM INDIVIDUO IND2
                   INNER JOIN (
                     SELECT IND.ID ID_INDIVIDUO, MAX(PROC.FECHA_HISTORICO) FECHA_HISTORICO, MAX(OPER.FECHA_APERTURA) FECHA_APERTURA
                     FROM INDIVIDUO IND 
                       LEFT JOIN PROCESO PROC ON IND.ID=PROC.ID_INDIVIDUO
                       LEFT JOIN OPERACION OPER ON IND.ID=OPER.ID_INDIVIDUO AND OPER.FECHA_CIERRE IS NULL
                     WHERE 
                     IND.ID NOT IN (SELECT DISTINCT PRO.ID_INDIVIDUO FROM PROCESO PRO WHERE PRO.FECHA_HISTORICO=(SELECT MAX(FECHA) FROM DATOHISTORICO))    
                     GROUP BY IND.ID) IND_MAXIMOS ON IND2.ID=IND_MAXIMOS.ID_INDIVIDUO
                   INNER JOIN INDICADOR_INDIVIDUO IND3 ON IND2.ID=IND3.ID_INDIVIDUO
                   LEFT JOIN OPERACION OPER ON IND2.ID=OPER.ID_INDIVIDUO AND OPER.FECHA_APERTURA=IND_MAXIMOS.FECHA_APERTURA
                  WHERE IND2.ID=:1
                  ORDER BY IND2.ID DESC;
