DECLARE

BEGIN
  DELETE FROM FOREX.PROCESO P WHERE P.ID_INDIVIDUO IN 
    (SELECT PINT.ID_INDIVIDUO 
    FROM INTEGRATE.PROCESO PINT WHERE PINT.FECHA_PROCESO>=TO_DATE('2015/02/16 00:00', 'YYYY/MM/DD HH24:MI'))
  ;
  
  INSERT INTO FOREX.PROCESO(ID_INDIVIDUO, FECHA_HISTORICO, FECHA_PROCESO)
    SELECT PINT.ID_INDIVIDUO, PINT.FECHA_HISTORICO, PINT.FECHA_PROCESO 
    FROM INTEGRATE.PROCESO PINT WHERE PINT.FECHA_PROCESO>=TO_DATE('2015/02/16 00:00', 'YYYY/MM/DD HH24:MI')
  ;
  
INSERT INTO FOREX.OPERACION(
  ID_INDIVIDUO, TAKE_PROFIT, STOP_LOSS, FECHA_APERTURA, 
      FECHA_CIERRE, SPREAD, OPEN_PRICE, PIPS, LOTE, 
      TIPO, MAX_PIPS_RETROCESO, MAX_VALUE_RETROCESO, MAX_FECHA_RETROCESO,
      FECHA)
  SELECT OPINT.ID_INDIVIDUO, OPINT.TAKE_PROFIT, OPINT.STOP_LOSS, OPINT.FECHA_APERTURA, 
      OPINT.FECHA_CIERRE, OPINT.SPREAD, OPINT.OPEN_PRICE, OPINT.PIPS, OPINT.LOTE, 
      OPINT.TIPO, OPINT.MAX_PIPS_RETROCESO, OPINT.MAX_VALUE_RETROCESO, OPINT.MAX_FECHA_RETROCESO,
      OPINT.FECHA
    FROM INTEGRATE.OPERACION OPINT INNER JOIN (
      SELECT OINT.ID_INDIVIDUO, OINT.FECHA_APERTURA 
        FROM INTEGRATE.OPERACION OINT
      MINUS
      SELECT OFO.ID_INDIVIDUO, OFO.FECHA_APERTURA 
        FROM FOREX.OPERACION OFO) TMP
      ON TMP.ID_INDIVIDUO=OPINT.ID_INDIVIDUO AND TMP.FECHA_APERTURA=OPINT.FECHA_APERTURA
    WHERE OPINT.FECHA_CIERRE IS NOT NULL AND OPINT.FECHA IS NOT NULL
    AND OPINT.FECHA>=TO_DATE('2015/02/16 00:00', 'YYYY/MM/DD HH24:MI')
;

END;
