INSERT INTO MONEDA(ID_MONEDA, DIGITOS, STOP_LEVEL, MIN_VOLUME, MAX_VOLUME)
VALUES ('USDCAD', 5, 350, 0.01, 500.00);
INSERT INTO MONEDA(ID_MONEDA, DIGITOS, STOP_LEVEL, MIN_VOLUME, MAX_VOLUME)
VALUES ('EURJPY', 3, 380, 0.01, 500.00);
COMMIT;