
INSERT INTO INDIVIDUO(ID,PARENT_ID_1,PARENT_ID_2,TAKE_PROFIT,STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE, TIPO_OPERACION, TIPO_INDIVIDUO, MONEDA)
  SELECT (TRUNC(SYSDATE) - TO_DATE('1970/01/01', 'YYYY/MM/DD'))*24*60*60*1000||'.'||(ROWNUM) ID_IND, 
    IND.ID, NULL, IND.TAKE_PROFIT, IND.STOP_LOSS, IND.LOTE, IND.INITIAL_BALANCE, SYSDATE, IND.TIPO_OPERACION, IND.TIPO_INDIVIDUO, IND.MONEDA
  FROM INDIVIDUO IND WHERE IND.ID='1463541693654.351';

INSERT INTO INDICADOR_INDIVIDUO(ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO) 
SELECT 
   II.ID_INDICADOR, '1473465600000.1', 
   II.INTERVALO_INFERIOR,II.INTERVALO_SUPERIOR,II.TIPO
FROM INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO='1463541693654.351';

INSERT INTO INDIVIDUO(ID,PARENT_ID_1,PARENT_ID_2,TAKE_PROFIT,STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE)
  VALUES(to_char(systimestamp,'yyyymmddhh24miss')||'.1', '1461267489024.303', NULL, 54, 501, 0.1, 5000, SYSDATE);

INSERT INTO INDICADOR_INDIVIDUO(ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO) 
	SELECT ID_INDICADOR,
    TO_CHAR(SYSTIMESTAMP,'yyyymmddhh24miss')||'.1',
    --'20130320210030.1',
    INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO 
	FROM INDICADOR_INDIVIDUO WHERE ID_INDIVIDUO='1461267489024.303';
	
--COMMIT;

SELECT max(id) FROM INDIVIDUO;