-- SOLO APLICA PARA CUANDO SE BORRAN TODOS LOS REGISTROS DE LA TABLA Y SE DESEA LLENAR DE NUEVO
DECLARE
  minDate DATE;
  maxDate DATE;
  currentDate DATE;
BEGIN
  SELECT TRUNC(MIN(FECHA),'IW'), TRUNC(MAX(FECHA),'IW') INTO minDate, maxDate FROM DATOHISTORICO;
  currentDate := minDate;
  
  WHILE currentDate <= maxDate LOOP
    INSERT INTO OPERACION_X_SEMANA (ID_INDIVIDUO, TIPO_OPERACION, FECHA_HISTORICO, PIPS, CANTIDAD, FECHA_SEMANA)
        SELECT OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, MAX(P.FECHA_HISTORICO) FECHA_HISTORICO,
        SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD, TRUNC(MIN(FECHA_CIERRE),'IW')
        FROM OPERACION OPER
        INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO
        INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
        WHERE OPER.FECHA_CIERRE IS NOT NULL
        AND TRUNC(OPER.FECHA_CIERRE,'IW')=currentDate
        --AND OPER.FECHA_CIERRE>=(TRUNC(TO_DATE('20110101','YYYYMMDD'),'IW')+(i*step*7)) 
        AND IND.TIPO_INDIVIDUO = 'INDICADORES'
        --AND IND.ID='1332993893287.901'
        GROUP BY OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, TRUNC(FECHA_CIERRE,'IW');
      COMMIT;    
      currentDate := (currentDate+7);
  END LOOP;
END;
/      
