
SELECT (TRUNC(SYSDATE) - TO_DATE('1970/01/01', 'YYYY/MM/DD'))*24*60*60*1000||'.'||ROWNUM ID_IND, 
    IND.ID, NULL, 100, 2,IND.LOTE, IND.INITIAL_BALANCE, SYSDATE, 
    CANTIDAD, ROWNUM
FROM INDIVIDUO IND INNER JOIN (
    SELECT OPER.ID_INDIVIDUO, MIN(OPER.MAX_PIPS_RETROCESO) RETRO, COUNT(*) CANTIDAD, SUM(OPER.PIPS) TOTAL_PIPS
      FROM OPERACION OPER INNER JOIN INDIVIDUO IND ON OPER.ID_INDIVIDUO=IND.ID
    --WHERE OPER.PIPS>20000
    GROUP BY OPER.ID_INDIVIDUO
    HAVING SUM(OPER.PIPS)>20000 AND COUNT(*)>10
    ORDER BY SUM(OPER.PIPS) DESC--, OPER.ID_INDIVIDUO DESC
  ) MAX_RETRO_OPER ON MAX_RETRO_OPER.ID_INDIVIDUO=IND.ID
  ORDER BY TOTAL_PIPS --MAX_RETRO_OPER.CANTIDAD DESC, MAX_RETRO_OPER.ID_INDIVIDUO DESC
;

SELECT 
   II.ID_INDICADOR, IND.ID, 
   II.INTERVALO_INFERIOR,II.INTERVALO_SUPERIOR,II.TIPO
FROM INDICADOR_INDIVIDUO II 
  INNER JOIN INDIVIDUO IND ON IND.PARENT_ID_1=II.ID_INDIVIDUO AND IND.CREATION_DATE>TRUNC(SYSDATE)
WHERE NOT EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II2 WHERE II2.ID_INDIVIDUO=IND.ID)  
;


INSERT INTO INDIVIDUO(ID,PARENT_ID_1,PARENT_ID_2,TAKE_PROFIT,STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE)
  SELECT (TRUNC(SYSDATE) - TO_DATE('1970/01/01', 'YYYY/MM/DD'))*24*60*60*1000||'.'||(ROWNUM+10) ID_IND, 
    IND.ID, NULL, MAX_RETRO_OPER.RETRO, IND.STOP_LOSS, IND.LOTE, IND.INITIAL_BALANCE, SYSDATE 
  FROM INDIVIDUO IND INNER JOIN (
    SELECT OPER.ID_INDIVIDUO, ROUND(AVG(OPER.MAX_PIPS_RETROCESO)) RETRO, COUNT(*) CANTIDAD
      FROM OPERACION OPER INNER JOIN INDIVIDUO IND ON OPER.ID_INDIVIDUO=IND.ID
    WHERE OPER.PIPS<0
    GROUP BY OPER.ID_INDIVIDUO
    HAVING AVG(OPER.MAX_PIPS_RETROCESO)>0 AND COUNT(*)>1
    ORDER BY COUNT(*) DESC, OPER.ID_INDIVIDUO DESC) MAX_RETRO_OPER ON MAX_RETRO_OPER.ID_INDIVIDUO=IND.ID
    WHERE IND.CREATION_DATE>TRUNC(SYSDATE)-1
  ORDER BY MAX_RETRO_OPER.CANTIDAD DESC, MAX_RETRO_OPER.ID_INDIVIDUO DESC;

INSERT INTO INDICADOR_INDIVIDUO(ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO) 
SELECT 
   II.ID_INDICADOR, IND.ID, 
   II.INTERVALO_INFERIOR,II.INTERVALO_SUPERIOR,II.TIPO
FROM INDICADOR_INDIVIDUO II 
  INNER JOIN INDIVIDUO IND ON IND.PARENT_ID_1=II.ID_INDIVIDUO AND IND.CREATION_DATE>TRUNC(SYSDATE)
WHERE NOT EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II2 WHERE II2.ID_INDIVIDUO=IND.ID)
;

	
COMMIT;

