INSERT INTO INDIVIDUO(ID, PARENT_ID_1, PARENT_ID_2, TAKE_PROFIT, STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE, TIPO_OPERACION, TIPO_INDIVIDUO, MONEDA)
  SELECT ID, PARENT_ID_1, PARENT_ID_2, TAKE_PROFIT, STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE, TIPO_OPERACION, TIPO_INDIVIDUO, MONEDA
    FROM INDIVIDUO_TEMPORAL WHERE TIPO_OPERACION='SELL' AND CREATION_DATE>TO_DATE('20140101','YYYYMMDD');
COMMIT;

INSERT INTO INDICADOR_INDIVIDUO(ID_INDICADOR, ID_INDIVIDUO, INTERVALO_INFERIOR, INTERVALO_SUPERIOR, TIPO)
  SELECT ID_INDICADOR, ID_INDIVIDUO, INTERVALO_INFERIOR, INTERVALO_SUPERIOR, TIPO
  FROM INDIVIDUO IND INNER JOIN INDICADOR_INDIVIDUO_TEMPORAL ON ID=ID_INDIVIDUO;
COMMIT;

INSERT INTO INDIVIDUO_INDICADORES (ID, PARENT_ID_1, PARENT_ID_2, TAKE_PROFIT, STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE, TIPO_OPERACION,TIPO_INDIVIDUO,MONEDA,INFERIOR_MA,SUPERIOR_MA,INFERIOR_MACD,SUPERIOR_MACD,INFERIOR_COMPARE,SUPERIOR_COMPARE,INFERIOR_ADX,SUPERIOR_ADX,INFERIOR_BOLLINGER,SUPERIOR_BOLLINGER,INFERIOR_ICHISIGNAL,SUPERIOR_ICHISIGNAL,INFERIOR_ICHITREND,SUPERIOR_ICHITREND,INFERIOR_MOMENTUM,SUPERIOR_MOMENTUM,INFERIOR_RSI,SUPERIOR_RSI,INFERIOR_SAR,SUPERIOR_SAR,INFERIOR_MA1200,SUPERIOR_MA1200,INFERIOR_MACD20X,SUPERIOR_MACD20X,INFERIOR_COMPARE1200,SUPERIOR_COMPARE1200,INFERIOR_ADX168,SUPERIOR_ADX168,INFERIOR_BOLLINGER240,SUPERIOR_BOLLINGER240,INFERIOR_ICHISIGNAL6,SUPERIOR_ICHISIGNAL6,INFERIOR_ICHITREND6,SUPERIOR_ICHITREND6,INFERIOR_MOMENTUM1200,SUPERIOR_MOMENTUM1200,INFERIOR_RSI84,SUPERIOR_RSI84,INFERIOR_SAR1200,SUPERIOR_SAR1200)
SELECT TEMP.ID, TEMP.PARENT_ID_1, TEMP.PARENT_ID_2, TEMP.TAKE_PROFIT, TEMP.STOP_LOSS, TEMP.LOTE, TEMP.INITIAL_BALANCE, TEMP.CREATION_DATE, TEMP.TIPO_OPERACION, TEMP.TIPO_INDIVIDUO, TEMP.MONEDA, TEMP.INFERIOR_MA, TEMP.SUPERIOR_MA, TEMP.INFERIOR_MACD, TEMP.SUPERIOR_MACD, TEMP.INFERIOR_COMPARE, TEMP.SUPERIOR_COMPARE, TEMP.INFERIOR_ADX, TEMP.SUPERIOR_ADX, TEMP.INFERIOR_BOLLINGER, TEMP.SUPERIOR_BOLLINGER, TEMP.INFERIOR_ICHISIGNAL, TEMP.SUPERIOR_ICHISIGNAL, TEMP.INFERIOR_ICHITREND, TEMP.SUPERIOR_ICHITREND, TEMP.INFERIOR_MOMENTUM,SUPERIOR_MOMENTUM,INFERIOR_RSI,SUPERIOR_RSI,INFERIOR_SAR,SUPERIOR_SAR,INFERIOR_MA1200,SUPERIOR_MA1200,INFERIOR_MACD20X,SUPERIOR_MACD20X,INFERIOR_COMPARE1200,SUPERIOR_COMPARE1200,INFERIOR_ADX168,SUPERIOR_ADX168,INFERIOR_BOLLINGER240,SUPERIOR_BOLLINGER240,INFERIOR_ICHISIGNAL6,SUPERIOR_ICHISIGNAL6,INFERIOR_ICHITREND6,SUPERIOR_ICHITREND6,INFERIOR_MOMENTUM1200,SUPERIOR_MOMENTUM1200,INFERIOR_RSI84,SUPERIOR_RSI84,INFERIOR_SAR1200,SUPERIOR_SAR1200
FROM INDIVIDUO_INDICADORES_TEMPORAL TEMP 
INNER JOIN INDIVIDUO IND ON IND.ID=TEMP.ID;
COMMIT;
