DECLARE

BEGIN

  FOR i IN 1..12 LOOP
    DELETE FROM INTEGRATE.TENDENCIA TEN_INT 
    WHERE EXISTS (SELECT 1 FROM FOREX.TENDENCIA TEN_FOR 
      WHERE TEN_INT.FECHA_BASE=TEN_FOR.FECHA_BASE 
      AND TEN_INT.ID_INDIVIDUO=TEN_FOR.ID_INDIVIDUO AND TEN_INT.TIPO_CALCULO=TEN_FOR.TIPO_CALCULO);
    COMMIT;
    INSERT INTO FOREX.TENDENCIA(
      FECHA_BASE,	PRECIO_BASE, ID_INDIVIDUO, FECHA_TENDENCIA, PIPS, PRECIO_CALCULADO, TIPO_TENDENCIA,
      FECHA_APERTURA, OPEN_PRICE, DURACION, PIPS_ACTUALES, DURACION_ACTUAL, PROBABILIDAD_POSITIVOS,
      PROBABILIDAD_NEGATIVOS, PROBABILIDAD, FECHA, FECHA_CIERRE, TIPO_CALCULO, PIPS_REALES)
    
    SELECT T.FECHA_BASE, T.PRECIO_BASE, T.ID_INDIVIDUO, T.FECHA_TENDENCIA, T.PIPS, T.PRECIO_CALCULADO, T.TIPO_TENDENCIA, 
        T.FECHA_APERTURA, T.OPEN_PRICE, T.DURACION, T.PIPS_ACTUALES, T.DURACION_ACTUAL, T.PROBABILIDAD_POSITIVOS, 
        T.PROBABILIDAD_NEGATIVOS, T.PROBABILIDAD, T.FECHA, T.FECHA_CIERRE, T.TIPO_CALCULO, T.PIPS_REALES
      FROM INTEGRATE.TENDENCIA T /*INNER JOIN (
        SELECT FECHA_BASE, ID_INDIVIDUO, TIPO_CALCULO
        FROM INTEGRATE.TENDENCIA TEN_INT
        MINUS
        SELECT FECHA_BASE, ID_INDIVIDUO, TIPO_CALCULO
        FROM FOREX.TENDENCIA TEN_FOR
        WHERE TEN_FOR.FECHA>=(SELECT MIN(TINT.FECHA) FROM INTEGRATE.TENDENCIA TINT)
        ) T2 
          ON T.FECHA_BASE=T2.FECHA_BASE AND T.ID_INDIVIDUO=T2.ID_INDIVIDUO AND T.TIPO_CALCULO=T2.TIPO_CALCULO*/
        WHERE --T.ID_INDIVIDUO='1322673642223.779003'
          --AND T.FECHA_BASE=TO_DATE('2012/01/16 15:00', 'YYYY/MM/DD HH24:MI')
        --AND 
        ROWNUM<10000;
        COMMIT;
    END LOOP;
END;