
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'SAR1200',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'ADX168',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'RSI84',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'BOLLINGER240',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'MOMENTUM1200',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'ICHIMOKU_SIGNAL6',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'ICHIMOKU_TREND6',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
COMMIT;

INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'SAR1200',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'ADX168',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'RSI84',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'BOLLINGER240',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'MOMENTUM1200',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'ICHIMOKU_SIGNAL6',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
INSERT INTO INDICADOR_INDIVIDUO II (ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO)
  SELECT 'ICHIMOKU_TREND6',IND.ID,NULL,NULL,'CLOSE' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993'
;
COMMIT;


--SELECT 'MA1200',IND.ID,NULL,NULL,'OPEN' FROM INDIVIDUO IND WHERE IND.ID<>'1329938135413.993';

SELECT COUNT(*) FROM INDICADOR_INDIVIDUO II
WHERE II.ID_INDICADOR='SAR1200' AND TIPO='OPEN';
