SELECT * FROM INTEGRATE.TENDENCIA;
SELECT * FROM INTEGRATE.PROCESO;
SELECT * FROM INTEGRATE.OPERACION;

DROP TABLE INTEGRATE.TENDENCIA;
DROP TABLE INTEGRATE.PROCESO;
DROP TABLE INTEGRATE.OPERACION;


SELECT * FROM INTEGRATE.PROCESO ORDER BY FECHA_PROCESO DESC;
SELECT COUNT(*) FROM INTEGRATE.OPERACION OPINT WHERE OPINT.FECHA>=TO_DATE('2015/02/07 00:00', 'YYYY/MM/DD HH24:MI');

SELECT COUNT(*) FROM INTEGRATE.TENDENCIA;

SELECT COUNT(*) FROM INTEGRATE.TENDENCIA
--WHERE ID_INDIVIDUO='1323026187141.2272386'
--AND FECHA_BASE=TO_DATE('2012/01/02 05:34', 'YYYY/MM/DD HH24:MI')
;

SELECT MIN(TINT.FECHA) FROM INTEGRATE.TENDENCIA TINT;

SELECT COUNT(*) FROM INTEGRATE.TENDENCIA TEN_INT 
    WHERE EXISTS (SELECT 1 FROM FOREX.TENDENCIA TEN_FOR 
      WHERE TEN_INT.FECHA_BASE=TEN_FOR.FECHA_BASE 
      AND TEN_INT.ID_INDIVIDUO=TEN_FOR.ID_INDIVIDUO AND TEN_INT.TIPO_CALCULO=TEN_FOR.TIPO_CALCULO);

