DECLARE
BEGIN

  FOR COUNTER IN 1..2000 LOOP
    DELETE FROM OPERACION OP WHERE TAKE_PROFIT=0 AND ROWNUM<30000;
    COMMIT;
  END LOOP;
  
END;
/

SELECT COUNT(*) FROM OPERACION OP WHERE TAKE_PROFIT=0;
