DECLARE
BEGIN

  FOR COUNTER IN 1..1000 LOOP
    --DELETE FROM TENDENCIA T WHERE T.FECHA_BASE<TO_DATE('20100101 00', 'YYYYMMDD HH24') AND ROWNUM<30000;
    --COMMIT;
    DELETE FROM TENDENCIA T WHERE T.TIPO_TENDENCIA<>'ESTADISTICAS_MAXMIN_23' AND ROWNUM<30000;
    COMMIT;
    --dbms_output.put_line(COUNTER);
  END LOOP;
  
END;
/

--SELECT COUNT(*) FROM TENDENCIA T WHERE T.FECHA_BASE<TO_DATE('20100101 00', 'YYYYMMDD HH24');
SELECT COUNT(*) FROM TENDENCIA T WHERE T.TIPO_TENDENCIA<>'ESTADISTICAS_MAXMIN_23';
