SELECT ADD_MONTHS(TO_DATE(MAXIMOS.FECHA,'YYYY/MM'),1), ADD_MONTHS(TO_DATE(MAXIMOS.FECHA,'YYYY/MM'),2), MAXIMOS.MAX_PIPS, MIN(IND.ID) FROM INDIVIDUO IND
  INNER JOIN (SELECT ID_INDIVIDUO, SUM(PIPS) PIPS_IND
    FROM OPERACION WHERE FECHA_APERTURA > TO_DATE('2012/05','YYYY/MM') 
    GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY/MM')) OPER1 ON IND.ID=OPER1.ID_INDIVIDUO
  INNER JOIN (
    SELECT FECHA, MAX(PIPS) MAX_PIPS FROM
      (SELECT OPER.ID_INDIVIDUO, TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') FECHA, 
        SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD, ROUND(AVG(PIPS),5) PROMEDIO
      FROM OPERACION OPER
      WHERE OPER.FECHA_APERTURA > TO_DATE('2012/05','YYYY/MM')
      GROUP BY OPER.ID_INDIVIDUO, TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') HAVING SUM(OPER.PIPS)>0)
    GROUP BY FECHA) MAXIMOS ON MAXIMOS.MAX_PIPS=OPER1.PIPS_IND
GROUP BY MAXIMOS.FECHA, MAXIMOS.MAX_PIPS
ORDER BY MAXIMOS.FECHA ASC;

SELECT FECHA, MAX(PIPS) MAX_PIPS FROM
      (SELECT OPER.ID_INDIVIDUO, TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') FECHA, 
        SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD, ROUND(AVG(PIPS),5) PROMEDIO
      FROM OPERACION OPER
      WHERE OPER.FECHA_APERTURA > TO_DATE('2012/05','YYYY/MM')
      GROUP BY OPER.ID_INDIVIDUO, TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') HAVING SUM(OPER.PIPS)>0)
    GROUP BY FECHA
ORDER BY FECHA ASC;

SELECT OPER.ID_INDIVIDUO, TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') FECHA, SUM(OPER.PIPS), COUNT(*) CANTIDAD,ROUND(AVG(PIPS),5) PROMEDIO
FROM OPERACION OPER
WHERE OPER.FECHA_APERTURA > TO_DATE('2012/08','YYYY/MM')
GROUP BY OPER.ID_INDIVIDUO, TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') HAVING SUM(OPER.PIPS)>0
ORDER BY TO_CHAR(OPER.FECHA_APERTURA,'YYYY/MM') ASC, SUM(OPER.PIPS) DESC, OPER.ID_INDIVIDUO DESC;

SELECT (OPER2.OPEN_PRICE - OPER1.OPEN_PRICE) DIFERENCIA_OPEN, COUNT(*) CONTAR, OPER2.OPEN_PRICE
--, OPER1.*, OPER2.* --, COUNT(*) CO 
FROM OPERACION OPER1, OPERACION OPER2
WHERE OPER2.FECHA_APERTURA <> OPER1.FECHA_APERTURA AND OPER2.FECHA_APERTURA > OPER1.FECHA_APERTURA 
AND (OPER2.FECHA_APERTURA - OPER1.FECHA_APERTURA) < 30 
--AND ROWNUM < 20000
GROUP BY (OPER2.OPEN_PRICE - OPER1.OPEN_PRICE), OPER2.OPEN_PRICE
ORDER BY COUNT(*) DESC
;

SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE) 
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS';

SELECT DISTINCT OPEN_PRICE, FECHA_APERTURA
FROM OPERACION WHERE OPEN_PRICE IN ('1,2409','1,0674') ORDER BY OPEN_PRICE DESC;

SELECT * FROM OPERACION WHERE FECHA_APERTURA=(SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE) 
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS');

SELECT OPER.*, ROUND(((SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE) 
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS')-OPER.FECHA_APERTURA),5) DURACION,
    ROUND((OPER.FECHA_CIERRE-OPER.FECHA_APERTURA),5) DURACION_FINAL FROM OPERACION OPER
WHERE FECHA_APERTURA BETWEEN (SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE) 
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS')-30
  AND (SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE) 
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS') 
  AND FECHA_CIERRE>(SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE) 
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS')
ORDER BY FECHA_APERTURA ASC;

SELECT V_OPERACIONES.ID, V_OPERACIONES.OPEN_FECHA, V_OPERACIONES.CLOSE_FECHA
FROM V_OPERACIONES WHERE V_OPERACIONES.OPEN_FECHA = TO_DATE('2009/11/25 13:58','YYYY/MM/DD HH24:MI')
--AND V_OPERACIONES.ID=REG_INDIVIDUO.ID
AND NOT EXISTS (
  SELECT 1 FROM OPERACION_BASE OP WHERE OP.ID_INDIVIDUO=V_OPERACIONES.ID 
  AND OP.FECHA_APERTURA=V_OPERACIONES.OPEN_FECHA AND OP.FECHA_CIERRE=V_OPERACIONES.CLOSE_FECHA
  )
AND NOT EXISTS (
  SELECT 1 FROM OPERACION_BASE OP2 WHERE OP2.ID_INDIVIDUO=V_OPERACIONES.ID 
  AND V_OPERACIONES.OPEN_FECHA > OP2.FECHA_APERTURA AND V_OPERACIONES.OPEN_FECHA <= OP2.FECHA_CIERRE
  );

SELECT * FROM PARAMETRO;
--UPDATE FOREX.PARAMETRO SET VALOR='2008/09/27 15:32',FPARAMETRO=SYSDATE WHERE NOMBRE='FECHA_ESTADISTICAS';
UPDATE FOREX.PARAMETRO SET VALOR=null,FPARAMETRO=SYSDATE WHERE NOMBRE='FECHA_ESTADISTICAS';
COMMIT;