SET ECHO ON;
SET feedback ON;
SPOOL ON;
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR_SELL...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARA_OPERAR_SELL"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR_BUY...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARA_OPERAR_BUY"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'TRUNCATING TMP_TOFILESTRING2...' FROM DUAL;
/
TRUNCATE TABLE TMP_TOFILESTRING2;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'INSERTING INTO TMP_TOFILESTRING2...' FROM DUAL;
/
INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2, FECHA_ORDER1, FECHA_ORDER2)
SELECT FILTERED.ID_INDIVIDUO, 		
		NVL(ROUND((MIN(NVL(FILTERED.PIPS_SEMANA,0))+MIN(FILTERED.PIPS_MES)+MIN(FILTERED.PIPS_ANYO)+MIN(FILTERED.PIPS_TOTALES))/4),0),		
		NVL(MIN(FILTERED.PIPS_SEMANA),0),
		FILTERED.FECHA_SEMANA, FILTERED.FECHA_SEMANA+7, 
		MAX(FILTERED.FECHA), MAX(FILTERED.FECHA_FINAL)
  FROM FILTERED_PARA_OPERAR_SELL FILTERED
  --FROM FILTERED_PARA_OPERAR FILTERED
  --WHERE FILTERED.FECHA_SEMANA BETWEEN TO_DATE('20160104', 'YYYYMMDD') AND TO_DATE('20160201', 'YYYYMMDD')
GROUP BY FILTERED.ID_INDIVIDUO, FILTERED.FECHA_SEMANA;
commit;
INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2, FECHA_ORDER1, FECHA_ORDER2)
SELECT FILTERED.ID_INDIVIDUO,
		NVL(ROUND((MIN(NVL(FILTERED.PIPS_SEMANA,0))+MIN(FILTERED.PIPS_MES)+MIN(FILTERED.PIPS_ANYO)+MIN(FILTERED.PIPS_TOTALES))/4),0),		
		NVL(MIN(FILTERED.PIPS_SEMANA),0),
		FILTERED.FECHA_SEMANA, FILTERED.FECHA_SEMANA+7, 
		MAX(FILTERED.FECHA), MAX(FILTERED.FECHA_FINAL)
  FROM FILTERED_PARA_OPERAR_BUY FILTERED
  --FROM FILTERED_PARA_OPERAR FILTERED
  --WHERE FILTERED.FECHA_SEMANA BETWEEN TO_DATE('20160104', 'YYYYMMDD') AND TO_DATE('20160201', 'YYYYMMDD')
GROUP BY FILTERED.ID_INDIVIDUO, FILTERED.FECHA_SEMANA;
commit;
/
@"d:\ricardorq85\JavaProjects\Git\genetic-forex\ForexGenetic\sql\ToFileStringFromTEMP_TOFILESTRING.sql";
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHING FILTERED_PARA_OPERAR...' FROM DUAL;
/
BEGIN DBMS_SNAPSHOT.REFRESH( '"FOREX"."FILTERED_PARA_OPERAR"','F'); end;
/
SELECT TO_CHAR(SYSDATE,'YYYYMMDD HH24:MI'), 'REFRESHED FILTERED_PARA_OPERAR...' FROM DUAL;
/
