SET feedback ON;
SET ECHO ON;
SPOOL ON;

TRUNCATE TABLE TMP_TOFILESTRING2;

--SELECT COUNT(*) FROM TMP_TOFILESTRING2;

INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2)
  SELECT OPER_SEMANA.ID_INDIVIDUO, MIN(OPER_SEMANA.PIPS), MIN(OPER.PIPS),
  SEMANAS.FECHA_SEMANA, SEMANAS.FECHA_SEMANA+7
  FROM SEMANAS
    LEFT JOIN OPERACION_X_SEMANA OPER_SEMANA 
		ON OPER_SEMANA.FECHA_SEMANA=(SEMANAS.FECHA_SEMANA-7)
    INNER JOIN OPERACIONES_ACUM_SEMANA_MES OPER_MES
      ON OPER_MES.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO     
        AND OPER_MES.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
    INNER JOIN OPERACIONES_ACUM_SEMANA_ANYO OPER_ANYO 
      ON OPER_ANYO.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO     
        AND OPER_ANYO.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
    INNER JOIN OPERACIONES_ACUM_SEMANA_CONSOL OPER
      ON OPER_SEMANA.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
      AND OPER.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO PERI
		ON ( NVL(OPER_SEMANA.PIPS,0)>PERI.FILTRO_PIPS_X_SEMANA AND OPER_MES.PIPS>PERI.FILTRO_PIPS_X_MES 
			AND OPER_ANYO.PIPS>PERI.FILTRO_PIPS_X_ANYO AND OPER.PIPS>PERI.FILTRO_PIPS_TOTALES) 
			AND OPER_SEMANA.TIPO_OPERACION=PERI.TIPO_OPERACION
      AND OPER_SEMANA.FECHA_SEMANA BETWEEN PERI.FECHA_FINAL AND ADD_MONTHS(PERI.FECHA_FINAL,1)
  WHERE 
  --( PERI.ID IN (615214,615326,611410,609954,611298,609842,615310,615198,615482)
  --)
	(PERI.PIPS_TOTALES>5000 AND PERI.ID BETWEEN 1251690 AND 1296093
	  AND PERI.PIPS_TOTALES_PARALELAS>0 AND PERI.PIPS_TOTALES>0 
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>0 AND PERI.PIPS_AGRUPADO_HORAS>0 AND PERI.PIPS_AGRUPADO_DIAS>0)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10)
  --AND SEMANAS.FECHA_SEMANA BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20120101','YYYYMMDD')
  --AND SEMANAS.FECHA_SEMANA > TO_DATE('20131102','YYYYMMDD')
  --AND SEMANAS.FECHA_SEMANA < TO_DATE('20131103','YYYYMMDD')
  --AND OPER_SEMANA.ID_INDIVIDUO ='1453664590875.284'
  --AND NOT EXISTS (SELECT 1 FROM OPERACION OP 
	--WHERE OP.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO 
	--AND OP.FECHA_APERTURA<OPER_SEMANA.FECHA_SEMANA AND (OP.FECHA_CIERRE IS NULL OR OP.FECHA_CIERRE>OPER_SEMANA.FECHA_SEMANA))
  GROUP BY OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA;
commit;

@"d:ricardorq85\JavaProjects\Git\genetic-forex\ForexGenetic\sql\ToFileStringFromTEMP_TOFILESTRING.sql";
