DELETE FROM OPERACION_X_SEMANA OPER
WHERE OPER.ID_INDIVIDUO IN (
	SELECT P.ID_INDIVIDUO FROM PROCESO P
	WHERE P.ID_INDIVIDUO=OPER.ID_INDIVIDUO AND P.FECHA_HISTORICO>OPER.FECHA_HISTORICO
);

INSERT INTO OPERACION_X_SEMANA (ID_INDIVIDUO, TIPO_OPERACION, FECHA_HISTORICO, PIPS, CANTIDAD, FECHA_SEMANA)
  SELECT OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, MAX(P.FECHA_HISTORICO) FECHA_HISTORICO,
  SUM(OPER.PIPS) PIPS, COUNT(*) CANTIDAD, TRUNC(MIN(FECHA_CIERRE),'IW')
  FROM OPERACION OPER
    INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO
    INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
  WHERE OPER.FECHA_CIERRE IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM OPERACION_X_SEMANA OPC WHERE OPC.ID_INDIVIDUO=OPER.ID_INDIVIDUO)  
  AND IND.TIPO_INDIVIDUO = 'INDICADORES'
  GROUP BY OPER.ID_INDIVIDUO, IND.TIPO_OPERACION, TRUNC(FECHA_CIERRE,'IW');
COMMIT;

INSERT INTO SEMANAS(FECHA_SEMANA)
  SELECT DISTINCT SEM.FECHA_SEMANA+7
  FROM OPERACION_X_SEMANA SEM WHERE SEM.FECHA_SEMANA+7 NOT IN(SELECT FECHA_SEMANA FROM SEMANAS);
COMMIT;

DELETE FROM OPERACIONES_ACUM_SEMANA_MES OPER
WHERE OPER.ID_INDIVIDUO IN (
	SELECT P.ID_INDIVIDUO FROM PROCESO P
	WHERE P.ID_INDIVIDUO=OPER.ID_INDIVIDUO AND P.FECHA_HISTORICO>OPER.FECHA_HISTORICO
);

INSERT INTO OPERACIONES_ACUM_SEMANA_MES (ID_INDIVIDUO, FECHA_SEMANA, PIPS, CANTIDAD, FECHA_HISTORICO)
	SELECT TMP.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, SUM(TMP.PIPS) PIPS, SUM(TMP.CANTIDAD) CANTIDAD,
	MAX(P.FECHA_HISTORICO) FECHA_HISTORICO
	FROM SEMANAS
	  INNER JOIN OPERACION_X_SEMANA TMP
		ON TMP.FECHA_SEMANA>=ADD_MONTHS(SEMANAS.FECHA_SEMANA,-1)
		  AND TMP.FECHA_SEMANA<=SEMANAS.FECHA_SEMANA
	INNER JOIN PROCESO P ON P.ID_INDIVIDUO=TMP.ID_INDIVIDUO
	WHERE --TMP.ID_INDIVIDUO='1453664590875.284' AND
	NOT EXISTS (SELECT 1 FROM OPERACIONES_ACUM_SEMANA_MES OPC WHERE OPC.ID_INDIVIDUO=TMP.ID_INDIVIDUO)
	AND SEMANAS.FECHA_SEMANA>=TO_DATE('20110101','YYYYMMDD')
	GROUP BY TMP.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA
	HAVING SUM(TMP.PIPS)>=-1000;
COMMIT;

DELETE FROM OPERACIONES_ACUM_SEMANA_ANYO OPER
WHERE OPER.ID_INDIVIDUO IN (
	SELECT P.ID_INDIVIDUO FROM PROCESO P
	WHERE P.ID_INDIVIDUO=OPER.ID_INDIVIDUO AND P.FECHA_HISTORICO>OPER.FECHA_HISTORICO
);
	
INSERT INTO OPERACIONES_ACUM_SEMANA_ANYO (ID_INDIVIDUO, FECHA_SEMANA, PIPS, CANTIDAD, FECHA_HISTORICO) 
	SELECT TMP.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, SUM(TMP.PIPS) PIPS, SUM(TMP.CANTIDAD) CANTIDAD, 
	MAX(P.FECHA_HISTORICO) FECHA_HISTORICO 
	FROM OPERACION_X_SEMANA TMP 
		INNER JOIN PROCESO P ON P.ID_INDIVIDUO=TMP.ID_INDIVIDUO   
	  INNER JOIN SEMANAS 
		ON TMP.FECHA_SEMANA>=ADD_MONTHS(SEMANAS.FECHA_SEMANA,-12) 
		  AND TMP.FECHA_SEMANA<=SEMANAS.FECHA_SEMANA 
	WHERE 
	NOT EXISTS (SELECT 1 FROM OPERACIONES_ACUM_SEMANA_ANYO OPC WHERE OPC.ID_INDIVIDUO=TMP.ID_INDIVIDUO) 
	AND SEMANAS.FECHA_SEMANA>=TO_DATE('20110101','YYYYMMDD') 
	GROUP BY TMP.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA 
	HAVING SUM(TMP.PIPS)>=-2000;
	
DELETE FROM OPERACIONES_ACUM_SEMANA_CONSOL OPER
WHERE OPER.ID_INDIVIDUO IN (
	SELECT P.ID_INDIVIDUO FROM PROCESO P
	WHERE P.ID_INDIVIDUO=OPER.ID_INDIVIDUO AND P.FECHA_HISTORICO>OPER.FECHA_HISTORICO
);
	
INSERT INTO OPERACIONES_ACUM_SEMANA_CONSOL (ID_INDIVIDUO, FECHA_SEMANA, PIPS, CANTIDAD, FECHA_HISTORICO) 
	SELECT TMP.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, SUM(TMP.PIPS) PIPS, SUM(TMP.CANTIDAD) CANTIDAD, 
	MAX(P.FECHA_HISTORICO) FECHA_HISTORICO 
	FROM OPERACION_X_SEMANA TMP 
		INNER JOIN PROCESO P ON P.ID_INDIVIDUO=TMP.ID_INDIVIDUO   
	  INNER JOIN SEMANAS 
		ON TMP.FECHA_SEMANA<=SEMANAS.FECHA_SEMANA 
	WHERE 
	NOT EXISTS (SELECT 1 FROM OPERACIONES_ACUM_SEMANA_CONSOL OPC WHERE OPC.ID_INDIVIDUO=TMP.ID_INDIVIDUO) 
	AND SEMANAS.FECHA_SEMANA>=TO_DATE('20110101','YYYYMMDD') 
	GROUP BY TMP.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA 
	HAVING SUM(TMP.PIPS)>=-3000;
COMMIT;

INSERT INTO PREVIO_TOFILESTRING(ID_INDIVIDUO, FECHA_SEMANA, PIPS_SEMANA, PIPS_MES, PIPS_ANYO, PIPS_TOTALES, TIPO_OPERACION)
  SELECT OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, 
    OPER_SEMANA.PIPS PIPS_SEMANA, OPER_MES.PIPS PIPS_MES, OPER_ANYO.PIPS PIPS_ANYO, OPER.PIPS PIPS_TOTALES, OPER_SEMANA.TIPO_OPERACION
  FROM SEMANAS 
    LEFT JOIN OPERACION_X_SEMANA OPER_SEMANA 
    ON SEMANAS.FECHA_SEMANA=OPER_SEMANA.FECHA_SEMANA+7
            INNER JOIN OPERACIONES_ACUM_SEMANA_MES OPER_MES 
            ON OPER_MES.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO 
            AND OPER_MES.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7   
      INNER JOIN OPERACIONES_ACUM_SEMANA_ANYO OPER_ANYO  
      ON OPER_ANYO.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO 
      AND OPER_ANYO.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7 
        INNER JOIN OPERACIONES_ACUM_SEMANA_CONSOL OPER 
        ON OPER.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO
        AND OPER.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7;  
COMMIT;  
