SET feedback ON; 
SET ECHO ON;
SPOOL ON;

TRUNCATE TABLE TMP_TOFILESTRING2;

INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2, FECHA_ORDER1, FECHA_ORDER2)
  SELECT PTFS.ID_INDIVIDUO, 
  MIN(PTFS.PIPS_SEMANA),
	ROUND((MIN(PTFS.PIPS_SEMANA)+MIN(PTFS.PIPS_MES)+MIN(PTFS.PIPS_ANYO)+MIN(PTFS.PIPS_TOTALES))/4),
  PTFS.FECHA_SEMANA, PTFS.FECHA_SEMANA+7, 
  MAX(EOP.FECHA), MAX(EOP.FECHA_FINAL) 
  FROM PREVIO_TOFILESTRING PTFS
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO EOP
		ON (NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND NVL(PTFS.PIPS_MES,0)>EOP.FILTRO_PIPS_X_MES 
			AND NVL(PTFS.PIPS_ANYO,0)>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND NVL(PTFS.R2_MES,0)>EOP.FILTRO_R2_MES 
			AND NVL(PTFS.R2_ANYO,0)>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND NVL(PTFS.PENDIENTE_MES,0)>EOP.FILTRO_PENDIENTE_MES 
			AND NVL(PTFS.PENDIENTE_ANYO,0)>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+28) 
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+28)
  WHERE 
	((EOP.TIPO_OPERACION='BUY' AND EOP.PIPS_TOTALES>1000 
	  AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
	  AND EOP.PIPS_TOTALES_PARALELAS>3000
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>1000 AND EOP.PIPS_AGRUPADO_HORAS>1000 AND EOP.PIPS_AGRUPADO_DIAS>1000)
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)<10	  
	  AND (EOP.CANTIDAD_PARALELAS/EOP.CANTIDAD)>1
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND EOP.CANTIDAD/((EOP.FECHA_FINAL-EOP.FECHA_INICIAL)/30)>1
	  AND (EOP.PIPS_TOTALES/EOP.CANTIDAD)>200
	  --AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200
	 ) OR
	(EOP.TIPO_OPERACION='SELL' AND EOP.PIPS_TOTALES>0  
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	 ) OR
	(EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
	  AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
	  AND EOP.CANTIDAD_INDIVIDUOS>1
	  AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200	
	 )
	)
	  AND PTFS.FECHA_SEMANA>TO_DATE('20160831','YYYYMMDD')
  GROUP BY PTFS.ID_INDIVIDUO, PTFS.FECHA_SEMANA;
commit;

@"d:\ricardorq85\JavaProjects\Git\genetic-forex\ForexGenetic\sql\ToFileStringFromTEMP_TOFILESTRING.sql";
