DROP MATERIALIZED VIEW FILTERED_EOP;

  CREATE MATERIALIZED VIEW "FOREX"."FILTERED_EOP" ("CANTIDAD", "FILTRO_PIPS_X_MES", "FILTRO_PIPS_X_ANYO", "FILTRO_PIPS_TOTALES", "FIRST_ORDER", "SECOND_ORDER", "FECHA", "PIPS_TOTALES", "FECHA_INICIAL", "FECHA_FINAL", "ID", "CANTIDAD_PARALELAS", "PIPS_TOTALES_PARALELAS", "PIPS_AGRUPADO_MINUTOS", "PIPS_AGRUPADO_HORAS", "PIPS_AGRUPADO_DIAS", "FILTRO_PIPS_X_SEMANA", "TIPO_OPERACION", "FILTRO_PENDIENTE_SEMANA", "FILTRO_PENDIENTE_MES", "FILTRO_PENDIENTE_ANYO", "FILTRO_PENDIENTE_TOTALES", "FILTRO_R2_SEMANA", "FILTRO_R2_MES", "FILTRO_R2_ANYO", "FILTRO_R2_TOTALES", "CANTIDAD_INDIVIDUOS", "MAX_FECHA_CIERRE", "EOP_VERSION")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  REFRESH FORCE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT PERI.* FROM ESTRATEGIA_OPERACION_PERIODO PERI
WHERE
	((PERI.TIPO_OPERACION='BUY' AND PERI.PIPS_TOTALES>1000
	  AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
	  AND PERI.PIPS_TOTALES_PARALELAS>3000
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>1000 AND PERI.PIPS_AGRUPADO_HORAS>1000 AND PERI.PIPS_AGRUPADO_DIAS>1000)
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)<10
	  AND (PERI.CANTIDAD_PARALELAS/PERI.CANTIDAD)>1
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND PERI.CANTIDAD/((PERI.FECHA_FINAL-PERI.FECHA_INICIAL)/30)>1
	  AND (PERI.PIPS_TOTALES/PERI.CANTIDAD)>200
	  --AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	 ) OR
	(PERI.TIPO_OPERACION='SELL' AND PERI.PIPS_TOTALES>1000
		AND PERI.PIPS_TOTALES_PARALELAS>PERI.PIPS_TOTALES
		AND PERI.PIPS_TOTALES_PARALELAS>3000
	 ) OR
	(PERI.PIPS_TOTALES<=1000
	  AND PERI.PIPS_TOTALES_PARALELAS>0
	  AND (PERI.PIPS_AGRUPADO_MINUTOS>0 AND PERI.PIPS_AGRUPADO_HORAS>0 AND PERI.PIPS_AGRUPADO_DIAS>0)
	  AND PERI.CANTIDAD_INDIVIDUOS>1
	  AND (PERI.PIPS_TOTALES_PARALELAS/PERI.CANTIDAD_PARALELAS)>200
	 )
	)
	  AND PERI.FECHA_FINAL>TO_DATE('20131231','YYYYMMDD');

   COMMENT ON MATERIALIZED VIEW "FOREX"."FILTERED_EOP"  IS 'snapshot table for snapshot FOREX.FILTERED_EOP';

DROP MATERIALIZED VIEW FILTERED_PTFS;

  CREATE MATERIALIZED VIEW "FOREX"."FILTERED_PTFS" ("ID_INDIVIDUO", "FECHA_SEMANA", "PIPS_SEMANA", "PIPS_MES", "PIPS_ANYO", "PIPS_TOTALES", "TIPO_OPERACION", "FECHA_HISTORICO", "R_COUNT_SEMANA", "R2_SEMANA", "PENDIENTE_SEMANA", "INTERCEPCION_SEMANA", "R_COUNT_MES", "R2_MES", "PENDIENTE_MES", "INTERCEPCION_MES", "R_COUNT_ANYO", "R2_ANYO", "PENDIENTE_ANYO", "INTERCEPCION_ANYO", "R_COUNT_CONSOL", "R2_CONSOL", "PENDIENTE_CONSOL", "INTERCEPCION_CONSOL")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  REFRESH FORCE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT PTFS.*
  FROM PREVIO_TOFILESTRING PTFS
		WHERE PTFS.FECHA_SEMANA>TO_DATE('20131231','YYYYMMDD')
	AND NVL(PIPS_SEMANA,0)>=-5000	AND PIPS_MES>=-5000 AND PIPS_ANYO>=-5000 AND PIPS_TOTALES>=-5000
	--AND NVL(R2_SEMANA,0)>0
	AND NVL(PENDIENTE_SEMANA,0)>=-5000	AND PENDIENTE_MES>=-5000 AND PENDIENTE_ANYO>=-5000 AND PENDIENTE_CONSOL>=-5000;

   COMMENT ON MATERIALIZED VIEW "FOREX"."FILTERED_PTFS"  IS 'snapshot table for snapshot FOREX.FILTERED_PTFS';

   
  CREATE INDEX "FOREX"."FILTERED_PTFS_IDX1" ON "FOREX"."FILTERED_PTFS" ("ID_INDIVIDUO", "FECHA_SEMANA", "TIPO_OPERACION", NVL("PIPS_SEMANA",0), "PIPS_MES", "PIPS_ANYO", "PIPS_TOTALES", NVL("R2_SEMANA",0), "R2_MES", "R2_ANYO", "R2_CONSOL", NVL("PENDIENTE_SEMANA",0), "PENDIENTE_MES", "PENDIENTE_ANYO", "PENDIENTE_CONSOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" ;

