SELECT COUNT(*) FROM DATOHISTORICO DH;
-- = 2402749

SELECT * --(DH.FECHA)-1/24/60
--COUNT(*), ROUND(COUNT(*)/2402749*100, 2) PORC
FROM DATOHISTORICO DH
  INNER JOIN INDICADORES_COLUMNAS IC ON
     (IC.INFERIOR_MA IS NULL OR IC.SUPERIOR_MA IS NULL OR
     ROUND(DH.AVERAGE-DH.LOW, 5) BETWEEN IC.INFERIOR_MA AND IC.SUPERIOR_MA OR ROUND(DH.AVERAGE-DH.HIGH,5) BETWEEN IC.INFERIOR_MA AND IC.SUPERIOR_MA)
    AND (IC.INFERIOR_MACD IS NULL OR IC.SUPERIOR_MACD IS NULL OR ROUND(DH.MACD_VALUE-DH.MACD_SIGNAL, 5) BETWEEN IC.INFERIOR_MACD AND IC.SUPERIOR_MACD)
    AND (IC.INFERIOR_COMPARE IS NULL OR IC.SUPERIOR_COMPARE IS NULL OR ROUND(DH.AVERAGE_COMPARE-DH.COMPARE_VALUE, 5) BETWEEN IC.INFERIOR_COMPARE AND IC.SUPERIOR_COMPARE)
    AND (IC.INFERIOR_ADX IS NULL OR IC.SUPERIOR_ADX IS NULL OR ROUND(DH.ADX_VALUE*(DH.ADX_PLUS-DH.ADX_MINUS), 5) BETWEEN IC.INFERIOR_ADX AND IC.SUPERIOR_ADX)
    AND (IC.INFERIOR_SAR IS NULL OR IC.SUPERIOR_SAR IS NULL OR ROUND(DH.SAR-DH.LOW, 5) BETWEEN IC.INFERIOR_SAR AND IC.SUPERIOR_SAR OR DH.SAR-DH.HIGH BETWEEN IC.INFERIOR_SAR AND IC.SUPERIOR_SAR)
    AND (IC.INFERIOR_RSI IS NULL OR IC.SUPERIOR_RSI IS NULL OR ROUND(DH.RSI, 5) BETWEEN IC.INFERIOR_RSI AND IC.SUPERIOR_RSI)
    AND (IC.INFERIOR_BOLLINGER IS NULL OR IC.SUPERIOR_BOLLINGER IS NULL OR ROUND(DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER, 5) BETWEEN IC.INFERIOR_BOLLINGER AND IC.SUPERIOR_BOLLINGER)
    AND (IC.INFERIOR_MOMENTUM IS NULL OR IC.SUPERIOR_MOMENTUM IS NULL OR ROUND(DH.MOMENTUM, 5) BETWEEN IC.INFERIOR_MOMENTUM AND IC.SUPERIOR_MOMENTUM)
    AND (IC.INFERIOR_ICHISIGNAL IS NULL OR IC.SUPERIOR_ICHISIGNAL IS NULL OR ROUND(DH.ICHIMOKUCHINKOUSPAN*(DH.ICHIMOKUTENKANSEN-DH.ICHIMOKUKIJUNSEN),5) BETWEEN IC.INFERIOR_ICHISIGNAL AND IC.SUPERIOR_ICHISIGNAL)
    AND (IC.INFERIOR_ICHITREND IS NULL OR IC.SUPERIOR_ICHITREND IS NULL OR ROUND(DH.ICHIMOKUSENKOUSPANA-DH.ICHIMOKUSENKOUSPANB-DH.LOW, 5) BETWEEN IC.INFERIOR_ICHITREND AND IC.SUPERIOR_ICHITREND
          OR ROUND(DH.ICHIMOKUSENKOUSPANA-DH.ICHIMOKUSENKOUSPANB-DH.HIGH, 5) BETWEEN IC.INFERIOR_ICHITREND AND IC.SUPERIOR_ICHITREND)
    --AND (IC.INFERIOR_MA1200 IS NULL OR IC.SUPERIOR_MA1200 IS NULL OR
     --ROUND(DH.AVERAGE-DH.LOW, 5) BETWEEN IC.INFERIOR_MA1200 AND IC.SUPERIOR_MA1200 OR ROUND(DH.AVERAGE-DH.HIGH,5) BETWEEN IC.INFERIOR_MA1200 AND IC.SUPERIOR_MA1200)
WHERE DH.FECHA>TO_DATE('2007/04/19 20:10', 'YYYY/MM/DD HH24:MI')
ORDER BY FECHA ASC
;
     
SELECT COUNT(*), ROUND(COUNT(*)/2402749*100, 2) PORC
FROM DATOHISTORICO DH
WHERE (DH.ICHIMOKUSENKOUSPANA-DH.ICHIMOKUSENKOUSPANB-DH.LOW BETWEEN -1.13269	AND -1.00729
  OR DH.ICHIMOKUSENKOUSPANA-DH.ICHIMOKUSENKOUSPANB-DH.HIGH BETWEEN -1.13269	AND -1.00729
  )
--ORDER BY FECHA ASC
;

SELECT --(DH.MACD_VALUE-DH.MACD_SIGNAL)
  COUNT(*), COUNT(*)/2402749*100 PORC
FROM DATOHISTORICO DH
WHERE (DH.MACD_VALUE-DH.MACD_SIGNAL) BETWEEN 0.00013 AND 0.00059
-- MACD MINIMO -0.0017 AND	MAXIMO 0.00288
--ORDER BY FECHA ASC
;

SELECT COUNT(*)/2402749*100 PORCENTAJE
FROM DATOHISTORICO DH
WHERE (DH.ADX_VALUE*(DH.ADX_PLUS-DH.ADX_MINUS)) BETWEEN -4886.8979996364 AND 46.41113;

SELECT DH.MACD_VALUE-DH.MACD_SIGNAL, COUNT(*) REG
FROM DATOHISTORICO DH
GROUP BY DH.MACD_VALUE-DH.MACD_SIGNAL 
ORDER BY COUNT(*) DESC
;

SELECT MIN(DH.MACD_VALUE-DH.MACD_SIGNAL) MIN_DIFF, MAX(DH.MACD_VALUE-DH.MACD_SIGNAL) MAX_DIFF
FROM DATOHISTORICO DH
;
  
SELECT COUNT(*) FROM INDICADOR_INDIVIDUO II
WHERE II.ID_INDICADOR='MACD' AND II.TIPO='OPEN'
AND II.INTERVALO_INFERIOR <= -0.007
AND II.INTERVALO_SUPERIOR >= 0.00288
--AND (II.INTERVALO_SUPERIOR-II.INTERVALO_INFERIOR)>0.00001
;

SELECT * --COUNT(*) 
FROM OPERACION OPER
WHERE OPER.PIPS > 200
  AND MAX_PIPS_RETROCESO > -400
  AND OPER.FECHA_APERTURA>TO_DATE('20140101', 'YYYYMMDD')
ORDER BY OPER.FECHA_APERTURA ASC
;

SELECT ROUND(AVG(II.INTERVALO_INFERIOR), 5) AVG_INF, ROUND(AVG(II.INTERVALO_SUPERIOR), 5) AVG_SUP,
  MIN(II.INTERVALO_INFERIOR) MIN_INF, MIN(II.INTERVALO_SUPERIOR) MIN_SUP,
  MAX(II.INTERVALO_INFERIOR) MAX_INF, MAX(II.INTERVALO_SUPERIOR) MAX_SUP,
  ROUND(AVG(II.INTERVALO_INFERIOR-II.INTERVALO_SUPERIOR), 5) AVG_DIFF,
  ROUND(MIN(II.INTERVALO_INFERIOR-II.INTERVALO_SUPERIOR), 5) MIN_DIFF,
  ROUND(MAX(II.INTERVALO_INFERIOR-II.INTERVALO_SUPERIOR), 5) MAX_DIFF
--COUNT(*) 
FROM INDIVIDUO IND 
  INNER JOIN INDICADOR_INDIVIDUO II ON IND.ID=II.ID_INDIVIDUO AND II.ID_INDICADOR='MA'
  INNER JOIN OPERACION OPER ON IND.ID=OPER.ID_INDIVIDUO
WHERE OPER.PIPS > 200
  AND MAX_PIPS_RETROCESO > -400
  AND OPER.FECHA_APERTURA BETWEEN TO_DATE('20140101', 'YYYYMMDD') AND TO_DATE('20150101', 'YYYYMMDD')
--ORDER BY OPER.FECHA_APERTURA ASC
  --AND ROWNUM<10
;

SELECT OPER.* --SUM(OPER.PIPS)
--COUNT(*) 
FROM INDIVIDUO IND 
  INNER JOIN INDICADOR_INDIVIDUO II ON IND.ID=II.ID_INDIVIDUO AND II.ID_INDICADOR='MA'
  INNER JOIN OPERACION OPER ON IND.ID=OPER.ID_INDIVIDUO
WHERE --OPER.PIPS > 200
  --AND MAX_PIPS_RETROCESO > -400
  OPER.FECHA_APERTURA BETWEEN TO_DATE('20140101', 'YYYYMMDD') AND TO_DATE('20150101', 'YYYYMMDD')
  AND II.INTERVALO_INFERIOR BETWEEN (-0.00886-0.00100) AND (-0.00886+0.00100)
  AND II.INTERVALO_SUPERIOR BETWEEN (-0.00027-0.00100) AND (-0.00027+0.00100)
--ORDER BY OPER.FECHA_APERTURA ASC
  --AND ROWNUM<10
;

SELECT ROUND(AVG(P.PIPS),5) PIPS, 
  ROUND(AVG(DIF_COMPARE),5) COMP, MIN(DIF_COMPARE) MIN_COMP, MAX(DIF_COMPARE) MAX_COMP,
  ROUND(AVG(DIF_BOLLINGER),5) BOL, MIN(DIF_BOLLINGER) MIN_BOL, MAX(DIF_BOLLINGER) MAX_BOL,
  ROUND(AVG(DIF_MA),5) MA, ROUND(AVG(DIF_SAR),5) SAR FROM (
  SELECT OPER.PIPS, DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER DIF_BOLLINGER, 
    DH.AVERAGE-OPER.OPEN_PRICE DIF_MA, DH.SAR-OPER.OPEN_PRICE DIF_SAR,
    DH.AVERAGE_COMPARE-DH.COMPARE_VALUE DIF_COMPARE
  FROM OPERACION OPER
    INNER JOIN DATOHISTORICO DH ON OPER.FECHA_APERTURA=DH.FECHA
  --WHERE OPER.ID_INDIVIDUO='1322622379655.43'
  WHERE OPER.PIPS>200
  AND OPER.FECHA_APERTURA>TO_DATE('20140101', 'YYYYMMDD')
  --ORDER BY OPER.FECHA_APERTURA ASC
) P
;


SELECT ROUND(AVG(P.PIPS),5) PIPS, 
  ROUND(AVG(DIF_COMPARE),5) COMP, 
  ROUND(AVG(DIF_BOLLINGER),5) BOL, 
  ROUND(AVG(DIF_MA),5) MA, ROUND(AVG(DIF_SAR),5) SAR 
FROM (
  SELECT OPER.PIPS, DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER DIF_BOLLINGER, 
    DH.AVERAGE-OPER.OPEN_PRICE DIF_MA, DH.SAR-OPER.OPEN_PRICE DIF_SAR,
    DH.AVERAGE_COMPARE-DH.COMPARE_VALUE DIF_COMPARE
  FROM OPERACION OPER
    INNER JOIN DATOHISTORICO DH ON OPER.FECHA_APERTURA=DH.FECHA
  --WHERE OPER.ID_INDIVIDUO='1322622379655.43'
  WHERE OPER.PIPS>0
  AND OPER.FECHA_APERTURA>TO_DATE('20140101', 'YYYYMMDD')
  --ORDER BY OPER.FECHA_APERTURA ASC
) P
;

SELECT ROUND(AVG(P.PIPS),5) PIPS, ROUND(AVG(DIF_BOLLINGER),5) BOL, 
  ROUND(AVG(DIF_MA),5) MA, ROUND(AVG(DIF_SAR),5) SAR FROM (
  SELECT OPER.PIPS, DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER DIF_BOLLINGER, 
    DH.AVERAGE-OPER.OPEN_PRICE DIF_MA, 
    DH.SAR-OPER.OPEN_PRICE DIF_SAR
  FROM OPERACION OPER
    INNER JOIN DATOHISTORICO DH ON OPER.FECHA_APERTURA=DH.FECHA
  --WHERE OPER.ID_INDIVIDUO='1322622379655.43'
  WHERE OPER.PIPS<0
  AND OPER.FECHA_APERTURA>TO_DATE('20140101', 'YYYYMMDD')
  --ORDER BY OPER.FECHA_APERTURA ASC
) P
;
SELECT ROUND(AVG(P.PIPS),5) PIPS, ROUND(AVG(DIF_BOLLINGER),5) BOL, 
  ROUND(AVG(DIF_MA),5) MA, ROUND(AVG(DIF_SAR),5) SAR FROM (
  SELECT OPER.PIPS, DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER DIF_BOLLINGER, 
    DH.AVERAGE-OPER.OPEN_PRICE DIF_MA, 
    DH.SAR-OPER.OPEN_PRICE DIF_SAR
  FROM OPERACION OPER
    INNER JOIN DATOHISTORICO DH ON OPER.FECHA_APERTURA=DH.FECHA
  --WHERE OPER.ID_INDIVIDUO='1322622379655.43'
  WHERE OPER.PIPS>200
  AND OPER.FECHA_APERTURA>TO_DATE('20140101', 'YYYYMMDD')
  --ORDER BY OPER.FECHA_APERTURA ASC
) P
;
SELECT ROUND(AVG(P.PIPS),5) PIPS, ROUND(AVG(DIF_BOLLINGER),5) BOL, 
  ROUND(AVG(DIF_MA),5) MA, ROUND(AVG(DIF_SAR),5) SAR FROM (
  SELECT OPER.PIPS, DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER DIF_BOLLINGER, 
    DH.AVERAGE-OPER.OPEN_PRICE DIF_MA, 
    DH.SAR-OPER.OPEN_PRICE DIF_SAR
  FROM OPERACION OPER
    INNER JOIN DATOHISTORICO DH ON OPER.FECHA_APERTURA=DH.FECHA
  --WHERE OPER.ID_INDIVIDUO='1322622379655.43'
  WHERE OPER.PIPS>500
  AND OPER.FECHA_APERTURA>TO_DATE('20140101', 'YYYYMMDD')
  --ORDER BY OPER.FECHA_APERTURA ASC
) P

;
