SELECT OPER.* 
 FROM FOREX.OPERACION OPER
ORDER BY FECHA_APERTURA DESC
;

SELECT TIPO, SUM(OPER.PIPS), COUNT(*)
 FROM FOREX.OPERACION OPER WHERE OPER.PIPS<0
GROUP BY TIPO
;

SELECT ROWID, OPER.* FROM OPERACION OPER
WHERE OPER.ID_INDIVIDUO LIKE '1483900498799.243'
--AND OPER.FECHA_CIERRE>=TO_DATE('20160121','YYYYMMDD')
ORDER BY FECHA_APERTURA DESC;

SELECT OPER.* FROM OPERACION OPER
WHERE OPER.TIPO='SELL' --OPER.ID_INDIVIDUO LIKE '1477365411387.5222'
AND OPER.FECHA_APERTURA>=TO_DATE('20160121','YYYYMMDD')
ORDER BY FECHA_APERTURA DESC;

SELECT TO_CHAR(FECHA_APERTURA, 'YYYYMMDD') FECHA, COUNT(*), SUM(OPER.PIPS) PIPS
FROM OPERACION OPER
WHERE OPER.TIPO='BUY' --OPER.ID_INDIVIDUO LIKE '1477365411387.5222'
AND OPER.FECHA_APERTURA>=TO_DATE('20160119','YYYYMMDD')
GROUP BY TO_CHAR(FECHA_APERTURA, 'YYYYMMDD')
ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYYMMDD') ASC;

SELECT TO_CHAR(FECHA_APERTURA, 'YYYYMM') FE, --OPER.TIPO, 
SUM(PIPS), COUNT(*) 
FROM OPERACION OPER
GROUP BY TO_CHAR(FECHA_APERTURA, 'YYYYMM')--, OPER.TIPO
ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYYMM') DESC--, OPER.TIPO ASC
;

SELECT OPER.ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYYMM') FE, --OPER.TIPO, 
SUM(PIPS), COUNT(*)
FROM OPERACION OPER
WHERE OPER.ID_INDIVIDUO LIKE '1477365411387.9913'
GROUP BY OPER.ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYYMM')--, OPER.TIPO
ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYYMM') DESC--, OPER.TIPO ASC
;

SELECT IND.PARENT_ID_1, OPER.* FROM OPERACION OPER
INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO 
WHERE IND.ID LIKE '1476538066635.%' AND IND.PARENT_ID_1 IS NOT NULL
ORDER BY IND.ID ASC, OPER.FECHA_APERTURA ASC;;

SELECT * FROM OPERACION OPER
WHERE OPER.FECHA_APERTURA>TO_DATE('2016/09/01 23:59','YYYY/MM/DD HH24:MI')
--AND OPER.ID_INDIVIDUO LIKE '1473%'
ORDER BY FECHA_APERTURA ASC;

SELECT * FROM OPERACION OPER
WHERE OPER.FECHA_APERTURA BETWEEN TO_DATE('2016/07/21 23:59','YYYY/MM/DD HH24:MI')
  AND TO_DATE('2016/08/21 23:59','YYYY/MM/DD HH24:MI')
AND OPER.ID_INDIVIDUO LIKE '1473%'
ORDER BY FECHA_APERTURA ASC;

SELECT ID_INDIVIDUO, COUNT(*), SUM(PIPS)
 FROM FOREX.OPERACION OPER
WHERE --OPER.ID_INDIVIDUO IN ('1463541693654.5583')
--AND TO_CHAR(OPER.FECHA_CIERRE, 'YYYYMM')='201411'
--AND
OPER.FECHA_CIERRE>=TO_DATE('20160320','YYYYMMDD')
--AND FECHA_CIERRE IS NOT NULL
--AND OPER.PIPS>0
GROUP BY ID_INDIVIDUO
--ORDER BY TO_CHAR(FECHA_CIERRE, 'YYYYMMDD') ASC
;


SELECT ID_INDIVIDUO, SUM(PIPS), COUNT(*)
FROM FOREX.OPERACION 
--WHERE ID_INDIVIDUO IN ('1330999046124.191')
GROUP BY ID_INDIVIDUO
ORDER BY COUNT(*) DESC;

SELECT MAX(FECHA_APERTURA), MAX(FECHA_CIERRE) FROM OPERACION OPER
;

SELECT ID_INDIVIDUO, 
SUM(OPER.PIPS), COUNT(*), MAX(OPER.FECHA_CIERRE),  
  IND.MONEDA, IND.TIPO_OPERACION, MAX(IND.CREATION_DATE)
 FROM FOREX.OPERACION OPER
  INNER JOIN INDIVIDUO IND ON OPER.ID_INDIVIDUO=IND.ID AND IND.TIPO_INDIVIDUO='INDICADORES'
WHERE IND.TIPO_OPERACION='SELL' --AND IND.ID LIKE '1462061850021.%'
GROUP BY ID_INDIVIDUO, 
IND.MONEDA, IND.TIPO_OPERACION
ORDER BY SUM(PIPS) DESC, ID_INDIVIDUO ASC
;

SELECT OPER.PIPS, ROUND((OPER.FECHA_CIERRE-OPER.FECHA_APERTURA)*24*60,5) DURACION , OPER.* 
 FROM FOREX.OPERACION OPER
  INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO AND IND.TIPO_INDIVIDUO='INDICADORES'
WHERE OPER.ID_INDIVIDUO IN ('1332993893287.901')
--AND TIPO='BUY'
--AND PIPS<0
AND TO_CHAR(FECHA_APERTURA, 'YYYYMMDD')>='20140101'
--AND OPER.OPEN_PRICE BETWEEN 1.00139 AND 1.00149 --AND STOP_LOSS>=TAKE_PROFIT*2
ORDER BY --ID_INDIVIDUO DESC, 
FECHA_APERTURA ASC
  --OPER.PIPS ASC
  ;

SELECT COUNT(*) FROM OPERACION;
-- 20150112 14:15 = 33.829.988
-- After delete individuos with too much orders 20160112 17:11 = 32.929.909
-- After delete individuos with too much orders 20160113 09:20 = 31.933.671
-- After delete individuos with too much orders 20160113 21:50 = 30.307.682
-- After delete individuos with too much orders 20160114 08:58 = 28.947.103
-- Borrando duplicado 20160114 12:00 = 28.937.954

--SELECT AVG(CO) FROM (
SELECT ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYYMMDD') DIA, COUNT(*) CO, SUM(PIPS)
 FROM FOREX.OPERACION OPER
WHERE OPER.ID_INDIVIDUO IN (
'1477883335391.1329'
)
--AND TO_CHAR(OPER.FECHA_CIERRE, 'YYYYMM')='201411'
AND FECHA_CIERRE IS NOT NULL
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYYMMDD')
ORDER BY TO_CHAR(FECHA_CIERRE, 'YYYYMMDD') ASC
--)
;

SELECT ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYY WW') SEMANA, COUNT(*), SUM(PIPS), MIN(FECHA_CIERRE) MIN_FECHA
 FROM FOREX.OPERACION OPER
WHERE OPER.ID_INDIVIDUO IN (
'1452804197914.9'
)
--AND TO_CHAR(OPER.FECHA_CIERRE, 'YYYY')='2014'
AND FECHA_CIERRE IS NOT NULL
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYY WW')
ORDER BY TO_CHAR(FECHA_CIERRE, 'YYYY WW') ASC
;

SELECT ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYYMM') FE, COUNT(*), SUM(PIPS)
 FROM FOREX.OPERACION OPER
WHERE OPER.ID_INDIVIDUO like '1455148800000.531'
--AND TO_CHAR(OPER.FECHA_CIERRE, 'YYYY')='2012'
AND FECHA_CIERRE IS NOT NULL
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYYMM')
ORDER BY TO_CHAR(FECHA_CIERRE, 'YYYYMM') ASC
;

SELECT ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYY') FE, COUNT(*), SUM(PIPS)
 FROM FOREX.OPERACION OPER
WHERE 
ID_INDIVIDUO LIKE '1455148800000.531'
AND FECHA_CIERRE IS NOT NULL
--AND TO_CHAR(FECHA_CIERRE, 'YYYY')='2015'
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_CIERRE, 'YYYY')
ORDER BY TO_CHAR(FECHA_CIERRE, 'YYYY') DESC, SUM(PIPS) DESC
;

SELECT COUNT(*), SUM(PIPS)
 FROM FOREX.OPERACION OPER
WHERE OPER.ID_INDIVIDUO IN (
'1453687605734.5'
)
AND FECHA_CIERRE IS NOT NULL
AND FECHA_CIERRE<TO_DATE('201203','YYYYMM')
;

SELECT TO_CHAR(OPER.FECHA_APERTURA, 'YYYY'), COUNT(*), SUM(OPER.PIPS)
FROM OPERACION OPER
GROUP BY TO_CHAR(OPER.FECHA_APERTURA, 'YYYY')
ORDER BY TO_CHAR(OPER.FECHA_APERTURA, 'YYYY') DESC;

-- operaciones hacia atras, dias fecha apertura, probabilidad, porcentaje st y tp

--PROBAR: 
  --OPERAR CUANDO ALGUNO DE LOS DOS DA ENTRADA, UNO PUEDE SER NULO (COMPRA O VENTA) --> NO DA PORQUE ESTO AYUDA A FILTRAR EN LOS PUNTOS EXTREMOS
  --AGRUPAR EN 15 MINUTOS
  --DISMINUIR EL MINIMO DE PIPS A 5, AUMENTARLO A 15
  --CON MUCHOS PUNTOS GENERADOS (OPERANDO MUCHAS VECES), PROBAR SIN LOS FILTROS
  --OPERAR AÚN CUANDO LA OPERACIÓN ANTERIOR ES PERDEDORA

SELECT OPER.ID_INDIVIDUO, COUNT(*), SUM(PIPS) FROM FOREX.OPERACION OPER  
WHERE TO_CHAR(OPER.FECHA_APERTURA, 'YYYY')='2014'
  AND EXISTS (
    SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO=OPER.ID_INDIVIDUO
  )
GROUP BY OPER.ID_INDIVIDUO 
HAVING SUM(PIPS) > 0
ORDER BY SUM(PIPS) DESC
--ORDER BY COUNT(*) DESC
;

SELECT * FROM OPERACION OPER
ORDER BY FECHA_APERTURA DESC
;

SELECT * FROM OPERACION OPER
WHERE FECHA>SYSDATE-1
--ORDER BY FECHA DESC
;

SELECT * FROM OPERACION OPER
WHERE OPER.FECHA_CIERRE IS NULL
ORDER BY OPER.FECHA_APERTURA DESC;

SELECT TO_CHAR(FECHA_APERTURA, 'YYYYMM') FE, 
--ROUND(OPER.OPEN_PRICE,3) PRECIO,
SUM(PIPS), COUNT(*) FROM OPERACION OPER
--WHERE OPER.ID_INDIVIDUO='1417310014681.38'
GROUP BY --ROUND(OPER.OPEN_PRICE,3)
TO_CHAR(FECHA_APERTURA, 'YYYYMM')
ORDER BY 
TO_CHAR(FECHA_APERTURA, 'YYYYMM') DESC
--SUM(OPER.PIPS) DESC
--ROUND(OPER.OPEN_PRICE, 3) DESC
;

/*
USAR-MM	Numeric month (e.g., 07)
MON	Abbreviated month name (e.g., JUL)
MONTH	Full month name (e.g., JULY)
USAR-DD	Day of month (e.g., 24)
USAR-DY	Abbreviated name of day (e.g., FRI)
USAR-YYYY	4-digit year (e.g., 1998)
YY	Last 2 digits of the year (e.g., 98)
RR	Like YY, but the two digits are ``rounded'' to a year in the range 1950 to 2049. Thus, 06 is considered 2006 instead of 1906
USAR-AM (or PM)	Meridian indicator
HH	Hour of day (1-12)
USAR-HH24	Hour of day (0-23)
MI	Minute (0-59)
SS	Second (0-59)
*/
SELECT * FROM OPERACION OPER
WHERE OPER.PIPS>500
ORDER BY OPER.FECHA_APERTURA DESC
;

SELECT DISTINCT ID_INDIVIDUO FROM OPERACION OPER
WHERE OPER.FECHA_APERTURA BETWEEN TO_DATE('2011/10/28 12:03','YYYY/MM/DD HH24:MI')-20
    AND TO_DATE('2011/10/28 12:03','YYYY/MM/DD HH24:MI')-1
AND OPER.FECHA_CIERRE<TO_DATE('2011/10/28 12:03','YYYY/MM/DD HH24:MI')
AND OPER.PIPS>0
MINUS
SELECT DISTINCT ID_INDIVIDUO  FROM OPERACION OPER2 WHERE 
    OPER2.FECHA_APERTURA BETWEEN TO_DATE('2011/10/28 12:03','YYYY/MM/DD HH24:MI')
        AND TO_DATE('2011/10/28 12:03','YYYY/MM/DD HH24:MI')+3
;

SELECT ID_INDIVIDUO, SUM(OPER.PIPS), COUNT(*) CANT, 
  ROUND(AVG(MAX_PIPS_RETROCESO)) AVG_RETRO, MIN(MAX_PIPS_RETROCESO) MIN_RETRO, MAX(MAX_PIPS_RETROCESO) MAX_RETROCESO
FROM FOREX.OPERACION OPER 
  INNER JOIN INDIVIDUO IND ON IND.ID=OPER.ID_INDIVIDUO AND IND.CREATION_DATE>TRUNC(SYSDATE)-1
GROUP BY OPER.ID_INDIVIDUO 
ORDER BY 
--AVG(MAX_PIPS_RETROCESO) DESC
SUM(PIPS) DESC
;

SELECT OPER.*
FROM FOREX.OPERACION OPER
WHERE ID_INDIVIDUO IN (
'1338262910518.7',
'1338348861018.5929'
)
ORDER BY (MAX_PIPS_RETROCESO) DESC;

SELECT ID_INDIVIDUO, TRUNC(OPER.TAKE_PROFIT/100) GRUPO, SUM(OPER.PIPS) PIPS,
  MIN(OPER.TAKE_PROFIT) MIN_TP, MAX(OPER.TAKE_PROFIT) MAX_TP, ROUND(AVG(OPER.TAKE_PROFIT),5) PROM_TP, 
  COUNT(*) CANTIDAD, ROUND(AVG(OPER.PIPS),5) PROM_PIPS
FROM FOREX.OPERACION OPER
WHERE ID_INDIVIDUO IN (
--'1379078348722.1',
'1379275588910.1'
)
--AND PIPS>0
GROUP BY ID_INDIVIDUO, TRUNC(OPER.TAKE_PROFIT/100)
ORDER BY ID_INDIVIDUO, SUM(OPER.PIPS) ASC
;

SELECT * FROM OPERACION WHERE FECHA_CIERRE<=FECHA_APERTURA;

SELECT TO_CHAR(OPER.FECHA_APERTURA, 'YYYY/MM/DD HH24:MI') FECHA, COUNT(*), SUM(PIPS) 
FROM OPERACION GROUP BY TO_CHAR(FECHA_APERTURA, 'YYYY/MM/DD HH24:MI')
--HAVING COUNT(*) > 100
ORDER BY COUNT(*) DESC;
---ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYY/MM/DD HH24:MI') DESC;

SELECT OPER.FECHA_APERTURA, COUNT(*), SUM(OPER.PIPS) 
FROM OPERACION OPER
  INNER JOIN (select * from TEMP_VIEW where rownum<10) TV ON OPER.ID_INDIVIDUO=TV.ID_INDIVIDUO
GROUP BY OPER.FECHA_APERTURA
--HAVING COUNT(*) > 100
--ORDER BY COUNT(*) DESC
;

SELECT * FROM TEMP_VIEW;

SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.OPEN_PRICE, OPER.SPREAD, OPER.LOTE 
FROM OPERACION OPER
 WHERE OPER.FECHA_APERTURA<=--(select max(fecha)-1 from datohistorico)
 (TO_DATE('2011/03/17 01:31','YYYY/MM/DD HH24:MI')) 
  AND (OPER.FECHA_CIERRE IS NULL OR OPER.FECHA_CIERRE>--(select max(fecha)-1 from datohistorico))
 (TO_DATE('2011/03/17 01:31','YYYY/MM/DD HH24:MI')))
 ;
                
SELECT IND.ID ID_INDIVIDUO, MAX(PROC.FECHA_HISTORICO) FECHA_HISTORICO, MAX(OPER.FECHA_APERTURA) FECHA_APERTURA 
FROM INDIVIDUO IND 
LEFT JOIN PROCESO PROC ON IND.ID=PROC.ID_INDIVIDUO 
LEFT JOIN OPERACION OPER ON IND.ID=OPER.ID_INDIVIDUO AND OPER.FECHA_CIERRE IS NULL 
WHERE IND.ID NOT IN (SELECT DISTINCT PRO.ID_INDIVIDUO FROM PROCESO PRO WHERE PRO.FECHA_HISTORICO=(SELECT MAX(FECHA) FROM DATOHISTORICO)) 
AND IND.ID='1332696593249.74'
GROUP BY IND.ID 
ORDER BY IND.ID DESC ;

SELECT * FROM OPERACION ORDER BY ID_INDIVIDUO ASC, FECHA_APERTURA ASC;

SELECT * FROM OPERACION ORDER BY FECHA_APERTURA ASC;

SELECT COUNT(*) FROM FOREX.OPERACION;

SELECT COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.PROCESO;
SELECT * FROM FOREX.PROCESO ORDER BY FECHA_PROCESO DESC;
/*SELECT * FROM FOREX.PROCESO PROC
  INNER JOIN FOREX.OPERACION OPER ON OPER.ID_INDIVIDUO=PROC.ID_INDIVIDUO
ORDER BY PROC.ID_INDIVIDUO ASC
;*/

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM FOREX.INDIVIDUO IND WHERE IND.CREATION_DATE IS NULL AND IND.PARENT_ID_1 IS NOT NULL AND IND.PARENT_ID_2 IS NOT NULL
  UNION ALL
  SELECT IND.ID FROM FOREX.INDIVIDUO_BORRADO IND WHERE IND.CREATION_DATE IS NULL AND IND.PARENT_ID_1 IS NOT NULL AND IND.PARENT_ID_2 IS NOT NULL
) ORDER BY FECHA_PROCESO DESC;

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM FOREX.INDIVIDUO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
    BETWEEN TO_DATE('2012/06/07', 'YYYY/MM/DD') AND TO_DATE('2012/08/07', 'YYYY/MM/DD')
  UNION ALL
    SELECT IND.ID FROM FOREX.INDIVIDUO_BORRADO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
    BETWEEN TO_DATE('2012/06/07', 'YYYY/MM/DD') AND TO_DATE('2012/08/07', 'YYYY/MM/DD')
  )
ORDER BY FECHA_PROCESO DESC;

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM FOREX.INDIVIDUO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
  BETWEEN TO_DATE('2012/05/07', 'YYYY/MM/DD') AND TO_DATE('2012/06/06', 'YYYY/MM/DD')
  UNION ALL
  SELECT IND.ID FROM FOREX.INDIVIDUO_BORRADO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
  BETWEEN TO_DATE('2012/05/07', 'YYYY/MM/DD') AND TO_DATE('2012/06/06', 'YYYY/MM/DD')

  )
ORDER BY FECHA_PROCESO DESC;

SELECT COUNT(*) FROM FOREX.OPERACION WHERE ID_INDIVIDUO='1327820389786.318';

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO='1339124687689.853' 
ORDER BY FECHA_PROCESO DESC;

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO='1329850420864.9747' ORDER BY FECHA_HISTORICO DESC;

SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO='1341687718670.3284'
ORDER BY ID_INDIVIDUO,FECHA_APERTURA DESC;

SELECT * FROM FOREX.V_OPERACIONES 
WHERE ID='1329927210938.986'
AND OPEN_FECHA=TO_DATE('2008/10/29 17:43','YYYY/MM/DD HH24:MI')
AND CLOSE_FECHA=TO_DATE('2008/10/29 17:50','YYYY/MM/DD HH24:MI')
ORDER BY ID,OPEN_FECHA;

SELECT * FROM FOREX.OPERACION ORDER BY ID_INDIVIDUO,FECHA_APERTURA;

SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO IN (
  SELECT ID_INDIVIDUO FROM FOREX.OPERACION 
  GROUP BY ID_INDIVIDUO HAVING COUNT(*) > 1)
ORDER BY ID_INDIVIDUO,FECHA_APERTURA;

SELECT OPER.*
FROM FOREX.DATOHIST_INDICADORINDIVIDUO OPER
WHERE OPER.ID_INDIVIDUO='1343862270390.14'
AND OPER.OPEN_FECHA=TO_DATE('2011/02/28 17:13','YYYY/MM/DD HH24:MI')
AND CLOSE_FECHA=TO_DATE('2011/03/15 04:46','YYYY/MM/DD HH24:MI')
;	

  SELECT MIN(FECHA) FROM DATOHISTORICO WHERE FECHA > TO_DATE('2008/05/08 02:29','YYYY/MM/DD HH24:MI');
  SELECT * FROM DATOHISTORICO WHERE FECHA=TO_DATE('2008/05/08 02:33','YYYY/MM/DD HH24:MI');
  SELECT 1.01179-(-0.00065),  1.01179-(-0.00039), 1.0114, 1.0126 ,
    (INTERSECT_INTERVAL(1.01179-(-0.00039), 1.01179-(-0.00065), 1.0114, 1.0126)) INTER FROM DUAL;

SELECT * FROM FOREX.OPERACION_BASE OPB1 
WHERE EXISTS (SELECT 1 FROM FOREX.OPERACION_BASE OPB2 WHERE 
OPB1.ID_INDIVIDUO=OPB2.ID_INDIVIDUO AND OPB1.FECHA_APERTURA > OPB2.FECHA_APERTURA AND OPB1.FECHA_APERTURA <= OPB2.FECHA_CIERRE)
ORDER BY OPB1.ID_INDIVIDUO,FECHA_APERTURA;

SELECT * FROM (
  SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO IN (
    SELECT ID_INDIVIDUO FROM FOREX.OPERACION 
    GROUP BY ID_INDIVIDUO HAVING COUNT(*) > 1)
  ORDER BY ID_INDIVIDUO,FECHA_APERTURA) OPM
WHERE OPM.ID_INDIVIDUO NOT IN (
  SELECT ID_INDIVIDUO FROM FOREX.OPERACION_BASE OPB1 
  WHERE EXISTS (SELECT 1 FROM FOREX.OPERACION_BASE OPB2 WHERE 
  OPB1.ID_INDIVIDUO=OPB2.ID_INDIVIDUO AND OPB1.FECHA_APERTURA > OPB2.FECHA_APERTURA AND OPB1.FECHA_APERTURA <= OPB2.FECHA_CIERRE)
);  

SELECT ROUND(AVG((OPER.FECHA_CIERRE-OPER.FECHA_APERTURA)*24*60),5) AVG_DURACION,
  MIN((OPER.FECHA_CIERRE-OPER.FECHA_APERTURA)*24*60) MIN_DURACION,
  MAX((OPER.FECHA_CIERRE-OPER.FECHA_APERTURA)*24*60) MAX_DURACION
FROM FOREX.OPERACION OPER;

SELECT AVG((FECHA_CIERRE-FECHA_APERTURA)) FROM OPERACION 
;

--UPDATE OPERACION SET FECHA_CIERRE=NULL 
--WHERE ID_INDIVIDUO='1473465600000.1' AND FECHA_APERTURA=TO_DATE('2014/09/26 01:22', 'YYYY/MM/DD HH24:MI');

--DELETE FROM OPERACION WHERE PIPS=0;
--UPDATE OPERACION SET ID_INDIVIDUO='1376666841707.1' WHERE ID_INDIVIDUO='1376678812647.1';

SELECT COUNT(*) FROM OPERACION OPER WHERE MAX_PIPS_RETROCESO IS NOT NULL;

--UPDATE OPERACION SET MAX_PIPS_RETROCESO=NULL, MAX_VALUE_RETROCESO=NULL, MAX_FECHA_RETROCESO=NULL 
--WHERE MAX_PIPS_RETROCESO IS NOT NULL;

--UPDATE OPERACION SET MAX_PIPS_RETROCESO=NULL, MAX_VALUE_RETROCESO=NULL, MAX_FECHA_RETROCESO=NULL 
--WHERE ID_INDIVIDUO='1327972190940.3' AND FECHA_APERTURA=TO_DATE('2008/05/06 15:58', 'YYYY/MM/DD HH24:MI');

--UPDATE OPERACION SET MAX_PIPS_RETROCESO=NULL, MAX_VALUE_RETROCESO=NULL, MAX_FECHA_RETROCESO=NULL 
--WHERE TIPO='BUY';

--INDIVIDUOS OPERACION ACTIVA
SELECT * FROM ( 
                  SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.FECHA_CIERRE, 
                  OPER.OPEN_PRICE, OPER.SPREAD, OPER.LOTE, OPER.PIPS, OPER.TIPO 
                  FROM OPERACION OPER 
                      INNER JOIN PROCESO PROC ON PROC.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
                      AND (PROC.FECHA_HISTORICO>=TO_DATE('2011/09/06 14:51', 'YYYY/MM/DD HH24:MI')) 
                  WHERE OPER.FECHA_APERTURA<TO_DATE('2011/09/06 14:51', 'YYYY/MM/DD HH24:MI') 
                    AND (OPER.FECHA_CIERRE IS NULL OR OPER.FECHA_CIERRE>TO_DATE('2011/09/06 14:51', 'YYYY/MM/DD HH24:MI'))
                  AND OPER.FECHA_APERTURA>TO_DATE('2011/09/06 14:51', 'YYYY/MM/DD HH24:MI')-30
                  AND OPER.TIPO = 'SELL'
                  AND OPER.ID_INDIVIDUO NOT IN (SELECT ID_INDIVIDUO FROM TENDENCIA TEND WHERE TEND.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
                    AND TEND.FECHA_BASE=TO_DATE('2011/09/06 14:51', 'YYYY/MM/DD HH24:MI')
                    --AND TEND.TIPO_TENDENCIA=?
                    )
                  AND EXISTS (SELECT 1 FROM OPERACION OPER2 
                      WHERE OPER2.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
                      AND OPER2.FECHA_CIERRE < OPER.FECHA_APERTURA) 
                  AND EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II 
                      WHERE II.ID_INDIVIDUO=OPER.ID_INDIVIDUO) 
                  ORDER BY OPER.FECHA_APERTURA DESC) 
                  --WHERE ROWNUM < ? 
;

--RETROCESOS INDIVIDUOS
SELECT OPER.ID_INDIVIDUO, OPER.TAKE_PROFIT, OPER.STOP_LOSS, 
    OPER.FECHA_APERTURA, OPER.FECHA_CIERRE, OPER.SPREAD, OPER.OPEN_PRICE, OPER.LOTE, OPER.PIPS, 
    OPER.TIPO, OPER.MAX_PIPS_RETROCESO, OPER.MAX_VALUE_RETROCESO, OPER.MAX_FECHA_RETROCESO 
FROM OPERACION OPER 
WHERE OPER.TIPO='SELL' AND ID_INDIVIDUO='1331293784637.1635' AND FECHA_APERTURA<=TO_DATE('2011/09/05 02:42', 'YYYY/MM/DD HH24:MI')
AND MAX_PIPS_RETROCESO IS NULL
;

SELECT * FROM OPERACION OPER
      WHERE OPER.FECHA_APERTURA<TO_DATE('2012/06/01 00:00', 'YYYY/MM/DD HH24:MI') 
      AND (OPER.FECHA_CIERRE IS NULL OR OPER.FECHA_CIERRE>TO_DATE('2012/06/01 00:00', 'YYYY/MM/DD HH24:MI') )
      AND OPER.FECHA_APERTURA>TO_DATE('2012/06/01 00:00', 'YYYY/MM/DD HH24:MI') -30
;

SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.FECHA_CIERRE, 
    OPER.OPEN_PRICE, OPER.SPREAD, OPER.LOTE, OPER.PIPS, OPER.TIPO 
    FROM OPERACION OPER 
    WHERE OPER.FECHA_APERTURA<TO_DATE('2012/06/01 00:00', 'YYYY/MM/DD HH24:MI') 
    AND (OPER.FECHA_CIERRE IS NULL OR OPER.FECHA_CIERRE>TO_DATE('2012/03/14 08:52', 'YYYY/MM/DD HH24:MI') )
    AND OPER.TIPO = 'SELL'
    ;    
    
--DELETE FROM TENDENCIA WHERE ID_INDIVIDUO NOT IN (SELECT IND.ID FROM INDIVIDUO IND);      

SELECT DISTINCT REP.ID_INDIVIDUO1, REP.ID_INDIVIDUO2 FROM INDIVIDUOS_REPETIDOS_OPER REP
  INNER JOIN INDICADOR_INDIVIDUO_TENDENCIAS IIT1 ON IIT1.ID_INDIVIDUO=REP.ID_INDIVIDUO1
  INNER JOIN INDICADOR_INDIVIDUO_TENDENCIAS IIT2 ON IIT2.ID_INDIVIDUO=REP.ID_INDIVIDUO2
WHERE ROWNUM <10;

SELECT * FROM INDIVIDUO IND
INNER JOIN PROCESO P ON IND.ID=P.ID_INDIVIDUO
WHERE IND.PARENT_ID_1 IS NOT NULL AND IND.PARENT_ID_2 IS NOT NULL 
;

