SELECT OPER.ID_INDIVIDUO, MIN(OPER.MAX_PIPS_RETROCESO) FROM OPERACION OPER
WHERE OPER.PIPS<0
GROUP BY OPER.ID_INDIVIDUO
HAVING MIN(OPER.MAX_PIPS_RETROCESO)>0 AND COUNT(*)>1
ORDER BY MIN(OPER.MAX_PIPS_RETROCESO) DESC
;

--- INDIVIDUOS QUE OPERAN EN LA MISMA FECHA Y NO TIENEN OPERACIONES CONTRARIAS
SELECT * FROM OPERACION OPER1
  INNER JOIN OPERACION OPER2 
    ON OPER1.FECHA_APERTURA=OPER2.FECHA_APERTURA AND OPER1.ID_INDIVIDUO<>OPER2.ID_INDIVIDUO
    AND OPER1.PIPS>0 AND OPER1.PIPS>0
WHERE NOT EXISTS 
  (SELECT 1 FROM OPERACION OPER3
    WHERE OPER3.ID_INDIVIDUO=OPER1.ID_INDIVIDUO AND OPER3.PIPS<0)
AND NOT EXISTS (SELECT 1 FROM OPERACION OPER3
    WHERE OPER3.ID_INDIVIDUO=OPER2.ID_INDIVIDUO AND OPER3.PIPS<0)

;


SELECT DH1.FECHA F1, DH2.FECHA F2, DH1.HIGH, DH2.LOW, (DH1.HIGH-DH2.LOW)*100000 DIFF FROM DATOHISTORICO DH1
  INNER JOIN DATOHISTORICO DH2 ON DH2.FECHA>DH1.FECHA AND (DH1.HIGH-DH2.LOW)*100000>500
WHERE NOT EXISTS (
  SELECT 1 FROM DATOHISTORICO DH3 
  WHERE (DH3.FECHA BETWEEN DH1.FECHA AND DH2.FECHA) AND (DH3.HIGH-DH1.HIGH)*100000>15
  )  
AND ROWNUM<2;