SELECT R1.ID_INDIVIDUO, R1.FECHA_APERTURA, MIN(DH2.FECHA), R1.FECHA_CIERRE, R1.OPEN_PRICE,R1.MINIMO,(R1.OPEN_PRICE-R1.MINIMO)*10000
  FROM DATOHISTORICO DH2 INNER JOIN (
    SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA,OPER.OPEN_PRICE, OPER.FECHA_CIERRE, MIN(DH.LOW) MINIMO FROM OPERACION OPER
      INNER JOIN DATOHISTORICO DH ON DH.FECHA>OPER.FECHA_APERTURA AND DH.FECHA<OPER.FECHA_CIERRE
    WHERE 
      OPER.PIPS<0  AND
      OPER.ID_INDIVIDUO='1331998280983.413'
    GROUP BY OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.FECHA_CIERRE, OPER.OPEN_PRICE
    ) R1 ON R1.MINIMO=DH2.LOW AND DH2.FECHA>R1.FECHA_APERTURA AND DH2.FECHA<R1.FECHA_CIERRE
WHERE (R1.OPEN_PRICE-R1.MINIMO)*10000>8
GROUP BY R1.ID_INDIVIDUO, R1.FECHA_APERTURA, R1.MINIMO, R1.FECHA_CIERRE, R1.OPEN_PRICE
--ORDER BY R1.ID_INDIVIDUO, R1.FECHA_APERTURA
;

SELECT R1.ID_INDIVIDUO, R1.FECHA_APERTURA, MIN(DH2.FECHA), R1.FECHA_CIERRE, R1.OPEN_PRICE,R1.MAXIMO,(R1.MAXIMO-R1.OPEN_PRICE)*10000
  FROM DATOHISTORICO DH2 INNER JOIN (
    SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA,OPER.OPEN_PRICE, OPER.FECHA_CIERRE, MAX(DH.HIGH) MAXIMO FROM OPERACION OPER
      INNER JOIN DATOHISTORICO DH ON DH.FECHA>OPER.FECHA_CIERRE AND DH.FECHA<OPER.FECHA_CIERRE+30
    WHERE 
     -- OPER.PIPS<0
      --AND
      OPER.ID_INDIVIDUO='1332391723361.992'
    GROUP BY OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.FECHA_CIERRE, OPER.OPEN_PRICE
    ) R1 ON R1.MAXIMO=DH2.HIGH AND DH2.FECHA>R1.FECHA_CIERRE AND DH2.FECHA<R1.FECHA_CIERRE+30
WHERE (R1.MAXIMO-R1.OPEN_PRICE)*10000>718-- AND ROWNUM<100
GROUP BY R1.ID_INDIVIDUO, R1.FECHA_APERTURA, R1.MAXIMO, R1.FECHA_CIERRE, R1.OPEN_PRICE
--ORDER BY R1.ID_INDIVIDUO, R1.FECHA_APERTURA
;

SELECT DEST.ID_INDIVIDUO, R2.CANTIDAD FROM
  (SELECT ID_INDIVIDUO, COUNT(*) CANTIDAD FROM OPERACION WHERE PIPS<0 
    GROUP BY ID_INDIVIDUO HAVING COUNT(*)>1) DEST
  INNER JOIN (
      SELECT R1.ID_INDIVIDUO, COUNT(*) CANTIDAD FROM (
          SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.OPEN_PRICE, OPER.FECHA_CIERRE, MIN(DH.LOW) MINIMO 
          FROM (SELECT ID_INDIVIDUO FROM OPERACION WHERE PIPS<0 GROUP BY ID_INDIVIDUO HAVING COUNT(*)>1) OPER1
            INNER JOIN OPERACION OPER ON OPER.ID_INDIVIDUO=OPER1.ID_INDIVIDUO
            INNER JOIN DATOHISTORICO DH ON DH.FECHA>OPER.FECHA_APERTURA AND DH.FECHA<OPER.FECHA_CIERRE AND PIPS<0
--          WHERE OPER.ID_INDIVIDUO='1331999548575.46'
          GROUP BY OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.OPEN_PRICE, OPER.FECHA_CIERRE
          HAVING (OPER.OPEN_PRICE-MIN(DH.LOW))*10000>8
          ) R1 GROUP BY R1.ID_INDIVIDUO
    ) R2 ON R2.ID_INDIVIDUO=DEST.ID_INDIVIDUO AND DEST.CANTIDAD=R2.CANTIDAD
;

