
  CREATE OR REPLACE FORCE VIEW "FOREX"."PARAMETROS_ESTADISTICAS" ("PARAM_RETROCESO", "PARAM_DURACION", "PARAM_FECHA") AS 
  SELECT TO_NUMBER(P1.VALOR) PARAM_RETROCESO, TO_NUMBER(P2.VALOR) PARAM_DURACION, TO_DATE(P3.VALOR, 'YYYY/MM/DD HH24:MI') PARAM_FECHA
FROM PARAMETRO P1
	INNER JOIN PARAMETRO P2 ON P2.NOMBRE='DURACION_ESTADISTICAS'
	INNER JOIN PARAMETRO P3 ON P3.NOMBRE='FECHA_ESTADISTICAS'
WHERE P1.NOMBRE='RETROCESO_ESTADISTICAS';
