--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_ESTADISTICAS', '2009/04/24 22:51', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_INDIVIDUO_OPTIMO', '2009/01/01 00:00', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_INICIO_TENDENCIA', '2009/01/01 00:00', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('STEP_TENDENCIA', '5', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('PERIODO_OPTIMOS', '10080', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_INICIO_PROCESAR_TENDENCIA', '2012/06/04 06:00', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('STEP_PROCESAR_TENDENCIA', '1440', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('SN_UPDATE_TENDENCIA', 'TRUE', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('RANGO_MAX_MIN_TENDENCIA', '7200', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('INDIVIDUOS_X_TENDENCIA', '1000', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('RETROCESO_ESTADISTICAS', NULL, SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('DURACION_ESTADISTICAS', NULL, SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_INDIVIDUO_PERIODO', NULL, SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_FIN_INDIVIDUO_PERIODO', NULL, SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('MESES_INDIVIDUO_PERIODO', NULL, SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('MONEDA', 'EURJPY', SYSDATE);

UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2010/12/31 23:59' WHERE NOMBRE='FECHA_INDIVIDUO_PERIODO';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2015/02/02 02:41' WHERE NOMBRE='FECHA_FIN_INDIVIDUO_PERIODO';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='12' WHERE NOMBRE='MESES_INDIVIDUO_PERIODO';

UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2015/01/01 00:00' WHERE NOMBRE='FECHA_MINIMA_CREAR_INDIVIDUO';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2017/12/31 23:59' WHERE NOMBRE='FECHA_MAXIMA_CREAR_INDIVIDUO';

UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='EURJPY' WHERE NOMBRE='MONEDA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2013/05/02 00:00' WHERE NOMBRE='FECHA_INICIO_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='800' WHERE NOMBRE='STEP_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2200' WHERE NOMBRE='INDIVIDUOS_X_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2015/12/31 23:59' WHERE NOMBRE='FECHA_ESTADISTICAS';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='1440' WHERE NOMBRE='PERIODO_OPTIMOS';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2012/01/02 00:00' WHERE NOMBRE='FECHA_INDIVIDUO_OPTIMO';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2013/01/16 23:59' WHERE NOMBRE='FECHA_INICIO_PROCESAR_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='1415' WHERE NOMBRE='STEP_PROCESAR_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='FALSE' WHERE NOMBRE='SN_UPDATE_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='3987' WHERE NOMBRE='RANGO_MAX_MIN_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='599' WHERE NOMBRE='RETROCESO_ESTADISTICAS';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='136' WHERE NOMBRE='DURACION_ESTADISTICAS';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR=null --'1422746069706.38' 
WHERE NOMBRE='INDIVIDUOS_TENDENCIA';
COMMIT;

SELECT NOMBRE, VALOR FROM PARAMETRO;
