WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
		0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
		TO_DATE('2017.02.06 23:57', 'YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170125' TIPO_TENDENCIA1, 'BUY_SELL_20170204-2' TIPO_TENDENCIA2, 'xxBUY_SELL_20170131-2' TIPO_TENDENCIA3
		FROM DUAL),
	BASE AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE, 1.30280 PRECIO_ACTUAL
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA),
	TENDENCIA_6H AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_12H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_1D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_2D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_5D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
SELECT ROUND(REGR_SLOPE(TEN6H.PRECIO_CALCULADO, TO_DATE(TEN6H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) PENDIENTE_6H,
	ROUND(REGR_SLOPE(TEN12H.PRECIO_CALCULADO, TO_DATE(TEN12H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) PENDIENTE_12H,
	ROUND(REGR_SLOPE(TEN1D.PRECIO_CALCULADO, TO_DATE(TEN1D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) PENDIENTE_1D,
	ROUND(REGR_SLOPE(TEN2D.PRECIO_CALCULADO, TO_DATE(TEN2D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) PENDIENTE_2D,
	ROUND(REGR_SLOPE(TEN5D.PRECIO_CALCULADO, TO_DATE(TEN5D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) PENDIENTE_5D,
	
	ROUND(REGR_INTERCEPT(TEN6H.PRECIO_CALCULADO, TO_DATE(TEN6H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) INTERS_6H,
	ROUND(REGR_INTERCEPT(TEN12H.PRECIO_CALCULADO, TO_DATE(TEN12H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) INTERS_12H,
	ROUND(REGR_INTERCEPT(TEN1D.PRECIO_CALCULADO, TO_DATE(TEN1D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) INTERS_1D,
	ROUND(REGR_INTERCEPT(TEN2D.PRECIO_CALCULADO, TO_DATE(TEN2D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) INTERS_2D,
	ROUND(REGR_INTERCEPT(TEN5D.PRECIO_CALCULADO, TO_DATE(TEN5D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) INTERS_5D,
	
	ROUND(REGR_R2(TEN6H.PRECIO_CALCULADO, TO_DATE(TEN6H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) R2_6H,
	ROUND(REGR_R2(TEN12H.PRECIO_CALCULADO, TO_DATE(TEN12H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) R2_12H,
	ROUND(REGR_R2(TEN1D.PRECIO_CALCULADO, TO_DATE(TEN1D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) R2_1D,
	ROUND(REGR_R2(TEN2D.PRECIO_CALCULADO, TO_DATE(TEN2D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) R2_2D,
	ROUND(REGR_R2(TEN5D.PRECIO_CALCULADO, TO_DATE(TEN5D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) R2_5D
FROM BASE, TIEMPO_TENDENCIA TT, TENDENCIA_5D TEN5D
	LEFT JOIN TENDENCIA_6H TEN6H ON TEN5D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_12H TEN12H ON TEN5D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_1D TEN1D ON TEN5D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_2D TEN2D ON TEN5D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
ORDER BY TO_DATE(TEN5D.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
;

WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
		0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
		TO_DATE('2017/02/02 13:21', 'YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170125' TIPO_TENDENCIA1, 'BUY_SELL_20170201' TIPO_TENDENCIA2, 'xxBUY_SELL_20170131-2' TIPO_TENDENCIA3
		FROM DUAL),
	BASE AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE, 1.30200 PRECIO_ACTUAL
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA),
	TENDENCIA_6H AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY/MM/DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY/MM/DD HH24'))
SELECT REGR_SLOPE(TEN6H.PRECIO_CALCULADO, TO_DATE(TEN6H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA)
FROM BASE, TIEMPO_TENDENCIA TT, TENDENCIA_6H TEN6H
ORDER BY TO_DATE(TEN6H.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
;

WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
		0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
		TO_DATE('2017/02/02 13:21', 'YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170125' TIPO_TENDENCIA1, 'BUY_SELL_20170201' TIPO_TENDENCIA2, 'xxBUY_SELL_20170131-2' TIPO_TENDENCIA3
		FROM DUAL),
	BASE AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE, 1.30200 PRECIO_ACTUAL
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA),
	TENDENCIA_5D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
SELECT ROUND(REGR_SLOPE(TEN5D.PRECIO_CALCULADO, TO_DATE(TEN5D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5)
FROM BASE, TIEMPO_TENDENCIA TT, TENDENCIA_5D TEN5D
ORDER BY TO_DATE(TEN5D.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
;

WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
		0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
		TO_DATE('2017/02/02 13:21', 'YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170125' TIPO_TENDENCIA1, 'BUY_SELL_20170201' TIPO_TENDENCIA2, 'xxBUY_SELL_20170131-2' TIPO_TENDENCIA3
		FROM DUAL),
	BASE AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE, 1.30200 PRECIO_ACTUAL
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA),
	TENDENCIA_5D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
SELECT TT.FECHA, TO_DATE(TEN5D.FECHA_TENDENCIA, 'YYYY.MM.DD HH24:MI'), 
	ROUND((TO_DATE(TEN5D.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) DIFF,
	TEN5D.PRECIO_CALCULADO
FROM BASE, TIEMPO_TENDENCIA TT, TENDENCIA_5D TEN5D
ORDER BY TO_DATE(TEN5D.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
;

WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
		0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
		TO_DATE('2017/02/02 13:21', 'YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170125' TIPO_TENDENCIA1, 'BUY_SELL_20170201' TIPO_TENDENCIA2, 'xxBUY_SELL_20170131-2' TIPO_TENDENCIA3
		FROM DUAL),
	BASE AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE, 1.30200 PRECIO_ACTUAL
					FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA),	
	TENDENCIA_12H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
SELECT ROUND(REGR_SLOPE(TEN12H.PRECIO_CALCULADO, TO_DATE(TEN12H.FECHA_TENDENCIA,'YYYY/MM/DD HH24:MI')-TT.FECHA),5) PENDIENTE_12H
FROM BASE, TIEMPO_TENDENCIA TT, TENDENCIA_12H TEN12H
ORDER BY TO_DATE(TEN12H.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
;
