  SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYYMMDD') DIA, 
    TRUNC(MIN(FECHA_APERTURA)) MIN_FECHA,
    COUNT(*) NUM_OPERACIONES, SUM(PIPS) PIPS
   FROM FOREX.OPERACION OPER
  WHERE FECHA_CIERRE IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO=OPER.ID_INDIVIDUO
    )
  --AND ID_INDIVIDUO='1327698225613.250'
  HAVING SUM(PIPS)>0
  GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYYMMDD')
  --ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYYWW') ASC
;

  SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY WW') SEMANA, 
    TRUNC(MIN(FECHA_APERTURA)) MIN_FECHA,
    COUNT(*) NUM_OPERACIONES, SUM(PIPS) PIPS
   FROM FOREX.OPERACION OPER
  WHERE FECHA_CIERRE IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO=OPER.ID_INDIVIDUO
    )  
    --AND ID_INDIVIDUO='1327698225613.250'
--  HAVING SUM(PIPS)>0
  GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY WW')
  ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYY WW') ASC
;

  SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYYMM') MES, 
    TRUNC(MIN(FECHA_APERTURA)) MIN_FECHA,
    COUNT(*) NUM_OPERACIONES, SUM(PIPS) PIPS
   FROM FOREX.OPERACION OPER
  WHERE FECHA_CIERRE IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM INDICADOR_INDIVIDUO II WHERE II.ID_INDIVIDUO=OPER.ID_INDIVIDUO
    )  
--  HAVING SUM(PIPS)>0
  GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYYMM')
  --ORDER BY TO_CHAR(FECHA_APERTURA, 'YYYYWW') ASC
;
