
SELECT 
IND.ID, DH1_OPEN.FECHA OPEN_FECHA, DH1_CLOSE.FECHA CLOSE_FECHA
/*, (PROCESS_OPEN(II_OPEN_MA.INTERVALO_INFERIOR, II_OPEN_MA.INTERVALO_SUPERIOR, DH1_OPEN.AVERAGE,(DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4)) MA
, (PROCESS_OPEN(II_OPEN_MACD.INTERVALO_INFERIOR, II_OPEN_MACD.INTERVALO_SUPERIOR, DH1_OPEN.MACD_VALUE, DH1_OPEN.MACD_SIGNAL)) MACD
, (PROCESS_OPEN(II_OPEN_COMPARE.INTERVALO_INFERIOR, II_OPEN_COMPARE.INTERVALO_SUPERIOR, DH1_OPEN.COMPARE_VALUE, DH1_OPEN.AVERAGE_COMPARE)) COMPARE
, (PROCESS_OPEN(II_OPEN_SAR.INTERVALO_INFERIOR, II_OPEN_SAR.INTERVALO_SUPERIOR, DH1_OPEN.SAR,(DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4)) SAR
, (PROCESS_OPEN(II_OPEN_ADX.INTERVALO_INFERIOR, II_OPEN_ADX.INTERVALO_SUPERIOR, DH1_OPEN.ADX_VALUE*DH1_OPEN.ADX_PLUS, DH1_OPEN.ADX_VALUE*DH1_OPEN.ADX_MINUS)) ADX
, (PROCESS_OPEN(II_OPEN_RSI.INTERVALO_INFERIOR, II_OPEN_RSI.INTERVALO_SUPERIOR, DH1_OPEN.RSI, DH1_OPEN.RSI)) RSI
, (PROCESS_OPEN(II_OPEN_BOLLINGER.INTERVALO_INFERIOR, II_OPEN_BOLLINGER.INTERVALO_SUPERIOR, DH1_OPEN.BOLLINGER_UPPER, DH1_OPEN.BOLLINGER_LOWER)) BOLLINGER
, (PROCESS_OPEN(II_OPEN_MOMENTUM.INTERVALO_INFERIOR, II_OPEN_MOMENTUM.INTERVALO_SUPERIOR, DH1_OPEN.MOMENTUM, 0)) MOMENTUM
, (PROCESS_OPEN(II_OPEN_ICHITREND.INTERVALO_INFERIOR, II_OPEN_ICHITREND.INTERVALO_SUPERIOR, DH1_OPEN.ICHIMOKUSENKOUSPANA-DH1_OPEN.ICHIMOKUSENKOUSPANB,(DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4)) ICHITREND
, (PROCESS_OPEN(II_OPEN_ICHISIGNAL.INTERVALO_INFERIOR, II_OPEN_ICHISIGNAL.INTERVALO_SUPERIOR, DH1_OPEN.ICHIMOKUCHINKOUSPAN*DH1_OPEN.ICHIMOKUTENKANSEN, DH1_OPEN.ICHIMOKUCHINKOUSPAN*DH1_OPEN.ICHIMOKUKIJUNSEN)) ICHISIGNAL
*/, DH1_CLOSE.FECHA CLOSE_FECHA, (SELECT MAX(FECHA) FROM DATOHISTORICO) MAX_FECHA
, ((DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4) OPENVALUE
, ((DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4) CLOSEVALUE
, DH1_OPEN.SPREAD
, CALCULAR_PIPS(DH1_OPEN.OPEN,DH1_OPEN.CLOSE,DH1_OPEN.HIGH,DH1_OPEN.LOW, DH1_CLOSE.OPEN,DH1_CLOSE.CLOSE,DH1_CLOSE.HIGH,DH1_CLOSE.LOW,DH1_OPEN.SPREAD) PIPS
,  (PROCESS_CLOSE(II_CLOSE_MA.INTERVALO_INFERIOR, II_CLOSE_MA.INTERVALO_SUPERIOR, DH1_CLOSE.AVERAGE, (DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4)) MA_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_MACD.INTERVALO_INFERIOR, II_CLOSE_MACD.INTERVALO_SUPERIOR, DH1_CLOSE.MACD_VALUE, DH1_CLOSE.MACD_SIGNAL)) MACD_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_COMPARE.INTERVALO_INFERIOR, II_CLOSE_COMPARE.INTERVALO_SUPERIOR, DH1_CLOSE.COMPARE_VALUE, DH1_CLOSE.AVERAGE_COMPARE)) COMPARE_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_SAR.INTERVALO_INFERIOR, II_CLOSE_SAR.INTERVALO_SUPERIOR, DH1_CLOSE.SAR, (DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4)) SAR_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_ADX.INTERVALO_INFERIOR, II_CLOSE_ADX.INTERVALO_SUPERIOR, DH1_CLOSE.ADX_VALUE*DH1_CLOSE.ADX_PLUS, DH1_CLOSE.ADX_VALUE*DH1_CLOSE.ADX_MINUS)) ADX_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_RSI.INTERVALO_INFERIOR, II_CLOSE_RSI.INTERVALO_SUPERIOR, DH1_CLOSE.RSI, 0)) RSI_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_BOLLINGER.INTERVALO_INFERIOR, II_CLOSE_BOLLINGER.INTERVALO_SUPERIOR, DH1_CLOSE.BOLLINGER_UPPER, DH1_CLOSE.BOLLINGER_LOWER)) BOLL_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_MOMENTUM.INTERVALO_INFERIOR, II_CLOSE_MOMENTUM.INTERVALO_SUPERIOR, DH1_CLOSE.MOMENTUM, 0)) MOM_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_ICHITREND.INTERVALO_INFERIOR, II_CLOSE_ICHITREND.INTERVALO_SUPERIOR, DH1_CLOSE.ICHIMOKUSENKOUSPANA-DH1_CLOSE.ICHIMOKUSENKOUSPANB, (DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4))  ICHITREND_CLOSE
  , (PROCESS_CLOSE(II_CLOSE_ICHISIGNAL.INTERVALO_INFERIOR, II_CLOSE_ICHISIGNAL.INTERVALO_SUPERIOR, DH1_CLOSE.ICHIMOKUCHINKOUSPAN*DH1_CLOSE.ICHIMOKUTENKANSEN, DH1_CLOSE.ICHIMOKUCHINKOUSPAN*DH1_CLOSE.ICHIMOKUKIJUNSEN)) ICHISIGNAL_CLOSE

FROM DATOHISTORICO DH1_OPEN, DATOHISTORICO DH1_CLOSE, INDIVIDUO IND, 
  INDICADOR_INDIVIDUO II_OPEN_MA, INDICADOR_INDIVIDUO II_CLOSE_MA,
  INDICADOR_INDIVIDUO II_OPEN_MACD, INDICADOR_INDIVIDUO II_CLOSE_MACD,
  INDICADOR_INDIVIDUO II_OPEN_COMPARE, INDICADOR_INDIVIDUO II_CLOSE_COMPARE,
  INDICADOR_INDIVIDUO II_OPEN_SAR, INDICADOR_INDIVIDUO II_CLOSE_SAR,
  INDICADOR_INDIVIDUO II_OPEN_ADX, INDICADOR_INDIVIDUO II_CLOSE_ADX,
  INDICADOR_INDIVIDUO II_OPEN_RSI, INDICADOR_INDIVIDUO II_CLOSE_RSI,
  INDICADOR_INDIVIDUO II_OPEN_BOLLINGER, INDICADOR_INDIVIDUO II_CLOSE_BOLLINGER,
  INDICADOR_INDIVIDUO II_OPEN_MOMENTUM, INDICADOR_INDIVIDUO II_CLOSE_MOMENTUM,
  INDICADOR_INDIVIDUO II_OPEN_ICHITREND, INDICADOR_INDIVIDUO II_CLOSE_ICHITREND,
  INDICADOR_INDIVIDUO II_OPEN_ICHISIGNAL, INDICADOR_INDIVIDUO II_CLOSE_ICHISIGNAL
  
WHERE IND.ID=II_OPEN_MA.ID_INDIVIDUO AND IND.ID=II_CLOSE_MA.ID_INDIVIDUO 
AND IND.ID=II_OPEN_MACD.ID_INDIVIDUO AND IND.ID=II_CLOSE_MACD.ID_INDIVIDUO
AND IND.ID=II_OPEN_COMPARE.ID_INDIVIDUO AND IND.ID=II_CLOSE_COMPARE.ID_INDIVIDUO
AND IND.ID=II_OPEN_SAR.ID_INDIVIDUO AND IND.ID=II_CLOSE_SAR.ID_INDIVIDUO
AND IND.ID=II_OPEN_ADX.ID_INDIVIDUO AND IND.ID=II_CLOSE_ADX.ID_INDIVIDUO
AND IND.ID=II_OPEN_RSI.ID_INDIVIDUO AND IND.ID=II_CLOSE_RSI.ID_INDIVIDUO
AND IND.ID=II_OPEN_BOLLINGER.ID_INDIVIDUO AND IND.ID=II_CLOSE_BOLLINGER.ID_INDIVIDUO
AND IND.ID=II_OPEN_MOMENTUM.ID_INDIVIDUO AND IND.ID=II_CLOSE_MOMENTUM.ID_INDIVIDUO
AND IND.ID=II_OPEN_ICHITREND.ID_INDIVIDUO AND IND.ID=II_CLOSE_ICHITREND.ID_INDIVIDUO
AND IND.ID=II_OPEN_ICHISIGNAL.ID_INDIVIDUO AND IND.ID=II_CLOSE_ICHISIGNAL.ID_INDIVIDUO

AND II_OPEN_MA.TIPO='OPEN' AND II_OPEN_MA.ID_INDICADOR='MA' 
AND II_OPEN_MACD.TIPO='OPEN' AND II_OPEN_MACD.ID_INDICADOR='MACD' 
AND II_OPEN_COMPARE.TIPO='OPEN' AND II_OPEN_COMPARE.ID_INDICADOR='COMPARE_MA' 
AND II_OPEN_SAR.TIPO='OPEN' AND II_OPEN_SAR.ID_INDICADOR='SAR' 
AND II_OPEN_ADX.TIPO='OPEN' AND II_OPEN_ADX.ID_INDICADOR='ADX' 
AND II_OPEN_RSI.TIPO='OPEN' AND II_OPEN_RSI.ID_INDICADOR='RSI' 
AND II_OPEN_BOLLINGER.TIPO='OPEN' AND II_OPEN_BOLLINGER.ID_INDICADOR='BOLLINGER' 
AND II_OPEN_MOMENTUM.TIPO='OPEN' AND II_OPEN_MOMENTUM.ID_INDICADOR='MOMENTUM' 
AND II_OPEN_ICHITREND.TIPO='OPEN' AND II_OPEN_ICHITREND.ID_INDICADOR='ICHIMOKU_TREND' 
AND II_OPEN_ICHISIGNAL.TIPO='OPEN' AND II_OPEN_ICHISIGNAL.ID_INDICADOR='ICHIMOKU_SIGNAL' 

AND II_CLOSE_MA.TIPO='CLOSE' AND II_CLOSE_MA.ID_INDICADOR='MA' 
AND II_CLOSE_MACD.TIPO='CLOSE' AND II_CLOSE_MACD.ID_INDICADOR='MACD'
AND II_CLOSE_COMPARE.TIPO='CLOSE' AND II_CLOSE_COMPARE.ID_INDICADOR='COMPARE_MA'
AND II_CLOSE_SAR.TIPO='CLOSE' AND II_CLOSE_SAR.ID_INDICADOR='SAR' 
AND II_CLOSE_ADX.TIPO='CLOSE' AND II_CLOSE_ADX.ID_INDICADOR='ADX' 
AND II_CLOSE_RSI.TIPO='CLOSE' AND II_CLOSE_RSI.ID_INDICADOR='RSI' 
AND II_CLOSE_BOLLINGER.TIPO='CLOSE' AND II_CLOSE_BOLLINGER.ID_INDICADOR='BOLLINGER' 
AND II_CLOSE_MOMENTUM.TIPO='CLOSE' AND II_CLOSE_MOMENTUM.ID_INDICADOR='MOMENTUM' 
AND II_CLOSE_ICHITREND.TIPO='CLOSE' AND II_CLOSE_ICHITREND.ID_INDICADOR='ICHIMOKU_TREND' 
AND II_CLOSE_ICHISIGNAL.TIPO='CLOSE' AND II_CLOSE_ICHISIGNAL.ID_INDICADOR='ICHIMOKU_SIGNAL' 

AND (PROCESS_OPEN(II_OPEN_MA.INTERVALO_INFERIOR, II_OPEN_MA.INTERVALO_SUPERIOR, DH1_OPEN.AVERAGE,(DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4)>0)
AND (PROCESS_OPEN(II_OPEN_MACD.INTERVALO_INFERIOR, II_OPEN_MACD.INTERVALO_SUPERIOR, DH1_OPEN.MACD_VALUE, DH1_OPEN.MACD_SIGNAL)>0)
AND (PROCESS_OPEN(II_OPEN_COMPARE.INTERVALO_INFERIOR, II_OPEN_COMPARE.INTERVALO_SUPERIOR, DH1_OPEN.COMPARE_VALUE, DH1_OPEN.AVERAGE_COMPARE)>0)
AND (PROCESS_OPEN(II_OPEN_SAR.INTERVALO_INFERIOR, II_OPEN_SAR.INTERVALO_SUPERIOR, DH1_OPEN.SAR,(DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4)>0)
AND (PROCESS_OPEN(II_OPEN_ADX.INTERVALO_INFERIOR, II_OPEN_ADX.INTERVALO_SUPERIOR, DH1_OPEN.ADX_VALUE*DH1_OPEN.ADX_PLUS, DH1_OPEN.ADX_VALUE*DH1_OPEN.ADX_MINUS)>0)
AND (PROCESS_OPEN(II_OPEN_RSI.INTERVALO_INFERIOR, II_OPEN_RSI.INTERVALO_SUPERIOR, DH1_OPEN.RSI, DH1_OPEN.RSI)>0)
AND (PROCESS_OPEN(II_OPEN_BOLLINGER.INTERVALO_INFERIOR, II_OPEN_BOLLINGER.INTERVALO_SUPERIOR, DH1_OPEN.BOLLINGER_UPPER, DH1_OPEN.BOLLINGER_LOWER)>0)
AND (PROCESS_OPEN(II_OPEN_MOMENTUM.INTERVALO_INFERIOR, II_OPEN_MOMENTUM.INTERVALO_SUPERIOR, DH1_OPEN.MOMENTUM, 0)>0)
AND (PROCESS_OPEN(II_OPEN_ICHITREND.INTERVALO_INFERIOR, II_OPEN_ICHITREND.INTERVALO_SUPERIOR, DH1_OPEN.ICHIMOKUSENKOUSPANA-DH1_OPEN.ICHIMOKUSENKOUSPANB,(DH1_OPEN.OPEN+DH1_OPEN.CLOSE+DH1_OPEN.HIGH+DH1_OPEN.LOW)/4)>0)
AND (PROCESS_OPEN(II_OPEN_ICHISIGNAL.INTERVALO_INFERIOR, II_OPEN_ICHISIGNAL.INTERVALO_SUPERIOR, DH1_OPEN.ICHIMOKUCHINKOUSPAN*DH1_OPEN.ICHIMOKUTENKANSEN, DH1_OPEN.ICHIMOKUCHINKOUSPAN*DH1_OPEN.ICHIMOKUKIJUNSEN)>0)

AND ((DH1_CLOSE.FECHA = (SELECT MAX(FECHA) FROM DATOHISTORICO))
  OR (PROCESS_CLOSE_PIPS(CALCULAR_PIPS(DH1_OPEN.OPEN,DH1_OPEN.CLOSE,DH1_OPEN.HIGH,DH1_OPEN.LOW, DH1_CLOSE.OPEN,DH1_CLOSE.CLOSE,DH1_CLOSE.HIGH,DH1_CLOSE.LOW,DH1_OPEN.SPREAD),
    IND.TAKE_PROFIT, IND.STOP_LOSS)>0)
  OR(
  (PROCESS_CLOSE(II_CLOSE_MA.INTERVALO_INFERIOR, II_CLOSE_MA.INTERVALO_SUPERIOR, DH1_CLOSE.AVERAGE, (DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_MACD.INTERVALO_INFERIOR, II_CLOSE_MACD.INTERVALO_SUPERIOR, DH1_CLOSE.MACD_VALUE, DH1_CLOSE.MACD_SIGNAL)>0)
  AND (PROCESS_CLOSE(II_CLOSE_COMPARE.INTERVALO_INFERIOR, II_CLOSE_COMPARE.INTERVALO_SUPERIOR, DH1_CLOSE.COMPARE_VALUE, DH1_CLOSE.AVERAGE_COMPARE)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_SAR.INTERVALO_INFERIOR, II_CLOSE_SAR.INTERVALO_SUPERIOR, DH1_CLOSE.SAR, (DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4)>0)
  AND (PROCESS_CLOSE(II_CLOSE_ADX.INTERVALO_INFERIOR, II_CLOSE_ADX.INTERVALO_SUPERIOR, DH1_CLOSE.ADX_VALUE*DH1_CLOSE.ADX_PLUS, DH1_CLOSE.ADX_VALUE*DH1_CLOSE.ADX_MINUS)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_RSI.INTERVALO_INFERIOR, II_CLOSE_RSI.INTERVALO_SUPERIOR, DH1_CLOSE.RSI, 0)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_BOLLINGER.INTERVALO_INFERIOR, II_CLOSE_BOLLINGER.INTERVALO_SUPERIOR, DH1_CLOSE.BOLLINGER_UPPER, DH1_CLOSE.BOLLINGER_LOWER)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_MOMENTUM.INTERVALO_INFERIOR, II_CLOSE_MOMENTUM.INTERVALO_SUPERIOR, DH1_CLOSE.MOMENTUM, 0)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_ICHITREND.INTERVALO_INFERIOR, II_CLOSE_ICHITREND.INTERVALO_SUPERIOR, DH1_CLOSE.ICHIMOKUSENKOUSPANA-DH1_CLOSE.ICHIMOKUSENKOUSPANB, (DH1_CLOSE.OPEN+DH1_CLOSE.CLOSE+DH1_CLOSE.HIGH+DH1_CLOSE.LOW)/4)>0)  
  AND (PROCESS_CLOSE(II_CLOSE_ICHISIGNAL.INTERVALO_INFERIOR, II_CLOSE_ICHISIGNAL.INTERVALO_SUPERIOR, DH1_CLOSE.ICHIMOKUCHINKOUSPAN*DH1_CLOSE.ICHIMOKUTENKANSEN, DH1_CLOSE.ICHIMOKUCHINKOUSPAN*DH1_CLOSE.ICHIMOKUKIJUNSEN)>0)
  ))

AND DH1_CLOSE.FECHA > DH1_OPEN.FECHA
AND (DH1_OPEN.FECHA < (SELECT MAX(FECHA) FROM DATOHISTORICO))
AND DH1_OPEN.FECHA = TO_DATE('2009/01/02 06:10', 'YYYY/MM/DD HH24:MI')
AND DH1_CLOSE.FECHA = TO_DATE('2009/01/02 08:44', 'YYYY/MM/DD HH24:MI')
--AND ROWNUM < 2
AND IND.ID='1329420847661.3064'
--GROUP BY IND.ID, DH1_OPEN.FECHA
ORDER BY DH1_OPEN.FECHA ASC;

