CREATE VIEW OPERACIONES_COMPLETAS AS
  SELECT OPER.ID_INDIVIDUO, IND.TAKE_PROFIT, IND.STOP_LOSS, 
      OBTENER_FECHA_OPERACION(OPER.FECHA_APERTURA) FECHA_APERTURA, 
      OBTENER_FECHA_OPERACION(OPER.FECHA_CIERRE) FECHA_CIERRE
    ,OBTENER_SPREAD(OPER.FECHA_APERTURA) SPREAD
    ,CALCULAR_OPEN_PRICE(INTERVALO(II_OPEN_MA.INTERVALO_INFERIOR, II_OPEN_MA.INTERVALO_SUPERIOR)
      ,INTERVALO(II_OPEN_SAR.INTERVALO_INFERIOR, II_OPEN_SAR.INTERVALO_SUPERIOR)
      ,INTERVALO(II_OPEN_ICHITREND.INTERVALO_INFERIOR, II_OPEN_ICHITREND.INTERVALO_SUPERIOR)
      ,DH1_OPEN.AVERAGE, DH1_OPEN.SAR, DH1_OPEN.ICHIMOKUSENKOUSPANA-DH1_OPEN.ICHIMOKUSENKOUSPANB, DH1_OPEN.FECHA) OPEN_PRICE
    ,OBTENER_PIPS(CALCULAR_PIPS(
      CALCULAR_OPEN_PRICE(INTERVALO(II_OPEN_MA.INTERVALO_INFERIOR, II_OPEN_MA.INTERVALO_SUPERIOR)
        ,INTERVALO(II_OPEN_SAR.INTERVALO_INFERIOR, II_OPEN_SAR.INTERVALO_SUPERIOR)
        ,INTERVALO(II_OPEN_ICHITREND.INTERVALO_INFERIOR, II_OPEN_ICHITREND.INTERVALO_SUPERIOR)
        ,DH1_OPEN.AVERAGE, DH1_OPEN.SAR, DH1_OPEN.ICHIMOKUSENKOUSPANA-DH1_OPEN.ICHIMOKUSENKOUSPANB, DH1_OPEN.FECHA),
      CALCULAR_CLOSE_PRICE(INTERVALO(II_CLOSE_MA.INTERVALO_INFERIOR, II_CLOSE_MA.INTERVALO_SUPERIOR)
        ,INTERVALO(II_CLOSE_SAR.INTERVALO_INFERIOR, II_CLOSE_SAR.INTERVALO_SUPERIOR)
        ,INTERVALO(II_CLOSE_ICHITREND.INTERVALO_INFERIOR, II_CLOSE_ICHITREND.INTERVALO_SUPERIOR)
        ,DH1_CLOSE.AVERAGE, DH1_CLOSE.SAR, DH1_CLOSE.ICHIMOKUSENKOUSPANA-DH1_CLOSE.ICHIMOKUSENKOUSPANB, DH1_CLOSE.FECHA),
      OBTENER_SPREAD(DH1_OPEN.FECHA))
    ,CALCULAR_PIPS(CALCULAR_OPEN_PRICE(INTERVALO(II_OPEN_MA.INTERVALO_INFERIOR, II_OPEN_MA.INTERVALO_SUPERIOR)
          ,INTERVALO(II_OPEN_SAR.INTERVALO_INFERIOR, II_OPEN_SAR.INTERVALO_SUPERIOR)
          ,INTERVALO(II_OPEN_ICHITREND.INTERVALO_INFERIOR, II_OPEN_ICHITREND.INTERVALO_SUPERIOR)
          ,DH1_OPEN.AVERAGE, DH1_OPEN.SAR, DH1_OPEN.ICHIMOKUSENKOUSPANA-DH1_OPEN.ICHIMOKUSENKOUSPANB, DH1_OPEN.FECHA),
        CALCULAR_CLOSE_PRICE_TP(DH1_CLOSE.FECHA),
        OBTENER_SPREAD(DH1_OPEN.FECHA))
    ,CALCULAR_PIPS(CALCULAR_OPEN_PRICE(INTERVALO(II_OPEN_MA.INTERVALO_INFERIOR, II_OPEN_MA.INTERVALO_SUPERIOR)
          ,INTERVALO(II_OPEN_SAR.INTERVALO_INFERIOR, II_OPEN_SAR.INTERVALO_SUPERIOR)
          ,INTERVALO(II_OPEN_ICHITREND.INTERVALO_INFERIOR, II_OPEN_ICHITREND.INTERVALO_SUPERIOR)
          ,DH1_OPEN.AVERAGE, DH1_OPEN.SAR, DH1_OPEN.ICHIMOKUSENKOUSPANA-DH1_OPEN.ICHIMOKUSENKOUSPANB, DH1_OPEN.FECHA),
        CALCULAR_CLOSE_PRICE_SL(DH1_CLOSE.FECHA),
        OBTENER_SPREAD(DH1_OPEN.FECHA)), IND.TAKE_PROFIT, IND.STOP_LOSS) PIPS
      FROM DATOHISTORICO DH1_OPEN, DATOHISTORICO DH1_CLOSE, INDIVIDUO IND, OPERACIONES OPER,
        INDICADOR_INDIVIDUO II_OPEN_MA, INDICADOR_INDIVIDUO II_CLOSE_MA,
        INDICADOR_INDIVIDUO II_OPEN_MACD, INDICADOR_INDIVIDUO II_CLOSE_MACD,
        INDICADOR_INDIVIDUO II_OPEN_COMPARE, INDICADOR_INDIVIDUO II_CLOSE_COMPARE,
        INDICADOR_INDIVIDUO II_OPEN_SAR, INDICADOR_INDIVIDUO II_CLOSE_SAR,
        INDICADOR_INDIVIDUO II_OPEN_ADX, INDICADOR_INDIVIDUO II_CLOSE_ADX,
        INDICADOR_INDIVIDUO II_OPEN_RSI, INDICADOR_INDIVIDUO II_CLOSE_RSI,
        INDICADOR_INDIVIDUO II_OPEN_BOLLINGER, INDICADOR_INDIVIDUO II_CLOSE_BOLLINGER,
        INDICADOR_INDIVIDUO II_OPEN_MOMENTUM, INDICADOR_INDIVIDUO II_CLOSE_MOMENTUM,
        INDICADOR_INDIVIDUO II_OPEN_ICHITREND, INDICADOR_INDIVIDUO II_CLOSE_ICHITREND,
        INDICADOR_INDIVIDUO II_OPEN_ICHISIGNAL, INDICADOR_INDIVIDUO II_CLOSE_ICHISIGNAL
        
      WHERE IND.ID=II_OPEN_MA.ID_INDIVIDUO AND IND.ID=II_CLOSE_MA.ID_INDIVIDUO 
      AND IND.ID=II_OPEN_MACD.ID_INDIVIDUO AND IND.ID=II_CLOSE_MACD.ID_INDIVIDUO
      AND IND.ID=II_OPEN_COMPARE.ID_INDIVIDUO AND IND.ID=II_CLOSE_COMPARE.ID_INDIVIDUO
      AND IND.ID=II_OPEN_SAR.ID_INDIVIDUO AND IND.ID=II_CLOSE_SAR.ID_INDIVIDUO
      AND IND.ID=II_OPEN_ADX.ID_INDIVIDUO AND IND.ID=II_CLOSE_ADX.ID_INDIVIDUO
      AND IND.ID=II_OPEN_RSI.ID_INDIVIDUO AND IND.ID=II_CLOSE_RSI.ID_INDIVIDUO
      AND IND.ID=II_OPEN_BOLLINGER.ID_INDIVIDUO AND IND.ID=II_CLOSE_BOLLINGER.ID_INDIVIDUO
      AND IND.ID=II_OPEN_MOMENTUM.ID_INDIVIDUO AND IND.ID=II_CLOSE_MOMENTUM.ID_INDIVIDUO
      AND IND.ID=II_OPEN_ICHITREND.ID_INDIVIDUO AND IND.ID=II_CLOSE_ICHITREND.ID_INDIVIDUO
      AND IND.ID=II_OPEN_ICHISIGNAL.ID_INDIVIDUO AND IND.ID=II_CLOSE_ICHISIGNAL.ID_INDIVIDUO
      
      AND II_OPEN_MA.TIPO='OPEN' AND II_OPEN_MA.ID_INDICADOR='MA' 
      AND II_OPEN_MACD.TIPO='OPEN' AND II_OPEN_MACD.ID_INDICADOR='MACD' 
      AND II_OPEN_COMPARE.TIPO='OPEN' AND II_OPEN_COMPARE.ID_INDICADOR='COMPARE_MA' 
      AND II_OPEN_SAR.TIPO='OPEN' AND II_OPEN_SAR.ID_INDICADOR='SAR' 
      AND II_OPEN_ADX.TIPO='OPEN' AND II_OPEN_ADX.ID_INDICADOR='ADX' 
      AND II_OPEN_RSI.TIPO='OPEN' AND II_OPEN_RSI.ID_INDICADOR='RSI' 
      AND II_OPEN_BOLLINGER.TIPO='OPEN' AND II_OPEN_BOLLINGER.ID_INDICADOR='BOLLINGER' 
      AND II_OPEN_MOMENTUM.TIPO='OPEN' AND II_OPEN_MOMENTUM.ID_INDICADOR='MOMENTUM' 
      AND II_OPEN_ICHITREND.TIPO='OPEN' AND II_OPEN_ICHITREND.ID_INDICADOR='ICHIMOKU_TREND' 
      AND II_OPEN_ICHISIGNAL.TIPO='OPEN' AND II_OPEN_ICHISIGNAL.ID_INDICADOR='ICHIMOKU_SIGNAL' 
      
      AND II_CLOSE_MA.TIPO='CLOSE' AND II_CLOSE_MA.ID_INDICADOR='MA' 
      AND II_CLOSE_MACD.TIPO='CLOSE' AND II_CLOSE_MACD.ID_INDICADOR='MACD'
      AND II_CLOSE_COMPARE.TIPO='CLOSE' AND II_CLOSE_COMPARE.ID_INDICADOR='COMPARE_MA'
      AND II_CLOSE_SAR.TIPO='CLOSE' AND II_CLOSE_SAR.ID_INDICADOR='SAR' 
      AND II_CLOSE_ADX.TIPO='CLOSE' AND II_CLOSE_ADX.ID_INDICADOR='ADX' 
      AND II_CLOSE_RSI.TIPO='CLOSE' AND II_CLOSE_RSI.ID_INDICADOR='RSI' 
      AND II_CLOSE_BOLLINGER.TIPO='CLOSE' AND II_CLOSE_BOLLINGER.ID_INDICADOR='BOLLINGER' 
      AND II_CLOSE_MOMENTUM.TIPO='CLOSE' AND II_CLOSE_MOMENTUM.ID_INDICADOR='MOMENTUM' 
      AND II_CLOSE_ICHITREND.TIPO='CLOSE' AND II_CLOSE_ICHITREND.ID_INDICADOR='ICHIMOKU_TREND' 
      AND II_CLOSE_ICHISIGNAL.TIPO='CLOSE' AND II_CLOSE_ICHISIGNAL.ID_INDICADOR='ICHIMOKU_SIGNAL'
      
      AND IND.ID=OPER.ID_INDIVIDUO 
      AND OPER.FECHA_APERTURA=DH1_OPEN.FECHA
      AND OPER.FECHA_CIERRE=DH1_CLOSE.FECHA;
