WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, '2016/11/11 23:59' FECHA FROM DUAL),
	TENDENCIA_6H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_12H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_1D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_2D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_5D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
				--AND TEN.FECHA_BASE<TEN.FECHA_TENDENCIA-1/24
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
SELECT TEN6H.FECHA_TENDENCIA, 
	TEN6H.PRECIO_CALCULADO PRECIO6H, TEN12H.PRECIO_CALCULADO PRECIO12H, 
	TEN1D.PRECIO_CALCULADO PRECIO1D, TEN2D.PRECIO_CALCULADO PRECIO2D, TEN5D.PRECIO_CALCULADO PRECIO5D, 
	TEN6H.PROBABILIDAD PROBABILIDAD6H, TEN12H.PROBABILIDAD PROBABILIDAD12H, 
	TEN1D.PROBABILIDAD PROBABILIDAD1D, TEN2D.PROBABILIDAD PROBABILIDAD2D, TEN5D.PROBABILIDAD PROBABILIDAD5D
FROM TENDENCIA_6H TEN6H
	INNER JOIN TENDENCIA_12H TEN12H ON TEN6H.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
	INNER JOIN TENDENCIA_1D TEN1D ON TEN6H.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
	INNER JOIN TENDENCIA_2D TEN2D ON TEN6H.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
	INNER JOIN TENDENCIA_5D TEN5D ON TEN6H.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA
;

WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, 
		0.3 PORC6H, 0.25 PORC12H, 0.2 PORC1D, 0.15 PORC2D, 0.1 PORC5D,
		'2016/11/11 23:59' FECHA 
		FROM DUAL),
	TENDENCIA_6H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_12H AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_1D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_2D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_5D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
				--AND TEN.FECHA_BASE<TEN.FECHA_TENDENCIA-1/24
				AND TEN.FECHA_BASE<=TO_DATE(TT.FECHA,'YYYY/MM/DD HH24:MI')
				AND TEN.FECHA_TENDENCIA>TT.FECHA
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))
SELECT TEN6H.FECHA_TENDENCIA, 
	ROUND((TEN6H.PRECIO_CALCULADO*TT.PORC6H+TEN12H.PRECIO_CALCULADO*TT.PORC12H+TEN1D.PRECIO_CALCULADO*TT.PORC1D
		+TEN2D.PRECIO_CALCULADO*TT.PORC2D+TEN5D.PRECIO_CALCULADO*TT.PORC5D),5) PRECIO_CALCULADO,
	TEN6H.PRECIO_CALCULADO PRECIO6H, TEN12H.PRECIO_CALCULADO PRECIO12H, 
	TEN1D.PRECIO_CALCULADO PRECIO1D, TEN2D.PRECIO_CALCULADO PRECIO2D, TEN5D.PRECIO_CALCULADO PRECIO5D, 
	TEN6H.PROBABILIDAD PROBABILIDAD6H, TEN12H.PROBABILIDAD PROBABILIDAD12H, 
	TEN1D.PROBABILIDAD PROBABILIDAD1D, TEN2D.PROBABILIDAD PROBABILIDAD2D, TEN5D.PROBABILIDAD PROBABILIDAD5D
FROM TIEMPO_TENDENCIA TT, TENDENCIA_6H TEN6H
	INNER JOIN TENDENCIA_12H TEN12H ON TEN6H.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
	INNER JOIN TENDENCIA_1D TEN1D ON TEN6H.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
	INNER JOIN TENDENCIA_2D TEN2D ON TEN6H.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
	INNER JOIN TENDENCIA_5D TEN5D ON TEN6H.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA
;
