SET feedback ON;
SET ECHO ON;
SPOOL ON;

TRUNCATE TABLE TMP_TOFILESTRING2;

INSERT INTO TMP_TOFILESTRING2 (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2)
  SELECT PTFS.ID_INDIVIDUO, 
	ROUND(((PTFS.PENDIENTE_SEMANA)+(PTFS.PENDIENTE_MES)+(PTFS.PENDIENTE_ANYO)+(PTFS.PENDIENTE_CONSOL))/4, 5),
	ROUND(((PTFS.R2_SEMANA)+(PTFS.R2_MES)+(PTFS.R2_ANYO)+(PTFS.R2_CONSOL))/4, 5),
  PTFS.FECHA_SEMANA, PTFS.FECHA_SEMANA+7
  FROM PREVIO_TOFILESTRING PTFS
	--INNER JOIN PROCESO P ON PTFS.ID_INDIVIDUO=P.ID_INDIVIDUO --AND P.FECHA_PROCESO>TRUNC(SYSDATE)
  WHERE PTFS.R_COUNT_CONSOL>50 
	--AND PTFS.PIPS_SEMANA>0 AND PTFS.PIPS_MES>0 AND PTFS.PIPS_ANYO>0 AND PTFS.PIPS_TOTALES>0
  AND PTFS.PIPS_SEMANA>0 AND PTFS.PIPS_MES>PTFS.PIPS_SEMANA AND PTFS.PIPS_ANYO>PTFS.PIPS_MES AND PTFS.PIPS_TOTALES>PTFS.PIPS_ANYO  
  --AND PTFS.PENDIENTE_CONSOL>0	AND PTFS.PENDIENTE_ANYO>PTFS.PENDIENTE_CONSOL AND PTFS.PENDIENTE_MES>PTFS.PENDIENTE_ANYO AND PTFS.PENDIENTE_SEMANA>PTFS.PENDIENTE_MES	
  --AND PTFS.PENDIENTE_CONSOL>0	--AND PTFS.PENDIENTE_ANYO>PTFS.PENDIENTE_CONSOL AND PTFS.PENDIENTE_MES>PTFS.PENDIENTE_ANYO AND PTFS.PENDIENTE_SEMANA>PTFS.PENDIENTE_MES	
  ;
commit;

@"d:ricardorq85\JavaProjects\Git\genetic-forex\ForexGenetic\sql\ToFileStringFromTEMP_TOFILESTRING.sql";
