--INSERT INTO OPERACION_X_SEMANA (ID_INDIVIDUO, FECHA_HISTORICO, PIPS, CANTIDAD, FECHA_SEMANA, R_COUNT, R2, PENDIENTE, INTERCEPCION) 
				 SELECT AC2.ID_INDIVIDUO, AC2.FECHA_HISTORICO,
				  AC2.PIPS PIPS, AC2.CANTIDAD, AC2.FECHA_SEMANA, AC2.R_COUNT, AC2.R2, AC2.PENDIENTE, AC2.INTERCEPCION
				 FROM (
				   SELECT AC.ID_INDIVIDUO, AC.FECHA_SEMANA, AC.FECHA_CIERRE, AC.PIPS, AC.CANTIDAD, 
				     AC.MAXFE, AC.FECHA_HISTORICO,
				     REGR_COUNT(AC.PIPS, AC.FECHA_CIERRE-AC.FECHA_HISTORICO) 
				       OVER (PARTITION BY TRUNC((AC.FECHA_CIERRE),'IW') ORDER BY AC.FECHA_CIERRE ASC) R_COUNT,
				     ROUND(REGR_R2((AC.PIPS), AC.FECHA_CIERRE-AC.FECHA_HISTORICO) 
				       OVER (PARTITION BY TRUNC((AC.FECHA_CIERRE),'IW') ORDER BY AC.FECHA_CIERRE ASC),5) R2,
				     ROUND(REGR_SLOPE(AC.PIPS, AC.FECHA_CIERRE-AC.FECHA_HISTORICO)
				       OVER (PARTITION BY TRUNC((AC.FECHA_CIERRE),'IW') ORDER BY AC.FECHA_CIERRE ASC),5) PENDIENTE,
				     ROUND(REGR_INTERCEPT(AC.PIPS, AC.FECHA_CIERRE-AC.FECHA_HISTORICO)
				       OVER (PARTITION BY TRUNC((AC.FECHA_CIERRE),'IW') ORDER BY AC.FECHA_CIERRE ASC),5) INTERCEPCION
				   FROM (SELECT OPER.ID_INDIVIDUO, TRUNC((OPER.FECHA_CIERRE),'IW') FECHA_SEMANA, OPER.FECHA_CIERRE, 
				      SUM(OPER.PIPS) OVER (PARTITION BY TRUNC((OPER.FECHA_CIERRE),'IW') ORDER BY OPER.FECHA_CIERRE) PIPS,
				       COUNT(OPER.PIPS) OVER (PARTITION BY TRUNC((OPER.FECHA_CIERRE),'IW') ORDER BY OPER.FECHA_CIERRE) CANTIDAD,
				       MAX(OPER.FECHA_CIERRE) OVER (PARTITION BY TRUNC((OPER.FECHA_CIERRE),'IW')) MAXFE,
				       P.FECHA_HISTORICO
				     FROM OPERACION OPER
				     INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
				     WHERE OPER.FECHA_CIERRE IS NOT NULL AND OPER.ID_INDIVIDUO='1469622989774.36'
             ORDER BY OPER.FECHA_CIERRE DESC
				   ) AC ORDER BY AC.FECHA_SEMANA DESC) AC2
				   INNER JOIN INDIVIDUO IND ON IND.ID=AC2.ID_INDIVIDUO AND IND.TIPO_INDIVIDUO = 'INDICADORES'
				   WHERE --NOT EXISTS (SELECT 1 FROM OPERACION_X_SEMANA OPC WHERE OPC.ID_INDIVIDUO=AC2.ID_INDIVIDUO)
				     --AND 
             AC2.MAXFE=AC2.FECHA_CIERRE
ORDER BY AC2.FECHA_SEMANA DESC;
