SELECT COUNT(*)
FROM DATOHISTORICO DH 
   INNER JOIN INDIVIDUO_INDICADORES IC ON IC.ID LIKE '1476485020741.34' 
       AND (IC.OPEN_INFERIOR_MA IS NULL OR IC.OPEN_SUPERIOR_MA IS NULL OR  
      ROUND(DH.AVERAGE-DH.LOW, 5) BETWEEN IC.OPEN_INFERIOR_MA AND IC.OPEN_SUPERIOR_MA OR ROUND(DH.AVERAGE-DH.HIGH,5) BETWEEN IC.OPEN_INFERIOR_MA AND IC.OPEN_SUPERIOR_MA)  
     AND (IC.OPEN_INFERIOR_MACD IS NULL OR IC.OPEN_SUPERIOR_MACD IS NULL OR ROUND(DH.MACD_VALUE-DH.MACD_SIGNAL, 5) BETWEEN IC.OPEN_INFERIOR_MACD AND IC.OPEN_SUPERIOR_MACD)  
     AND (IC.OPEN_INFERIOR_COMPARE IS NULL OR IC.OPEN_SUPERIOR_COMPARE IS NULL OR ROUND(DH.AVERAGE_COMPARE-DH.COMPARE_VALUE, 5) BETWEEN IC.OPEN_INFERIOR_COMPARE AND IC.OPEN_SUPERIOR_COMPARE)  
     AND (IC.OPEN_INFERIOR_ADX IS NULL OR IC.OPEN_SUPERIOR_ADX IS NULL OR ROUND(DH.ADX_VALUE*(DH.ADX_PLUS-DH.ADX_MINUS), 5) BETWEEN IC.OPEN_INFERIOR_ADX AND IC.OPEN_SUPERIOR_ADX)  
     AND (IC.OPEN_INFERIOR_SAR IS NULL OR IC.OPEN_SUPERIOR_SAR IS NULL OR ROUND(DH.SAR-DH.LOW, 5) BETWEEN IC.OPEN_INFERIOR_SAR AND IC.OPEN_SUPERIOR_SAR OR DH.SAR-DH.HIGH BETWEEN IC.OPEN_INFERIOR_SAR AND IC.OPEN_SUPERIOR_SAR)  
     AND (IC.OPEN_INFERIOR_RSI IS NULL OR IC.OPEN_SUPERIOR_RSI IS NULL OR ROUND(DH.RSI, 5) BETWEEN IC.OPEN_INFERIOR_RSI AND IC.OPEN_SUPERIOR_RSI)  
     AND (IC.OPEN_INFERIOR_BOLLINGER IS NULL OR IC.OPEN_SUPERIOR_BOLLINGER IS NULL OR ROUND(DH.BOLLINGER_UPPER-DH.BOLLINGER_LOWER, 5) BETWEEN IC.OPEN_INFERIOR_BOLLINGER AND IC.OPEN_SUPERIOR_BOLLINGER)  
     AND (IC.OPEN_INFERIOR_MOMENTUM IS NULL OR IC.OPEN_SUPERIOR_MOMENTUM IS NULL OR ROUND(DH.MOMENTUM, 5) BETWEEN IC.OPEN_INFERIOR_MOMENTUM AND IC.OPEN_SUPERIOR_MOMENTUM)  
     AND (IC.OPEN_INFERIOR_ICHISIGNAL IS NULL OR IC.OPEN_SUPERIOR_ICHISIGNAL IS NULL OR ROUND(DH.ICHIMOKUCHINKOUSPAN*(DH.ICHIMOKUTENKANSEN-DH.ICHIMOKUKIJUNSEN),5) BETWEEN IC.OPEN_INFERIOR_ICHISIGNAL AND IC.OPEN_SUPERIOR_ICHISIGNAL)  
     AND (IC.OPEN_INFERIOR_ICHITREND IS NULL OR IC.OPEN_SUPERIOR_ICHITREND IS NULL OR ROUND(DH.ICHIMOKUSENKOUSPANA-DH.ICHIMOKUSENKOUSPANB-DH.LOW, 5) BETWEEN IC.OPEN_INFERIOR_ICHITREND AND IC.OPEN_SUPERIOR_ICHITREND  
           OR ROUND(DH.ICHIMOKUSENKOUSPANA-DH.ICHIMOKUSENKOUSPANB-DH.HIGH, 5) BETWEEN IC.OPEN_INFERIOR_ICHITREND AND IC.OPEN_SUPERIOR_ICHITREND)  
     AND (IC.OPEN_INFERIOR_MA1200 IS NULL OR IC.OPEN_SUPERIOR_MA1200 IS NULL OR  
      ROUND(DH.MA1200-DH.LOW, 5) BETWEEN IC.OPEN_INFERIOR_MA1200 AND IC.OPEN_SUPERIOR_MA1200 OR ROUND(DH.MA1200-DH.HIGH,5) BETWEEN IC.OPEN_INFERIOR_MA1200 AND IC.OPEN_SUPERIOR_MA1200)  
     AND (IC.OPEN_INFERIOR_MACD20X IS NULL OR IC.OPEN_SUPERIOR_MACD20X IS NULL OR ROUND(DH.MACD20X_VALUE+DH.MACD20X_SIGNAL, 5) BETWEEN IC.OPEN_INFERIOR_MACD20X AND IC.OPEN_SUPERIOR_MACD20X)  
     AND (IC.OPEN_INFERIOR_COMPARE1200 IS NULL OR IC.OPEN_SUPERIOR_COMPARE1200 IS NULL OR ROUND(DH.AVERAGE_COMPARE1200-DH.COMPARE_VALUE, 5) BETWEEN IC.OPEN_INFERIOR_COMPARE1200 AND IC.OPEN_SUPERIOR_COMPARE1200)  
     AND (IC.OPEN_INFERIOR_ADX168 IS NULL OR IC.OPEN_SUPERIOR_ADX168 IS NULL OR ROUND(DH.ADX_VALUE168*(DH.ADX_PLUS168-DH.ADX_MINUS168), 5) BETWEEN IC.OPEN_INFERIOR_ADX168 AND IC.OPEN_SUPERIOR_ADX168)  
     AND (IC.OPEN_INFERIOR_SAR1200 IS NULL OR IC.OPEN_SUPERIOR_SAR1200 IS NULL 
      OR ROUND(DH.SAR1200-DH.LOW, 5) BETWEEN IC.OPEN_INFERIOR_SAR1200 AND IC.OPEN_SUPERIOR_SAR1200 OR ROUND(DH.SAR1200-DH.HIGH, 5) BETWEEN IC.OPEN_INFERIOR_SAR1200 AND IC.OPEN_SUPERIOR_SAR1200)  
     AND (IC.OPEN_INFERIOR_RSI84 IS NULL OR IC.OPEN_SUPERIOR_RSI84 IS NULL OR ROUND(DH.RSI84, 5) BETWEEN IC.OPEN_INFERIOR_RSI84 AND IC.OPEN_SUPERIOR_RSI84)  
     AND (IC.OPEN_INFERIOR_BOLLINGER240 IS NULL OR IC.OPEN_SUPERIOR_BOLLINGER240 IS NULL OR ROUND(DH.BOLLINGER_UPPER240-DH.BOLLINGER_LOWER240, 5) BETWEEN IC.OPEN_INFERIOR_BOLLINGER240 AND IC.OPEN_SUPERIOR_BOLLINGER240)  
     AND (IC.OPEN_INFERIOR_MOMENTUM1200 IS NULL OR IC.OPEN_SUPERIOR_MOMENTUM1200 IS NULL OR ROUND(DH.MOMENTUM1200, 5) BETWEEN IC.OPEN_INFERIOR_MOMENTUM1200 AND IC.OPEN_SUPERIOR_MOMENTUM1200)  
     AND (IC.OPEN_INFERIOR_ICHISIGNAL6 IS NULL OR IC.OPEN_SUPERIOR_ICHISIGNAL6 IS NULL OR ROUND(DH.ICHIMOKUCHINKOUSPAN6*(DH.ICHIMOKUTENKANSEN6-DH.ICHIMOKUKIJUNSEN6),5) BETWEEN IC.OPEN_INFERIOR_ICHISIGNAL6 AND IC.OPEN_SUPERIOR_ICHISIGNAL6)  
     AND (IC.OPEN_INFERIOR_ICHITREND6 IS NULL OR IC.OPEN_SUPERIOR_ICHITREND6 IS NULL OR ROUND(DH.ICHIMOKUSENKOUSPANA6-DH.ICHIMOKUSENKOUSPANB6-DH.LOW, 5) BETWEEN IC.OPEN_INFERIOR_ICHITREND6 AND IC.OPEN_SUPERIOR_ICHITREND6  
           OR ROUND(DH.ICHIMOKUSENKOUSPANA6-DH.ICHIMOKUSENKOUSPANB6-DH.HIGH, 5) BETWEEN IC.OPEN_INFERIOR_ICHITREND6 AND IC.OPEN_SUPERIOR_ICHITREND6)  
  WHERE DH.FECHA>TO_DATE('2008/07/25 04:35','YYYY/MM/DD HH24:MI') --AND ROWNUM<100
--  ORDER BY FECHA ASC  
  ;

