SELECT PAR, MINUTOS, FECHA
, PAR_COMPARE, OPEN, LOW, HIGH, CLOSE, VOLUME, SPREAD
, AVERAGE, MACD_VALUE, MACD_SIGNAL,   
  COMPARE_VALUE, AVERAGE_COMPARE, SAR, ADX_VALUE, ADX_PLUS, ADX_MINUS,   
  RSI, BOLLINGER_UPPER, BOLLINGER_LOWER, MOMENTUM, ICHIMOKUTENKANSEN,   
  ICHIMOKUKIJUNSEN, ICHIMOKUSENKOUSPANA, ICHIMOKUSENKOUSPANB, ICHIMOKUCHINKOUSPAN,   
  MA1200, MACD20X_VALUE, MACD20X_SIGNAL, AVERAGE_COMPARE1200,   
  SAR1200, ADX_VALUE168, ADX_PLUS168, ADX_MINUS168,   
  RSI84, BOLLINGER_UPPER240, BOLLINGER_LOWER240, MOMENTUM1200, ICHIMOKUTENKANSEN6,   
  ICHIMOKUKIJUNSEN6, ICHIMOKUSENKOUSPANA6, ICHIMOKUSENKOUSPANB6, ICHIMOKUCHINKOUSPAN6   
  FROM DATOHISTORICO WHERE --PAR='USDCAD' AND MINUTOS=1 AND 
  FECHA BETWEEN TO_DATE('20090101', 'YYYYMMDD') AND TO_DATE('20091231', 'YYYYMMDD')
  ORDER BY FECHA DESC
  ;
 