SELECT PERI.ID, SUM(PERI.PIPS_TOTALES), SUM(PERI.PIPS_TOTALES_PARALELAS), OPER_SEMANA.ID_INDIVIDUO, SUM(OPER_SEMANA.PIPS), SUM(OPER.PIPS),
  SEMANAS.FECHA_SEMANA, SEMANAS.FECHA_SEMANA+7
  FROM SEMANAS 
    LEFT JOIN OPERACION_X_SEMANA OPER_SEMANA ON OPER_SEMANA.FECHA_SEMANA=(SEMANAS.FECHA_SEMANA-7) 
    INNER JOIN OPERACIONES_ACUM_SEMANA_MES OPER_MES
      ON OPER_MES.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO     
        AND OPER_MES.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
    INNER JOIN OPERACIONES_ACUM_SEMANA_ANYO OPER_ANYO 
      ON OPER_ANYO.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO     
        AND OPER_ANYO.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
    INNER JOIN OPERACIONES_ACUM_SEMANA_CONSOL OPER
      ON OPER_SEMANA.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
      AND OPER.FECHA_SEMANA=SEMANAS.FECHA_SEMANA-7
	INNER JOIN ESTRATEGIA_OPERACION_PERIODO PERI
		ON ( NVL(OPER_SEMANA.PIPS,0)>PERI.FILTRO_PIPS_X_SEMANA AND OPER_MES.PIPS>PERI.FILTRO_PIPS_X_MES 
			AND OPER_ANYO.PIPS>PERI.FILTRO_PIPS_X_ANYO AND OPER.PIPS>PERI.FILTRO_PIPS_TOTALES) 
  WHERE 
  ( PERI.ID>=151506 AND PERI.PIPS_TOTALES>0 AND PERI.PIPS_TOTALES_PARALELAS>0
  --( OPER_SEMANA.PIPS>-1000 AND OPER_MES.PIPS>3000 AND OPER_ANYO.PIPS>2800 AND OPER.PIPS>-3000) 
   )
  --AND SEMANAS.FECHA_SEMANA BETWEEN TO_DATE('20110101','YYYYMMDD') AND TO_DATE('20120101','YYYYMMDD')
  AND SEMANAS.FECHA_SEMANA > TO_DATE('20150201','YYYYMMDD')
  --AND OPER_SEMANA.ID_INDIVIDUO ='1453664590875.284'
  GROUP BY OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, PERI.ID
  ORDER BY --SUM(OPER_SEMANA.PIPS) DESC
  --SEMANAS.FECHA_SEMANA  DESC
  SUM(PERI.PIPS_TOTALES) DESC
  ;

SELECT FECHA_SEMANA FROM SEMANAS ORDER BY FECHA_SEMANA DESC;

CREATE OR REPLACE VIEW V_SEMANAS AS
SELECT ROWNUM RN, FECHA_SEMANA FROM SEMANAS ORDER BY FECHA_SEMANA;

SELECT S1.FECHA_SEMANA, S2.FECHA_SEMANA, (S2.FECHA_SEMANA-S1.FECHA_SEMANA) DIFF FROM V_SEMANAS S1
INNER JOIN V_SEMANAS S2 ON S1.RN=S2.RN-1 
--AND (S2.FECHA_SEMANA-S1.FECHA_SEMANA)>7
;