DROP TABLE TEMP_INDIVIDUO;

CREATE TABLE TEMP_INDIVIDUO AS 
  SELECT (TRUNC(SYSDATE) - TO_DATE('1970/01/01', 'YYYY/MM/DD'))*24*60*60*1000||'.'||(ROWNUM+1) NUEVO_INDIVIDUO, 
  IND.* FROM INDIVIDUO IND
  WHERE IND.ID LIKE '1453780593359.%'
  AND EXISTS (
    SELECT 1 FROM OPERACION OPER 
    WHERE IND.ID = OPER.ID_INDIVIDUO AND OPER.FECHA_APERTURA>TO_DATE('2014/01/30 00:00', 'YYYY/MM/DD HH24:MI')
  )
  ORDER BY IND.CREATION_DATE DESC
;

SELECT count(*) FROM TEMP_INDIVIDUO ORDER BY NUEVO_INDIVIDUO ASC;

INSERT INTO INDIVIDUO(ID,PARENT_ID_1,PARENT_ID_2,TAKE_PROFIT,STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE, TIPO_OPERACION)
  SELECT IND.NUEVO_INDIVIDUO, 
    IND.ID, NULL, IND.TAKE_PROFIT, IND.STOP_LOSS, IND.LOTE, IND.INITIAL_BALANCE, SYSDATE, 'BUY' 
  FROM TEMP_INDIVIDUO IND ORDER BY IND.NUEVO_INDIVIDUO;

INSERT INTO INDICADOR_INDIVIDUO(ID_INDICADOR,ID_INDIVIDUO,INTERVALO_INFERIOR,INTERVALO_SUPERIOR,TIPO) 
  SELECT 
     II.ID_INDICADOR, IND.NUEVO_INDIVIDUO, 
     II.INTERVALO_INFERIOR,II.INTERVALO_SUPERIOR,II.TIPO
  FROM INDICADOR_INDIVIDUO II 
    INNER JOIN TEMP_INDIVIDUO IND ON IND.ID=II.ID_INDIVIDUO
;

SELECT 
   II.ID_INDICADOR, IND.NUEVO_INDIVIDUO, IND.ID,
   II.INTERVALO_INFERIOR,II.INTERVALO_SUPERIOR,II.TIPO
FROM INDICADOR_INDIVIDUO II 
  INNER JOIN TEMP_INDIVIDUO IND ON IND.ID=II.ID_INDIVIDUO
WHERE IND.NUEVO_INDIVIDUO LIKE '%.2'
;
