--INSERT INTO TMP_TOFILESTRING (ID_INDIVIDUO, CRITERIO_ORDER1, CRITERIO_ORDER2, VIGENCIA1, VIGENCIA2)  
  SELECT OPER_SEMANA.*, SEMANAS.*
  --OPER_SEMANA.ID_INDIVIDUO, SUM(OPER_SEMANA.PIPS),  SUM(OPER_SEMANA.PIPS), 
  --SEMANAS.FECHA_SEMANA, SEMANAS.FECHA_SEMANA+7 
  --OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, COUNT(*)
  FROM OPERACION_X_SEMANA OPER_SEMANA  
  INNER JOIN (SELECT DISTINCT SEM.FECHA_SEMANA FROM OPERACION_X_SEMANA SEM) SEMANAS  
    ON OPER_SEMANA.FECHA_SEMANA=(SEMANAS.FECHA_SEMANA-7)  
    /*INNER JOIN OPERACIONES_ACUM_SEMANA_MES OPER_MES 
      ON OPER_MES.ID_INDIVIDUO=OPEROPERACIONES_ACUM_SEMANA_ANYO_SEMANA.ID_INDIVIDUO  AND OPER_SEMANA.FECHA_SEMANA=ADD_MONTHS(OPER_MES.FECHA_SEMANA,-1)  
    INNER JOIN  OPER_ANYO 
      ON OPER_ANYO.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO  AND OPER_SEMANA.FECHA_SEMANA=ADD_MONTHS(OPER_ANYO.FECHA_SEMANA,-1)  
    INNER JOIN OPERACIONES_ACUM_SEMANA_CONSOL OPER ON OPER_SEMANA.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
      AND OPER_SEMANA.FECHA_SEMANA=ADD_MONTHS(OPER.FECHA_SEMANA,-1)  */
WHERE EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II 
    WHERE OPER_SEMANA.ID_INDIVIDUO=II.ID_INDIVIDUO AND II.INTERVALO_INFERIOR IS NOT NULL)  
  --AND (( OPER_SEMANA.PIPS>0 AND OPER_MES.PIPS>0 AND OPER_ANYO.PIPS>0 AND OPER.PIPS>0))  
  AND OPER_SEMANA.ID_INDIVIDUO='1454630400000.409'
--GROUP BY OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA	
--HAVING COUNT(*)>1
order by SEMANAS.FECHA_SEMANA ASC, OPER_SEMANA.ID_INDIVIDUO
;    

SELECT 
--  OPER_SEMANA.*, SEMANAS.*
  OPER_SEMANA.ID_INDIVIDUO, SUM(OPER_SEMANA.PIPS),  SUM(OPER_SEMANA.PIPS), 
  SEMANAS.FECHA_SEMANA, SEMANAS.FECHA_SEMANA+7 , COUNT(*)
  --OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA, COUNT(*)
  FROM OPERACION_X_SEMANA OPER_SEMANA  
  INNER JOIN (SELECT DISTINCT SEM.FECHA_SEMANA FROM OPERACION_X_SEMANA SEM) SEMANAS  
    ON OPER_SEMANA.FECHA_SEMANA=(SEMANAS.FECHA_SEMANA-7)  
    /*INNER JOIN OPERACIONES_ACUM_SEMANA_MES OPER_MES 
      ON OPER_MES.ID_INDIVIDUO=OPEROPERACIONES_ACUM_SEMANA_ANYO_SEMANA.ID_INDIVIDUO  AND OPER_SEMANA.FECHA_SEMANA=ADD_MONTHS(OPER_MES.FECHA_SEMANA,-1)  
    INNER JOIN  OPER_ANYO 
      ON OPER_ANYO.ID_INDIVIDUO=OPER_SEMANA.ID_INDIVIDUO  AND OPER_SEMANA.FECHA_SEMANA=ADD_MONTHS(OPER_ANYO.FECHA_SEMANA,-1)  
    INNER JOIN OPERACIONES_ACUM_SEMANA_CONSOL OPER ON OPER_SEMANA.ID_INDIVIDUO=OPER.ID_INDIVIDUO  
      AND OPER_SEMANA.FECHA_SEMANA=ADD_MONTHS(OPER.FECHA_SEMANA,-1)  */
WHERE EXISTS (SELECT 1 FROM INDICADOR_INDIVIDUO II 
    WHERE OPER_SEMANA.ID_INDIVIDUO=II.ID_INDIVIDUO AND II.INTERVALO_INFERIOR IS NOT NULL)  
  --AND (( OPER_SEMANA.PIPS>0 AND OPER_MES.PIPS>0 AND OPER_ANYO.PIPS>0 AND OPER.PIPS>0))  
  AND OPER_SEMANA.ID_INDIVIDUO='1454630400000.409'
GROUP BY OPER_SEMANA.ID_INDIVIDUO, SEMANAS.FECHA_SEMANA	
HAVING COUNT(*)>1
;    

SELECT TRUNC(FECHA_APERTURA, 'WW') SEMY, TO_CHAR(FECHA_APERTURA, 'YYYYWW') SEM, OPER.PIPS, ROUND((OPER.FECHA_CIERRE-OPER.FECHA_APERTURA)*24*60,5) DURACION , OPER.* 
 FROM FOREX.OPERACION OPER
WHERE OPER.ID_INDIVIDUO IN (
'1454630400000.409')
AND TO_CHAR(FECHA_APERTURA, 'YYYY')='2010'
ORDER BY --ID_INDIVIDUO DESC, 
  FECHA_APERTURA ASC
  --OPER.PIPS ASC
;

SELECT * FROM OPERACION_X_SEMANA OPER_SEMANA 
WHERE OPER_SEMANA.ID_INDIVIDUO='1454630400000.409'
AND SEMANA LIKE '20101_'
ORDER BY SEMANA ASC;

SELECT TRUNC(TO_DATE('2010/04/30 17:34','YYYY/MM/DD HH24:MI'), 'IW') FROM DUAL;

SELECT DISTINCT SEM.FECHA_SEMANA, SEM.SEMANA FROM OPERACION_X_SEMANA SEM WHERE