DROP MATERIALIZED VIEW "FOREX"."FILTERED_PARALELAS_EOP";

  CREATE MATERIALIZED VIEW "FOREX"."FILTERED_PARALELAS_EOP" ("CANTIDAD", "FILTRO_PIPS_X_MES", "FILTRO_PIPS_X_ANYO", "FILTRO_PIPS_TOTALES", "FIRST_ORDER", "SECOND_ORDER", "FECHA", "PIPS_TOTALES", "FECHA_INICIAL", "FECHA_FINAL", "ID", "TIPO_OPERACION", "CANTIDAD_PARALELAS", "PIPS_TOTALES_PARALELAS", "PIPS_AGRUPADO_MINUTOS", "PIPS_AGRUPADO_HORAS", "PIPS_AGRUPADO_DIAS", "FILTRO_PIPS_X_SEMANA", "FILTRO_PENDIENTE_SEMANA", "FILTRO_PENDIENTE_MES", "FILTRO_PENDIENTE_ANYO", "FILTRO_PENDIENTE_TOTALES", "FILTRO_R2_SEMANA", "FILTRO_R2_MES", "FILTRO_R2_ANYO", "FILTRO_R2_TOTALES", "CANTIDAD_INDIVIDUOS", "MAX_FECHA_CIERRE", "EOP_VERSION", "EOP_ROWID")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  REFRESH FAST ON DEMAND
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS	SELECT EOP.CANTIDAD,EOP.FILTRO_PIPS_X_MES,EOP.FILTRO_PIPS_X_ANYO,
	EOP.FILTRO_PIPS_TOTALES,EOP.FIRST_ORDER,EOP.SECOND_ORDER,EOP.FECHA,
	EOP.PIPS_TOTALES PIPS_TOTALES,EOP.FECHA_INICIAL,EOP.FECHA_FINAL,EOP.ID,TIPO_OPERACION,
	EOP.CANTIDAD_PARALELAS,EOP.PIPS_TOTALES_PARALELAS,EOP.PIPS_AGRUPADO_MINUTOS,
	EOP.PIPS_AGRUPADO_HORAS,EOP.PIPS_AGRUPADO_DIAS,EOP.FILTRO_PIPS_X_SEMANA,
	EOP.FILTRO_PENDIENTE_SEMANA,EOP.FILTRO_PENDIENTE_MES,EOP.FILTRO_PENDIENTE_ANYO,
	EOP.FILTRO_PENDIENTE_TOTALES,EOP.FILTRO_R2_SEMANA,EOP.FILTRO_R2_MES,
	EOP.FILTRO_R2_ANYO,EOP.FILTRO_R2_TOTALES,EOP.CANTIDAD_INDIVIDUOS,
	EOP.MAX_FECHA_CIERRE,EOP.EOP_VERSION,EOP.ROWID EOP_ROWID
	FROM ESTRATEGIA_OPERACION_PERIODO EOP
  WHERE EOP.PIPS_TOTALES<=1000
	  AND EOP.PIPS_TOTALES_PARALELAS>0
		AND (EOP.PIPS_AGRUPADO_MINUTOS>0 AND EOP.PIPS_AGRUPADO_HORAS>0 AND EOP.PIPS_AGRUPADO_DIAS>0)
		AND EOP.CANTIDAD_INDIVIDUOS>1
		AND (EOP.PIPS_TOTALES_PARALELAS/EOP.CANTIDAD_PARALELAS)>200
	  AND EOP.FECHA_FINAL>TO_DATE('20141231','YYYYMMDD');

  CREATE UNIQUE INDEX "FOREX"."I_SNAP$_FILTERED_PARALELAS" ON "FOREX"."FILTERED_PARALELAS_EOP" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" ;
  CREATE UNIQUE INDEX "FOREX"."FILT_PARAL_EOP_IDX1" ON "FOREX"."FILTERED_PARALELAS_EOP" ("FILTRO_PIPS_X_SEMANA", "FILTRO_PIPS_X_MES", "FILTRO_PIPS_X_ANYO", "FILTRO_PIPS_TOTALES", "FIRST_ORDER", "FECHA_INICIAL", "FECHA_FINAL", "TIPO_OPERACION", "FILTRO_PENDIENTE_SEMANA", "FILTRO_PENDIENTE_MES", "FILTRO_PENDIENTE_ANYO", "FILTRO_PENDIENTE_TOTALES", "FILTRO_R2_SEMANA", "FILTRO_R2_MES", "FILTRO_R2_ANYO", "FILTRO_R2_TOTALES", "MAX_FECHA_CIERRE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" ;
  CREATE INDEX "FOREX"."FILT_PARAL_EOP_TOTALES_IDX2" ON "FOREX"."FILTERED_PARALELAS_EOP" ("ID", "TIPO_OPERACION" DESC, "FECHA_INICIAL" DESC, "FECHA_FINAL" DESC, "CANTIDAD" DESC, "PIPS_TOTALES" DESC, "PIPS_TOTALES_PARALELAS" DESC, "PIPS_AGRUPADO_MINUTOS" DESC, "PIPS_AGRUPADO_HORAS" DESC, "PIPS_AGRUPADO_DIAS" DESC, "CANTIDAD_INDIVIDUOS" DESC, "CANTIDAD_PARALELAS" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" ;

   COMMENT ON MATERIALIZED VIEW "FOREX"."FILTERED_PARALELAS_EOP"  IS 'snapshot table for snapshot FOREX.FILTERED_PARALELAS_EOP';

DROP MATERIALIZED VIEW "FOREX"."FILTERED_PARA_OPERAR_SELL";

  CREATE MATERIALIZED VIEW "FOREX"."FILTERED_PARA_OPERAR_SELL" ("ID_INDIVIDUO", "FECHA_SEMANA", "PIPS_SEMANA", "PIPS_MES", "PIPS_ANYO", "PIPS_TOTALES", "TIPO_OPERACION", "FECHA_HISTORICO", "R_COUNT_SEMANA", "R2_SEMANA", "PENDIENTE_SEMANA", "INTERCEPCION_SEMANA", "R_COUNT_MES", "R2_MES", "PENDIENTE_MES", "INTERCEPCION_MES", "R_COUNT_ANYO", "R2_ANYO", "PENDIENTE_ANYO", "INTERCEPCION_ANYO", "R_COUNT_CONSOL", "R2_CONSOL", "PENDIENTE_CONSOL", "INTERCEPCION_CONSOL", "CANTIDAD", "FILTRO_PIPS_X_MES", "FILTRO_PIPS_X_ANYO", "FILTRO_PIPS_TOTALES", "FIRST_ORDER", "SECOND_ORDER", "FECHA", "EOP_PIPS_TOTALES", "FECHA_INICIAL", "FECHA_FINAL", "ID", "CANTIDAD_PARALELAS", "PIPS_TOTALES_PARALELAS", "PIPS_AGRUPADO_MINUTOS", "PIPS_AGRUPADO_HORAS", "PIPS_AGRUPADO_DIAS", "FILTRO_PIPS_X_SEMANA", "FILTRO_PENDIENTE_SEMANA", "FILTRO_PENDIENTE_MES", "FILTRO_PENDIENTE_ANYO", "FILTRO_PENDIENTE_TOTALES", "FILTRO_R2_SEMANA", "FILTRO_R2_MES", "FILTRO_R2_ANYO", "FILTRO_R2_TOTALES", "CANTIDAD_INDIVIDUOS", "MAX_FECHA_CIERRE", "EOP_VERSION", "PTFS_ROWID", "EOP_ROWID")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_FOREX" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FAST ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT PTFS.ID_INDIVIDUO,PTFS.FECHA_SEMANA,PTFS.PIPS_SEMANA,PTFS.PIPS_MES,PTFS.PIPS_ANYO,PTFS.PIPS_TOTALES,PTFS.TIPO_OPERACION,PTFS.FECHA_HISTORICO,PTFS.R_COUNT_SEMANA,PTFS.R2_SEMANA,PTFS.PENDIENTE_SEMANA,PTFS.INTERCEPCION_SEMANA,PTFS.R_COUNT_MES,PTFS.R2_MES,PTFS.PENDIENTE_MES,PTFS.INTERCEPCION_MES,PTFS.R_COUNT_ANYO,PTFS.R2_ANYO,PTFS.PENDIENTE_ANYO,PTFS.INTERCEPCION_ANYO,PTFS.R_COUNT_CONSOL,PTFS.R2_CONSOL,PTFS.PENDIENTE_CONSOL,PTFS.INTERCEPCION_CONSOL,
	EOP.CANTIDAD,EOP.FILTRO_PIPS_X_MES,EOP.FILTRO_PIPS_X_ANYO,EOP.FILTRO_PIPS_TOTALES,EOP.FIRST_ORDER,EOP.SECOND_ORDER,EOP.FECHA,EOP.PIPS_TOTALES EOP_PIPS_TOTALES,EOP.FECHA_INICIAL,EOP.FECHA_FINAL,EOP.ID,EOP.CANTIDAD_PARALELAS,EOP.PIPS_TOTALES_PARALELAS,EOP.PIPS_AGRUPADO_MINUTOS,EOP.PIPS_AGRUPADO_HORAS,EOP.PIPS_AGRUPADO_DIAS,EOP.FILTRO_PIPS_X_SEMANA,EOP.FILTRO_PENDIENTE_SEMANA,EOP.FILTRO_PENDIENTE_MES,EOP.FILTRO_PENDIENTE_ANYO,EOP.FILTRO_PENDIENTE_TOTALES,EOP.FILTRO_R2_SEMANA,EOP.FILTRO_R2_MES,EOP.FILTRO_R2_ANYO,EOP.FILTRO_R2_TOTALES,EOP.CANTIDAD_INDIVIDUOS,EOP.MAX_FECHA_CIERRE,EOP.EOP_VERSION,
	PTFS.ROWID PTFS_ROWID, EOP.ROWID EOP_ROWID
  FROM FILTERED_PTFS PTFS, --PREVIO_TOFILESTRING PTFS, 
	--ESTRATEGIA_OPERACION_PERIODO EOP
		FILTERED_EOP EOP
		WHERE ( NVL(PTFS.PIPS_SEMANA,0)>EOP.FILTRO_PIPS_X_SEMANA AND NVL(PTFS.PIPS_MES,0)>EOP.FILTRO_PIPS_X_MES 
			AND NVL(PTFS.PIPS_ANYO,0)>EOP.FILTRO_PIPS_X_ANYO AND PTFS.PIPS_TOTALES>EOP.FILTRO_PIPS_TOTALES)
			AND (NVL(PTFS.R2_SEMANA,0)>EOP.FILTRO_R2_SEMANA AND NVL(PTFS.R2_MES,0)>EOP.FILTRO_R2_MES 
			AND NVL(PTFS.R2_ANYO,0)>EOP.FILTRO_R2_ANYO AND PTFS.R2_CONSOL>EOP.FILTRO_R2_TOTALES)
			AND (NVL(PTFS.PENDIENTE_SEMANA,0)>EOP.FILTRO_PENDIENTE_SEMANA AND NVL(PTFS.PENDIENTE_MES,0)>EOP.FILTRO_PENDIENTE_MES 
			AND NVL(PTFS.PENDIENTE_ANYO,0)>EOP.FILTRO_PENDIENTE_ANYO AND PTFS.PENDIENTE_CONSOL>EOP.FILTRO_PENDIENTE_TOTALES)
			AND PTFS.TIPO_OPERACION=EOP.TIPO_OPERACION
			AND PTFS.FECHA_SEMANA BETWEEN EOP.FECHA_FINAL AND (EOP.FECHA_FINAL+7)
			AND PTFS.FECHA_SEMANA BETWEEN EOP.MAX_FECHA_CIERRE AND (EOP.MAX_FECHA_CIERRE+7)   
	AND ((EOP.TIPO_OPERACION='SELL' AND EOP.PIPS_TOTALES>0
--		AND EOP.PIPS_TOTALES_PARALELAS>EOP.PIPS_TOTALES
		AND EOP.PIPS_TOTALES_PARALELAS>0
	 )	)
	AND EOP.TIPO_OPERACION='SELL'
	AND PTFS.FECHA_SEMANA>TO_DATE('20141231','YYYYMMDD');

   COMMENT ON MATERIALIZED VIEW "FOREX"."FILTERED_PARA_OPERAR_SELL"  IS 'snapshot table for snapshot FOREX.FILTERED_PARA_OPERAR_SELL';
