SELECT * FROM TENDENCIA_PARA_OPERAR 
--ORDER BY FECHA_BASE ASC;
ORDER BY FECHA DESC;

SELECT * FROM TENDENCIA_PARA_OPERAR TPO
WHERE TPO.FECHA_BASE>=TO_DATE('2016.03.08 23:49', 'YYYY/MM/DD HH24:MI')
ORDER BY FECHA_BASE ASC;


SELECT TRUNC(FECHA_BASE, 'HH24') FROM TENDENCIA_PARA_OPERAR TPO;

SELECT COUNT(*) FROM TENDENCIA_PARA_OPERAR ;

--UPDATE TENDENCIA_PARA_OPERAR SET ID_EJECUCION='1';