SELECT * FROM TENDENCIA --WHERE TIPO_TENDENCIA='ESTADISTICAS'
--ORDER BY FECHA_BASE ASC
ORDER BY FECHA_TENDENCIA DESC
;

--update tendencia set probabilidad_positivos=null where probabilidad_positivos IS NOT null AND id_individuo='1341548450906.1997';

SELECT COUNT(*) FROM TENDENCIA WHERE PROBABILIDAD_POSITIVOS IS NOT NULL;

SELECT TEN.ID_INDIVIDUO,OPER.FECHA_APERTURA, TEN.FECHA_BASE, OPER.OPEN_PRICE, 
  (OPER.OPEN_PRICE-OPER.PIPS/100000) VALOR_CIERRE, TEN.PRECIO_CALCULADO, 
  OPER.FECHA_CIERRE, TEN.FECHA_TENDENCIA, TEN.DURACION_ACTUAL, TEN.DURACION,
  OPER.PIPS PIPS_OPER, TEN.PIPS_ACTUALES, TEN.PIPS PIPS_CALCULADOS,  
  --ROUND(((TEN.PRECIO_CALCULADO-(OPER.OPEN_PRICE-OPER.PIPS/100000))/OPER.OPEN_PRICE)*100,5) PERCENT,
  ROUND((OPER.PIPS-(TEN.PIPS+TEN.PIPS_ACTUALES)),5) DIFF_PIPS, TEN.PROBABILIDAD_POSITIVOS, TEN.PROBABILIDAD_NEGATIVOS
FROM TENDENCIA TEN
  INNER JOIN OPERACION OPER ON TEN.ID_INDIVIDUO=OPER.ID_INDIVIDUO
WHERE OPER.FECHA_APERTURA=TEN.FECHA_APERTURA AND OPER.FECHA_CIERRE IS NOT NULL
--AND OPER.ID_INDIVIDUO='1341548450906.1997'
AND TEN.PROBABILIDAD_POSITIVOS IS NOT NULL
--AND ROWNUM < 100
--ORDER BY FECHA_TENDENCIA ASC
ORDER BY FECHA_BASE DESC
;

SELECT TO_CHAR(DH.FECHA, 'YYYY/MM/DD HH24:MI') FECHA, 
  ROUND(AVG(TEN.PRECIO_CALCULADO),5) PRECIO, ROUND( AVG(TEN.PIPS),5) PIPS, 
  COUNT(DISTINCT TEN.ID_INDIVIDUO) CINDIVIDUOS 
FROM DATOHISTORICO DH
  LEFT JOIN TENDENCIA TEN ON DH.FECHA=TEN.FECHA_TENDENCIA
    AND TEN.FECHA_BASE<TO_DATE('2012/06/04 00:00', 'YYYY/MM/DD HH24:MI')
    AND TEN.FECHA_TENDENCIA>=TO_DATE('2012/06/04 00:00', 'YYYY/MM/DD HH24:MI')
    AND TEN.PROBABILIDAD_POSITIVOS IS NOT NULL
    AND (TEN.PROBABILIDAD_POSITIVOS>.6 OR TEN.PROBABILIDAD_NEGATIVOS>.6)
WHERE DH.FECHA>=TO_DATE('2012/06/04 00:00', 'YYYY/MM/DD HH24:MI')
AND DH.FECHA<TO_DATE('2012/06/04 00:00', 'YYYY/MM/DD HH24:MI')+1
GROUP BY TO_CHAR(DH.FECHA, 'YYYY/MM/DD HH24:MI')
ORDER BY TO_CHAR(DH.FECHA, 'YYYY/MM/DD HH24:MI') ASC
;

SELECT TO_CHAR(FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') FECHA, COUNT(DISTINCT ID_INDIVIDUO) CINDIVIDUOS 
FROM TENDENCIA TEN
WHERE TEN.PROBABILIDAD_POSITIVOS IS NOT NULL
AND (TEN.PROBABILIDAD_POSITIVOS>.6 OR TEN.PROBABILIDAD_NEGATIVOS>.6)
GROUP BY TO_CHAR(FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI')
--ORDER BY TO_CHAR(FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC
ORDER BY COUNT(DISTINCT ID_INDIVIDUO) DESC
;

SELECT * FROM TENDENCIA --WHERE TIPO_TENDENCIA='ESTADISTICAS'
--ORDER BY FECHA_BASE ASC
WHERE PROBABILIDAD_POSITIVOS IS NOT NULL
ORDER BY FECHA_BASE DESC
;

SELECT * FROM TENDENCIA WHERE ID_INDIVIDUO='1331601592515.26894'
--order by fecha_tendencia desc
AND PROBABILIDAD_POSITIVOS IS NOT NULL
ORDER BY FECHA_BASE DESC
;

SELECT * FROM TENDENCIA 
WHERE FECHA_TENDENCIA=TO_DATE('2012/06/04 13:27', 'YYYY/MM/DD HH24:MI')
ORDER BY FECHA_TENDENCIA ASC;

select * from tendencia where precio_base=open_price;

SELECT * FROM TENDENCIA WHERE TIPO_TENDENCIA='ESTADISTICAS'
and FECHA_BASE<TO_DATE('2012/08/10 10:00', 'YYYY/MM/DD HH24:MI')
AND FECHA_TENDENCIA>=TO_DATE('2012/08/10 10:00', 'YYYY/MM/DD HH24:MI')
ORDER BY FECHA_TENDENCIA ASC;

SELECT * FROM DETALLE_ESTADISTICAS WHERE ID_INDIVIDUO='1332460820218.382';

SELECT ID_INDIVIDUO, FECHA_BASE, FECHA_TENDENCIA, PRECIO_CALCULADO FROM TENDENCIA 
WHERE TO_CHAR(FECHA_TENDENCIA, 'YYYY')<=2011-- AND TO_CHAR(FECHA_TENDENCIA, 'YYYY')<2012
AND FECHA_BASE<TO_DATE('2012/08/06', 'YYYY/MM/DD HH24:MI') 
--AND FECHA_BASE<TO_DATE('2012/08/13', 'YYYY/MM/DD HH24:MI')
--AND FECHA_TENDENCIA>TO_DATE('2012/08/09 23:59', 'YYYY/MM/DD HH24:MI')
--ORDER BY FECHA_BASE ASC;
ORDER BY FECHA_BASE DESC;

SELECT min(fecha_base), max(fecha_base) FROM TENDENCIA ORDER BY FECHA_BASE DESC;

SELECT COUNT(*) FROM TENDENCIA;

SELECT * FROM TENDENCIA 
WHERE ID_INDIVIDUO='1332808411718.28'
ORDER BY FECHA_BASE ASC;

SELECT count(*) FROM TENDENCIA WHERE FECHA_BASE=TO_DATE('2011/01/10 14:58', 'YYYY/MM/DD HH24:MI');

SELECT * FROM OPERACION
WHERE ID_INDIVIDUO='1329927210938.5087' ORDER BY FECHA_APERTURA DESC;

SELECT count(*) FROM TENDENCIA;

SELECT --COUNT(*)
OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.OPEN_PRICE, OPER.SPREAD, OPER.LOTE, OPER.FECHA_CIERRE 
  FROM OPERACION OPER
  INNER JOIN DETALLE_ESTADISTICAS EST ON EST.ID_INDIVIDUO=OPER.ID_INDIVIDUO
  WHERE OPER.FECHA_APERTURA<=TO_DATE('2012/08/10 00:00', 'YYYY/MM/DD HH24:MI')
  AND (OPER.FECHA_CIERRE IS NULL OR OPER.FECHA_CIERRE>TO_DATE('2012/08/10 00:00', 'YYYY/MM/DD HH24:MI'))
  AND OPER.FECHA_APERTURA>TO_DATE('2012/08/10 00:00', 'YYYY/MM/DD HH24:MI')-30
  AND OPER.ID_INDIVIDUO NOT IN (SELECT ID_INDIVIDUO FROM TENDENCIA TEND WHERE TEND.ID_INDIVIDUO=OPER.ID_INDIVIDUO
    AND TEND.FECHA_BASE=TO_DATE('2012/08/10 00:00', 'YYYY/MM/DD HH24:MI'))
;

SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.OPEN_PRICE, OPER.SPREAD, OPER.LOTE 
                  FROM OPERACION OPER
                  INNER JOIN DETALLE_ESTADISTICAS EST ON EST.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
                  WHERE OPER.ID_INDIVIDUO='133280;8411718.28';

SELECT count(*) FROM TENDENCIA WHERE PROBABILIDAD_POSITIVOS IS NULL
 ORDER BY FECHA_BASE ASC;
                
UPDATE TENDENCIA SET PROBABILIDAD_POSITIVOS=NULL;