WITH 
PARAMETROS AS (
		SELECT
		--:PARAM_PERIODO 
		'XD' PERIODO,
		--:PARAM_TIEMPO_TENDENCIA
		(1440*1) TIEMPO_TENDENCIA,
		--TO_DATE(:PARAM_FECHA_PROCESO, 'YYYY/MM/DD HH24:MI') FECHA_PROCESO,
		TO_DATE('2015.03.12 04:58', 'YYYY/MM/DD HH24:MI') FECHA_PROCESO,
		--:PARAM_TIPO_TENDENCIA
		'BUY_SELL_20170204-2' TIPO_TENDENCIA 
		FROM DUAL	
),
DATO_INICIAL AS (
	SELECT PARAM.FECHA_PROCESO FECHA_BASE, TRUNC((PARAM.FECHA_PROCESO-1/24),'HH24') FECHA_TENDENCIA,
		ROUND((DH.OPEN+DH.LOW+DH.HIGH+DH.CLOSE)/4, 5) PRECIO_CALCULADO, 10000000 CANTIDAD, 
		PARAM.FECHA_PROCESO MINFEBASE, PARAM.FECHA_PROCESO MAXFEBASE, 
		PARAM.FECHA_PROCESO MINFETENDENCIA, PARAM.FECHA_PROCESO MAXFETENDENCIA,
		SYSDATE MAXFE
	FROM PARAMETROS PARAM, DATOHISTORICO DH WHERE DH.FECHA=PARAM.FECHA_PROCESO
		),
TENDENCIA_CALCULADA AS (SELECT 
			PARAM.FECHA_PROCESO FECHA_BASE,
			TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			COUNT(*) CANTIDAD, MIN(TEN.FECHA_BASE) MINFEBASE, MAX(TEN.FECHA_BASE) MAXFEBASE,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
			MAX(FECHA) MAXFE
		FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,PARAM.FECHA_PROCESO)<PARAM.TIEMPO_TENDENCIA
			--AND WEEK_MINUTES(PARAM.FECHA_PROCESO, TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO 
			--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO
--			AND TEN.ID_INDIVIDUO='1455148800000.2546'
		--AND TRUNC(TEN.FECHA) = TRUNC(SYSDATE)
		--AND WEEK_MINUTES(PARAM.FECHA_PROCESO,TEN.FECHA_APERTURA)<PARAM.TIEMPO_TENDENCIA
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24'), PARAM.FECHA_PROCESO),
PROMEDIOS AS (SELECT ROUND(AVG(TEN.CANTIDAD)) AVGCANTIDAD, ROUND(COUNT(TEN.CANTIDAD)) CANTIDAD
		FROM PARAMETROS PARAM, TENDENCIA_CALCULADA TEN),
UNION_TENDENCIA AS (SELECT * FROM DATO_INICIAL UNION ALL SELECT * FROM TENDENCIA_CALCULADA),
REGRESION AS (SELECT PARAM.FECHA_PROCESO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-PARAM.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-PARAM.FECHA_PROCESO),5) PENDIENTE,
		ROUND(STDDEV(TEN.PRECIO_CALCULADO),5) DESV,
		ROUND(REGR_INTERCEPT(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-PARAM.FECHA_PROCESO),5) INTERCEP,
		MIN(TEN.PRECIO_CALCULADO) MINPRECIO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO,
		SUM(TEN.CANTIDAD) SUMCANTIDAD,
		MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
		MIN(TEN.MINFEBASE) MINFEBASE, MAX(TEN.MAXFEBASE) MAXFEBASE,		
		COUNT(*) CANTIDAD_TENDENCIAS
		FROM PARAMETROS PARAM, PROMEDIOS PROM, TENDENCIA_CALCULADA TEN 
		--UNION_TENDENCIA TEN
		WHERE --(TEN.CANTIDAD>=PROM.AVGCANTIDAD)
			(TEN.CANTIDAD/PROM.AVGCANTIDAD)>=0.0
		)
		--SELECT * FROM PARAMETROS
--SELECT PARAM.PERIODO PERIODO, TEN.*, ROUND(TEN.CANTIDAD/PROM.AVGCANTIDAD,2) FACTORCANTIDAD FROM PARAMETROS PARAM, PROMEDIOS PROM, UNION_TENDENCIA TEN	ORDER BY TEN.FECHA_TENDENCIA DESC --WHERE TEN.CANTIDAD>=PROM.AVGCANTIDAD
SELECT PARAM.PERIODO PERIODO, REG.*  FROM PARAMETROS PARAM, REGRESION REG
--SELECT PARAM.PERIODO PERIODO, PROM.*  FROM PARAMETROS PARAM, PROMEDIOS PROM
--SELECT * FROM DATO_INICIAL
--SELECT * FROM UNION_TENDENCIA
;
-- COMO FILTRAR EL PUNTO 2017.02.02 20:59, està vendiendo. Con TP mìnimo de 20 pips, funciona, pero con pips de 10 quiebra la cuenta.

WITH 
PARAMETROS AS (
		SELECT 
		--:PARAM_PERIODO 
		'XD' PERIODO,
		--:PARAM_TIEMPO_TENDENCIA 
		(1440*1) TIEMPO_TENDENCIA,
		--TO_DATE(:PARAM_FECHA_PROCESO, 'YYYY/MM/DD HH24:MI') FECHA_PROCESO,
		TO_DATE('2015.03.12 02:10', 'YYYY/MM/DD HH24:MI') FECHA_PROCESO,
		--:PARAM_TIPO_TENDENCIA 
		'BUY_SELL_20170204-2' TIPO_TENDENCIA 
		FROM DUAL	
),
DETALLE_TENDENCIA AS (SELECT 
			TEN.*
		FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO
--			AND TEN.ID_INDIVIDUO='1477365411387.11169'
		),
TENDENCIA_CALCULADA AS (SELECT 
			TRUNC(TEN.FECHA_BASE, 'HH24') FECHA_BASE,
			TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			ROUND(AVG(TEN.PROBABILIDAD),5) PROBABILIDAD,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
			MAX(FECHA) MAXFE
		FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO
--			AND TEN.ID_INDIVIDUO='1477365411387.11169'
		--AND TEN.FECHA<TRUNC(SYSDATE)-1
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24'), TRUNC(TEN.FECHA_BASE, 'HH24')
		),
TENDENCIA_CALCULADA_MINUTOS AS (SELECT 
			TRUNC(TEN.FECHA_BASE, 'HH24') FECHA_BASE,
			TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			ROUND(AVG(TEN.PROBABILIDAD),5) PROBABILIDAD,
			COUNT(*) CANTIDAD, 
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
			MAX(FECHA) MAXFE
		FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24'), TRUNC(TEN.FECHA_BASE, 'HH24')
		)
--SELECT WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE) DIFF, TEN.* FROM DETALLE_TENDENCIA TEN ORDER BY TEN.FECHA DESC;
--SELECT PARAM.PERIODO PERIODO, TEN.*  FROM PARAMETROS PARAM, TENDENCIA_CALCULADA TEN	
--	WHERE TEN.FECHA_TENDENCIA>=TO_DATE('2017/02/17 11:00', 'YYYY:MM:DD HH24:MI')
--ORDER BY TEN.FECHA_TENDENCIA ASC, TEN.FECHA_BASE ASC
	--ORDER BY TEN.PRECIO_CALCULADO ASC
--SELECT * FROM DETALLE_TENDENCIA TEN ORDER BY TEN.FECHA_TENDENCIA ASC;

SELECT --TEN.FECHA_TENDENCIA, --
	TEN.FECHA_BASE, ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,	
	SUM(TEN.CANTIDAD) SUMCANTIDAD,
	MIN(TEN.PRECIO_CALCULADO) MINPRECIO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO,
	MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
	FROM PARAMETROS PARAM, TENDENCIA_CALCULADA TEN	
	--WHERE TEN.FECHA_TENDENCIA>=TO_DATE('2017/03/01 18:00', 'YYYY/MM/DD HH24:MI')	
GROUP BY --TEN.FECHA_TENDENCIA 
	TEN.FECHA_BASE
--ORDER BY COUNT(*) DESC
ORDER BY --TEN.FECHA_TENDENCIA --
TEN.FECHA_BASE ASC
;

SELECT WEEK_MINUTES(TO_DATE('20161216 09:49', 'YYYYMMDD HH24:MI'),TO_DATE('20161214 22:11','YYYYMMDD HH24:MI'))
FROM DUAL;