WITH TIEMPO_TENDENCIA AS (
	SELECT (24*0.25/24)*24*60 T6H, (24*0.5/24)*24*60 T12H, (24*1/24)*24*60 T1D,
		(24*2/24)*24*60 T2D, (24*5/24)*24*60 T5D, (24*10/24)*24*60 T10D,
		0.1 PORC6H, 0.1 PORC12H, 0.1 PORC1D, 0.2 PORC2D, 0.2 PORC5D, 0.3 PORC10D,
		--0.4 PORC6H, 0.3 PORC12H, 0.1 PORC1D, 0.1 PORC2D, 0.05 PORC5D, 0.05 PORC10D,
			5000 PIPS_BASE,
			TO_DATE('2017/02/03 23:58', 'YYYY/MM/DD HH24:MI') FECHA,
			'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3 
			FROM DUAL),
		BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE, 1.30208 PRECIO_ACTUAL
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA),
		TENDENCIA_6H AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
					ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
					ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
				FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
					WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
					AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T6H
					AND TEN.FECHA_BASE<=TT.FECHA
					AND TEN.FECHA_TENDENCIA>TT.FECHA
					--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
					--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TT.FECHA)
				GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
		TENDENCIA_12H AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
					ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
					ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
				FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
					WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
					AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T12H
					AND TEN.FECHA_BASE<=TT.FECHA
					AND TEN.FECHA_TENDENCIA>TT.FECHA
					--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
					--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TT.FECHA)
				GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
		TENDENCIA_1D AS (SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
					ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
					ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
				FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
					WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
					AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T1D
					AND TEN.FECHA_BASE<=TT.FECHA
					AND TEN.FECHA_TENDENCIA>TT.FECHA
					--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
					--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TT.FECHA)
				GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
		TENDENCIA_2D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
					ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
					ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
				FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
					WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
					AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T2D
					AND TEN.FECHA_BASE<=TT.FECHA
					AND TEN.FECHA_TENDENCIA>TT.FECHA
					--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
					--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TT.FECHA)
				GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
		TENDENCIA_5D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
					ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
					ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
				FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
					WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
					AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T5D
					AND TEN.FECHA_BASE<=TT.FECHA
					AND TEN.FECHA_TENDENCIA>TT.FECHA
					--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
					--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TT.FECHA)
				GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')),
	TENDENCIA_10D AS (SELECT 	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD, COUNT(*) CANTIDAD
			FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.T10D
				AND TEN.FECHA_BASE<=TT.FECHA
				AND TEN.FECHA_TENDENCIA>TT.FECHA
				--AND ABS(TEN.PRECIO_BASE-BASE.PRECIO_BASE)*10000<TT.PIPS_BASE
				--AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TT.FECHA)
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24'))			
SELECT TEN10D.FECHA_TENDENCIA FECHA_TENDENCIA, BASE.PRECIO_BASE, BASE.PRECIO_ACTUAL,
		TEN6H.PRECIO_CALCULADO PRECIO6H , TEN12H.PRECIO_CALCULADO PRECIO12H, 
		TEN1D.PRECIO_CALCULADO PRECIO1D, TEN2D.PRECIO_CALCULADO PRECIO2D, 
		TEN5D.PRECIO_CALCULADO PRECIO5D, TEN10D.PRECIO_CALCULADO PRECIO10D,
		ROUND((NVL(TEN6H.PRECIO_CALCULADO,MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO))*TT.PORC6H
			+MULTIPLE_NVL(TEN12H.PRECIO_CALCULADO,TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC12H
			+MULTIPLE_NVL(TEN1D.PRECIO_CALCULADO,TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO,NULL)*TT.PORC1D
			+MULTIPLE_NVL(TEN2D.PRECIO_CALCULADO,TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO,NULL)*TT.PORC2D
			+NVL(TEN5D.PRECIO_CALCULADO,TEN10D.PRECIO_CALCULADO)*TT.PORC5D
			+TEN10D.PRECIO_CALCULADO*TT.PORC10D),5) POND,
			TEN6H.CANTIDAD CANTIDAD6H, TEN12H.CANTIDAD CANTIDAD12H, TEN1D.CANTIDAD CANTIDAD1D, 
			TEN2D.CANTIDAD CANTIDAD2D, TEN5D.CANTIDAD CANTIDAD5D, 
		(NVL(TEN6H.CANTIDAD,0)+NVL(TEN12H.CANTIDAD,0)+NVL(TEN1D.CANTIDAD,0)
		+NVL(TEN2D.CANTIDAD,0)+NVL(TEN5D.CANTIDAD,0)+NVL(TEN10D.CANTIDAD,0)) CANTIDAD
FROM TIEMPO_TENDENCIA TT, BASE_TENDENCIA BASE, TENDENCIA_10D TEN10D
	LEFT JOIN TENDENCIA_6H TEN6H ON TEN10D.FECHA_TENDENCIA=TEN6H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_12H TEN12H ON TEN10D.FECHA_TENDENCIA=TEN12H.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_1D TEN1D ON TEN10D.FECHA_TENDENCIA=TEN1D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_2D TEN2D ON TEN10D.FECHA_TENDENCIA=TEN2D.FECHA_TENDENCIA
	LEFT JOIN TENDENCIA_5D TEN5D ON TEN10D.FECHA_TENDENCIA=TEN5D.FECHA_TENDENCIA
ORDER BY TO_DATE(TEN10D.FECHA_TENDENCIA, 'YYYY/MM/DD HH24:MI') ASC;
