WITH PARAMETROS AS (SELECT 'XD' PERIODO,
	  0 VALIDAR_CANTIDAD,
		(1440*1) TIEMPO_TENDENCIA,
		TO_DATE(
		'
		2017/06/14 20:48
		', 'YYYY/MM/DD HH24:MI') FECHA_PROCESO, 'BUY_SELL_20170204-2' TIPO_TENDENCIA FROM DUAL),
TENDENCIA_CALCULADA AS (SELECT PARAM.FECHA_PROCESO FECHA_BASE,TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			ROUND(AVG(TEN.PROBABILIDAD),5) PROBABILIDAD,
			ROUND(AVG(TEN.PRECIO_BASE),5) PRECIO_BASE,
			--WEEK_MINUTES(TRUNC(TEN.FECHA_TENDENCIA, 'HH24'),TRUNC(PARAM.FECHA_PROCESO, 'HH24'))/60 WM,
			--PARAM.TIEMPO_TENDENCIA/60 PTM,
			--(PARAM.TIEMPO_TENDENCIA/60-WEEK_MINUTES(TRUNC(TEN.FECHA_TENDENCIA, 'HH24'),TRUNC(PARAM.FECHA_PROCESO, 'HH24'))/60) DTM,
			(5+2*(PARAM.TIEMPO_TENDENCIA/60-WEEK_MINUTES(TRUNC(TEN.FECHA_TENDENCIA, 'HH24'),TRUNC(PARAM.FECHA_PROCESO, 'HH24'))/60)) MAYORQ_EXIGIDA,
			COUNT(*) CANTIDAD, MIN(TEN.FECHA_BASE) MINFEBASE, MAX(TEN.FECHA_BASE) MAXFEBASE,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
			MIN(TEN.PRECIO_CALCULADO) MINPRECIO_CALCULADO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO_CALCULADO,
			MAX(FECHA) MAXFE FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO 
			--AND TEN.ID_INDIVIDUO='1484511934277.1881'
		--AND TRUNC(TEN.FECHA_BASE)<>TO_DATE('2017/05/19 00:00','YYYY/MM/DD HH24:MI')
			--AND TEN.FECHA<TO_DATE('2017/06/21 12:47','YYYY/MM/DD HH24:MI')
			--AND TEN.PROBABILIDAD>0.52
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24'), PARAM.FECHA_PROCESO, PARAM.TIEMPO_TENDENCIA),
PROMEDIOS AS (SELECT ROUND(AVG(TEN.CANTIDAD)) AVGCANTIDAD, ROUND(COUNT(TEN.CANTIDAD)) CANTIDAD
		FROM PARAMETROS PARAM, TENDENCIA_CALCULADA TEN),
REGRESION AS (SELECT PARAM.FECHA_PROCESO, ROUND(REGR_R2(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-PARAM.FECHA_PROCESO),5) R2,
		ROUND(REGR_SLOPE(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-PARAM.FECHA_PROCESO),5) PENDIENTE,
		ROUND(REGR_INTERCEPT(TEN.PRECIO_CALCULADO, TEN.FECHA_TENDENCIA-PARAM.FECHA_PROCESO),5) INTERCEP,
		MIN(TEN.PRECIO_CALCULADO) MINPRECIO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO,
		COUNT(*) CANTIDAD_TENDENCIAS, SUM(TEN.CANTIDAD) SUMCANTIDAD,
		ROUND(AVG(TEN.PROBABILIDAD),5) PROBABILIDAD,
		ROUND(AVG(TEN.PRECIO_BASE),5) PRECIO_BASE,
		MIN(TEN.MINPRECIO_CALCULADO) MINPRECIO_EXTREMO, MAX(TEN.MAXPRECIO_CALCULADO) MAXPRECIO_EXTREMO,		
		ROUND(AVG(TEN.PRECIO_CALCULADO),5) AVGPRECIO,
		ROUND(STDDEV(TEN.PRECIO_CALCULADO),5) DESV,		
		MIN(TEN.MINFETENDENCIA) MINFETENDENCIA, MAX(TEN.MAXFETENDENCIA) MAXFETENDENCIA,
		MIN(TEN.MINFEBASE) MINFEBASE, MAX(TEN.MAXFEBASE) MAXFEBASE, MAX(MAXFE) MAXFECHA
		FROM PARAMETROS PARAM, PROMEDIOS PROM, TENDENCIA_CALCULADA TEN 
			WHERE ((TEN.CANTIDAD)>TEN.MAYORQ_EXIGIDA OR (PARAM.VALIDAR_CANTIDAD=0))
		)
--SELECT (TEN.CANTIDAD-TEN.MAYORQ_EXIGIDA) DIFFCANT, TEN.*, ROUND(TEN.CANTIDAD/PROM.AVGCANTIDAD,2) FACTORCANTIDAD FROM PARAMETROS PARAM, PROMEDIOS PROM, TENDENCIA_CALCULADA TEN
--ORDER BY TEN.FECHA_TENDENCIA aSC;
--ORDER BY TEN.PRECIO_CALCULADO deSC;
SELECT REG.*  FROM PARAMETROS PARAM, REGRESION REG
;

WITH 
PARAMETROS AS (
		SELECT 'XD' PERIODO, (1440*13) TIEMPO_TENDENCIA,
		TO_DATE(
		'
		2017.06.29 06:11
		'
		, 'YYYY/MM/DD HH24:MI') FECHA_PROCESO, 'BUY_SELL_20170204-2' TIPO_TENDENCIA 
		FROM DUAL	
),
DETALLE_TENDENCIA AS (SELECT 
			--WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE) MINUTES, PARAM.TIEMPO_TENDENCIA, 
			TEN.*
		FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
--			AND TEN.ID_INDIVIDUO='1477365411387.11169'
		),
TENDENCIA_CALCULADA AS (SELECT 
			TRUNC(TEN.FECHA_BASE, 'HH24') FECHA_BASE,
			TRUNC(TEN.FECHA_TENDENCIA, 'HH24') FECHA_TENDENCIA,
			ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
			ROUND(AVG(TEN.PROBABILIDAD),5) PROBABILIDAD,
			MIN(TEN.PRECIO_CALCULADO) MINPRECIO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO,
			COUNT(*) CANTIDAD_TENDENCIAS,
			MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
			MIN(TEN.FECHA_APERTURA) MINFEAPERTURA, MAX(TEN.FECHA_APERTURA) MAXFEAPERTURA,
			MAX(FECHA) MAXFE
		FROM PARAMETROS PARAM, TENDENCIA TEN
			WHERE TEN.TIPO_TENDENCIA=PARAM.TIPO_TENDENCIA
			AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<PARAM.TIEMPO_TENDENCIA
			AND TEN.FECHA_BASE<=PARAM.FECHA_PROCESO --AND (TEN.FECHA_CIERRE IS NULL OR TEN.FECHA_CIERRE>TEN.FECHA_TENDENCIA)
			AND TEN.FECHA_TENDENCIA>PARAM.FECHA_PROCESO
--			AND TEN.ID_INDIVIDUO='1477365411387.11169'
		--AND TEN.FECHA<TRUNC(SYSDATE)-1
		GROUP BY TRUNC(TEN.FECHA_TENDENCIA, 'HH24'), TRUNC(TEN.FECHA_BASE, 'HH24')
		)
--SELECT TRUNC(TEN.FECHA_APERTURA), COUNT(*),	ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,	
--	ROUND(AVG(TEN.PROBABILIDAD),2) PROB,	MIN(TEN.PRECIO_CALCULADO) MINPRECIO, MAX(TEN.PRECIO_CALCULADO) MAXPRECIO,
--	MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA FROM DETALLE_TENDENCIA TEN
--GROUP BY TRUNC(TEN.FECHA_APERTURA) ORDER BY TRUNC(TEN.FECHA_APERTURA) ASC;

--SELECT TEN.* FROM DETALLE_TENDENCIA TEN 
---WHERE TRUNC(TEN.FECHA_TENDENCIA,'HH24')=TO_DATE('2017/05/29 00:00', 'YYYY:MM:DD HH24:MI') --AND TRUNC(TEN.FECHA_BASE,'HH24')=TO_DATE('2017/02/01 03:00', 'YYYY:MM:DD HH24:MI')
--WHERE TRUNC(TEN.FECHA_TENDENCIA)<=TO_DATE('2017/05/30 00:00', 'YYYY:MM:DD HH24:MI') 
--WHERE TRUNC(TEN.FECHA_BASE,'HH24')=TO_DATE('2017/06/27 00:00', 'YYYY:MM:DD HH24:MI') --AND TRUNC(TEN.FECHA_TENDENCIA,'HH24')=TO_DATE('2017/05/29 11:00', 'YYYY:MM:DD HH24:MI') 
--ORDER BY FECHA DESC;
--ORDER BY TEN.FECHA_TENDENCIA ASC
--ORDER BY TEN.FECHA_BASE ASC;
--ORDER BY TEN.PRECIO_CALCULADO deSC;

SELECT --TEN.FECHA_BASE, --TEN.FECHA_TENDENCIA, 
	TRUNC(TEN.FECHA_BASE) TFEBASE,
	ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,	
	SUM(TEN.CANTIDAD_TENDENCIAS) SUMCANTIDAD, ROUND(AVG(TEN.PROBABILIDAD),2) PROB,
	MIN(TEN.MINPRECIO) MINPRECIO, MAX(TEN.MAXPRECIO) MAXPRECIO,
	MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA,
	MIN(TEN.FECHA_BASE) MINFECHA_BASE, MAX(TEN.FECHA_BASE) MAXFECHA_BASE,
	MIN(TEN.MINFEAPERTURA) MINFECHA_APERTURA, MAX(TEN.MAXFEAPERTURA) MAXFECHA_APERTURA
	FROM PARAMETROS PARAM, TENDENCIA_CALCULADA TEN	
--	WHERE TEN.FECHA_TENDENCIA<=TO_DATE('2017/06/01 00:00', 'YYYY/MM/DD HH24:MI')	
--GROUP BY TEN.FECHA_BASE--,TEN.FECHA_TENDENCIA
GROUP BY TRUNC(TEN.FECHA_BASE)
--ORDER BY COUNT(*) DESC
--ORDER BY SUMCANTIDAD DESC
--ORDER BY TEN.FECHA_TENDENCIA ASC
--ORDER BY MINPRECIO ASC
--ORDER BY PRECIO_CALCULADO ASC
--ORDER BY TEN.FECHA_BASE ASC
ORDER BY TRUNC(TEN.FECHA_BASE) deSC
;

