SELECT * FROM TENDENCIA_QUERY TQ;

SELECT * FROM TENDENCIA_QUERY TQ
WHERE TQ.TEN_PIPS<0 
ORDER BY (TEN_PIPS_ACTUALES-(AVG_PIPS_POS+AVG_PIPS_NEG)/2) ASC
--TEN_PROBABILIDAD DESC
;

SELECT TO_CHAR(TQ.TEN_FECHA_TENDENCIA, 'YYYY/MM/DD HH24'), COUNT(*) CONT, 
  ROUND(AVG(TQ.TEN_PIPS),4) AVG_PIPS, ROUND(AVG(TQ.TEN_PRECIO_CALCULADO),4) AVG_PRECIO
FROM TENDENCIA_QUERY TQ
GROUP BY TO_CHAR(TQ.TEN_FECHA_TENDENCIA, 'YYYY/MM/DD HH24')
ORDER BY TO_CHAR(TQ.TEN_FECHA_TENDENCIA, 'YYYY/MM/DD HH24') ASC
--ORDER BY COUNT(*) DESC
;

SELECT 'NEGATIVOS', COUNT(*) CANTIDAD, ROUND(STDDEV(TQ.CANTIDAD_POSITIVOS),4) CANTIDAD_POSITIVOS,
  ROUND(STDDEV(TQ.CANTIDAD_NEGATIVOS),4) CANTIDAD_NEGATIVOS,	ROUND(STDDEV(TQ.CANTIDAD_TOTAL),4) CANTIDAD_TOTAL,
  ROUND(STDDEV(TQ.PIPS_POSITIVOS),4) PIPS_POSITIVOS,	ROUND(STDDEV(TQ.PIPS_NEGATIVOS),4) PIPS_NEGATIVOS,
  ROUND(STDDEV(TQ.PIPS_TOTALES),4) PIPS_TOTALES,	ROUND(STDDEV(TQ.PIPS_MINIMOS_POS),4) PIPS_MINIMOS_POS,
  ROUND(STDDEV(TQ.PIPS_MINIMOS_NEG),4) PIPS_MINIMOS_NEG,	ROUND(STDDEV(TQ.PIPS_MINIMOS),4) PIPS_MINIMOS,
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MINIMO_POS),4) PIPS_RETROCESO_MINIMO_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MINIMO_NEG),4) PIPS_RETROCESO_MINIMO_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MINIMO_TOTAL),4) PIPS_RETROCESO_MINIMO_TOTAL,	
  ROUND(STDDEV(TQ.PIPS_MAXIMOS_POS),4) PIPS_MAXIMOS_POS,	ROUND(STDDEV(TQ.PIPS_MAXIMOS_NEG),4) PIPS_MAXIMOS_NEG,
  ROUND(STDDEV(TQ.PIPS_MAXIMOS),4) PIPS_MAXIMOS,	ROUND(STDDEV(TQ.PIPS_RETROCESO_MAXIMO_POS),4) PIPS_RETROCESO_MAXIMO_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MAXIMO_NEG),4) PIPS_RETROCESO_MAXIMO_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MAXIMO_TOTAL),4) PIPS_RETROCESO_MAXIMO_TOTAL,
  ROUND(STDDEV(TQ.AVG_PIPS_POS),4) AVG_PIPS_POS,	ROUND(STDDEV(TQ.AVG_PIPS_NEG),4) AVG_PIPS_NEG,
  ROUND(STDDEV(TQ.AVG_PIPS),4) AVG_PIPS,	ROUND(STDDEV(TQ.PIPS_RETROCESO_PROMEDIO_POS),4) PIPS_RETROCESO_PROMEDIO_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_PROMEDIO_NEG),4) PIPS_RETROCESO_PROMEDIO_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_PROMEDIO_TOTAL),4) PIPS_RETROCESO_PROMEDIO_TOTAL,	
  ROUND(STDDEV(TQ.PIPS_MODA_POS),4) PIPS_MODA_POS,	ROUND(STDDEV(TQ.PIPS_MODA_NEG),4) PIPS_MODA_NEG,
  ROUND(STDDEV(TQ.PIPS_MODA),4) PIPS_MODA,	ROUND(STDDEV(TQ.PIPS_RETROCESO_MODA_POS),4) PIPS_RETROCESO_MODA_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MODA_NEG),4) PIPS_RETROCESO_MODA_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MODA_TOTAL),4) PIPS_RETROCESO_MODA_TOTAL,	
  ROUND(STDDEV(TQ.DUR_MIN_POS),4) DUR_MIN_POS,	ROUND(STDDEV(TQ.DUR_MIN_NEG),4) DUR_MIN_NEG,	
  ROUND(STDDEV(TQ.DUR_MIN),4) DUR_MIN,	ROUND(STDDEV(TQ.DUR_MAX_POS),4) DUR_MAX_POS,	
  ROUND(STDDEV(TQ.DUR_MAX_NEG),4) DUR_MAX_NEG,	ROUND(STDDEV(TQ.DUR_MAX),4) DUR_MAX,	
  ROUND(STDDEV(TQ.DUR_PROM_POS),4) DUR_PROM_POS,	ROUND(STDDEV(TQ.DUR_PROM_NEG),4) DUR_PROM_NEG,	
  ROUND(STDDEV(TQ.DUR_PROM),4) DUR_PROM,	ROUND(STDDEV(TQ.DUR_MODA_POS),4) DUR_MODA_POS,	
  ROUND(STDDEV(TQ.DUR_MODA_NEG),4) DUR_MODA_NEG,	ROUND(STDDEV(TQ.DUR_MODA),4) DUR_MODA,	
  ROUND(STDDEV(TQ.DUR_DESV_POS),4) DUR_DESV_POS,	ROUND(STDDEV(TQ.DUR_DESV_NEG),4) DUR_DESV_NEG,	
  ROUND(STDDEV(TQ.DUR_DESV),4) DUR_DESV,	
  --ROUND(STDDEV(TQ.TEN_FECHA_BASE),4) TEN_FECHA_BASE,	
  ROUND(STDDEV(TQ.TEN_PRECIO_BASE),4) TEN_PRECIO_BASE,	
  --ROUND(STDDEV(TQ.TEN_ID_INDIVIDUO),4) TEN_ID_INDIVIDUO,	
  --ROUND(STDDEV(TQ.TEN_FECHA_TENDENCIA),4) TEN_FECHA_TENDENCIA,	
  ROUND(STDDEV(TQ.TEN_PIPS),4) TEN_PIPS,	
  ROUND(STDDEV(TQ.TEN_PRECIO_CALCULADO),4) TEN_PRECIO_CALCULADO,	
  --ROUND(STDDEV(TQ.TEN_TIPO_TENDENCIA),4) TEN_TIPO_TENDENCIA,	
  --ROUND(STDDEV(TQ.TEN_FECHA_APERTURA),4) TEN_FECHA_APERTURA,	
  ROUND(STDDEV(TQ.TEN_OPEN_PRICE),4) TEN_OPEN_PRICE,	
  ROUND(STDDEV(TQ.TEN_DURACION),4) TEN_DURACION,	ROUND(STDDEV(TQ.TEN_PIPS_ACTUALES),4) TEN_PIPS_ACTUALES,	
  ROUND(STDDEV(TQ.TEN_DURACION_ACTUAL),4) TEN_DURACION_ACTUAL,	
  ROUND(STDDEV(TQ.TEN_PROBABILIDAD_POSITIVOS),4) TEN_PROBABILIDAD_POSITIVOS,	
  ROUND(STDDEV(TQ.TEN_PROBABILIDAD_NEGATIVOS),4) TEN_PROBABILIDAD_NEGATIVOS,	
  ROUND(STDDEV(TQ.TEN_PROBABILIDAD),4) TEN_PROBABILIDAD,	
  --ROUND(STDDEV(TQ.TEN_FECHA),4) TEN_FECHA,	ROUND(STDDEV(TQ.TEN_FECHA_CIERRE),4) TEN_FECHA_CIERRE,	
  ROUND(STDDEV(TQ.OPER_TEN_PIPS),4) OPER_TEN_PIPS
  FROM TENDENCIA_QUERY TQ
  WHERE TQ.TEN_PIPS<0
UNION ALL
SELECT 'POSITIVOS', COUNT(*) CANTIDAD,  ROUND(STDDEV(TQ.CANTIDAD_POSITIVOS),4) CANTIDAD_POSITIVOS,
  ROUND(STDDEV(TQ.CANTIDAD_NEGATIVOS),4) CANTIDAD_NEGATIVOS,	ROUND(STDDEV(TQ.CANTIDAD_TOTAL),4) CANTIDAD_TOTAL,
  ROUND(STDDEV(TQ.PIPS_POSITIVOS),4) PIPS_POSITIVOS,	ROUND(STDDEV(TQ.PIPS_NEGATIVOS),4) PIPS_NEGATIVOS,
  ROUND(STDDEV(TQ.PIPS_TOTALES),4) PIPS_TOTALES,	ROUND(STDDEV(TQ.PIPS_MINIMOS_POS),4) PIPS_MINIMOS_POS,
  ROUND(STDDEV(TQ.PIPS_MINIMOS_NEG),4) PIPS_MINIMOS_NEG,	ROUND(STDDEV(TQ.PIPS_MINIMOS),4) PIPS_MINIMOS,
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MINIMO_POS),4) PIPS_RETROCESO_MINIMO_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MINIMO_NEG),4) PIPS_RETROCESO_MINIMO_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MINIMO_TOTAL),4) PIPS_RETROCESO_MINIMO_TOTAL,	
  ROUND(STDDEV(TQ.PIPS_MAXIMOS_POS),4) PIPS_MAXIMOS_POS,	ROUND(STDDEV(TQ.PIPS_MAXIMOS_NEG),4) PIPS_MAXIMOS_NEG,
  ROUND(STDDEV(TQ.PIPS_MAXIMOS),4) PIPS_MAXIMOS,	ROUND(STDDEV(TQ.PIPS_RETROCESO_MAXIMO_POS),4) PIPS_RETROCESO_MAXIMO_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MAXIMO_NEG),4) PIPS_RETROCESO_MAXIMO_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MAXIMO_TOTAL),4) PIPS_RETROCESO_MAXIMO_TOTAL,
  ROUND(STDDEV(TQ.AVG_PIPS_POS),4) AVG_PIPS_POS,	ROUND(STDDEV(TQ.AVG_PIPS_NEG),4) AVG_PIPS_NEG,
  ROUND(STDDEV(TQ.AVG_PIPS),4) AVG_PIPS,	ROUND(STDDEV(TQ.PIPS_RETROCESO_PROMEDIO_POS),4) PIPS_RETROCESO_PROMEDIO_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_PROMEDIO_NEG),4) PIPS_RETROCESO_PROMEDIO_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_PROMEDIO_TOTAL),4) PIPS_RETROCESO_PROMEDIO_TOTAL,	
  ROUND(STDDEV(TQ.PIPS_MODA_POS),4) PIPS_MODA_POS,	ROUND(STDDEV(TQ.PIPS_MODA_NEG),4) PIPS_MODA_NEG,
  ROUND(STDDEV(TQ.PIPS_MODA),4) PIPS_MODA,	ROUND(STDDEV(TQ.PIPS_RETROCESO_MODA_POS),4) PIPS_RETROCESO_MODA_POS,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MODA_NEG),4) PIPS_RETROCESO_MODA_NEG,	
  ROUND(STDDEV(TQ.PIPS_RETROCESO_MODA_TOTAL),4) PIPS_RETROCESO_MODA_TOTAL,	
  ROUND(STDDEV(TQ.DUR_MIN_POS),4) DUR_MIN_POS,	ROUND(STDDEV(TQ.DUR_MIN_NEG),4) DUR_MIN_NEG,	
  ROUND(STDDEV(TQ.DUR_MIN),4) DUR_MIN,	ROUND(STDDEV(TQ.DUR_MAX_POS),4) DUR_MAX_POS,	
  ROUND(STDDEV(TQ.DUR_MAX_NEG),4) DUR_MAX_NEG,	ROUND(STDDEV(TQ.DUR_MAX),4) DUR_MAX,	
  ROUND(STDDEV(TQ.DUR_PROM_POS),4) DUR_PROM_POS,	ROUND(STDDEV(TQ.DUR_PROM_NEG),4) DUR_PROM_NEG,	
  ROUND(STDDEV(TQ.DUR_PROM),4) DUR_PROM,	ROUND(STDDEV(TQ.DUR_MODA_POS),4) DUR_MODA_POS,	
  ROUND(STDDEV(TQ.DUR_MODA_NEG),4) DUR_MODA_NEG,	ROUND(STDDEV(TQ.DUR_MODA),4) DUR_MODA,	
  ROUND(STDDEV(TQ.DUR_DESV_POS),4) DUR_DESV_POS,	ROUND(STDDEV(TQ.DUR_DESV_NEG),4) DUR_DESV_NEG,	
  ROUND(STDDEV(TQ.DUR_DESV),4) DUR_DESV,	
  --ROUND(STDDEV(TQ.TEN_FECHA_BASE),4) TEN_FECHA_BASE,	
  ROUND(STDDEV(TQ.TEN_PRECIO_BASE),4) TEN_PRECIO_BASE,	
  --ROUND(STDDEV(TQ.TEN_ID_INDIVIDUO),4) TEN_ID_INDIVIDUO,	
  --ROUND(STDDEV(TQ.TEN_FECHA_TENDENCIA),4) TEN_FECHA_TENDENCIA,	
  ROUND(STDDEV(TQ.TEN_PIPS),4) TEN_PIPS,	
  ROUND(STDDEV(TQ.TEN_PRECIO_CALCULADO),4) TEN_PRECIO_CALCULADO,	
  --ROUND(STDDEV(TQ.TEN_TIPO_TENDENCIA),4) TEN_TIPO_TENDENCIA,	
  --ROUND(STDDEV(TQ.TEN_FECHA_APERTURA),4) TEN_FECHA_APERTURA,	
  ROUND(STDDEV(TQ.TEN_OPEN_PRICE),4) TEN_OPEN_PRICE,	
  ROUND(STDDEV(TQ.TEN_DURACION),4) TEN_DURACION,	ROUND(STDDEV(TQ.TEN_PIPS_ACTUALES),4) TEN_PIPS_ACTUALES,	
  ROUND(STDDEV(TQ.TEN_DURACION_ACTUAL),4) TEN_DURACION_ACTUAL,	
  ROUND(STDDEV(TQ.TEN_PROBABILIDAD_POSITIVOS),4) TEN_PROBABILIDAD_POSITIVOS,	
  ROUND(STDDEV(TQ.TEN_PROBABILIDAD_NEGATIVOS),4) TEN_PROBABILIDAD_NEGATIVOS,	
  ROUND(STDDEV(TQ.TEN_PROBABILIDAD),4) TEN_PROBABILIDAD,	
  --ROUND(STDDEV(TQ.TEN_FECHA),4) TEN_FECHA,	ROUND(STDDEV(TQ.TEN_FECHA_CIERRE),4) TEN_FECHA_CIERRE,	
  ROUND(STDDEV(TQ.OPER_TEN_PIPS),4) OPER_TEN_PIPS
  FROM TENDENCIA_QUERY TQ
  WHERE TQ.TEN_PIPS>0
;
