SELECT TP.* 
FROM TENDENCIA_PROCESADA TP 
--ORDER BY FECHA_BASE DESC, TIPO ASC
--ORDER BY FECHA DESC
;

SELECT TP.VALOR_PROBABLE,  TP.* FROM TENDENCIA_PROCESADA TP 
WHERE TP.FECHA_BASE<TO_DATE('2012/06/07 16:41', 'YYYY/MM/DD HH24:MI')
--AND TP.FECHA_BASE_FIN>=TO_DATE('2012/06/04 02:00', 'YYYY/MM/DD HH24:MI')
--AND TP.PRECIO_MAXIMO>1.03941 AND TP.PRECIO_MAXIMO<1.04100
ORDER BY FECHA_BASE DESC, TIPO ASC
;

SELECT COUNT(*) CANTIDAD FROM (
  SELECT TP.FECHA_BASE, MIN(TP.VALOR_PROBABLE), 
    MIN(DH.LOW) MIN_DH, MAX(DH.HIGH) MAX_DH,
    MIN(TP.PRECIO_MINIMO), MIN(TP.PRECIO_MAXIMO),
    MIN(TP.CANTIDAD),
    ROUND(AVG(TP.PRECIO_MINIMO-TP.PRECIO_MAXIMO),5),
    MIN(DH.FECHA) MIN_FECHA_DH, MAX(DH.FECHA) MAX_FECHA_DH
  FROM TENDENCIA_PROCESADA TP, DATOHISTORICO DH
    WHERE DH.FECHA>=TP.FECHA_BASE AND DH.FECHA<=TP.FECHA_BASE_FIN
    AND TP.TIPO='BASE'
    --AND TP.FECHA_BASE=TO_DATE('2012/02/16 12:00', 'YYYY/MM/DD HH24:MI')
  GROUP BY TP.FECHA_BASE
  HAVING MIN(TP.VALOR_PROBABLE) NOT BETWEEN MIN(DH.LOW) AND MAX(DH.HIGH)
  --AND MIN(TP.VALOR_PROBABLE)<MIN(DH.LOW)
  --ORDER BY (MIN(TP.VALOR_PROBABLE)-MAX(DH.HIGH)) DESC
  ORDER BY MIN(TP.CANTIDAD) DESC
)
;

  SELECT TP.FECHA_BASE, (TP.VALOR_PROBABLE), 
    (DH.LOW) MIN_DH, (DH.HIGH) MAX_DH,
    (TP.PRECIO_MINIMO), (TP.PRECIO_MAXIMO),
    (TP.CANTIDAD),
    (DH.FECHA) MIN_FECHA_DH, (DH.FECHA) MAX_FECHA_DH
  FROM TENDENCIA_PROCESADA TP, DATOHISTORICO DH
    WHERE DH.FECHA>=TP.FECHA_BASE AND DH.FECHA<=TP.FECHA_BASE_FIN
    AND TP.TIPO='BASE'
    AND TP.FECHA_BASE=TO_DATE('2012/02/16 12:00', 'YYYY/MM/DD HH24:MI')
  --HAVING MIN(TP.VALOR_PROBABLE) NOT BETWEEN MIN(DH.LOW) AND MAX(DH.HIGH)
  --AND MIN(TP.VALOR_PROBABLE)>MAX(DH.HIGH)
  --ORDER BY (MIN(TP.VALOR_PROBABLE)-MAX(DH.HIGH)) DESC
  ;

SELECT ROUND(AVG(TP.PRECIO_MINIMO-TP.PRECIO_MAXIMO),5)*100000
FROM TENDENCIA_PROCESADA TP;

SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, TP.TIPO, TP.VALOR_PROBABLE,
  OPER.OPEN_PRICE, OPER.PIPS, OPER.TAKE_PROFIT, OPER.STOP_LOSS,
  (OPER.OPEN_PRICE-TP.VALOR_PROBABLE)*100000 PIPS_CALCULADOS,
  OPER.FECHA_CIERRE
FROM TENDENCIA_PROCESADA TP 
    INNER JOIN OPERACION OPER 
      ON TP.FECHA_BASE=OPER.FECHA_APERTURA
      AND TP.VALOR_PROBABLE<OPER.OPEN_PRICE
ORDER BY TP.FECHA_BASE ASC;


