SELECT TEN.FECHA_BASE,
TEN.TIPO_TENDENCIA,  COUNT(*), MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
FROM TENDENCIA TEN 
WHERE TEN.TIPO_TENDENCIA = 'BUY_SELL_20170204-2'
AND TEN.FECHA_BASE<=TO_DATE('2016/12/01 00:00','YYYY/MM/DD HH24:MI')
--AND TEN.FECHA_TENDENCIA>=TO_DATE('2017/02/16 15:13','YYYY/MM/DD HH24:MI')
GROUP BY TEN.FECHA_BASE, 
TEN.TIPO_TENDENCIA
ORDER BY TEN.FECHA_BASE DESC, TEN.TIPO_TENDENCIA ASC;

SELECT TRUNC(TEN.FECHA_BASE, 'HH24') FECHA_BASE, 
TEN.TIPO_TENDENCIA,  COUNT(*), MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
FROM TENDENCIA TEN 
WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170204-2'
--AND TEN.FECHA_BASE<=TO_DATE('2017/01/23 18:02','YYYY/MM/DD HH24:MI')
--AND TEN.FECHA_TENDENCIA>TO_DATE('2017/01/27 23:56','YYYY/MM/DD HH24:MI')
GROUP BY TRUNC(TEN.FECHA_BASE, 'HH24'), TEN.TIPO_TENDENCIA
ORDER BY TRUNC(TEN.FECHA_BASE, 'HH24') DESC, TEN.TIPO_TENDENCIA ASC;

SELECT TRUNC(TEN.FECHA_BASE) FECHA_BASE, 
TEN.TIPO_TENDENCIA,  COUNT(*), MIN(TEN.FECHA_TENDENCIA) MINFETENDENCIA, MAX(TEN.FECHA_TENDENCIA) MAXFETENDENCIA
FROM TENDENCIA TEN 
WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170204-2'
--AND TEN.FECHA_BASE<=TO_DATE('2017/01/23 18:02','YYYY/MM/DD HH24:MI')
--AND TEN.FECHA_TENDENCIA>TO_DATE('2017/01/27 23:56','YYYY/MM/DD HH24:MI')
GROUP BY TRUNC(TEN.FECHA_BASE), TEN.TIPO_TENDENCIA
ORDER BY TRUNC(TEN.FECHA_BASE) DESC, TEN.TIPO_TENDENCIA ASC;

WITH TIEMPO_TENDENCIA AS (SELECT (24*10/24)*24*60 TIEMPO, TO_DATE('2017/01/26 17:39','YYYY/MM/DD HH24:MI') FECHA,
		'xBUY_SELL_20170131-3' TIPO_TENDENCIA1, 'xBUY_SELL_20170125' TIPO_TENDENCIA2, 'BUY_SELL_20170204-2' TIPO_TENDENCIA3,
		1020 PIPS_BASE
		FROM DUAL),
	BASE_TENDENCIA AS (SELECT AVG(TEN.PRECIO_BASE) PRECIO_BASE
						FROM TIEMPO_TENDENCIA TT, TENDENCIA TEN WHERE TEN.FECHA_BASE=TT.FECHA)
	SELECT 	TEN.*
	FROM BASE_TENDENCIA BASE, TIEMPO_TENDENCIA TT, TENDENCIA TEN
		WHERE TEN.TIPO_TENDENCIA IN (TIPO_TENDENCIA1,TIPO_TENDENCIA2,TIPO_TENDENCIA3)
		AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<TT.TIEMPO
		AND TEN.FECHA_BASE<=TT.FECHA
		AND TEN.FECHA_TENDENCIA>TT.FECHA
		AND TEN.FECHA_TENDENCIA>=TO_DATE('20170131', 'YYYYMMDD')
	ORDER BY TEN.FECHA_TENDENCIA ASC
	--ORDER BY TEN.FECHA_APERTURA DESC
;

SELECT *
			FROM TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170204-2')
				--AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<(24*0.25/24)*24*60
				AND TEN.FECHA_BASE=to_date('2017/01/30 00:02','yyyy/mm/dd hh24:mi')
				AND TEN.FECHA_TENDENCIA>to_date('2017/01/30 00:02','yyyy/mm/dd hh24:mi')
				--AND TRUNC(TEN.FECHA_TENDENCIA,'HH24')=to_date('2017/01/30 00:00','yyyy/mm/dd hh24:mi')
order by ten.fecha_tendencia asc
				--ORDER BY TEN.PRECIO_CALCULADO ASC
			;
			
SELECT TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00' FECHA_TENDENCIA,
				ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO,
				ROUND(AVG(TEN.PROBABILIDAD),2) PROBABILIDAD
			FROM TENDENCIA TEN
				WHERE TEN.TIPO_TENDENCIA IN ('BUY_SELL_20170131-3')
				AND WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<(24*0.25/24)*24*60
				AND TEN.FECHA_BASE<=to_date('2017/01/30 00:02','yyyy/mm/dd hh24:mi')
				AND TEN.FECHA_TENDENCIA>to_date('2017/01/30 00:02','yyyy/mm/dd hh24:mi')
			GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24');

SELECT MAX(TEN.FECHA_BASE) MAX_FEBASE, MAX(PRECIO_BASE) MAX_PRECIOBASE, MAX(FECHA_APERTURA) MAXFEAPERTURA,
	TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24') FECHA_TENDENCIA,
	--TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24:MI') FECHA_TENDENCIA,
	ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5) PRECIO_CALCULADO, 
	COUNT(*), MAX(WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)) WEEK_MIN
        FROM TENDENCIA TEN
	WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
	--WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<(24*1/24)*24*60
	--AND TEN.FECHA_TENDENCIA>=TO_DATE('2016/12/01 12:59','YYYY/MM/DD HH24:MI')
	AND TEN.FECHA_BASE<=TO_DATE('2016/12/02 21:59','YYYY/MM/DD HH24:MI')
GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')
ORDER BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24') ASC
				--ORDER BY MAX(TEN.FECHA_BASE) DESC
				;

SELECT TEN.FECHA_BASE, TEN.PRECIO_BASE, 
	TEN.FECHA_TENDENCIA, TEN.FECHA_APERTURA, TEN.FECHA_CIERRE, 
	TEN.PRECIO_CALCULADO, (TEN.PIPS+TEN.PIPS_ACTUALES) PIPS, TEN.PIPS_REALES, TEN.PIPS_ACTUALES, 
	TEN.ID_INDIVIDUO, TEN.*
    FROM TENDENCIA TEN
	WHERE TEN.TIPO_TENDENCIA='BUY_SELL_20170125'
	--WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<(24*1/24)*24*60
	--AND TEN.FECHA_TENDENCIA>=TO_DATE('2016/12/01 12:59','YYYY/MM/DD HH24:MI')
	AND TEN.FECHA_BASE<=TO_DATE('2016/12/02 13:59','YYYY/MM/DD HH24:MI')
ORDER BY TEN.FECHA_TENDENCIA ASC, TEN.FECHA_BASE ASC
;

SELECT COUNT(*) FROM TENDENCIA TEN WHERE TEN.DURACION=0 
AND TEN.TIPO_TENDENCIA='BUY_SELL_20170131-3';

SELECT * FROM TENDENCIA WHERE DURACION=0 ORDER BY FECHA_TENDENCIA ASC;

SELECT 	TRUNC(SYSDATE, 'HH')+TRUNC(TO_CHAR(SYSDATE, 'MI')/20)*20/1440 SUMA,
	GROUP_BY_MINUTES(SYSDATE, 20) GDATE
	FROM DUAL;

SELECT WEEK_MINUTES(TO_DATE('2016/11/14 00:00', 'YYYY/MM/DD HH24:MI'),TO_DATE('2016/11/11 22:38', 'YYYY/MM/DD HH24:MI')) DURACION
FROM DUAL;


SELECT * FROM REGRESION_6H REG6H, REGRESION_12H REG12H, REGRESION_1D REG1D,
	REGRESION_2D REG2D, REGRESION_3D REG3D, REGRESION_5D REG5D, REGRESION_10D REG10D
WHERE (REG6H.PENDIENTE>0 AND REG12H.PENDIENTE>0 AND REG1D.PENDIENTE>0 AND REG2D.PENDIENTE>0 AND REG3D.PENDIENTE>0 AND REG5D.PENDIENTE>0 AND REG10D.PENDIENTE>0)
	OR (REG6H.PENDIENTE<0 AND REG12H.PENDIENTE<0 AND REG1D.PENDIENTE<0 AND REG2D.PENDIENTE<0 AND REG3D.PENDIENTE<0 AND REG5D.PENDIENTE<0 AND REG10D.PENDIENTE<0)
;
