--CREATE TABLE TENDENCIA_QUERY AS 
INSERT INTO TENDENCIA_QUERY (
SELECT 
  DEST.*,
  TEN.FECHA_BASE TEN_FECHA_BASE,	TEN.PRECIO_BASE TEN_PRECIO_BASE,	TEN.ID_INDIVIDUO TEN_ID_INDIVIDUO,	TEN.FECHA_TENDENCIA TEN_FECHA_TENDENCIA,	TEN.PIPS TEN_PIPS,	TEN.PRECIO_CALCULADO TEN_PRECIO_CALCULADO,	TEN.TIPO_TENDENCIA TEN_TIPO_TENDENCIA,	TEN.FECHA_APERTURA TEN_FECHA_APERTURA,	TEN.OPEN_PRICE TEN_OPEN_PRICE,	TEN.DURACION TEN_DURACION,	TEN.PIPS_ACTUALES TEN_PIPS_ACTUALES,	TEN.DURACION_ACTUAL TEN_DURACION_ACTUAL,	TEN.PROBABILIDAD_POSITIVOS TEN_PROBABILIDAD_POSITIVOS,	TEN.PROBABILIDAD_NEGATIVOS TEN_PROBABILIDAD_NEGATIVOS,	TEN.PROBABILIDAD TEN_PROBABILIDAD,	TEN.FECHA TEN_FECHA,	TEN.FECHA_CIERRE TEN_FECHA_CIERRE,
  (OPER.PIPS*TEN.PIPS) OPER_TEN_PIPS
  FROM TENDENCIA TEN 
    INNER JOIN OPERACION OPER 
    ON TEN.ID_INDIVIDUO=OPER.ID_INDIVIDUO
    AND TEN.FECHA_APERTURA=OPER.FECHA_APERTURA
    INNER JOIN DETALLE_ESTADISTICAS DEST
    ON DEST.ID_INDIVIDUO=TEN.ID_INDIVIDUO
  --WHERE TEN.ID_INDIVIDUO='1340728292919.41507'
  WHERE (OPER.PIPS*TEN.PIPS>0) --AND TEN.PIPS<0
  )
;

