SET echo OFF; 
SET feedback off;
SET term off;
SET pagesize 0;
SET linesize 5000;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';

SELECT 'FECHA_TENDENCIA='||TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')||':00,PRECIO_CALCULADO='||
ROUND(SUM(TEN.PRECIO_CALCULADO*TEN.PROBABILIDAD)/SUM(TEN.PROBABILIDAD),5)
        FROM TENDENCIA TEN				
          --INNER JOIN (SELECT TO_DATE('2016/11/14 23:59','YYYY/MM/DD HH24:MI') FECHA_PROCESO FROM DUAL) FP 
          --ON TEN.FECHA_BASE=FP.FECHA_PROCESO 
					--AND TEN4.ID_INDIVIDUO='1454889600000.1019'
					WHERE WEEK_MINUTES(TEN.FECHA_TENDENCIA,TEN.FECHA_BASE)<24*60 
					AND TEN.FECHA_BASE<TEN.FECHA_TENDENCIA-1/24
					--AND TEN.FECHA_TENDENCIA>=TO_DATE('2016/11/14 00:00','YYYY/MM/DD HH24:MI')
				--ORDER BY TEN4.FECHA_APERTURA ASC
				GROUP BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24')
				ORDER BY TO_CHAR(TEN.FECHA_TENDENCIA, 'YYYY.MM.DD HH24') ASC
				;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
SPOOL OFF;
SET echo ON; 
