SELECT DATPO.MIN_EXTREMO_SINFILTRAR, DATPO.MAX_EXTREMO_SINFILTRAR, TPO.LIMIT_APERTURA, TPO.PRECIO_CALCULADO,
	TPO.* FROM TENDENCIA_PARA_OPERAR TPO
	INNER JOIN DATO_ADICIONAL_TPO DATPO ON TPO.FECHA_BASE=DATPO.FECHA_BASE
WHERE TPO.FECHA_BASE>=TO_DATE('2015/07/07 16:17', 'YYYY/MM/DD HH24:MI')
AND TPO.TIPO_TENDENCIA='MEJOR_TENDENCIA' AND DATPO.MAX_EXTREMO_SINFILTRAR IS NOT NULL
AND (TPO.TIPO_OPERACION='SELL' AND TPO.LIMIT_APERTURA>DATPO.MAX_EXTREMO_SINFILTRAR)
ORDER BY TPO.FECHA_BASE ASC
;
