
TRUNCATE TABLE INDICADOR_INDIVIDUO_BORRADO;
TRUNCATE TABLE INDICADOR_INDIVIDUO_TENDENCIAS;
TRUNCATE TABLE INDIVIDUO_BORRADO;

TRUNCATE TABLE INDIVIDUOS_ESTRATEGIA;
TRUNCATE TABLE ESTRATEGIAS;

TRUNCATE TABLE PREVIO_TOFILESTRING;

TRUNCATE TABLE OPERACION_CONSOLIDADAS;
TRUNCATE TABLE OPERACION_ESTRATEGIA_PERIODO;
TRUNCATE TABLE ESTRATEGIA_OPERACION_PERIODO;
TRUNCATE TABLE OPERACION_NEGATIVAS;
TRUNCATE TABLE OPERACION_POSITIVAS;
TRUNCATE TABLE OPERACIONES_ACUM_SEMANA_ANYO;
TRUNCATE TABLE OPERACIONES_ACUM_SEMANA_CONSOL;
TRUNCATE TABLE OPERACIONES_ACUM_SEMANA_MES;
TRUNCATE TABLE OPERACION_X_SEMANA;

TRUNCATE TABLE PROCESO_REPETIDOS;
TRUNCATE TABLE TENDENCIA;
TRUNCATE TABLE TENDENCIA_PROCESADA;
TRUNCATE TABLE TENDENCIA_QUERY;
TRUNCATE TABLE TMP_TOFILESTRING;
TRUNCATE TABLE TMP_TOFILESTRING2;

DROP VIEW IND_COL_FILTRO_ADICIONAL_1;
DROP VIEW IND_COL_FILTRO_ADICIONAL_2;
DROP VIEW IND_COL_FILTRO_ADICIONAL_3;
DROP VIEW IND_COL_FILTRO_ADICIONAL_4;
DROP VIEW IND_COL_FILTRO_ADICIONAL_5;
DROP VIEW IND_COL_FILTRO_ADICIONAL_6;
DROP VIEW IND_COL_FILTRO_ADICIONAL_7;
DROP VIEW IND_COL_FILTRO_ADICIONAL_8;
DROP VIEW IND_COL_FILTRO_ADICIONAL_9;
DROP VIEW IND_COL_FILTRO_ADICIONAL_10;

TRUNCATE TABLE PROCESO;
TRUNCATE TABLE OPERACION;
TRUNCATE TABLE INDICADOR_INDIVIDUO;
TRUNCATE TABLE INDIVIDUO_INDICADORES;
TRUNCATE TABLE INDIVIDUO;

drop materialized view "FOREX"."INDICADOR_INDIVIDUO_MV";
drop materialized view "FOREX"."INDIVIDUO_MV";

DROP VIEW INDICADORES_COLUMNAS;