DECLARE 
  
BEGIN
  P_FECHA:=TO_DATE('2016.04.19 00:04', 'YYYY.MM.DD HH24:MI');
  P_COUNT := 0;

TRUNCATE TABLE DATOHISTORICO;

TRUNCATE TABLE OPERACION OPER;

TRUNCATE TABLE OPERACION_X_SEMANA;
TRUNCATE TABLE OPERACIONES_ACUM_SEMANA_MES;
TRUNCATE TABLE OPERACIONES_ACUM_SEMANA_ANYO;
TRUNCATE TABLE OPERACIONES_ACUM_SEMANA_CONSOL;
TRUNCATE TABLE PREVIO_TOFILESTRING;

TRUNCATE TABLE PROCESO;

TRUNCATE TABLE OPERACION_ESTRATEGIA_PERIODO;
  
TRUNCATE TABLE ESTRATEGIA_OPERACION_PERIODO;

END;