UPDATE DATO_ADICIONAL_TPO TPO SET FACTOR_DATOS=(
	SELECT MAX(TPO2.CANTIDAD_FILTRADA)/(24*13+1)
	FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA NOT LIKE 'EXTREMO%'
	)
WHERE FACTOR_DATOS IS NULL
;
COMMIT;

UPDATE TENDENCIA_PARA_OPERAR TPO 
	SET LOTE=GREATEST(NVL((SELECT ROUND(FACTOR_DATOS/10,2) FROM DATO_ADICIONAL_TPO DATPO WHERE DATPO.FECHA_BASE=TPO.FECHA_BASE),0),0.01)
;
COMMIT;

SELECT SYSDATE FROM DUAL;

--SELECT FECHA_BASE, FACTOR_DATOS, ROUND(FACTOR_DATOS/10,2), ROUND(FACTOR_DATOS/10,5) FROM DATO_ADICIONAL_TPO DATPO 
--ORDER BY FACTOR_DATOS ASC;
