DECLARE

BEGIN
  FOR i IN 1..100 LOOP
    UPDATE OPERACION OP SET OP.FECHA=(SELECT PRO.FECHA_PROCESO FROM PROCESO PRO WHERE PRO.ID_INDIVIDUO=OP.ID_INDIVIDUO) 
    WHERE OP.FECHA IS NULL AND EXISTS (SELECT 1 FROM PROCESO PRO WHERE PRO.ID_INDIVIDUO=OP.ID_INDIVIDUO)
    AND ROWNUM<10000
    --AND OP.ID_INDIVIDUO='1422746069706.38'
    ;
    COMMIT;
    --DBMS_OUTPUT.PUT_LINE('i='||i);
  END LOOP;
END
;