DECLARE
BEGIN
	for I in 1..4 LOOP
		UPDATE OPERACION OPER SET MAX_PIPS_RETROCESO=NULL, MAX_VALUE_RETROCESO=NULL, MAX_FECHA_RETROCESO=NULL
		WHERE TIPO='BUY' AND FECHA<TO_DATE('20170116 18:45', 'YYYYMMDD HH24:MI')
		AND OPER.MAX_PIPS_RETROCESO IS NOT NULL
		AND ROWNUM<10000;
		COMMIT;
	end LOOP;
END;
/
SELECT COUNT(OPER.MAX_PIPS_RETROCESO) FROM OPERACION OPER
WHERE OPER.TIPO='BUY' 
AND OPER.MAX_PIPS_RETROCESO IS NOT NULL
AND OPER.FECHA<TO_DATE('20170116 18:45', 'YYYYMMDD HH24:MI')
;
/