/*UPDATE DATO_ADICIONAL_TPO TPO SET FACTOR_DATOS=(
	SELECT TPO2.CANTIDAD_FILTRADA/314 
	FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400 AND ROWNUM<2);

COMMIT;
*/

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.12
WHERE TPO.TIPO_TENDENCIA='MEJOR_TENDENCIA' AND TPO.TIEMPO_TENDENCIA>=14400
AND LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.01 
WHERE NOT EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	)
AND LOTE=0.11;
	
UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.02 
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.1)
AND LOTE=0.11;
	
UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.03
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.2)
AND LOTE=0.11;	

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.04
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.3)
AND LOTE=0.11;	

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.05
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.4)
AND LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.06
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.5)
AND LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.07
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.6)
AND LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.08
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.7)
AND LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.09
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.8)
AND LOTE=0.11;

UPDATE TENDENCIA_PARA_OPERAR TPO SET LOTE=0.1
WHERE EXISTS (
	SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE 
	AND TPO2.TIPO_TENDENCIA='ULTIMA_TENDENCIA' AND TPO2.TIEMPO_TENDENCIA>=14400
	
	AND (TPO2.CANTIDAD_FILTRADA/314)<=0.9)
AND LOTE=0.11;

COMMIT;

SELECT SYSDATE FROM DUAL;

