UPDATE TENDENCIA_PARA_OPERAR TPO SET UPDATE_TEMPORAL='1', 
	LIMIT_APERTURA=(SELECT MAX_EXTREMO_SINFILTRAR FROM DATO_ADICIONAL_TPO DATPO WHERE TPO.FECHA_BASE=DATPO.FECHA_BASE)
WHERE TPO.TIPO_OPERACION='SELL'
--AND ROWNUM<20
;
UPDATE TENDENCIA_PARA_OPERAR TPO SET UPDATE_TEMPORAL='1', 
	LIMIT_APERTURA=(SELECT MIN_EXTREMO_SINFILTRAR FROM DATO_ADICIONAL_TPO DATPO WHERE TPO.FECHA_BASE=DATPO.FECHA_BASE)
WHERE TPO.TIPO_OPERACION='BUY'
--AND ROWNUM<20
;

UPDATE TENDENCIA_PARA_OPERAR TPO SET ACTIVA=1;

UPDATE TENDENCIA_PARA_OPERAR TPO SET UPDATE_TEMPORAL='1' WHERE ACTIVA=0;

UPDATE TENDENCIA_PARA_OPERAR TPO SET ACTIVA=0 WHERE UPDATE_TEMPORAL='1';

UPDATE TENDENCIA_PARA_OPERAR TPO SET UPDATE_TEMPORAL=NULL WHERE UPDATE_TEMPORAL='1';

UPDATE TENDENCIA_PARA_OPERAR TPO SET UPDATE_TEMPORAL='0' WHERE UPDATE_TEMPORAL='1';

SELECT * FROM TENDENCIA_PARA_OPERAR TPO WHERE UPDATE_TEMPORAL='1';

UPDATE TENDENCIA_PARA_OPERAR TPO
SET TPO.STOP_APERTURA=(SELECT PRECIO_CALCULADO FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE AND TPO2.TIPO_OPERACION='BUY' AND TPO2.PERIODO NOT LIKE 'EXTREMO%')
WHERE TPO.TIPO_OPERACION='SELL' AND TPO.STOP_APERTURA IS NULL;

UPDATE TENDENCIA_PARA_OPERAR TPO
SET TPO.STOP_APERTURA=(SELECT PRECIO_CALCULADO FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE AND TPO2.TIPO_OPERACION='SELL' AND TPO2.PERIODO NOT LIKE 'EXTREMO%')
WHERE TPO.TIPO_OPERACION='BUY' AND TPO.STOP_APERTURA IS NULL;

UPDATE TENDENCIA_PARA_OPERAR TPO SET TPO.PERIODO='EXTEXT' WHERE TPO.PERIODO='EXTREMOEXTREMO';
UPDATE TENDENCIA_PARA_OPERAR TPO SET TPO.PERIODO='EXTSINF' WHERE TPO.PERIODO='EXTREMOSINFILT';

SELECT TPO.ROWID, TPO.*, DATPO.* FROM TENDENCIA_PARA_OPERAR TPO 
	INNER JOIN DATO_ADICIONAL_TPO DATPO ON TPO.FECHA_BASE=DATPO.FECHA_BASE
WHERE ABS(DATPO.PENDIENTE_PROMEDIO) < 0.0001 AND DATPO.NUM_PENDIENTES_POSITIVAS>DATPO.NUM_PENDIENTES_NEGATIVAS
AND TPO.ACTIVA=1
;


UPDATE TENDENCIA_PARA_OPERAR TPO SET ACTIVA=0, UPDATE_TEMPORAL='1'
WHERE TPO.ACTIVA=1 AND ABS(TPO.PENDIENTE)<0.001 AND TPO.TIPO_OPERACION='SELL'
AND EXISTS (SELECT 1 FROM DATO_ADICIONAL_TPO DATPO 
WHERE TPO.FECHA_BASE=DATPO.FECHA_BASE AND ABS(DATPO.PENDIENTE_PROMEDIO) < 0.0001 AND DATPO.NUM_PENDIENTES_POSITIVAS>DATPO.NUM_PENDIENTES_NEGATIVAS
)
--AND ROWNUM<2
;

UPDATE TENDENCIA_PARA_OPERAR TPO SET ACTIVA=0, UPDATE_TEMPORAL='1'
WHERE TPO.ACTIVA=1 AND ABS(TPO.PENDIENTE)<0.001 AND TPO.TIPO_OPERACION='BUY'
AND EXISTS (SELECT 1 FROM DATO_ADICIONAL_TPO DATPO 
WHERE TPO.FECHA_BASE=DATPO.FECHA_BASE AND ABS(DATPO.PENDIENTE_PROMEDIO) < 0.0001 AND DATPO.NUM_PENDIENTES_POSITIVAS<DATPO.NUM_PENDIENTES_NEGATIVAS
)
--AND ROWNUM<2
;

UPDATE TENDENCIA_PARA_OPERAR TPO SET ACTIVA=0 WHERE TPO.PERIODO='EXTEXT' AND ACTIVA=1;

UPDATE TENDENCIA_PARA_OPERAR TPO SET ACTIVA=1, UPDATE_TEMPORAL=NULL WHERE UPDATE_TEMPORAL='1';


UPDATE TENDENCIA_PARA_OPERAR TPO SET TIPO_TENDENCIA='ULTIMA_TENDENCIA' WHERE PERIODO NOT LIKE 'EXT%' AND ACTIVA=0;

UPDATE TENDENCIA_PARA_OPERAR TPO SET TIPO_TENDENCIA='MEJOR_PENDIENTE' WHERE PERIODO NOT LIKE 'EXT%' AND ACTIVA=0
AND NOT EXISTS (SELECT 1 FROM TENDENCIA_PARA_OPERAR TPO2 WHERE TPO.FECHA_BASE=TPO2.FECHA_BASE AND ABS(TPO2.PENDIENTE)>ABS(TPO.PENDIENTE)
)
;

SELECT * FROM TENDENCIA_PARA_OPERAR TPO WHERE STOP_APERTURA IS NULL
AND PERIODO NOT LIKE 'EXT%'
ORDER BY FECHA_BASE ASC;

DELETE FROM TENDENCIA_PARA_OPERAR WHERE ROWID IN (
SELECT TPO.ROWID FROM TENDENCIA_PARA_OPERAR TPO
	INNER JOIN DATO_ADICIONAL_TPO DA ON DA.FECHA_BASE=TPO.FECHA_BASE
	WHERE TPO.TIPO_OPERACION='SELL' AND
	TPO.PRECIO_CALCULADO <> DA.MAX_EXTREMO_FILTRADO
	AND PERIODO NOT LIKE 'EXT%'
	AND DA.MAX_EXTREMO_FILTRADO IS NOT NULL
--ORDER BY TPO.FECHA_BASE ASC	
);

DELETE FROM TENDENCIA_PARA_OPERAR WHERE ROWID IN (
SELECT TPO.ROWID FROM TENDENCIA_PARA_OPERAR TPO
	INNER JOIN DATO_ADICIONAL_TPO DA ON DA.FECHA_BASE=TPO.FECHA_BASE
	WHERE TPO.TIPO_OPERACION='BUY' AND
	TPO.PRECIO_CALCULADO <> DA.MIN_EXTREMO_FILTRADO
	AND PERIODO NOT LIKE 'EXT%'
	AND DA.MAX_EXTREMO_FILTRADO IS NOT NULL
--ORDER BY TPO.FECHA_BASE ASC	
)
		;

	
	