DECLARE
--UPDATE INDIVIDUO SET MONEDA='USDCAD';
--UPDATE INDIVIDUO_BORRADO SET MONEDA='USDCAD';

BEGIN 
  FOR i IN 0..1000 LOOP
    UPDATE OPERACION SET MONEDA='USDCAD' WHERE MONEDA IS NULL AND ROWNUM<1000;
    COMMIT;
    UPDATE OPERACION_ESTRATEGIA_PERIODO SET MONEDA='USDCAD' WHERE MONEDA IS NULL AND ROWNUM<1000;
    COMMIT;
  END LOOP;
END;
/