SET feedback off;
SET term off;
SET pagesize 0;
SET linesize 2000;
SET newpage 0;
SET space 0;

SPOOL d:/ricardorq85/Informacion/FOREX/DATABASE/SecuenciaPips/log/CREATE_TABLE_TOFILESTRING_2014.txt;

DROP TABLE TOFILESTRING_1D1S1M_2014;

CREATE TABLE TOFILESTRING_1D1S1M_2014 AS
SELECT PD1.ID_INDIVIDUO, TRUNC(MIN(PD1.MIN_FECHA_F)+1) VIGENCIA1, TRUNC(MIN(PD1.MIN_FECHA_F)+1)+1 VIGENCIA2, 
  AVG(PD1.PIPS_F) PIPS_PROM
    FROM PDI_MVIEW_2014 PD1 INNER JOIN PSI_MVIEW_2014 PS1 
        ON PS1.ID_INDIVIDUO = PD1.ID_INDIVIDUO AND TO_CHAR(PS1.MIN_FECHA_F, 'WW')=TO_CHAR(PD1.MIN_FECHA1, 'WW')-1
      INNER JOIN PMI_MVIEW_2014 PM1  ON PM1.ID_INDIVIDUO = PD1.ID_INDIVIDUO 
        AND TO_CHAR(PM1.MIN_FECHA_F, 'MM')=TO_CHAR(PD1.MIN_FECHA_F, 'MM')-1
        AND TO_CHAR(PM1.MIN_FECHA_F, 'MM')=TO_CHAR(PS1.MIN_FECHA1, 'MM')-1
        AND TO_CHAR(PM1.MIN_FECHA_F, 'MM')=TO_CHAR(PS1.MIN_FECHA_F, 'MM')-1
      WHERE (SELECT SUM(OPER2.PIPS) 
            FROM OPERACION OPER2 WHERE OPER2.ID_INDIVIDUO = PD1.ID_INDIVIDUO 
              AND OPER2.FECHA_APERTURA>=TO_DATE(TO_CHAR(ADD_MONTHS(PM1.MIN_FECHA_F,1), 'YYYYMM')||'01', 'YYYYMMDD')
              AND OPER2.FECHA_CIERRE<=PD1.MIN_FECHA_F
              GROUP BY OPER2.ID_INDIVIDUO)>0 
	  AND PD1.ID_INDIVIDUO NOT IN (
        SELECT OPER3.ID_INDIVIDUO FROM OPERACION OPER3 WHERE OPER3.ID_INDIVIDUO = PD1.ID_INDIVIDUO
          AND OPER3.FECHA_APERTURA<TRUNC(PD1.MIN_FECHA_F)+1
          AND (OPER3.FECHA_CIERRE IS NULL OR OPER3.FECHA_CIERRE>TRUNC(PD1.MIN_FECHA_F)+1)
        )
	  --AND PS1.PIPS_F > 100	
	  --AND PM1.PIPS_F > 100
    /*AND (
      SELECT COUNT(*) FROM PSI_MVIEW_2014 PS2 
      WHERE PS2.ID_INDIVIDUO=PD1.ID_INDIVIDUO AND TO_CHAR(PS2.MIN_FECHA_F, 'MM')<TO_CHAR(PD1.MIN_FECHA_F, 'MM')
      ) > 1
    AND (
      SELECT COUNT(*) FROM PMI_MVIEW_2014 PM2 
      WHERE PM2.ID_INDIVIDUO=PD1.ID_INDIVIDUO AND TO_CHAR(PM2.MIN_FECHA_F, 'MM')<TO_CHAR(PD1.MIN_FECHA_F, 'MM')
      ) > 2	 */ 
GROUP BY PD1.ID_INDIVIDUO, PD1.MIN_FECHA_F
;

UPDATE TOFILESTRING_1D1S1M_2014 SET VIGENCIA1=VIGENCIA1+2, VIGENCIA2=VIGENCIA2+2 WHERE TO_CHAR(VIGENCIA1, 'D')=7;
COMMIT;

SPOOL OFF;