SELECT * FROM ALL_TABLES
WHERE OWNER = 'HIDRO';

SELECT * FROM ALL_TAB_COLUMNS;

SELECT  TRIM(TABLE_NAME || '.' || COLUMN_NAME || ' ' || DATA_TYPE || '('
         || DATA_LENGTH || ',' || DATA_PRECISION
         || ') NULLABLE=' || NULLABLE) ATRIBUTOS_TABLA
FROM     ALL_TAB_COLUMNS
WHERE OWNER = 'FOREX'
--AND TABLE_NAME = 'DATOHISTORICO'
AND TABLE_NAME NOT LIKE '%_VW'
ORDER BY TABLE_NAME,
         COLUMN_ID;
         
         
SELECT   TABLE_NAME || '.' || COLUMN_NAME,
         DATA_TYPE,
         DATA_LENGTH,
         DATA_PRECISION,
         DATA_SCALE,
         NULLABLE
FROM     ALL_TAB_COLUMNS
WHERE OWNER = 'FOREX'
AND TABLE_NAME NOT LIKE '%_VW'
ORDER BY TABLE_NAME,
         COLUMN_ID;
         
         
