CREATE TABLE TENDENCIA 
(
  FECHA_BASE DATE NOT NULL 
, PRECIO_BASE NUMBER(10, 5) NOT NULL 
, ID_INDIVIDUO VARCHAR2(50 CHAR) NOT NULL 
, FECHA_TENDENCIA DATE NOT NULL 
, PIPS NUMBER(10, 5) NOT NULL 
, PRECIO_CALCULADO NUMBER(10, 5) NOT NULL 
, CONSTRAINT TENDENCIA_PK PRIMARY KEY 
  (
    FECHA_BASE 
  , ID_INDIVIDUO 
  )
  ENABLE 
);

ALTER TABLE TENDENCIA
ADD CONSTRAINT TENDENCIA_INDIVIDUO_FK1 FOREIGN KEY
(
  ID_INDIVIDUO 
)
REFERENCES INDIVIDUO
(
  ID 
)
ENABLE;

  CREATE INDEX "FOREX"."INDEX1" ON "FOREX"."TENDENCIA" ("FECHA_TENDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;

  CREATE INDEX "FOREX"."INDEX1" ON "FOREX"."TENDENCIA" ("FECHA_TENDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
