CREATE OR REPLACE PROCEDURE SMART_DELETE 
(
  ID_IND_REPETIDO IN VARCHAR2  
, TIPO_BORRADO IN VARCHAR2  
, ID_IND_PADRE IN VARCHAR2  
) AS 
BEGIN
  INSERT INTO INDIVIDUO_BORRADO(ID, PARENT_ID_1, PARENT_ID_2, TAKE_PROFIT, STOP_LOSS, LOTE, INITIAL_BALANCE, CREATION_DATE, TIPO_BORRADO, FECHA_BORRADO, ID_INDIVIDUO_PADRE)
    SELECT IND.ID, IND.PARENT_ID_1, IND.PARENT_ID_2, IND.TAKE_PROFIT, IND.STOP_LOSS, IND.LOTE, IND.INITIAL_BALANCE, IND.CREATION_DATE, TIPO_BORRADO, SYSDATE, ID_IND_PADRE
    FROM INDIVIDUO IND WHERE IND.ID=ID_IND_REPETIDO;

  INSERT INTO INDICADOR_INDIVIDUO_BORRADO(ID_INDICADOR, ID_INDIVIDUO, INTERVALO_INFERIOR, INTERVALO_SUPERIOR, TIPO)
    SELECT ID_INDICADOR, ID_INDIVIDUO, INTERVALO_INFERIOR, INTERVALO_SUPERIOR, TIPO
    FROM INDICADOR_INDIVIDUO WHERE ID_INDIVIDUO=ID_IND_REPETIDO;
  
  DELETE FROM INDICADOR_INDIVIDUO WHERE ID_INDIVIDUO=ID_IND_REPETIDO;
  DELETE FROM INDIVIDUO WHERE ID=ID_IND_REPETIDO;  
  
  COMMIT;  
END SMART_DELETE;