SELECT DH.* 
FROM DATOHISTORICO DH 
WHERE DH.FECHA>TO_DATE('2012/08/13 00:00')
ORDER BY DH.FECHA ASC;

SELECT FECHA, TO_CHAR(FECHA,'D') FROM FOREX.DATOHISTORICO --WHERE ROWNUM < 10
where to_char(FECHA, 'D') IN (1) AND TO_CHAR(FECHA, 'HH24')<1
ORDER BY FECHA DESC
;


SELECT * FROM (SELECT PAR, MINUTOS, PAR_COMPARE, FECHA,
                OPEN, LOW, HIGH, CLOSE, VOLUME, SPREAD, AVERAGE, MACD_VALUE, MACD_SIGNAL,
                COMPARE_VALUE, AVERAGE_COMPARE, SAR, ADX_VALUE, ADX_PLUS, ADX_MINUS,
                RSI, BOLLINGER_UPPER, BOLLINGER_LOWER, MOMENTUM, ICHIMOKUTENKANSEN,
                ICHIMOKUKIJUNSEN, ICHIMOKUSENKOUSPANA, ICHIMOKUSENKOUSPANB, ICHIMOKUCHINKOUSPAN
                FROM DATOHISTORICO WHERE FECHA > NVL(TO_DATE('2012/08/15 06:00','YYYY/MM/DD HH24:MI'),(SELECT MIN(FECHA) FROM DATOHISTORICO)) ORDER BY FECHA ASC)
                WHERE ROWNUM<5000
;
                
SELECT PAR, MINUTOS, PAR_COMPARE, FECHA, OPEN, LOW, HIGH, CLOSE, VOLUME, SPREAD, 
AVERAGE, MACD_VALUE, MACD_SIGNAL, COMPARE_VALUE, AVERAGE_COMPARE, SAR, ADX_VALUE, ADX_PLUS, ADX_MINUS, 
RSI, BOLLINGER_UPPER, BOLLINGER_LOWER, MOMENTUM, ICHIMOKUTENKANSEN, 
ICHIMOKUKIJUNSEN, ICHIMOKUSENKOUSPANA, ICHIMOKUSENKOUSPANB, ICHIMOKUCHINKOUSPAN
FROM DATOHISTORICO WHERE FECHA > NVL(NULL,(SELECT MIN(DH2.FECHA) FROM DATOHISTORICO DH2));

SELECT COUNT(*) FROM DATOHISTORICO;

SELECT DH.* 
FROM FOREX.DATOHISTORICO DH WHERE DH.FECHA>TO_DATE('2008/07/29 03:11','YYYY/MM/DD HH24:MI')
ORDER BY DH.FECHA ASC;

SELECT DH.* 
FROM FOREX.DATOHISTORICO DH WHERE DH.FECHA IN (TO_DATE('2012/06/21 17:35','YYYY/MM/DD HH24:MI'), TO_DATE('2012/06/28 02:53','YYYY/MM/DD HH24:MI'))
ORDER BY DH.FECHA ASC;

SELECT *
FROM DATOHISTORICO DH WHERE DH.FECHA>=TO_DATE('2009/01/01 00:00', 'YYYY/MM/DD HH24:MI');

SELECT DH.* 
FROM FOREX.DATOHISTORICO DH WHERE AVERAGE_COMPARE IS NOT NULL
ORDER BY DH.FECHA ASC;

SELECT 
COUNT(*)
--DH1.* 
FROM DATOHISTORICO DH1
WHERE NOT EXISTS (SELECT * FROM DATOHISTORICO DH2
  WHERE  DH1.PAR=DH2.PAR AND DH1.MINUTOS=DH2.MINUTOS
  AND DH2.FECHA = (DH1.FECHA+1/1440)
  )
AND NOT ((TO_CHAR(DH1.FECHA, 'D')='5') AND (TO_CHAR(DH1.FECHA+1/24, 'HH24')=22) AND (TO_CHAR(DH1.FECHA+1/1440, 'MI')=59))
ORDER BY DH1.FECHA DESC;

SELECT 
TO_CHAR(DH1.FECHA, 'MM'), COUNT(*)
FROM DATOHISTORICO DH1
WHERE NOT EXISTS (SELECT * FROM DATOHISTORICO DH2
  WHERE  DH1.PAR=DH2.PAR AND DH1.MINUTOS=DH2.MINUTOS
  AND DH2.FECHA = (DH1.FECHA+1/1440)
  )
AND NOT ((TO_CHAR(DH1.FECHA, 'D')='5') AND (TO_CHAR(DH1.FECHA+1/24, 'HH24')=22) AND (TO_CHAR(DH1.FECHA+1/1440, 'MI')=59))
GROUP BY TO_CHAR(DH1.FECHA, 'MM')
ORDER BY TO_CHAR(DH1.FECHA, 'MM')
;

