
SELECT IND.ID ID_INDIVIDUO, 
  NVL(SUM(POSITIVOS.PIPS),0) PIPS_POSITIVOS, NVL(SUM(NEGATIVOS.PIPS),0) PIPS_NEGATIVOS, NVL((SUM(POSITIVOS.PIPS)+SUM(NEGATIVOS.PIPS)),0) PIPS_TOTALES,
  NVL(SUM(POSITIVOS.CO),0) NUM_POSITIVOS, NVL(SUM(NEGATIVOS.CO),0) NUM_NEGATIVOS
FROM INDIVIDUO IND
  INNER JOIN (SELECT OPER.ID_INDIVIDUO 
    FROM OPERACION OPER WHERE OPER.FECHA_CIERRE IS NOT NULL AND OPER.FECHA_APERTURA < (SYSDATE)
	GROUP BY OPER.ID_INDIVIDUO) OPER ON OPER.ID_INDIVIDUO=IND.ID

  LEFT JOIN (SELECT P.ID_INDIVIDUO, SUM(P.PIPS) PIPS, COUNT(*) CO
    FROM OPERACION P WHERE P.PIPS>0 AND P.FECHA_CIERRE IS NOT NULL AND P.FECHA_APERTURA < (SYSDATE)
	GROUP BY P.ID_INDIVIDUO) POSITIVOS ON POSITIVOS.ID_INDIVIDUO=IND.ID

  LEFT JOIN (SELECT N.ID_INDIVIDUO, SUM(N.PIPS) PIPS, COUNT(*) CO
    FROM OPERACION N WHERE N.PIPS<=0 AND N.FECHA_CIERRE IS NOT NULL AND N.FECHA_APERTURA < (SYSDATE)
	GROUP BY N.ID_INDIVIDUO) NEGATIVOS ON NEGATIVOS.ID_INDIVIDUO=IND.ID
GROUP BY IND.ID
HAVING NVL(SUM(NEGATIVOS.CO),0)=0 
--AND (NVL(SUM(POSITIVOS.CO),0)/NVL(COUNT(POSITIVOS.CO),0))>100
ORDER BY NVL(SUM(POSITIVOS.CO),0) DESC
--ORDER BY SUM(NEGATIVOS.CO) DESC
;

--CREATE OR REPLACE VIEW TEMP_VIEW AS
SELECT IND.ID ID_INDIVIDUO/*, 
  NVL(SUM(POSITIVOS.PIPS),0) PIPS_POSITIVOS, ROUND(NVL(SUM(POSITIVOS.PIPS),0)/NVL(SUM(POSITIVOS.CO),1),2) PROM_POSITIVOS,
  NVL(SUM(NEGATIVOS.PIPS),0) PIPS_NEGATIVOS, ROUND(NVL(SUM(NEGATIVOS.PIPS),0)/NVL(SUM(NEGATIVOS.CO),1),2) PROM_NEGATIVOS,
  NVL(SUM(POSITIVOS.PIPS),0)+NVL(SUM(NEGATIVOS.PIPS),0) PIPS_TOTALES,
  NVL(SUM(POSITIVOS.CO),0) NUM_POSITIVOS, NVL(SUM(NEGATIVOS.CO),0) NUM_NEGATIVOS,
  ROUND((NVL(SUM(POSITIVOS.PIPS),0)+NVL(SUM(NEGATIVOS.PIPS),0)) / (NVL(SUM(POSITIVOS.CO),0)+NVL(SUM(NEGATIVOS.CO),0)),2) PROM*/
FROM INDIVIDUO IND
  INNER JOIN (SELECT OPER.ID_INDIVIDUO 
    FROM OPERACION OPER WHERE OPER.FECHA_CIERRE IS NOT NULL AND OPER.FECHA_APERTURA < (SYSDATE)      
	GROUP BY OPER.ID_INDIVIDUO) OPER ON OPER.ID_INDIVIDUO=IND.ID
  
  LEFT JOIN (SELECT P.ID_INDIVIDUO, SUM(P.PIPS) PIPS, COUNT(*) CO
    FROM OPERACION P WHERE P.PIPS>0 AND P.FECHA_CIERRE IS NOT NULL AND P.FECHA_APERTURA < (SYSDATE)
	GROUP BY P.ID_INDIVIDUO) POSITIVOS ON POSITIVOS.ID_INDIVIDUO=IND.ID

  LEFT JOIN (SELECT N.ID_INDIVIDUO, SUM(N.PIPS) PIPS, COUNT(*) CO
    FROM OPERACION N WHERE N.PIPS<=0 AND N.FECHA_CIERRE IS NOT NULL AND N.FECHA_APERTURA < (SYSDATE)
	GROUP BY N.ID_INDIVIDUO) NEGATIVOS ON NEGATIVOS.ID_INDIVIDUO=IND.ID
GROUP BY IND.ID
--HAVING NVL(SUM(NEGATIVOS.CO),0)=0 
HAVING ROUND((NVL(SUM(POSITIVOS.PIPS),0)+NVL(SUM(NEGATIVOS.PIPS),0)) / (NVL(SUM(POSITIVOS.CO),0)+NVL(SUM(NEGATIVOS.CO),0)),2)>60
 AND (NVL(SUM(POSITIVOS.CO),0)+NVL(SUM(NEGATIVOS.CO),0))>20
 AND (NVL(SUM(POSITIVOS.PIPS),0)/NVL(SUM(POSITIVOS.CO),0))>100
 AND (NVL(SUM(NEGATIVOS.PIPS),0)/NVL(SUM(NEGATIVOS.CO),0))<-100
AND ROUND(NVL(SUM(POSITIVOS.CO),0)/NVL(SUM(NEGATIVOS.CO),1),2)>3
--AND (NVL(SUM(POSITIVOS.CO),0)/NVL(COUNT(POSITIVOS.CO),0))>100
ORDER BY (NVL(SUM(POSITIVOS.PIPS),0)+ NVL(SUM(NEGATIVOS.PIPS),0)) DESC
--ORDER BY SUM(NEGATIVOS.CO) DESC
;

SELECT TO_CHAR(OPER2.FECHA_APERTURA,'YYYY'), SUM(OPER2.PIPS), COUNT(*) CO
FROM OPERACION OPER2
WHERE OPER2.ID_INDIVIDUO IN (
  SELECT IND.ID
  FROM INDIVIDUO IND
    INNER JOIN (SELECT OPER.ID_INDIVIDUO 
      FROM OPERACION OPER WHERE OPER.FECHA_CIERRE IS NOT NULL AND OPER.FECHA_APERTURA < (SYSDATE)
    GROUP BY OPER.ID_INDIVIDUO) OPER ON OPER.ID_INDIVIDUO=IND.ID
  
    LEFT JOIN (SELECT P.ID_INDIVIDUO, SUM(P.PIPS) PIPS, COUNT(*) CO
      FROM OPERACION P WHERE P.PIPS>0 AND P.FECHA_CIERRE IS NOT NULL AND P.FECHA_APERTURA < (SYSDATE)
    GROUP BY P.ID_INDIVIDUO) POSITIVOS ON POSITIVOS.ID_INDIVIDUO=IND.ID
  
    LEFT JOIN (SELECT N.ID_INDIVIDUO, SUM(N.PIPS) PIPS, COUNT(*) CO
      FROM OPERACION N WHERE N.PIPS<=0 AND N.FECHA_CIERRE IS NOT NULL AND N.FECHA_APERTURA < (SYSDATE)
    GROUP BY N.ID_INDIVIDUO) NEGATIVOS ON NEGATIVOS.ID_INDIVIDUO=IND.ID
  GROUP BY IND.ID
  HAVING ROUND((NVL(SUM(POSITIVOS.PIPS),0)+NVL(SUM(NEGATIVOS.PIPS),0)) / (NVL(SUM(POSITIVOS.CO),0)+NVL(SUM(NEGATIVOS.CO),0)),2)>60
  AND (NVL(SUM(POSITIVOS.CO),0)+NVL(SUM(NEGATIVOS.CO),0))>50
  AND (NVL(SUM(POSITIVOS.PIPS),0)/NVL(SUM(POSITIVOS.CO),0))>100
  AND (NVL(SUM(NEGATIVOS.PIPS),0)/NVL(SUM(NEGATIVOS.CO),0))<-100
  AND ROUND(NVL(SUM(POSITIVOS.CO),0)/NVL(SUM(NEGATIVOS.CO),1),2)>3
)
GROUP BY TO_CHAR(OPER2.FECHA_APERTURA, 'YYYY') 
ORDER BY TO_CHAR(OPER2.FECHA_APERTURA, 'YYYY') DESC;
;
