SELECT * FROM DETALLES_ESTADISTICAS;

SELECT AVG(DUR_PROM_POS), AVG(DUR_PROM_NEG) FROM DETALLES_ESTADISTICAS;

SELECT * FROM DETALLES_ESTADISTICAS WHERE ID_INDIVIDUO='1338955830567.96025'
;

-- PIPS POR AÑO
SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY') ANYO, SUM(PIPS) FROM FOREX.OPERACION 
--WHERE ID_INDIVIDUO = '1341766313059.988'
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY') ORDER BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY') ASC;

-- PIPS POR MES
SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY/MM') MES, SUM(PIPS) FROM FOREX.OPERACION 
WHERE ID_INDIVIDUO = '1341766313059.988'
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') ORDER BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') ASC;

-- NUMERO DE MESES CON BALANCE POSITIVO, SIN TENER NINGUN MES CON BALANCE NEGATIVO
SELECT ID_INDIVIDUO, COUNT(*) FROM (
  SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY/MM') MES_APERTURA, SUM(PIPS) SUMA_PIPS
  FROM FOREX.OPERACION GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM')
  ) PIPS_X_MES
WHERE PIPS_X_MES.ID_INDIVIDUO NOT IN (
  SELECT ID_INDIVIDUO FROM FOREX.OPERACION 
  GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') HAVING SUM(PIPS) < 0)
GROUP BY ID_INDIVIDUO HAVING COUNT(*)>1 ORDER BY COUNT(*) DESC;
  
-- COMPARACION DE MESES CON BALANCE POSITIVO Y NEGATIVO
SELECT POSITIVOS.ID_INDIVIDUO, POSITIVOS.COUNT_POSITIVOS, NEGATIVOS.COUNT_NEGATIVOS, 
  (POSITIVOS.COUNT_POSITIVOS-NEGATIVOS.COUNT_NEGATIVOS) DIFERENCIA, (PIPS_POSITIVOS+PIPS_NEGATIVOS) PIPS
  FROM (
  SELECT ID_INDIVIDUO, COUNT(*) COUNT_POSITIVOS, SUM(SUMA_PIPS) PIPS_POSITIVOS FROM (
    SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY/MM') MES_APERTURA, SUM(PIPS) SUMA_PIPS
      FROM FOREX.OPERACION --WHERE ID_INDIVIDUO = '1341687718670.3603'
      GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') HAVING SUM(PIPS) > 0)
  GROUP BY ID_INDIVIDUO) POSITIVOS,
  (SELECT ID_INDIVIDUO, COUNT(*) COUNT_NEGATIVOS, SUM(SUMA_PIPS) PIPS_NEGATIVOS FROM (
    SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY/MM') MES_APERTURA, SUM(PIPS) SUMA_PIPS
      FROM FOREX.OPERACION --WHERE ID_INDIVIDUO = '1341687718670.3603'
      GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') HAVING SUM(PIPS) < 0)
  GROUP BY ID_INDIVIDUO) NEGATIVOS
WHERE POSITIVOS.ID_INDIVIDUO = NEGATIVOS.ID_INDIVIDUO
ORDER BY (POSITIVOS.COUNT_POSITIVOS-NEGATIVOS.COUNT_NEGATIVOS) DESC, PIPS DESC
--ORDER BY (PIPS_POSITIVOS+PIPS_NEGATIVOS) DESC
;

--INDIVIDUO SIN OPERACIONES NEGATIVAS
SELECT * FROM DETALLES_ESTADISTICAS DEST
  INNER JOIN (SELECT PROC.ID_INDIVIDUO, MAX(PROC.FECHA_HISTORICO) FECHA_HISTORICO FROM PROCESO PROC GROUP BY PROC.ID_INDIVIDUO) PROC
    ON DEST.ID_INDIVIDUO=PROC.ID_INDIVIDUO
WHERE NEGATIVOS=0 AND PROC.FECHA_HISTORICO>TO_DATE('2012','YYYY') AND TOTAL_CANT>1
ORDER BY POSITIVOS DESC;

--INDIVIDUOS SIN OPERACIONES POSITIVAS
SELECT IND.TAKE_PROFIT, IND.STOP_LOSS, 
DEST.* FROM DETALLES_ESTADISTICAS DEST
  INNER JOIN (SELECT PROC.ID_INDIVIDUO, MAX(PROC.FECHA_HISTORICO) FECHA_HISTORICO FROM PROCESO PROC GROUP BY PROC.ID_INDIVIDUO) PROC
    ON DEST.ID_INDIVIDUO=PROC.ID_INDIVIDUO
  INNER JOIN INDIVIDUO IND ON DEST.ID_INDIVIDUO=IND.ID
WHERE DEST.POSITIVOS=0 --AND PROC.FECHA_HISTORICO>TO_DATE('2012','YYYY') 
AND DEST.TOTAL_CANT>1
ORDER BY DEST.NEGATIVOS DESC;

SELECT * FROM DETALLES_ESTADISTICAS WHERE ID_INDIVIDUO='1344092068979.55';

SELECT * FROM OPERACION WHERE ID_INDIVIDUO='1341687718670.42926';

SELECT * FROM OPERACION ORDER BY FECHA_APERTURA DESC;

SELECT * FROM OPERACION WHERE FECHA_APERTURA=TO_DATE('2012/07/20 15:04','YYYY/MM/DD HH24:MI');

SELECT FECHA_APERTURA, MAX(PIPS), COUNT(*) FROM OPERACION 
GROUP BY FECHA_APERTURA HAVING COUNT(*) > 1 AND  MAX(PIPS) < 0 ORDER BY FECHA_APERTURA DESC;

--ESTADISTICAS
SELECT ROUND(PROMEDIO_PIPS_OPER()) PROMEDIO, ROUND(VARIANZA_PIPS_OPER()) VARIANZA, ROUND(DESV_ESTANDAR_PIPS_OPER()) DESV_ESTANDARD,
       ROUND(PROMEDIO_PIPS_OPER()-DESV_ESTANDAR_PIPS_OPER()) PROB_68_MINUS,
       ROUND(PROMEDIO_PIPS_OPER()+DESV_ESTANDAR_PIPS_OPER()) PROB_68_PLUS,
       ROUND(PROMEDIO_PIPS_OPER()-2*DESV_ESTANDAR_PIPS_OPER()) PROB_95_MINUS,
       ROUND(PROMEDIO_PIPS_OPER()+2*DESV_ESTANDAR_PIPS_OPER()) PROB_95_PLUS,
       ROUND(PROMEDIO_PIPS_OPER()-3*DESV_ESTANDAR_PIPS_OPER()) PROB_98_MINUS,
       ROUND(PROMEDIO_PIPS_OPER()+3*DESV_ESTANDAR_PIPS_OPER()) PROB_98_PLUS
FROM DUAL;

SELECT * FROM OPERACION ORDER BY FECHA_APERTURA ASC;

SELECT FECHA_APERTURA, COUNT(*) FROM OPERACION GROUP BY FECHA_APERTURA ORDER BY COUNT(*) DESC;

SELECT --COUNT(*) C 
  OPER1.FECHA_APERTURA, OPER1.ID_INDIVIDUO, OPER2.ID_INDIVIDUO, 
  OPER1.FECHA_CIERRE, OPER2.FECHA_CIERRE, 
  OPER1.PIPS, OPER2.PIPS
  FROM OPERACION OPER1, OPERACION OPER2 
WHERE OPER1.FECHA_APERTURA=OPER2.FECHA_APERTURA AND ABS(OPER1.PIPS+OPER2.PIPS)<>ABS(OPER1.PIPS)+ABS(OPER2.PIPS)
/*AND (OPER1.PIPS > 0 OR OPER2.PIPS > 0)*/ AND OPER1.ID_INDIVIDUO > OPER2.ID_INDIVIDUO
ORDER BY OPER1.FECHA_APERTURA DESC
;

--SELECT SUM(SUMA) FROM (
SELECT OPER.FECHA_APERTURA, COUNT(*) C, SUM(PIPS) SUMA
  FROM OPERACION OPER 
GROUP BY OPER.FECHA_APERTURA HAVING COUNT(*) > 1
--ORDER BY OPER.FECHA_APERTURA ASC
ORDER BY COUNT(*) DESC
--)
;
