SELECT (OPER2.OPEN_PRICE - OPER1.OPEN_PRICE) DIFERENCIA_OPEN, COUNT(*) CONTAR--, OPER2.OPEN_PRICE, OPER1.OPEN_PRICE
--, OPER1.*, OPER2.* --, COUNT(*) CO 
FROM (SELECT DISTINCT FECHA_APERTURA, OPEN_PRICE FROM OPERACION) OPER1, (SELECT DISTINCT FECHA_APERTURA, OPEN_PRICE FROM OPERACION) OPER2
WHERE OPER2.FECHA_APERTURA <> OPER1.FECHA_APERTURA AND OPER2.FECHA_APERTURA > OPER1.FECHA_APERTURA 
AND OPER2.FECHA_APERTURA<=(SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE)
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS')
--AND (OPER2.FECHA_APERTURA - OPER1.FECHA_APERTURA) < 30 
--AND ROWNUM < 2000000
--AND OPER2.OPEN_PRICE='1,2409'
GROUP BY (OPER2.OPEN_PRICE - OPER1.OPEN_PRICE)--, OPER2.OPEN_PRICE, OPER1.OPEN_PRICE
ORDER BY COUNT(*) DESC
;

SELECT OPER1.FECHA_APERTURA, OPER2.FECHA_APERTURA, OPER1.PIPS, OPER2.PIPS, OPER1.OPEN_PRICE, OPER2.OPEN_PRICE,
(OPER2.OPEN_PRICE-OPER1.OPEN_PRICE) DIFF
FROM OPERACION OPER1, OPERACION OPER2 
WHERE OPER2.FECHA_APERTURA <> OPER1.FECHA_APERTURA AND OPER2.FECHA_APERTURA > OPER1.FECHA_APERTURA 
AND OPER2.FECHA_APERTURA<=(SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE)
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS')
AND OPER2.OPEN_PRICE-OPER1.OPEN_PRICE=0.0004
ORDER BY OPER1.FECHA_APERTURA;

SELECT DISTINCT FECHA_APERTURA FROM OPERACION;