SELECT * FROM FOREX.OPERACION 
WHERE ID_INDIVIDUO IN ('1338955830567.96025')
ORDER BY FECHA_APERTURA DESC;

SELECT * FROM OPERACION ORDER BY ID_INDIVIDUO ASC, FECHA_APERTURA ASC;
SELECT COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.OPERACION;
SELECT ID_INDIVIDUO, COUNT(*), SUM(PIPS) FROM FOREX.OPERACION GROUP BY ID_INDIVIDUO 
ORDER BY SUM(PIPS) DESC
--ORDER BY COUNT(*) DESC
;

SELECT * FROM OPERACION ORDER BY FECHA_APERTURA ASC;
SELECT * FROM OPERACION WHERE FECHA_APERTURA=TO_DATE('2009/11/25 13:58','YYYY/MM/DD HH24:MI');

SELECT COUNT(*) FROM FOREX.OPERACION;

SELECT ID_INDIVIDUO, FECHA_HISTORICO, TO_CHAR(FECHA_PROCESO, 'YYYY/MM/DD HH24:MI:SS') FECHA_PROCESO FROM FOREX.PROCESO ORDER BY FECHA_PROCESO DESC;
SELECT TRUNC(FECHA_PROCESO), COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.PROCESO GROUP BY TRUNC(FECHA_PROCESO) ORDER BY TRUNC(FECHA_PROCESO) DESC;
SELECT COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.PROCESO;
SELECT * FROM FOREX.PROCESO ORDER BY FECHA_PROCESO DESC;
/*SELECT * FROM FOREX.PROCESO PROC
  INNER JOIN FOREX.OPERACION OPER ON OPER.ID_INDIVIDUO=PROC.ID_INDIVIDUO
ORDER BY PROC.ID_INDIVIDUO ASC
;*/

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM FOREX.INDIVIDUO IND WHERE IND.CREATION_DATE IS NULL AND IND.PARENT_ID_1 IS NOT NULL AND IND.PARENT_ID_2 IS NOT NULL
  UNION ALL
  SELECT IND.ID FROM FOREX.INDIVIDUO_BORRADO IND WHERE IND.CREATION_DATE IS NULL AND IND.PARENT_ID_1 IS NOT NULL AND IND.PARENT_ID_2 IS NOT NULL
) ORDER BY FECHA_PROCESO DESC;

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM FOREX.INDIVIDUO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
    BETWEEN TO_DATE('2012/06/07', 'YYYY/MM/DD') AND TO_DATE('2012/08/07', 'YYYY/MM/DD')
  UNION ALL
    SELECT IND.ID FROM FOREX.INDIVIDUO_BORRADO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
    BETWEEN TO_DATE('2012/06/07', 'YYYY/MM/DD') AND TO_DATE('2012/08/07', 'YYYY/MM/DD')
  )
ORDER BY FECHA_PROCESO DESC;

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO IN (
  SELECT IND.ID FROM FOREX.INDIVIDUO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
  BETWEEN TO_DATE('2012/05/07', 'YYYY/MM/DD') AND TO_DATE('2012/06/06', 'YYYY/MM/DD')
  UNION ALL
  SELECT IND.ID FROM FOREX.INDIVIDUO_BORRADO IND WHERE IND.CREATION_DATE IS NOT NULL AND IND.CREATION_DATE 
  BETWEEN TO_DATE('2012/05/07', 'YYYY/MM/DD') AND TO_DATE('2012/06/06', 'YYYY/MM/DD')

  )
ORDER BY FECHA_PROCESO DESC;

SELECT ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA,'YYYY/MM'), SUM(PIPS)
FROM FOREX.OPERACION WHERE ID_INDIVIDUO IN ('1338955830567.96025')
GROUP BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') 
ORDER BY ID_INDIVIDUO, TO_CHAR(FECHA_APERTURA, 'YYYY/MM') DESC;

SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO IN ('1338955830567.1170')
ORDER BY FECHA_APERTURA ASC;

SELECT SUM(PIPS) FROM FOREX.OPERACION WHERE ID_INDIVIDUO='1329927210938.97';

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO='1341687718670.3603' 
ORDER BY FECHA_PROCESO ASC;

SELECT * FROM FOREX.PROCESO WHERE ID_INDIVIDUO='1329850420864.9747' ORDER BY FECHA_HISTORICO DESC;

SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO='1341687718670.3284'
ORDER BY ID_INDIVIDUO,FECHA_APERTURA DESC;

SELECT * FROM FOREX.V_OPERACIONES 
WHERE ID='1329927210938.986'
AND OPEN_FECHA=TO_DATE('2008/10/29 17:43','YYYY/MM/DD HH24:MI')
AND CLOSE_FECHA=TO_DATE('2008/10/29 17:50','YYYY/MM/DD HH24:MI')
ORDER BY ID,OPEN_FECHA;

SELECT * FROM FOREX.OPERACION ORDER BY ID_INDIVIDUO,FECHA_APERTURA;

SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO IN (
  SELECT ID_INDIVIDUO FROM FOREX.OPERACION 
  GROUP BY ID_INDIVIDUO HAVING COUNT(*) > 1)
ORDER BY ID_INDIVIDUO,FECHA_APERTURA;

SELECT OPER.*
FROM FOREX.DATOHIST_INDICADORINDIVIDUO OPER
WHERE OPER.ID_INDIVIDUO='1343862270390.14'
AND OPER.OPEN_FECHA=TO_DATE('2011/02/28 17:13','YYYY/MM/DD HH24:MI')
AND CLOSE_FECHA=TO_DATE('2011/03/15 04:46','YYYY/MM/DD HH24:MI')
;	

  SELECT MIN(FECHA) FROM DATOHISTORICO WHERE FECHA > TO_DATE('2008/05/08 02:29','YYYY/MM/DD HH24:MI');
  SELECT * FROM DATOHISTORICO WHERE FECHA=TO_DATE('2008/05/08 02:33','YYYY/MM/DD HH24:MI');
  SELECT 1.01179-(-0.00065),  1.01179-(-0.00039), 1.0114, 1.0126 ,
    (INTERSECT_INTERVAL(1.01179-(-0.00039), 1.01179-(-0.00065), 1.0114, 1.0126)) INTER FROM DUAL;

SELECT * FROM FOREX.OPERACION_BASE OPB1 
WHERE EXISTS (SELECT 1 FROM FOREX.OPERACION_BASE OPB2 WHERE 
OPB1.ID_INDIVIDUO=OPB2.ID_INDIVIDUO AND OPB1.FECHA_APERTURA > OPB2.FECHA_APERTURA AND OPB1.FECHA_APERTURA <= OPB2.FECHA_CIERRE)
ORDER BY OPB1.ID_INDIVIDUO,FECHA_APERTURA;

SELECT * FROM (
  SELECT * FROM FOREX.OPERACION_BASE WHERE ID_INDIVIDUO IN (
    SELECT ID_INDIVIDUO FROM FOREX.OPERACION 
    GROUP BY ID_INDIVIDUO HAVING COUNT(*) > 1)
  ORDER BY ID_INDIVIDUO,FECHA_APERTURA) OPM
WHERE OPM.ID_INDIVIDUO NOT IN (
  SELECT ID_INDIVIDUO FROM FOREX.OPERACION_BASE OPB1 
  WHERE EXISTS (SELECT 1 FROM FOREX.OPERACION_BASE OPB2 WHERE 
  OPB1.ID_INDIVIDUO=OPB2.ID_INDIVIDUO AND OPB1.FECHA_APERTURA > OPB2.FECHA_APERTURA AND OPB1.FECHA_APERTURA <= OPB2.FECHA_CIERRE)
);  

SELECT PROC.ID_INDIVIDUO, PROC.FECHA_PROCESO --COUNT(*) 
FROM OPERACION OPER 
INNER JOIN PROCESO PROC ON OPER.ID_INDIVIDUO = PROC.ID_INDIVIDUO
WHERE PROC.FECHA_PROCESO > SYSDATE - 1/24
ORDER BY PROC.FECHA_PROCESO DESC;