--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_ESTADISTICAS', '2009/04/24 22:51', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('FECHA_INICIO_TENDENCIA', '2009/01/01 00:00', SYSDATE);
--INSERT INTO PARAMETRO (NOMBRE, VALOR, FECHA) VALUES ('STEP_TENDENCIA', '5', SYSDATE);
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2012/06/01 00:01' WHERE NOMBRE='FECHA_INICIO_TENDENCIA';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='2012/06/01 00:02' WHERE NOMBRE='FECHA_ESTADISTICAS';
UPDATE PARAMETRO SET FECHA=SYSDATE, VALOR='3' WHERE NOMBRE='STEP_TENDENCIA';

COMMIT;

SELECT NOMBRE, VALOR FROM PARAMETRO;

--WHERE NOMBRE='FECHA_ESTADISTICAS';

/*
SELECT OPER.ID_INDIVIDUO, OPER.FECHA_APERTURA, OPER.OPEN_PRICE, OPER.SPREAD, OPER.LOTE 
  FROM OPERACION OPER
  INNER JOIN DETALLE_ESTADISTICAS EST ON EST.ID_INDIVIDUO=OPER.ID_INDIVIDUO 
  WHERE OPER.FECHA_APERTURA<=(SELECT TO_DATE(VALOR, 'YYYY/MM/DD HH24:MI') FROM PARAMETRO WHERE NOMBRE='FECHA_INICIO_TENDENCIA') 
  AND (OPER.FECHA_CIERRE IS NULL OR OPER.FECHA_CIERRE>(SELECT TO_DATE(VALOR, 'YYYY/MM/DD HH24:MI') FROM PARAMETRO WHERE NOMBRE='FECHA_INICIO_TENDENCIA') )
  AND OPER.FECHA_APERTURA>(SELECT TO_DATE(VALOR, 'YYYY/MM/DD HH24:MI') FROM PARAMETRO WHERE NOMBRE='FECHA_INICIO_TENDENCIA')-30
  AND OPER.ID_INDIVIDUO NOT IN (SELECT ID_INDIVIDUO FROM TENDENCIA TEND WHERE TEND.ID_INDIVIDUO=OPER.ID_INDIVIDUO
  AND TEND.FECHA_BASE=(SELECT TO_DATE(VALOR, 'YYYY/MM/DD HH24:MI') FROM PARAMETRO WHERE NOMBRE='FECHA_INICIO_TENDENCIA'));

*/