SELECT ID_INDIVIDUO, FECHA_HISTORICO, TO_CHAR(FECHA_PROCESO, 'YYYY/MM/DD HH24:MI:SS') FECHA_PROCESO FROM FOREX.PROCESO ORDER BY FECHA_PROCESO DESC;
SELECT TRUNC(FECHA_PROCESO), COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.PROCESO GROUP BY TRUNC(FECHA_PROCESO) ORDER BY TRUNC(FECHA_PROCESO) DESC;
SELECT TO_CHAR(FECHA_PROCESO, 'YYYY/MM/DD HH24'), COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.PROCESO GROUP BY TO_CHAR(FECHA_PROCESO, 'YYYY/MM/DD HH24') 
  ORDER BY TO_CHAR(FECHA_PROCESO, 'YYYY/MM/DD HH24') DESC;
SELECT COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.OPERACION;
SELECT COUNT(DISTINCT ID_INDIVIDUO) FROM FOREX.PROCESO;
SELECT COUNT(*) FROM FOREX.OPERACION;
SELECT OPER.* FROM OPERACION OPER 
 --INNER JOIN PROCESO P ON P.ID_INDIVIDUO=OPER.ID_INDIVIDUO
 WHERE OPER.TAKE_PROFIT=0
--ORDER BY P.FECHA_PROCESO DESC
;

UPDATE PROCESO SET FECHA_HISTORICO=(SELECT MAX(FECHA_APERTURA) FROM OPERACION WHERE ID_INDIVIDUO='1338171613583.42')
WHERE ID_INDIVIDUO='1338171613583.42';

SELECT * FROM PROCESO WHERE ID_INDIVIDUO='1331599853600.50';

SELECT * FROM PROCESO_REPETIDOS;

INSERT INTO PROCESO (ID_INDIVIDUO, FECHA_HISTORICO, FECHA_PROCESO)
  SELECT OPER.ID_INDIVIDUO, MAX (OPER.FECHA_CIERRE) FECHA_HISTORICO, SYSDATE FECHA_PROCESO
  FROM OPERACION OPER WHERE ID_INDIVIDUO NOT IN (
    SELECT ID_INDIVIDUO FROM PROCESO P
  ) GROUP BY OPER.ID_INDIVIDUO;