DECLARE
REG_INDIVIDUO_OPERACION FOREX.OPERACION_BASE%ROWTYPE;
--FECHA_PROCESO DATE;

CURSOR C_OPERACIONES IS
  SELECT DISTINCT FECHA_APERTURA FROM OPERACION
  WHERE FECHA_APERTURA<=(SELECT NVL(TO_DATE(PARAM.VALOR,'YYYY/MM/DD HH24:MI'),SYSDATE)
    FROM PARAMETRO PARAM WHERE NOMBRE='FECHA_ESTADISTICAS')
    AND FECHA_APERTURA>(SELECT MIN(FECHA_APERTURA) FROM OPERACION)
  ORDER BY FECHA_APERTURA ASC;
BEGIN

  FOR REG_INDIVIDUO_OPERACION IN C_OPERACIONES LOOP 
    INSERT INTO TENDENCIA_PIPS(SUMA_PIPS, NUMERO_OPERACIONES, FECHA_OPERACION)
      SELECT SUM(PIPS), COUNT(*), REG_INDIVIDUO_OPERACION.FECHA_APERTURA
      FROM OPERACION WHERE FECHA_APERTURA<REG_INDIVIDUO_OPERACION.FECHA_APERTURA;
      COMMIT;
  END LOOP;
  
END;
/

