CREATE TABLE PROCESO_TEMP AS SELECT ID_INDIVIDUO, MAX(FECHA_HISTORICO) FECHA_HISTORICO, MAX(FECHA_PROCESO) FECHA_PROCESO 
  FROM PROCESO GROUP BY ID_INDIVIDUO;

TRUNCATE TABLE PROCESO;
ALTER TABLE PROCESO DROP CONSTRAINT PROCESO_PK2;
DROP INDEX PROCESO_PK2;
DROP INDEX PROCESO_INDIVIDUO_IDX;

ALTER TABLE PROCESO ADD CONSTRAINT PROCESO_PK2 PRIMARY KEY 
(  ID_INDIVIDUO ) ENABLE;

INSERT INTO PROCESO (ID_INDIVIDUO, FECHA_HISTORICO, FECHA_PROCESO) 
  SELECT ID_INDIVIDUO, FECHA_HISTORICO, FECHA_PROCESO FROM PROCESO_TEMP;
  
DROP TABLE PROCESO_TEMP;